// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/do_name.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/do_name.c
// Input sha256: 64c6cb5e7f4034e9edbd8fac983b313a7df0e029b4812bd3a9327852d12ad9d1
// Transpiler: tools/c2js c2js emit v1+batch

import { i16, schar, u32mod } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import * as FLD from './nhfield.js';
import { canspotmon, glyph_is_object, glyph_is_swallow, has_ebones, has_mgivenname, has_oname, helpless, is_mplayer, is_plural, is_rider, ismnum, m_next2u } from './nhmacrofn.js';
import { Blind, Deaf, EHalluc_resistance, Hallucination, Role_switch, See_invisible, Upolyd, create_nhwindow, destroy_nhwindow, display_nhwindow, end_menu, start_menu } from './nhprop.js';
import { newmextra } from './makemon.js';
import { alloc, dupstr, fmt_ptr } from './alloc.js';
import { dealloc_obj, newoextra } from './mkobj.js';
import { add_menu, getlin, select_menu, windowprocs } from './windows.js';
import { dist2, eos, fuzzymatch, highc, lcase, mungspaces, s_suffix, strncmpi, strstri, upstart } from './hacklib.js';
import { carrying, getobj, update_inventory } from './invent.js';
import { There, You, impossible, livelog_printf, pline, verbalize } from './pline.js';
import { mons } from './monst.js';
import { genders } from './role.js';
import { pronoun_gender } from './mondata.js';
import { WIN_MESSAGE, c_obj_colors, cg, flags, gi, gu, gv, gy, program_state, svd, svl, svp, u, uswapwep, uwep } from './decl.js';
import { getpos } from './getpos.js';
import { cmdq_clear, cmdq_pop, isok } from './cmd.js';
import { canseemon, flush_screen, glyph_at, nul_glyphinfo, see_with_infrared, sensemon } from './display.js';
import { beautiful } from './apply.js';
import { shkname } from './shknam.js';
import { The, Ysimple_name2, an, ansimpleoname, bare_artifactname, just_an, makeplural, safe_qbuf, simpleonames, vtense, xname } from './objnam.js';
import { artifact_exists, artifact_name, exist_artifact, restrict_name, set_artifact_intrinsic, undiscovered_artifact } from './artifact.js';
import { wipeout_text } from './engrave.js';
import { rn2, rn2_on_display_rng, rnd_on_display_rng, rng_log_enabled, rng_log_set_caller } from './rnd.js';
import { body_part } from './polyself.js';
import { untwoweapon } from './wield.js';
import { alter_cost } from './shk.js';
import { obj_descr, objects } from './objects.js';
import { discover_object, rename_disco, undiscover_object } from './o_init.js';
import { donamelevel, on_level } from './dungeon.js';
import { object_from_map } from './pager.js';
import { rank_of } from './botl.js';
import { priestname } from './priest.js';
import { get_rnd_text } from './rumors.js';
import { nh_getenv } from './options.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $Gender_he = FLD.Gender_he, $Gender_him = FLD.Gender_him, $Gender_his = FLD.Gender_his,
    $RoleName_f = FLD.RoleName_f, $Role_mnum = FLD.Role_mnum, $_cmd_queue_key = FLD._cmd_queue_key,
    $const_globals_zeroany = FLD.const_globals_zeroany, $d_level_dlevel = FLD.d_level_dlevel,
    $dgn_topology_d_astral_level = FLD.dgn_topology_d_astral_level,
    $dlevel_t_monsters = FLD.dlevel_t_monsters, $dlevel_t_objects = FLD.dlevel_t_objects,
    $flag_female = FLD.flag_female, $flag_lootabc = FLD.flag_lootabc,
    $instance_globals_i_invent = FLD.instance_globals_i_invent,
    $instance_globals_saved_d_dungeon_topology = FLD.instance_globals_saved_d_dungeon_topology,
    $instance_globals_saved_l_level = FLD.instance_globals_saved_l_level,
    $instance_globals_u_urole = FLD.instance_globals_u_urole,
    $instance_globals_v_viz_array = FLD.instance_globals_v_viz_array,
    $instance_globals_y_youmonst = FLD.instance_globals_y_youmonst, $mextra_ebones = FLD.mextra_ebones,
    $monst_cham = FLD.monst_cham, $monst_data = FLD.monst_data, $monst_female = FLD.monst_female,
    $monst_isminion = FLD.monst_isminion, $monst_ispriest = FLD.monst_ispriest,
    $monst_isshk = FLD.monst_isshk, $monst_m_ap_type = FLD.monst_m_ap_type, $monst_m_id = FLD.monst_m_id,
    $monst_m_lev = FLD.monst_m_lev, $monst_mappearance = FLD.monst_mappearance, $monst_mcan = FLD.monst_mcan,
    $monst_mcanmove = FLD.monst_mcanmove, $monst_mextra = FLD.monst_mextra, $monst_minvis = FLD.monst_minvis,
    $monst_misc_worn_check = FLD.monst_misc_worn_check, $monst_mleashed = FLD.monst_mleashed,
    $monst_mpeaceful = FLD.monst_mpeaceful, $monst_msleeping = FLD.monst_msleeping,
    $monst_mtame = FLD.monst_mtame, $monst_mundetected = FLD.monst_mundetected, $monst_mx = FLD.monst_mx,
    $monst_my = FLD.monst_my, $nhcoord_y = FLD.nhcoord_y, $obj_blessed = FLD.obj_blessed,
    $obj_corpsenm = FLD.obj_corpsenm, $obj_cursed = FLD.obj_cursed, $obj_dknown = FLD.obj_dknown,
    $obj_globby = FLD.obj_globby, $obj_known = FLD.obj_known, $obj_oartifact = FLD.obj_oartifact,
    $obj_oclass = FLD.obj_oclass, $obj_oeroded = FLD.obj_oeroded, $obj_oextra = FLD.obj_oextra,
    $obj_otrapped = FLD.obj_otrapped, $obj_otyp = FLD.obj_otyp, $obj_owt = FLD.obj_owt,
    $obj_quan = FLD.obj_quan, $obj_spe = FLD.obj_spe, $obj_unpaid = FLD.obj_unpaid,
    $obj_where = FLD.obj_where, $objclass_oc_class = FLD.objclass_oc_class,
    $objclass_oc_descr_idx = FLD.objclass_oc_descr_idx, $objclass_oc_name_known = FLD.objclass_oc_name_known,
    $objclass_oc_uname = FLD.objclass_oc_uname, $objclass_oc_weight = FLD.objclass_oc_weight,
    $objdescr_oc_descr = FLD.objdescr_oc_descr, $permonst_geno = FLD.permonst_geno,
    $permonst_mflags1 = FLD.permonst_mflags1, $permonst_mflags2 = FLD.permonst_mflags2,
    $permonst_msound = FLD.permonst_msound, $permonst_pmidx = FLD.permonst_pmidx,
    $prop_blocked = FLD.prop_blocked, $prop_intrinsic = FLD.prop_intrinsic,
    $u_conduct_literate = FLD.u_conduct_literate, $u_roleplay_deaf = FLD.u_roleplay_deaf,
    $window_procs_win_create_nhwindow = FLD.window_procs_win_create_nhwindow,
    $window_procs_win_destroy_nhwindow = FLD.window_procs_win_destroy_nhwindow,
    $window_procs_win_display_nhwindow = FLD.window_procs_win_display_nhwindow,
    $window_procs_win_end_menu = FLD.window_procs_win_end_menu,
    $window_procs_win_start_menu = FLD.window_procs_win_start_menu, $you_mfemale = FLD.you_mfemale,
    $you_uconduct = FLD.you_uconduct, $you_umonnum = FLD.you_umonnum, $you_umonster = FLD.you_umonster,
    $you_uprops = FLD.you_uprops, $you_uroleplay = FLD.you_uroleplay, $you_usteed = FLD.you_usteed,
    $you_ustuck = FLD.you_ustuck, $you_uswallow = FLD.you_uswallow, $you_uundetected = FLD.you_uundetected,
    $you_uy = FLD.you_uy, $you_uz = FLD.you_uz;

// string literals (C char* uses decay to CPtr into these static buffers)
const __sl0 = cptr.lit("");
const __sl1 = cptr.lit("%s would rather keep %s existing %s.");
const __sl2 = cptr.lit("its");
const __sl3 = cptr.lit("name");
const __sl4 = cptr.lit("title");
const __sl5 = cptr.lit(" -_");
const __sl6 = cptr.lit("the ");
const __sl7 = cptr.lit("invisible ");
const __sl8 = cptr.lit(" of ");
const __sl9 = cptr.lit("%s is already called that.");
const __sl10 = cptr.lit("%s is already called %s.");
const __sl11 = cptr.lit("Juiblex");
const __sl12 = cptr.lit("Jubilex");
const __sl13 = cptr.lit("%s doesn't like being called %s.");
const __sl14 = cptr.lit("would never recognize it anyway.");
const __sl15 = cptr.lit("the monster you want to name");
const __sl16 = cptr.lit("This %s creature is called %s and cannot be renamed.");
const __sl17 = cptr.lit("I see no monster there.");
const __sl18 = cptr.lit("What do you want to call %s?");
const __sl19 = cptr.lit("%s doesn't like being called names!");
const __sl20 = cptr.lit("I'm %s, not %s.");
const __sl21 = cptr.lit("%s will not accept the name %s.");
const __sl22 = cptr.lit("%s already has a published name.");
const __sl23 = cptr.lit("What do you want to name %s ");
const __sl24 = cptr.lit("these");
const __sl25 = cptr.lit("this");
const __sl26 = cptr.lit("?");
const __sl27 = cptr.lit("item");
const __sl28 = cptr.lit("%s resists the attempt.");
const __sl29 = cptr.lit("The artifact");
const __sl30 = cptr.lit("While engraving, your %s slips.");
const __sl31 = cptr.lit("engrave: \"%s\".");
const __sl32 = cptr.lit("do_oname");
const __sl33 = cptr.lit("do_name.c");
const __sl34 = cptr.lit("aname != 0");
const __sl35 = cptr.lit("became literate by naming %s");
const __sl36 = cptr.lit("chose %s to be named \"%s\"");
const __sl37 = cptr.lit("a monster");
const __sl38 = cptr.lit("a particular object in inventory");
const __sl39 = cptr.lit("the type of an object in inventory");
const __sl40 = cptr.lit("the type of an object upon the floor");
const __sl41 = cptr.lit("the type of an object on discoveries list");
const __sl42 = cptr.lit("record an annotation for the current level");
const __sl43 = cptr.lit("What do you want to name?");
const __sl44 = cptr.lit("call");
const __sl45 = cptr.lit("would never recognize another one.");
const __sl46 = cptr.lit("Call a stream of %s fluid:");
const __sl47 = cptr.lit("Call ");
const __sl48 = cptr.lit(":");
const __sl49 = cptr.lit("thing");
const __sl50 = cptr.lit("object on map (or '.' for one %s you)");
const __sl51 = cptr.lit("over");
const __sl52 = cptr.lit("under");
const __sl53 = cptr.lit("doesn't seem to be any object %s.");
const __sl54 = cptr.lit("under you");
const __sl55 = cptr.lit("there");
const __sl56 = cptr.lit("Wibbly Wobbly");
const __sl57 = cptr.lit("%s %s to call you \"%s.\"");
const __sl58 = cptr.lit("decide");
const __sl59 = cptr.lit("decides");
const __sl60 = cptr.lit("%s %s can't be assigned a type name.");
const __sl61 = cptr.lit("Those");
const __sl62 = cptr.lit("That");
const __sl63 = cptr.lit("don't know %s %s well enough to name %s.");
const __sl64 = cptr.lit("those");
const __sl65 = cptr.lit("that");
const __sl66 = cptr.lit("them");
const __sl67 = cptr.lit("it");
const __sl68 = cptr.lit("Adri");
const __sl69 = cptr.lit("Andries");
const __sl70 = cptr.lit("Andreas");
const __sl71 = cptr.lit("Bert");
const __sl72 = cptr.lit("David");
const __sl73 = cptr.lit("Dirk");
const __sl74 = cptr.lit("Emile");
const __sl75 = cptr.lit("Frans");
const __sl76 = cptr.lit("Fred");
const __sl77 = cptr.lit("Greg");
const __sl78 = cptr.lit("Hether");
const __sl79 = cptr.lit("Jay");
const __sl80 = cptr.lit("John");
const __sl81 = cptr.lit("Jon");
const __sl82 = cptr.lit("Karnov");
const __sl83 = cptr.lit("Kay");
const __sl84 = cptr.lit("Kenny");
const __sl85 = cptr.lit("Kevin");
const __sl86 = cptr.lit("Maud");
const __sl87 = cptr.lit("Michiel");
const __sl88 = cptr.lit("Mike");
const __sl89 = cptr.lit("Peter");
const __sl90 = cptr.lit("Robert");
const __sl91 = cptr.lit("Ron");
const __sl92 = cptr.lit("Tom");
const __sl93 = cptr.lit("Wilmar");
const __sl94 = cptr.lit("Nick Danger");
const __sl95 = cptr.lit("Phoenix");
const __sl96 = cptr.lit("Jiro");
const __sl97 = cptr.lit("Mizue");
const __sl98 = cptr.lit("Stephan");
const __sl99 = cptr.lit("Lance Braccus");
const __sl100 = cptr.lit("Shadowhawk");
const __sl101 = cptr.lit("Murphy");
const __sl102 = cptr.lit("rndghostname");
const __sl103 = cptr.lit("you");
const __sl104 = cptr.lit("x_monnam");
const __sl105 = cptr.lit("someone");
const __sl106 = cptr.lit("something");
const __sl107 = cptr.lit(" ");
const __sl108 = cptr.lit(" the ");
const __sl109 = cptr.lit("saddled ");
const __sl110 = cptr.lit("%s ghost");
const __sl111 = cptr.lit("%s called %s");
const __sl112 = cptr.lit("your ");
const __sl113 = cptr.lit("high priestess");
const __sl114 = cptr.lit("high priest");
const __sl115 = cptr.lit("himself");
const __sl116 = cptr.lit("herself");
const __sl117 = cptr.lit("itself");
const __sl118 = cptr.lit("themselves");
const __sl119 = cptr.lit("[Null monster]");
const __sl120 = cptr.lit("[Null mon->data]");
const __sl121 = cptr.lit("[Invalid mon->data %s < %s]");
const __sl122 = cptr.lit("[Invalid mon->data %s >= %s]");
const __sl123 = cptr.lit("%s <%d,%d>");
const __sl124 = cptr.lit("%s%s <%d,%d>");
const __sl125 = cptr.lit("tame ");
const __sl126 = cptr.lit("peaceful ");
const __sl127 = cptr.lit("{%s}");
const __sl128 = cptr.lit("obj_pmname otyp:%i,corpsenm:%i");
const __sl129 = cptr.lit("two-legged glorkum-seeker");
const __sl130 = cptr.lit("bogusmon");
const __sl131 = cptr.lit("bogon");
const __sl132 = cptr.lit("-+=");
const __sl133 = cptr.lit("ROGUEOPTS");
const __sl134 = cptr.lit("name=");
const __sl135 = cptr.lit("roguename");
const __sl136 = cptr.lit("Michael Toy");
const __sl137 = cptr.lit("Kenneth Arnold");
const __sl138 = cptr.lit("Glenn Wichman");
const __sl139 = cptr.lit("ultraviolet");
const __sl140 = cptr.lit("infrared");
const __sl141 = cptr.lit("bluish-orange");
const __sl142 = cptr.lit("reddish-green");
const __sl143 = cptr.lit("dark white");
const __sl144 = cptr.lit("light black");
const __sl145 = cptr.lit("sky blue-pink");
const __sl146 = cptr.lit("pinkish-cyan");
const __sl147 = cptr.lit("indigo-chartreuse");
const __sl148 = cptr.lit("salty");
const __sl149 = cptr.lit("sweet");
const __sl150 = cptr.lit("sour");
const __sl151 = cptr.lit("bitter");
const __sl152 = cptr.lit("umami");
const __sl153 = cptr.lit("striped");
const __sl154 = cptr.lit("spiral");
const __sl155 = cptr.lit("swirly");
const __sl156 = cptr.lit("plaid");
const __sl157 = cptr.lit("checkered");
const __sl158 = cptr.lit("argyle");
const __sl159 = cptr.lit("paisley");
const __sl160 = cptr.lit("blotchy");
const __sl161 = cptr.lit("guernsey-spotted");
const __sl162 = cptr.lit("polka-dotted");
const __sl163 = cptr.lit("square");
const __sl164 = cptr.lit("round");
const __sl165 = cptr.lit("triangular");
const __sl166 = cptr.lit("cabernet");
const __sl167 = cptr.lit("sangria");
const __sl168 = cptr.lit("fuchsia");
const __sl169 = cptr.lit("wisteria");
const __sl170 = cptr.lit("lemon-lime");
const __sl171 = cptr.lit("strawberry-banana");
const __sl172 = cptr.lit("peppermint");
const __sl173 = cptr.lit("romantic");
const __sl174 = cptr.lit("incandescent");
const __sl175 = cptr.lit("octarine");
const __sl176 = cptr.lit("excitingly dull");
const __sl177 = cptr.lit("mauve");
const __sl178 = cptr.lit("electric");
const __sl179 = cptr.lit("neon");
const __sl180 = cptr.lit("fluorescent");
const __sl181 = cptr.lit("phosphorescent");
const __sl182 = cptr.lit("translucent");
const __sl183 = cptr.lit("opaque");
const __sl184 = cptr.lit("psychedelic");
const __sl185 = cptr.lit("iridescent");
const __sl186 = cptr.lit("rainbow-colored");
const __sl187 = cptr.lit("polychromatic");
const __sl188 = cptr.lit("colorless");
const __sl189 = cptr.lit("colorless green");
const __sl190 = cptr.lit("dancing");
const __sl191 = cptr.lit("singing");
const __sl192 = cptr.lit("loving");
const __sl193 = cptr.lit("loudy");
const __sl194 = cptr.lit("noisy");
const __sl195 = cptr.lit("clattery");
const __sl196 = cptr.lit("silent");
const __sl197 = cptr.lit("apocyan");
const __sl198 = cptr.lit("infra-pink");
const __sl199 = cptr.lit("opalescent");
const __sl200 = cptr.lit("violant");
const __sl201 = cptr.lit("tuneless");
const __sl202 = cptr.lit("viridian");
const __sl203 = cptr.lit("aureolin");
const __sl204 = cptr.lit("cinnabar");
const __sl205 = cptr.lit("purpurin");
const __sl206 = cptr.lit("gamboge");
const __sl207 = cptr.lit("madder");
const __sl208 = cptr.lit("bistre");
const __sl209 = cptr.lit("ecru");
const __sl210 = cptr.lit("fulvous");
const __sl211 = cptr.lit("tekhelet");
const __sl212 = cptr.lit("selective yellow");
const __sl213 = cptr.lit("rndcolor");
const __sl214 = cptr.lit("yoghurt");
const __sl215 = cptr.lit("oobleck");
const __sl216 = cptr.lit("clotted blood");
const __sl217 = cptr.lit("diluted water");
const __sl218 = cptr.lit("purified water");
const __sl219 = cptr.lit("instant coffee");
const __sl220 = cptr.lit("tea");
const __sl221 = cptr.lit("herbal infusion");
const __sl222 = cptr.lit("liquid rainbow");
const __sl223 = cptr.lit("creamy foam");
const __sl224 = cptr.lit("mulled wine");
const __sl225 = cptr.lit("bouillon");
const __sl226 = cptr.lit("nectar");
const __sl227 = cptr.lit("grog");
const __sl228 = cptr.lit("flubber");
const __sl229 = cptr.lit("ketchup");
const __sl230 = cptr.lit("slow light");
const __sl231 = cptr.lit("oil");
const __sl232 = cptr.lit("vinaigrette");
const __sl233 = cptr.lit("liquid crystal");
const __sl234 = cptr.lit("honey");
const __sl235 = cptr.lit("caramel sauce");
const __sl236 = cptr.lit("ink");
const __sl237 = cptr.lit("aqueous humour");
const __sl238 = cptr.lit("milk substitute");
const __sl239 = cptr.lit("fruit juice");
const __sl240 = cptr.lit("glowing lava");
const __sl241 = cptr.lit("gastric acid");
const __sl242 = cptr.lit("mineral water");
const __sl243 = cptr.lit("cough syrup");
const __sl244 = cptr.lit("quicksilver");
const __sl245 = cptr.lit("sweet vitriol");
const __sl246 = cptr.lit("grey goo");
const __sl247 = cptr.lit("pink slime");
const __sl248 = cptr.lit("cosmic latte");
const __sl249 = cptr.lit("bone oil");
const __sl250 = cptr.lit("custard");
const __sl251 = cptr.lit("lard");
const __sl252 = cptr.lit("vinegar");
const __sl253 = cptr.lit("creosote");
const __sl254 = cptr.lit("Carnivorous Vulgaris");
const __sl255 = cptr.lit("Road-Runnerus Digestus");
const __sl256 = cptr.lit("Eatibus Anythingus");
const __sl257 = cptr.lit("Famishus-Famishus");
const __sl258 = cptr.lit("Eatibus Almost Anythingus");
const __sl259 = cptr.lit("Eatius Birdius");
const __sl260 = cptr.lit("Famishius Fantasticus");
const __sl261 = cptr.lit("Eternalii Famishiis");
const __sl262 = cptr.lit("Famishus Vulgarus");
const __sl263 = cptr.lit("Famishius Vulgaris Ingeniusi");
const __sl264 = cptr.lit("Eatius-Slobbius");
const __sl265 = cptr.lit("Hardheadipus Oedipus");
const __sl266 = cptr.lit("Carnivorous Slobbius");
const __sl267 = cptr.lit("Hard-Headipus Ravenus");
const __sl268 = cptr.lit("Evereadii Eatibus");
const __sl269 = cptr.lit("Apetitius Giganticus");
const __sl270 = cptr.lit("Hungrii Flea-Bagius");
const __sl271 = cptr.lit("Overconfidentii Vulgaris");
const __sl272 = cptr.lit("Caninus Nervous Rex");
const __sl273 = cptr.lit("Grotesques Appetitus");
const __sl274 = cptr.lit("Nemesis Ridiculii");
const __sl275 = cptr.lit("Canis latrans");
const __sl276 = cptr.lit("%s - %s");
const __sl277 = cptr.lit("rndorcname");
const __sl278 = cptr.lit("%s%s");
const __sl279 = cptr.lit("-");
const __sl280 = cptr.lit("a");
const __sl281 = cptr.lit("ai");
const __sl282 = cptr.lit("og");
const __sl283 = cptr.lit("u");
const __sl284 = cptr.lit("gor");
const __sl285 = cptr.lit("gris");
const __sl286 = cptr.lit("un");
const __sl287 = cptr.lit("bane");
const __sl288 = cptr.lit("ruk");
const __sl289 = cptr.lit("oth");
const __sl290 = cptr.lit("ul");
const __sl291 = cptr.lit("z");
const __sl292 = cptr.lit("thos");
const __sl293 = cptr.lit("akh");
const __sl294 = cptr.lit("hai");
const __sl295 = cptr.lit("%s of %s");
const __sl296 = cptr.lit("The Colour of Magic");
const __sl297 = cptr.lit("The Light Fantastic");
const __sl298 = cptr.lit("Equal Rites");
const __sl299 = cptr.lit("Mort");
const __sl300 = cptr.lit("Sourcery");
const __sl301 = cptr.lit("Wyrd Sisters");
const __sl302 = cptr.lit("Pyramids");
const __sl303 = cptr.lit("Guards! Guards!");
const __sl304 = cptr.lit("Eric");
const __sl305 = cptr.lit("Moving Pictures");
const __sl306 = cptr.lit("Reaper Man");
const __sl307 = cptr.lit("Witches Abroad");
const __sl308 = cptr.lit("Small Gods");
const __sl309 = cptr.lit("Lords and Ladies");
const __sl310 = cptr.lit("Men at Arms");
const __sl311 = cptr.lit("Soul Music");
const __sl312 = cptr.lit("Interesting Times");
const __sl313 = cptr.lit("Maskerade");
const __sl314 = cptr.lit("Feet of Clay");
const __sl315 = cptr.lit("Hogfather");
const __sl316 = cptr.lit("Jingo");
const __sl317 = cptr.lit("The Last Continent");
const __sl318 = cptr.lit("Carpe Jugulum");
const __sl319 = cptr.lit("The Fifth Elephant");
const __sl320 = cptr.lit("The Truth");
const __sl321 = cptr.lit("Thief of Time");
const __sl322 = cptr.lit("The Last Hero");
const __sl323 = cptr.lit("The Amazing Maurice and His Educated Rodents");
const __sl324 = cptr.lit("Night Watch");
const __sl325 = cptr.lit("The Wee Free Men");
const __sl326 = cptr.lit("Monstrous Regiment");
const __sl327 = cptr.lit("A Hat Full of Sky");
const __sl328 = cptr.lit("Going Postal");
const __sl329 = cptr.lit("Thud!");
const __sl330 = cptr.lit("Wintersmith");
const __sl331 = cptr.lit("Making Money");
const __sl332 = cptr.lit("Unseen Academicals");
const __sl333 = cptr.lit("I Shall Wear Midnight");
const __sl334 = cptr.lit("Snuff");
const __sl335 = cptr.lit("Raising Steam");
const __sl336 = cptr.lit("The Shepherd's Crown");
const __sl337 = cptr.lit("noveltitle");
const __sl338 = cptr.lit("The Color of Magic");
const __sl339 = cptr.lit("Sorcery");
const __sl340 = cptr.lit("Masquerade");
const __sl341 = cptr.lit("The Amazing Maurice");
const __sl342 = cptr.lit("Thud");

const __static_nextmbuf_bufs = (function () { const flat = new Uint8Array(5 * (256 * 1)); const a = []; for (let r = 0; r < 5; r++) a.push(flat.subarray(r * (256 * 1), (r + 1) * (256 * 1))); a.buf = flat; return a; })(); /** C ref: do_name.c:22 — char[5][256] (function-static) */
let __static_nextmbuf_bufidx = 0; /** C ref: do_name.c:23 — int (function-static) */

/** C ref: do_name.c:20 @returns {CPtr} */
function nextmbuf() {
    __static_nextmbuf_bufidx = ((__static_nextmbuf_bufidx + 1) | 0) % 5;
    return cptr.decay(__static_nextmbuf_bufs[__static_nextmbuf_bufidx]);
}

/** C ref: do_name.c:31 — @param {CPtr} mon @param {CInt} lth */
export function* new_mgivenname(mon, lth) {
    if (lth) {
        if (!cptr.ldPtro(mon, $monst_mextra))
            cptr.stPtro(mon, $monst_mextra, (yield* newmextra()));
        else
            free_mgivenname(mon);
        cptr.stPtr(cptr.ldPtro((mon), $monst_mextra), (yield* alloc(lth >>> 0)));
    } else {
        if (has_mgivenname(mon))
            free_mgivenname(mon);
    }
}

/** C ref: do_name.c:51 — @param {CPtr} mon */
export function free_mgivenname(mon) {
    if (has_mgivenname(mon)) {
        cptr.free((cptr.ldPtr(cptr.ldPtro((mon), $monst_mextra))));
        cptr.stPtr(cptr.ldPtro((mon), $monst_mextra), null);
    }
}

/** C ref: do_name.c:61 — @param {CPtr} obj @param {CInt} lth */
export function* new_oname(obj, lth) {
    if (lth) {
        if (!cptr.ldPtro(obj, $obj_oextra))
            cptr.stPtro(obj, $obj_oextra, (yield* newoextra()));
        else
            free_oname(obj);
        cptr.stPtr(cptr.ldPtro((obj), $obj_oextra), (yield* alloc(lth >>> 0)));
    } else {
        if (has_oname(obj))
            free_oname(obj);
    }
}

/** C ref: do_name.c:81 — @param {CPtr} obj */
export function free_oname(obj) {
    if (has_oname(obj)) {
        cptr.free((cptr.ldPtr(cptr.ldPtro((obj), $obj_oextra))));
        cptr.stPtr(cptr.ldPtro((obj), $obj_oextra), null);
    }
}

/** C ref: do_name.c:95 — @param {CPtr} obj @returns {CPtr} */
export function safe_oname(obj) {
    if (has_oname(obj))
        return (cptr.ldPtr(cptr.ldPtro((obj), $obj_oextra)));
    return __sl0;
}

/** C ref: do_name.c:105 — @param {CPtr} outbuf @param {CPtr} prompt @param {CPtr} defres @returns {CPtr} */
function* name_from_player(outbuf, prompt, defres) {
    cptr.st1o(outbuf, 0, 0);
    (void (defres));
    (yield* getlin(prompt, outbuf));
    if (!cptr.ld1s(outbuf) || cptr.ld1s(outbuf) == 27)
        return null;
    void (yield* mungspaces(outbuf));
    if (cptr.strlen(outbuf) >= 63n)
        cptr.st1o(outbuf, 62, 0);
    return outbuf;
}

/** C ref: do_name.c:133 — @param {CPtr} mtmp @param {CPtr} name @returns {CPtr} */
export function* christen_monst(mtmp, name) {
    let lth;
    let buf = new Uint8Array(63);
    lth = (name && cptr.ld1s(name)) ? ((Number(BigInt.asIntN(32, cptr.strlen(name))) + 1) | 0) : 0;
    if (lth > NHM.PL_PSIZ) {
        lth = NHM.PL_PSIZ;
        name = __builtin___strncpy_chk(cptr.decay(buf), name, 62n, __builtin_object_size(cptr.decay(buf), 1));
        cptr.st1o(cptr.decay(buf), 62, 0, 1);
    }
    (yield* new_mgivenname(mtmp, lth));
    if (lth)
        void cptr.strcpy((cptr.ldPtr(cptr.ldPtro((mtmp), $monst_mextra))), name);
    if ((cptr.ldI32o(mtmp, $monst_mleashed) & 1))
        (yield* update_inventory());
    return mtmp;
}

/** C ref: do_name.c:158 — @param {CPtr} mtmp @param {CPtr} monnambuf @param {CPtr} usrbuf @returns {CInt} */
function* alreadynamed(mtmp, monnambuf, usrbuf) {
    let pronounbuf = new Uint8Array(10);
    let p;
    if (!cptr.ld1s(usrbuf)) {
        let name_not_title = schar((has_mgivenname(mtmp) || ((cptr.ldU64o((cptr.ldPtro(mtmp, $monst_data)), $permonst_mflags2) & 524288n) != 0n) || (cptr.ldI32o(mtmp, $monst_isshk) & 1) | 0 ? 1 : 0));
        (yield* pline(__sl1, upstart(monnambuf), is_rider(cptr.ldPtro(mtmp, $monst_data)) ? __sl2 : (cptr.ldPtro2(genders, pronoun_gender(mtmp, NHM.PRONOUN_HALLU), 48, $Gender_his)), name_not_title ? __sl3 : __sl4));
        return 1;
    } else if ((yield* fuzzymatch(usrbuf, monnambuf, __sl5, 1)) || (!(yield* strncmpi(monnambuf, __sl6, 4)) && (yield* fuzzymatch(usrbuf, cptr.add(monnambuf, 4), __sl5, 1))) || ((p = (yield* strstri(monnambuf, __sl7))) !== null && (yield* fuzzymatch(usrbuf, cptr.add(p, 10), __sl5, 1))) || ((p = (yield* strstri(monnambuf, __sl8))) !== null && (yield* fuzzymatch(usrbuf, cptr.add(p, 4), __sl5, 1)))) {
        if (is_rider(cptr.ldPtro(mtmp, $monst_data))) {
            (yield* pline(__sl9, upstart(monnambuf)));
        } else {
            (yield* pline(__sl10, upstart(cptr.strcpy(cptr.decay(pronounbuf), (cptr.ldPtro2(genders, pronoun_gender(mtmp, NHM.PRONOUN_HALLU), 48, $Gender_he)))), monnambuf));
        }
        return 1;
    } else if (cptr.eq(cptr.ldPtro(mtmp, $monst_data), cptr.add(mons, NHC.PM_JUIBLEX, 96)) && (yield* strstri(monnambuf, __sl11)) && !(yield* strncmpi((usrbuf), (__sl12), -1))) {
        (yield* pline(__sl13, upstart(monnambuf), usrbuf));
        return 1;
    }
    return 0;
}

/** C ref: do_name.c:199 */
function* do_mgivenname() {
    let buf = new Uint8Array(256);
    let monnambuf = new Uint8Array(256);
    let qbuf = new Uint8Array(128);
    let cc = cptr.alloc(4);
    let cx;
    let cy;
    let mtmp = null;
    let do_swallow = 0;
    if (Hallucination()) {
        (yield* You(__sl14));
        return;
    }
    cptr.stI16(cc, cptr.ldI16(u));
    cptr.stI16o(cc, $nhcoord_y, cptr.ldI16o(u, $you_uy));
    if ((yield* getpos(cc, 0, __sl15)) < 0 || !isok(cptr.ldI16(cc), cptr.ldI16o(cc, $nhcoord_y)))
        return;
    cx = cptr.ldI16(cc), cy = cptr.ldI16o(cc, $nhcoord_y);
    if (((cx) == cptr.ldI16(u) && (cy) == cptr.ldI16o(u, $you_uy))) {
        if (cptr.ldPtro(u, $you_usteed) && canspotmon(cptr.ldPtro(u, $you_usteed))) {
            mtmp = cptr.ldPtro(u, $you_usteed);
        } else {
            (yield* pline(__sl16, beautiful(), svp));
            return;
        }
    } else
        mtmp = (cptr.ldPtro3(svl, cx, 168, cy, 8, $instance_globals_saved_l_level + $dlevel_t_monsters));
    if (!mtmp && (cptr.ldI32o(u, $you_uswallow) & 1) | 0) {
        let glyph = glyph_at(i16(cx), i16(cy));
        if (glyph_is_swallow(glyph)) {
            mtmp = cptr.ldPtro(u, $you_ustuck);
            do_swallow = 1;
        }
    }
    if (!do_swallow && (!mtmp || (!sensemon(mtmp) && (!(((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, $instance_globals_v_viz_array), cy, 8), cx) & NHM.IN_SIGHT) != 0) || see_with_infrared(mtmp)) || (cptr.ldI32o(mtmp, $monst_mundetected) & 1) | 0 || (cptr.ld1uo((mtmp), $monst_m_ap_type) & NHM.M_AP_TYPMASK) == NHC.M_AP_FURNITURE || (cptr.ld1uo((mtmp), $monst_m_ap_type) & NHM.M_AP_TYPMASK) == NHC.M_AP_OBJECT || ((cptr.ldI32o(mtmp, $monst_minvis) & 1) | 0 && !See_invisible()))))) {
        (yield* pline(__sl17));
        return;
    }
    void cptr.sprintf(cptr.decay(qbuf), __sl18, (yield* distant_monnam(mtmp, NHM.ARTICLE_THE, cptr.decay(monnambuf))));
    if (!(yield* name_from_player(cptr.decay(buf), cptr.decay(qbuf), has_mgivenname(mtmp) ? (cptr.ldPtr(cptr.ldPtro((mtmp), $monst_mextra))) : null)))
        return;
    if ((cptr.ldU16o(cptr.ldPtro(mtmp, $monst_data), $permonst_geno) & NHM.G_UNIQ) && !(cptr.ldI32o(mtmp, $monst_ispriest) & 1)) {
        if (!(yield* alreadynamed(mtmp, cptr.decay(monnambuf), cptr.decay(buf))))
            (yield* pline(__sl19, upstart(cptr.decay(monnambuf))));
    } else if ((cptr.ldI32o(mtmp, $monst_isshk) & 1) | 0 && !(Deaf() || helpless(mtmp) || cptr.ld1uo(cptr.ldPtro(mtmp, $monst_data), $permonst_msound) <= NHC.MS_ANIMAL)) {
        if (!(yield* alreadynamed(mtmp, cptr.decay(monnambuf), cptr.decay(buf)))) {
            ;
            (yield* verbalize(__sl20, (yield* shkname(mtmp)), cptr.decay(buf)));
        }
    } else if ((cptr.ldI32o(mtmp, $monst_ispriest) & 1) | 0 || (cptr.ldI32o(mtmp, $monst_isminion) & 1) | 0 || (cptr.ldI32o(mtmp, $monst_isshk) & 1) | 0 || cptr.eq(cptr.ldPtro(mtmp, $monst_data), cptr.add(mons, NHC.PM_GHOST, 96)) || has_ebones(mtmp)) {
        if (!(yield* alreadynamed(mtmp, cptr.decay(monnambuf), cptr.decay(buf))))
            (yield* pline(__sl21, upstart(cptr.decay(monnambuf)), cptr.decay(buf)));
    } else {
        void (yield* christen_monst(mtmp, cptr.decay(buf)));
    }
}

/** C ref: do_name.c:290 — @param {CPtr} obj */
function* do_oname(obj) {
    let bufp;
    let buf = new Uint8Array(256);
    let bufcpy = new Uint8Array(256);
    let qbuf = new Uint8Array(128);
    let aname;
    let objtyp = cptr.box(NHC.STRANGE_OBJECT);
    if (cptr.ldI16o(obj, $obj_otyp) == NHC.SPE_NOVEL) {
        (yield* pline(__sl22, (yield* Ysimple_name2(obj))));
        return;
    }
    void cptr.sprintf(cptr.decay(qbuf), __sl23, is_plural(obj) ? __sl24 : __sl25);
    void (yield* safe_qbuf(cptr.decay(qbuf), cptr.decay(qbuf), __sl26, obj, xname, simpleonames, __sl27));
    if (!(yield* name_from_player(cptr.decay(buf), cptr.decay(qbuf), safe_oname(obj))))
        return;
    if (cptr.ld1so(obj, $obj_oartifact)) {
        (yield* pline(__sl28, has_oname(obj) ? (cptr.ldPtr(cptr.ldPtro((obj), $obj_oextra))) : __sl29));
        return;
    }
    if ((aname = (yield* artifact_name(cptr.decay(buf), objtyp, 1))) !== null && ((yield* restrict_name(obj, aname)) || exist_artifact(cptr.ldI16o(obj, $obj_otyp), aname))) {
        void cptr.strcpy(cptr.decay(buf), aname);
        void cptr.strcpy(cptr.decay(bufcpy), cptr.decay(buf));
        bufp = !(yield* strncmpi(cptr.decay(buf), __sl6, 4)) ? (cptr.add(cptr.decay(buf), 4)) : cptr.decay(buf);
        do {
            wipeout_text(bufp, rnd_on_display_rng(2), 0);
        } while (!strcmp(cptr.decay(buf), cptr.decay(bufcpy)));
        (yield* pline(__sl30, (yield* body_part(NHC.HAND))));
        (yield* Y.icall(display_nhwindow()(WIN_MESSAGE.v, 0)));
        (yield* You(__sl31, cptr.decay(buf)));
        (cptr.stI64o(u, $you_uconduct + $u_conduct_literate, cptr.ldI64o(u, $you_uconduct + $u_conduct_literate) + 1n)) - (1n);
    } else if (cptr.ldI16o(obj, $obj_otyp) == objtyp.v) {
        (__builtin_expect(BigInt((!(aname !== null))), 0n) ? __assert_rtn(__sl32, __sl33, 359, __sl34) : void 0);
        void cptr.strcpy(cptr.decay(buf), aname);
    }
    obj = (yield* oname(obj, cptr.decay(buf), 258));
    (void (obj));
}

/** C ref: do_name.c:372 — @param {CPtr} obj @param {CPtr} name @param {CUInt} oflgs @returns {CPtr} */
export function* oname(obj, name, oflgs) {
    let lth;
    let buf = new Uint8Array(63);
    let via_naming = schar((((oflgs & NHM.ONAME_VIA_NAMING) >>> 0) != 0));
    let skip_inv_update = schar((((oflgs & NHM.ONAME_SKIP_INVUPD) >>> 0) != 0));
    lth = cptr.ld1s(name) ? Number(BigInt.asIntN(32, (BigInt.asUintN(64, cptr.strlen(name) + 1n)))) : 0;
    if (lth > NHM.PL_PSIZ) {
        lth = NHM.PL_PSIZ;
        name = __builtin___strncpy_chk(cptr.decay(buf), name, 62n, __builtin_object_size(cptr.decay(buf), 1));
        cptr.st1o(cptr.decay(buf), 62, 0, 1);
    }
    if (cptr.ld1so(obj, $obj_oartifact) || (lth && exist_artifact(cptr.ldI16o(obj, $obj_otyp), name)))
        return obj;
    (yield* new_oname(obj, lth));
    if (lth)
        void cptr.strcpy((cptr.ldPtr(cptr.ldPtro((obj), $obj_oextra))), name);
    if (lth)
        (yield* artifact_exists(obj, name, 1, oflgs));
    if (cptr.ld1so(obj, $obj_oartifact)) {
        if (cptr.eq(obj, uswapwep.v))
            (yield* untwoweapon());
        if (cptr.eq(obj, uwep.v))
            (yield* set_artifact_intrinsic(obj, 1, 256n));
        if ((cptr.ldI32o(obj, $obj_unpaid) & 1))
            (yield* alter_cost(obj, 0n));
        if (via_naming) {
            if (!((cptr.stI64o(u, $you_uconduct + $u_conduct_literate, cptr.ldI64o(u, $you_uconduct + $u_conduct_literate) + 1n)) - (1n)))
                (yield* livelog_printf(96n, __sl35, (yield* bare_artifactname(obj))));
            else
                (yield* livelog_printf(64n, __sl36, (yield* ansimpleoname(obj)), (yield* bare_artifactname(obj))));
        }
    }
    if ((cptr.ld1so((obj), $obj_where) == NHM.OBJ_INVENT) && !skip_inv_update)
        (yield* update_inventory());
    return obj;
}

/** C ref: do_name.c:429 — @param {CInt} i @returns {CInt} */
export function objtyp_is_callable(i) {
    if (cptr.ldPtro2(objects, i, 120, $objclass_oc_uname))
        return 1;
    switch (cptr.ld1so2(objects, i, 120, $objclass_oc_class)) {
        case NHC.AMULET_CLASS:
        if (i == NHC.AMULET_OF_YENDOR || i == NHC.FAKE_AMULET_OF_YENDOR)
            break;
        // @FallThrough
        ;
        case NHC.SCROLL_CLASS:
        case NHC.POTION_CLASS:
        case NHC.WAND_CLASS:
        case NHC.RING_CLASS:
        case NHC.GEM_CLASS:
        case NHC.SPBOOK_CLASS:
        case NHC.ARMOR_CLASS:
        case NHC.TOOL_CLASS:
        case NHC.VENOM_CLASS:
        if ((cptr.ldPtro2(obj_descr, cptr.ldI16o((cptr.add(objects, i, 120)), $objclass_oc_descr_idx), 16, $objdescr_oc_descr)))
            return 1;
        break;
        default:
        break;
    }
    return 0;
}

/** C ref: do_name.c:467 — @param {CPtr} obj @returns {CInt} */
export function name_ok(obj) {
    if (!obj || cptr.ld1so(obj, $obj_oclass) == NHC.COIN_CLASS)
        return NHC.GETOBJ_EXCLUDE;
    if (!(cptr.ldI32o(obj, $obj_dknown) & 1) || cptr.ld1so(obj, $obj_oartifact) || cptr.ldI16o(obj, $obj_otyp) == NHC.SPE_NOVEL)
        return NHC.GETOBJ_DOWNPLAY;
    return NHC.GETOBJ_SUGGEST;
}

/** C ref: do_name.c:480 — @param {CPtr} obj @returns {CInt} */
export function call_ok(obj) {
    if (!obj || !objtyp_is_callable(cptr.ldI16o(obj, $obj_otyp)))
        return NHC.GETOBJ_EXCLUDE;
    if (!(cptr.ldI32o(obj, $obj_dknown) & 1) || ((cptr.ldI32o2(objects, cptr.ldI16o(obj, $obj_otyp), 120, $objclass_oc_name_known) & 1) | 0 && !cptr.ldPtro2(objects, cptr.ldI16o(obj, $obj_otyp), 120, $objclass_oc_uname)))
        return NHC.GETOBJ_DOWNPLAY;
    return NHC.GETOBJ_SUGGEST;
}

/** C ref: do_name.c:499 @returns {CInt} */
export function* docallcmd() {
    let obj;
    let win;
    let any = cptr.alloc(8);
    let pick_list = cptr.box(null);
    let cq = cptr.alloc(32);
    let cmdq;
    let ch = 0;
    let abc = cptr.ld1so(flags, $flag_lootabc);
    let clr = NHM.NO_COLOR;
    __lbl_docallcmd: {
        if ((cmdq = cmdq_pop()) !== null) {
            cptr.memcpy(cq, cmdq, 32);
            cptr.free(cmdq);
            if (cptr.ldI32(cq) == NHC.CMDQ_KEY)
                ch = cptr.ld1so(cq, $_cmd_queue_key);
            else
                cmdq_clear(NHC.CQ_CANNED);
            break __lbl_docallcmd;
        }
        win = (yield* Y.icall(create_nhwindow()(NHM.NHW_MENU)));
        (yield* Y.icall(start_menu()(win, 0n)));
        cptr.memcpy(any, cptr.add(cg, $const_globals_zeroany), 8);
        cptr.st1(any, 109);
        (yield* add_menu(win, nul_glyphinfo.v, any, schar((abc ? 0 : cptr.ld1s(any))), 67, NHM.ATR_NONE, clr, __sl37, NHM.MENU_ITEMFLAGS_NONE));
        if (cptr.ldPtro(gi, $instance_globals_i_invent)) {
            cptr.st1(any, 105);
            (yield* add_menu(win, nul_glyphinfo.v, any, schar((abc ? 0 : cptr.ld1s(any))), 121, NHM.ATR_NONE, clr, __sl38, NHM.MENU_ITEMFLAGS_NONE));
            cptr.st1(any, 111);
            (yield* add_menu(win, nul_glyphinfo.v, any, schar((abc ? 0 : cptr.ld1s(any))), 110, NHM.ATR_NONE, clr, __sl39, NHM.MENU_ITEMFLAGS_NONE));
        }
        cptr.st1(any, 102);
        (yield* add_menu(win, nul_glyphinfo.v, any, schar((abc ? 0 : cptr.ld1s(any))), 44, NHM.ATR_NONE, clr, __sl40, NHM.MENU_ITEMFLAGS_NONE));
        cptr.st1(any, 100);
        (yield* add_menu(win, nul_glyphinfo.v, any, schar((abc ? 0 : cptr.ld1s(any))), 92, NHM.ATR_NONE, clr, __sl41, NHM.MENU_ITEMFLAGS_NONE));
        cptr.st1(any, 97);
        (yield* add_menu(win, nul_glyphinfo.v, any, schar((abc ? 0 : cptr.ld1s(any))), 108, NHM.ATR_NONE, clr, __sl42, NHM.MENU_ITEMFLAGS_NONE));
        (yield* Y.icall(end_menu()(win, __sl43)));
        if ((yield* select_menu(win, NHM.PICK_ONE, pick_list)) > 0) {
            ch = cptr.ld1so(pick_list.v, 0, 24);
            cptr.free(pick_list.v);
        } else
            ch = 113;
        (yield* Y.icall(destroy_nhwindow()(win)));
    }
    switch (ch) {
        default:
        case 113:
        break;
        case 109:
        (yield* do_mgivenname());
        break;
        case 105:
        obj = (yield* getobj(__sl3, name_ok, NHM.GETOBJ_PROMPT));
        if (obj)
            (yield* do_oname(obj));
        break;
        case 111:
        obj = (yield* getobj(__sl44, call_ok, NHM.GETOBJ_NOFLAGS));
        if (obj) {
            void (yield* xname(obj));
            if (!(cptr.ldI32o(obj, $obj_dknown) & 1)) {
                (yield* You(__sl45));
            } else {
                (yield* docall(obj));
            }
        }
        break;
        case 102:
        (yield* namefloorobj());
        break;
        case 100:
        (yield* rename_disco());
        break;
        case 97:
        (yield* donamelevel());
        break;
    }
    return NHM.ECMD_OK;
}

/** C ref: do_name.c:605 — @param {CPtr} obj @returns {CPtr} */
function* docall_xname(obj) {
    let otemp = cptr.alloc(216);
    cptr.memcpy(otemp, obj, 216);
    cptr.stPtro(otemp, $obj_oextra, null);
    cptr.stI64o(otemp, $obj_quan, 1n);
    cptr.stI32o(otemp, $obj_blessed, cptr.stI32o(otemp, $obj_cursed, 0));
    if (cptr.ld1so(otemp, $obj_oclass) == NHC.WEAPON_CLASS)
        cptr.stI32o(otemp, $obj_otrapped, 0);
    else if (cptr.ld1so(otemp, $obj_oclass) == NHC.POTION_CLASS)
        cptr.stI32o(otemp, $obj_oeroded, 0);
    else if (cptr.ldI16o(otemp, $obj_otyp) == NHC.TOWEL || cptr.ldI16o(otemp, $obj_otyp) == NHC.STATUE)
        cptr.st1o(otemp, $obj_spe, 0);
    else if (cptr.ldI16o(otemp, $obj_otyp) == NHC.TIN)
        cptr.stI32o(otemp, $obj_known, 0);
    else if (cptr.ldI16o(otemp, $obj_otyp) == NHC.FIGURINE)
        cptr.stI32o(otemp, $obj_corpsenm, NHC.NON_PM);
    else if (cptr.ldI16o(otemp, $obj_otyp) == NHC.HEAVY_IRON_BALL)
        cptr.stI32o(otemp, $obj_owt, cptr.ldI32o2(objects, NHC.HEAVY_IRON_BALL, 120, $objclass_oc_weight));
    else if (cptr.ld1so(otemp, $obj_oclass) == NHC.FOOD_CLASS && (cptr.ldI32o(otemp, $obj_globby) & 1) | 0)
        cptr.stI32o(otemp, $obj_owt, 120);
    return (yield* an((yield* xname(otemp))));
}

/** C ref: do_name.c:636 — @param {CPtr} obj */
export function* docall(obj) {
    let buf = new Uint8Array(256);
    let qbuf = new Uint8Array(128);
    let uname_p;
    let had_name = 0;
    if (!(cptr.ldI32o(obj, $obj_dknown) & 1))
        return;
    (yield* flush_screen(1));
    if (cptr.ld1so(obj, $obj_oclass) == NHC.POTION_CLASS && cptr.ldI32o(obj, $obj_corpsenm))
        void cptr.sprintf(cptr.decay(qbuf), __sl46, (cptr.ldPtro2(obj_descr, cptr.ldI16o((cptr.add(objects, cptr.ldI16o(obj, $obj_otyp), 120)), $objclass_oc_descr_idx), 16, $objdescr_oc_descr)));
    else
        void (yield* safe_qbuf(cptr.decay(qbuf), __sl47, __sl48, obj, docall_xname, simpleonames, __sl49));
    uname_p = cptr.add(cptr.add(objects, cptr.ldI16o(obj, $obj_otyp), 120), $objclass_oc_uname);
    if (!(yield* name_from_player(cptr.decay(buf), cptr.decay(qbuf), cptr.ldPtr(uname_p))))
        return;
    if (cptr.ldPtr(uname_p)) {
        had_name = 1;
        cptr.free(cptr.ldPtr(uname_p)), cptr.stPtr(uname_p, null);
    }
    void (yield* mungspaces(cptr.decay(buf)));
    if (!cptr.ld1s(cptr.decay(buf))) {
        if (had_name)
            (yield* undiscover_object(cptr.ldI16o(obj, $obj_otyp)));
    } else {
        cptr.stPtr(uname_p, (yield* dupstr(cptr.decay(buf))));
        (yield* discover_object(cptr.ldI16o(obj, $obj_otyp), 0, 1, 1));
    }
    if (cptr.ld1so(obj, $obj_where) == NHM.OBJ_INVENT || carrying(cptr.ldI16o(obj, $obj_otyp)))
        (yield* update_inventory());
}

/** C ref: do_name.c:679 */
function* namefloorobj() {
    let cc = cptr.alloc(4);
    let glyph;
    let buf = new Uint8Array(256);
    let obj = cptr.box(null);
    let fakeobj = 0;
    let use_plural;
    cptr.stI16(cc, cptr.ldI16(u)), cptr.stI16o(cc, $nhcoord_y, cptr.ldI16o(u, $you_uy));
    void cptr.sprintf(cptr.decay(buf), __sl50, ((cptr.ldI32o(u, $you_uundetected) & 1) | 0 && ((cptr.ldU64o((cptr.ldPtro(gy, $instance_globals_y_youmonst + $monst_data)), $permonst_mflags1) & 128n) != 0n)) ? __sl51 : __sl52);
    if ((yield* getpos(cc, 0, cptr.decay(buf))) < 0 || cptr.ldI16(cc) <= 0)
        return;
    if (((cptr.ldI16(cc)) == cptr.ldI16(u) && (cptr.ldI16o(cc, $nhcoord_y)) == cptr.ldI16o(u, $you_uy))) {
        obj.v = (cptr.ldPtro3(svl, cptr.ldI16(u), 168, cptr.ldI16o(u, $you_uy), 8, $instance_globals_saved_l_level + $dlevel_t_objects));
    } else {
        glyph = glyph_at(cptr.ldI16(cc), cptr.ldI16o(cc, $nhcoord_y));
        if (glyph_is_object(glyph))
            fakeobj = (yield* object_from_map(glyph, cptr.ldI16(cc), cptr.ldI16o(cc, $nhcoord_y), obj));
    }
    if (!obj.v) {
        (yield* There(__sl53, ((cptr.ldI16(cc)) == cptr.ldI16(u) && (cptr.ldI16o(cc, $nhcoord_y)) == cptr.ldI16o(u, $you_uy)) ? __sl54 : __sl55));
        return;
    }
    void cptr.strcpy(cptr.decay(buf), (cptr.ldI16o(obj.v, $obj_otyp) != NHC.STRANGE_OBJECT) ? (yield* simpleonames(obj.v)) : cptr.ldPtro(obj_descr, NHC.STRANGE_OBJECT, 16));
    use_plural = schar((cptr.ldI64o(obj.v, $obj_quan) > 1n));
    if (Hallucination()) {
        let unames = cptr.alloc(6 * 8);
        let tmpbuf = new Uint8Array(256);
        cptr.stPtro(unames, 0, ((Upolyd() ? (cptr.ldI32o(u, $you_mfemale) & 1) | 0 : cptr.ld1so(flags, $flag_female)) && cptr.ldPtro(gu, $instance_globals_u_urole + $RoleName_f)) ? cptr.ldPtro(gu, $instance_globals_u_urole + $RoleName_f) : cptr.ldPtro(gu, $instance_globals_u_urole), 8);
        cptr.stPtro(unames, 1, rank_of((rn2_on_display_rng(30) + 1) | 0, Role_switch(), cptr.ld1so(flags, $flag_female)), 8);
        cptr.stPtro(unames, 2, (yield* bogusmon(cptr.decay(tmpbuf), null)), 8);
        cptr.stPtro(unames, 3, cptr.ldPtro(unames, 2, 8), 8);
        cptr.stPtro(unames, 4, roguename(), 8);
        cptr.stPtro(unames, 5, __sl56, 8);
        (yield* pline(__sl57, (yield* The(cptr.decay(buf))), use_plural ? __sl58 : __sl59, cptr.ldPtro(unames, rn2_on_display_rng(6), 8)));
    } else if (call_ok(obj.v) == NHC.GETOBJ_EXCLUDE) {
        (yield* pline(__sl60, use_plural ? __sl61 : __sl62, cptr.decay(buf)));
    } else if (!(cptr.ldI32o(obj.v, $obj_dknown) & 1)) {
        (yield* You(__sl63, use_plural ? __sl64 : __sl65, cptr.decay(buf), use_plural ? __sl66 : __sl67));
    } else {
        (yield* docall(obj.v));
    }
    if (fakeobj) {
        cptr.st1o(obj.v, $obj_where, NHM.OBJ_FREE);
        (yield* dealloc_obj(obj.v));
    }
}

/** C ref: do_name.c:759 — char *[34] */
const ghostnames = cptr.alloc(34 * 8);
cptr.stPtro(ghostnames, 0, __sl68);
cptr.stPtro(ghostnames, 8, __sl69);
cptr.stPtro(ghostnames, 16, __sl70);
cptr.stPtro(ghostnames, 24, __sl71);
cptr.stPtro(ghostnames, 32, __sl72);
cptr.stPtro(ghostnames, 40, __sl73);
cptr.stPtro(ghostnames, 48, __sl74);
cptr.stPtro(ghostnames, 56, __sl75);
cptr.stPtro(ghostnames, 64, __sl76);
cptr.stPtro(ghostnames, 72, __sl77);
cptr.stPtro(ghostnames, 80, __sl78);
cptr.stPtro(ghostnames, 88, __sl79);
cptr.stPtro(ghostnames, 96, __sl80);
cptr.stPtro(ghostnames, 104, __sl81);
cptr.stPtro(ghostnames, 112, __sl82);
cptr.stPtro(ghostnames, 120, __sl83);
cptr.stPtro(ghostnames, 128, __sl84);
cptr.stPtro(ghostnames, 136, __sl85);
cptr.stPtro(ghostnames, 144, __sl86);
cptr.stPtro(ghostnames, 152, __sl87);
cptr.stPtro(ghostnames, 160, __sl88);
cptr.stPtro(ghostnames, 168, __sl89);
cptr.stPtro(ghostnames, 176, __sl90);
cptr.stPtro(ghostnames, 184, __sl91);
cptr.stPtro(ghostnames, 192, __sl92);
cptr.stPtro(ghostnames, 200, __sl93);
cptr.stPtro(ghostnames, 208, __sl94);
cptr.stPtro(ghostnames, 216, __sl95);
cptr.stPtro(ghostnames, 224, __sl96);
cptr.stPtro(ghostnames, 232, __sl97);
cptr.stPtro(ghostnames, 240, __sl98);
cptr.stPtro(ghostnames, 248, __sl99);
cptr.stPtro(ghostnames, 256, __sl100);
cptr.stPtro(ghostnames, 264, __sl101);

/** C ref: do_name.c:772 @returns {CPtr} */
export function rndghostname() {
    return (rng_log_enabled() ? (rng_log_set_caller(__sl33, 774, __sl102), rn2(7)) : rn2(7)) ? cptr.ldPtro(ghostnames, (rng_log_enabled() ? (rng_log_set_caller(__sl33, 774, __sl102), rn2(34)) : rn2(34)), 8) : svp;
}

/** C ref: do_name.c:827 — @param {CPtr} mtmp @param {CInt} article @param {CPtr} adjective @param {CInt} suppress @param {CInt} called @returns {CPtr} */
export function* x_monnam(mtmp, article, adjective, suppress, called) {
    let buf = nextmbuf();
    let mdat = cptr.ldPtro(mtmp, $monst_data);
    let pm_name;
    let do_hallu;
    let do_invis;
    let do_it;
    let do_saddle;
    let do_mappear;
    let do_exact;
    let do_name;
    let augment_it;
    let name_at_start;
    let has_adjectives;
    let insertbuf2;
    let mappear_as_mon = schar(((cptr.ld1uo((mtmp), $monst_m_ap_type) & NHM.M_AP_TYPMASK) == NHC.M_AP_MONSTER));
    let bp;
    let buf2 = new Uint8Array(256);
    if (cptr.eq(mtmp, cptr.add(gy, $instance_globals_y_youmonst)))
        return cptr.strcpy(buf, __sl103);
    if (cptr.ldI32(program_state))
        suppress |= NHM.SUPPRESS_HALLUCINATION;
    if (article == NHM.ARTICLE_YOUR && !cptr.ld1so(mtmp, $monst_mtame))
        article = NHM.ARTICLE_THE;
    if ((cptr.ldI32o(u, $you_uswallow) & 1) | 0 && cptr.eq(mtmp, cptr.ldPtro(u, $you_ustuck))) {
        article = NHM.ARTICLE_THE;
        suppress |= NHM.SUPPRESS_INVISIBLE;
    }
    do_hallu = schar((Hallucination() && !(suppress & NHM.SUPPRESS_HALLUCINATION) ? 1 : 0));
    do_invis = schar(((cptr.ldI32o(mtmp, $monst_minvis) & 1) | 0 && !(suppress & NHM.SUPPRESS_INVISIBLE) ? 1 : 0));
    do_it = schar((!canspotmon(mtmp) && article != NHM.ARTICLE_YOUR && !cptr.ldI32(program_state) && !cptr.eq(mtmp, cptr.ldPtro(u, $you_usteed)) && !((cptr.ldI32o(u, $you_uswallow) & 1) | 0 && (cptr.eq(cptr.ldPtro(u, $you_ustuck), (mtmp)))) && !(suppress & NHM.SUPPRESS_IT) ? 1 : 0));
    do_saddle = schar((!(suppress & NHM.SUPPRESS_SADDLE)));
    do_mappear = schar((mappear_as_mon && !(suppress & NHM.SUPPRESS_MAPPEARANCE) ? 1 : 0));
    do_exact = schar(((suppress & NHM.EXACT_NAME) == NHM.EXACT_NAME));
    do_name = schar((!(suppress & NHM.SUPPRESS_NAME) || ((cptr.ldU64o((mdat), $permonst_mflags2) & 524288n) != 0n) ? 1 : 0));
    augment_it = schar(((suppress & NHM.AUGMENT_IT) != 0));
    cptr.st1o(buf, 0, 0);
    if (do_it) {
        let s_one = schar((((cptr.ldU64o((mdat), $permonst_mflags1) & 131072n) != 0n) && !((cptr.ldU64o((mdat), $permonst_mflags1) & 262144n) != 0n) && !((cptr.ldU64o((mdat), $permonst_mflags1) & 65536n) != 0n) ? 1 : 0));
        void cptr.strcpy(buf, !augment_it ? __sl67 : ((!do_hallu ? s_one : !(rng_log_enabled() ? (rng_log_set_caller(__sl33, 881, __sl104), rn2(2)) : rn2(2))) ? __sl105 : __sl106));
        return buf;
    }
    if (((cptr.ldI32o(mtmp, $monst_ispriest) & 1) | 0 || (cptr.ldI32o(mtmp, $monst_isminion) & 1) | 0) && !do_mappear) {
        let name;
        let save_prop = EHalluc_resistance();
        let save_invis = (cptr.ldI32o(mtmp, $monst_minvis) & 1);
        if (!do_hallu)
            cptr.stI64o2(u, NHC.HALLUC_RES, 24, $you_uprops, 1n);
        if (!do_invis)
            cptr.stI32o(mtmp, $monst_minvis, 0);
        name = (yield* priestname(mtmp, article, do_exact, cptr.decay(buf2)));
        cptr.stI64o2(u, NHC.HALLUC_RES, 24, $you_uprops, save_prop);
        cptr.stI32o(mtmp, $monst_minvis, save_invis);
        if (article == NHM.ARTICLE_NONE && !cptr.strncmp(name, __sl6, 4n))
            name = cptr.add(name, 4);
        return cptr.strcpy(buf, name);
    }
    if (do_mappear) {
        pm_name = pmname(cptr.add(mons, cptr.ldI32o(mtmp, $monst_mappearance), 96), Mgender(mtmp));
    } else {
        pm_name = mon_pmname(mtmp);
    }
    if ((cptr.ldI32o(mtmp, $monst_isshk) & 1) | 0 && !do_hallu && !do_mappear) {
        if (adjective && article == NHM.ARTICLE_THE) {
            void cptr.strcpy(buf, __sl6);
            void cptr.strcat(cptr.strcat(buf, adjective), __sl107);
            void cptr.strcat(buf, (yield* shkname(mtmp)));
        } else {
            void cptr.strcat(buf, (yield* shkname(mtmp)));
            if (!cptr.eq(mdat, cptr.add(mons, NHC.PM_SHOPKEEPER, 96)) || do_invis) {
                void cptr.strcat(buf, __sl108);
                if (do_invis)
                    void cptr.strcat(buf, __sl7);
                void cptr.strcat(buf, pm_name);
            }
        }
        return buf;
    }
    if (adjective)
        void cptr.strcat(cptr.strcat(buf, adjective), __sl107);
    if (do_invis)
        void cptr.strcat(buf, __sl7);
    if (do_saddle && (cptr.ldI64o(mtmp, $monst_misc_worn_check) & 1048576n) && !Blind() && !Hallucination())
        void cptr.strcat(buf, __sl109);
    has_adjectives = schar((cptr.ld1so(buf, 0) != 0));
    if (do_hallu) {
        let rnamecode = cptr.box(0);
        let rname = (yield* rndmonnam(rnamecode));
        void cptr.strcat(buf, rname);
        name_at_start = bogon_is_pname(rnamecode.v);
    } else if (do_name && has_mgivenname(mtmp)) {
        let name = (cptr.ldPtr(cptr.ldPtro((mtmp), $monst_mextra)));
        if (cptr.eq(mdat, cptr.add(mons, NHC.PM_GHOST, 96))) {
            void cptr.sprintf(eos(buf), __sl110, (yield* s_suffix(name)));
            name_at_start = 1;
        } else if (called) {
            void cptr.sprintf(eos(buf), __sl111, pm_name, name);
            name_at_start = schar(((cptr.ldU64o((mdat), $permonst_mflags2) & 524288n) != 0n));
        } else if (is_mplayer(mdat) && (bp = (yield* strstri(name, __sl108))) !== null) {
            let pbuf = new Uint8Array(256);
            void cptr.strcpy(cptr.decay(pbuf), name);
            cptr.st1o(cptr.decay(pbuf), BigInt.asIntN(64, cptr.diff(bp, name) + 5n), 0, 1);
            if (has_adjectives)
                void cptr.strcat(cptr.decay(pbuf), buf);
            void cptr.strcat(cptr.decay(pbuf), cptr.add(bp, 5));
            void cptr.strcpy(buf, cptr.decay(pbuf));
            article = NHM.ARTICLE_NONE;
            name_at_start = 1;
        } else {
            void cptr.strcat(buf, name);
            name_at_start = 1;
        }
    } else if (is_mplayer(mdat) && !(cptr.ldI16((cptr.add(u, $you_uz))) == cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level))))) {
        let pbuf = new Uint8Array(256);
        void cptr.strcpy(cptr.decay(pbuf), rank_of(cptr.ld1uo(mtmp, $monst_m_lev), (cptr.ldI32o((mdat), $permonst_pmidx)), schar((cptr.ldI32o(mtmp, $monst_female) & 1))));
        void cptr.strcat(buf, lcase(cptr.decay(pbuf)));
        name_at_start = 0;
    } else {
        void cptr.strcat(buf, pm_name);
        name_at_start = schar(((cptr.ldU64o((mdat), $permonst_mflags2) & 524288n) != 0n));
    }
    if (name_at_start && (article == NHM.ARTICLE_YOUR || !has_adjectives)) {
        if (cptr.eq(mdat, cptr.add(mons, NHC.PM_WIZARD_OF_YENDOR, 96)))
            article = NHM.ARTICLE_THE;
        else
            article = NHM.ARTICLE_NONE;
    } else if ((cptr.ldU16o(mdat, $permonst_geno) & NHM.G_UNIQ) != 0 && article == NHM.ARTICLE_A) {
        article = NHM.ARTICLE_THE;
    }
    insertbuf2 = 1;
    cptr.st1o(cptr.decay(buf2), 0, 0, 1);
    switch (article) {
        case NHM.ARTICLE_YOUR:
        void cptr.strcpy(cptr.decay(buf2), __sl112);
        break;
        case NHM.ARTICLE_THE:
        void cptr.strcpy(cptr.decay(buf2), __sl6);
        break;
        case NHM.ARTICLE_A:
        void (yield* just_an(cptr.decay(buf2), buf));
        break;
        case NHM.ARTICLE_NONE:
        default:
        insertbuf2 = 0;
        break;
    }
    if (insertbuf2) {
        void cptr.strcat(cptr.decay(buf2), buf);
        void cptr.strcpy(buf, cptr.decay(buf2));
    }
    return buf;
}

/** C ref: do_name.c:1035 — @param {CPtr} mtmp @returns {CPtr} */
export function* l_monnam(mtmp) {
    return (yield* x_monnam(mtmp, NHM.ARTICLE_NONE, null, (has_mgivenname(mtmp)) ? NHM.SUPPRESS_SADDLE : 0, 1));
}

/** C ref: do_name.c:1042 — @param {CPtr} mtmp @returns {CPtr} */
export function* mon_nam(mtmp) {
    return (yield* x_monnam(mtmp, NHM.ARTICLE_THE, null, (has_mgivenname(mtmp)) ? NHM.SUPPRESS_SADDLE : 0, 0));
}

/** C ref: do_name.c:1054 — @param {CPtr} mtmp @returns {CPtr} */
export function* noit_mon_nam(mtmp) {
    return (yield* x_monnam(mtmp, NHM.ARTICLE_YOUR, null, (has_mgivenname(mtmp) ? 9 : NHM.SUPPRESS_IT), 0));
}

/** C ref: do_name.c:1065 — @param {CPtr} mtmp @returns {CPtr} */
export function* some_mon_nam(mtmp) {
    return (yield* x_monnam(mtmp, NHM.ARTICLE_THE, null, (has_mgivenname(mtmp) ? 72 : NHM.AUGMENT_IT), 0));
}

/** C ref: do_name.c:1074 — @param {CPtr} mtmp @returns {CPtr} */
export function* Monnam(mtmp) {
    let bp = (yield* mon_nam(mtmp));
    cptr.st1(bp, highc(cptr.ld1s(bp)));
    return bp;
}

/** C ref: do_name.c:1083 — @param {CPtr} mtmp @returns {CPtr} */
export function* noit_Monnam(mtmp) {
    let bp = (yield* noit_mon_nam(mtmp));
    cptr.st1(bp, highc(cptr.ld1s(bp)));
    return bp;
}

/** C ref: do_name.c:1092 — @param {CPtr} mtmp @returns {CPtr} */
export function* Some_Monnam(mtmp) {
    let bp = (yield* some_mon_nam(mtmp));
    cptr.st1(bp, highc(cptr.ld1s(bp)));
    return bp;
}

/** C ref: do_name.c:1102 — @param {CPtr} mtmp @param {CInt} article @returns {CPtr} */
export function* noname_monnam(mtmp, article) {
    return (yield* x_monnam(mtmp, article, null, NHM.SUPPRESS_NAME, 0));
}

/** C ref: do_name.c:1110 — @param {CPtr} mtmp @returns {CPtr} */
export function* m_monnam(mtmp) {
    return (yield* x_monnam(mtmp, NHM.ARTICLE_NONE, null, NHM.EXACT_NAME, 0));
}

/** C ref: do_name.c:1117 — @param {CPtr} mtmp @returns {CPtr} */
export function* y_monnam(mtmp) {
    let prefix;
    let suppression_flag;
    prefix = cptr.ld1so(mtmp, $monst_mtame) ? NHM.ARTICLE_YOUR : NHM.ARTICLE_THE;
    suppression_flag = (has_mgivenname(mtmp) || cptr.eq(mtmp, cptr.ldPtro(u, $you_usteed))) ? NHM.SUPPRESS_SADDLE : 0;
    return (yield* x_monnam(mtmp, prefix, null, suppression_flag, 0));
}

/** C ref: do_name.c:1133 — @param {CPtr} mtmp @returns {CPtr} */
export function* YMonnam(mtmp) {
    let bp = (yield* y_monnam(mtmp));
    cptr.st1(bp, highc(cptr.ld1s(bp)));
    return bp;
}

/** C ref: do_name.c:1142 — @param {CPtr} mtmp @param {CPtr} adj @returns {CPtr} */
export function* Adjmonnam(mtmp, adj) {
    let bp = (yield* x_monnam(mtmp, NHM.ARTICLE_THE, adj, has_mgivenname(mtmp) ? NHM.SUPPRESS_SADDLE : 0, 0));
    cptr.st1(bp, highc(cptr.ld1s(bp)));
    return bp;
}

/** C ref: do_name.c:1152 — @param {CPtr} mtmp @returns {CPtr} */
export function* a_monnam(mtmp) {
    return (yield* x_monnam(mtmp, NHM.ARTICLE_A, null, has_mgivenname(mtmp) ? NHM.SUPPRESS_SADDLE : 0, 0));
}

/** C ref: do_name.c:1159 — @param {CPtr} mtmp @returns {CPtr} */
export function* Amonnam(mtmp) {
    let bp = (yield* a_monnam(mtmp));
    cptr.st1(bp, highc(cptr.ld1s(bp)));
    return bp;
}

/** C ref: do_name.c:1170 — @param {CPtr} mon @param {CInt} article @param {CPtr} outbuf @returns {CPtr} */
export function* distant_monnam(mon, article, outbuf) {
    if (cptr.eq(cptr.ldPtro(mon, $monst_data), cptr.add(mons, NHC.PM_HIGH_CLERIC, 96)) && !Hallucination() && (((cptr.ldI16o((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)), $d_level_dlevel) || cptr.ldI16((cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))) && on_level(cptr.add(u, $you_uz), cptr.add(svd, $instance_globals_saved_d_dungeon_topology + $dgn_topology_d_astral_level)))) && !m_next2u(mon)) {
        void cptr.strcpy(outbuf, article == NHM.ARTICLE_THE ? __sl6 : __sl0);
        void cptr.strcat(outbuf, (cptr.ldI32o(mon, $monst_female) & 1) | 0 ? __sl113 : __sl114);
    } else {
        void cptr.strcpy(outbuf, (yield* x_monnam(mon, article, null, 0, 1)));
    }
    return outbuf;
}

/** C ref: do_name.c:1191 — @param {CPtr} mon @param {CPtr} other_mon @returns {CPtr} */
export function* mon_nam_too(mon, other_mon) {
    let outbuf;
    if (!cptr.eq(mon, other_mon)) {
        outbuf = (yield* mon_nam(mon));
    } else {
        outbuf = nextmbuf();
        switch (pronoun_gender(mon, NHM.PRONOUN_HALLU)) {
            case 0:
            void cptr.strcpy(outbuf, __sl115);
            break;
            case 1:
            void cptr.strcpy(outbuf, __sl116);
            break;
            default:
            case 2:
            void cptr.strcpy(outbuf, __sl117);
            break;
            case 3:
            void cptr.strcpy(outbuf, __sl118);
            break;
        }
    }
    return outbuf;
}

/** C ref: do_name.c:1221 — @param {CPtr} mon @param {CPtr} monnamtext @param {CPtr} verb @param {CPtr} othertext @returns {CPtr} */
export function* monverbself(mon, monnamtext, verb, othertext) {
    let verbs;
    let selfbuf = new Uint8Array(40);
    void cptr.strcpy(cptr.decay(selfbuf), (yield* mon_nam_too(mon, mon)));
    verbs = (yield* vtense(cptr.decay(selfbuf), verb));
    if (!strcmp(verb, verbs)) {
        monnamtext = (yield* makeplural(monnamtext));
        if (!(yield* strncmpi((monnamtext), (cptr.ldPtro2(genders, 3, 48, $Gender_he)), -1))) {
            let capitaliz = schar((cptr.ld1so(monnamtext, 0) == highc(cptr.ld1so(monnamtext, 0))));
            void cptr.strcpy(monnamtext, cptr.ldPtro2(genders, 3, 48, $Gender_him));
            if (capitaliz)
                cptr.st1o(monnamtext, 0, highc(cptr.ld1so(monnamtext, 0)));
        }
    }
    void cptr.strcat(cptr.strcat(monnamtext, __sl107), verbs);
    if (othertext && cptr.ld1s(othertext))
        void cptr.strcat(cptr.strcat(monnamtext, __sl107), othertext);
    void cptr.strcat(cptr.strcat(monnamtext, __sl107), cptr.decay(selfbuf));
    return monnamtext;
}

/** C ref: do_name.c:1254 — @param {CPtr} mon @param {CInt} ckloc @returns {CPtr} */
export function minimal_monnam(mon, ckloc) {
    let ptr;
    let outbuf = nextmbuf();
    if (!mon) {
        void cptr.strcpy(outbuf, __sl119);
    } else if ((ptr = cptr.ldPtro(mon, $monst_data)) === null) {
        void cptr.strcpy(outbuf, __sl120);
    } else if (cptr.cmp(ptr, cptr.add(mons, 0, 96)) < 0) {
        void cptr.sprintf(outbuf, __sl121, fmt_ptr(cptr.ldPtro(mon, $monst_data)), fmt_ptr(cptr.add(mons, 0, 96)));
    } else if (cptr.cmp(ptr, cptr.add(mons, NHC.NUMMONS, 96)) >= 0) {
        void cptr.sprintf(outbuf, __sl122, fmt_ptr(cptr.ldPtro(mon, $monst_data)), fmt_ptr(cptr.add(mons, NHC.NUMMONS, 96)));
    } else if (ckloc && cptr.eq(ptr, cptr.add(mons, NHC.PM_LONG_WORM, 96)) && cptr.ldI16o(mon, $monst_mx) && !cptr.eq(cptr.ldPtro3(svl, cptr.ldI16o(mon, $monst_mx), 168, cptr.ldI16o(mon, $monst_my), 8, $instance_globals_saved_l_level + $dlevel_t_monsters), mon)) {
        void cptr.sprintf(outbuf, __sl123, pmname(cptr.add(mons, NHC.PM_LONG_WORM_TAIL, 96), Mgender(mon)), cptr.ldI16o(mon, $monst_mx), cptr.ldI16o(mon, $monst_my));
    } else {
        void cptr.sprintf(outbuf, __sl124, cptr.ld1so(mon, $monst_mtame) ? __sl125 : ((cptr.ldI32o(mon, $monst_mpeaceful) & 1) | 0 ? __sl126 : __sl0), mon_pmname(mon), cptr.ldI16o(mon, $monst_mx), cptr.ldI16o(mon, $monst_my));
        if (cptr.ldI16o(mon, $monst_cham) != NHC.NON_PM)
            void cptr.sprintf(eos(outbuf), __sl127, pmname(cptr.add(mons, cptr.ldI16o(mon, $monst_cham), 96), Mgender(mon)));
    }
    return outbuf;
}

/** C ref: do_name.c:1289 — @param {CPtr} mtmp @returns {CInt} */
export function Mgender(mtmp) {
    let mgender = NHC.MALE;
    if (cptr.eq(mtmp, cptr.add(gy, $instance_globals_y_youmonst))) {
        if (Upolyd() ? (cptr.ldI32o(u, $you_mfemale) & 1) | 0 : cptr.ld1so(flags, $flag_female))
            mgender = NHC.FEMALE;
    } else if ((cptr.ldI32o(mtmp, $monst_female) & 1)) {
        mgender = NHC.FEMALE;
    }
    return mgender;
}

/** C ref: do_name.c:1303 — @param {CPtr} pm @param {CInt} mgender @returns {CPtr} */
export function pmname(pm, mgender) {
    if (mgender < NHC.MALE || mgender >= NHC.NUM_MGENDERS || !cptr.ldPtro(pm, mgender, 8))
        mgender = NHC.NEUTRAL;
    return cptr.ldPtro(pm, mgender, 8);
}

/** C ref: do_name.c:1313 — @param {CPtr} mon @returns {CPtr} */
export function mon_pmname(mon) {
    return pmname(cptr.ldPtro(mon, $monst_data), Mgender(mon));
}

/** C ref: do_name.c:1321 — @param {CPtr} obj @returns {CPtr} */
export function* obj_pmname(obj) {
    if ((cptr.ldI16o(obj, $obj_otyp) == NHC.CORPSE || cptr.ldI16o(obj, $obj_otyp) == NHC.STATUE || cptr.ldI16o(obj, $obj_otyp) == NHC.FIGURINE) && ismnum(cptr.ldI32o(obj, $obj_corpsenm))) {
        let cgend = (cptr.ld1so(obj, $obj_spe) & NHM.CORPSTAT_GENDER);
        let mgend = ((cgend == NHM.CORPSTAT_MALE) ? NHC.MALE : ((cgend == NHM.CORPSTAT_FEMALE) ? NHC.FEMALE : NHC.NEUTRAL));
        let mndx = cptr.ldI32o(obj, $obj_corpsenm);
        if (mndx == NHC.PM_ALIGNED_CLERIC && cgend == NHM.CORPSTAT_RANDOM)
            mndx = NHC.PM_CLERIC;
        return pmname(cptr.add(mons, mndx, 96), mgend);
    }
    (yield* impossible(__sl128, cptr.ldI16o(obj, $obj_otyp), cptr.ldI32o(obj, $obj_corpsenm)));
    return __sl129;
}

/** C ref: do_name.c:1365 — char[6] */
export const bogon_codes = cptr.bytes("-_+|=");

/** C ref: do_name.c:1369 — @param {CPtr} buf @param {CPtr} code @returns {CPtr} */
export function* bogusmon(buf, code) {
    let mnam = buf;
    if (code)
        cptr.st1(code, 0);
    (yield* get_rnd_text(__sl130, buf, rn2_on_display_rng, NHM.MD_PAD_BOGONS));
    if (!cptr.ld1s(mnam)) {
        void cptr.strcpy(buf, __sl131);
    } else if (cptr.strchr(cptr.decay(bogon_codes), cptr.ld1s(mnam))) {
        if (code)
            cptr.st1(code, cptr.ld1s(mnam));
        mnam = cptr.add(mnam, 1);
    }
    return mnam;
}

const __static_rndmonnam_buf = new Uint8Array(256); /** C ref: do_name.c:1391 — char[256] (function-static) */

/** C ref: do_name.c:1389 — @param {CPtr} code @returns {CPtr} */
export function* rndmonnam(code) {
    let mnam;
    let name;
    if (code)
        cptr.st1(code, 0);
    do {
        name = (rn2_on_display_rng(((((NHC.SPECIAL_PM + 100) | 0) - NHC.LOW_PM) | 0)) + NHC.LOW_PM) | 0;
    } while (name < NHC.SPECIAL_PM && (((cptr.ldU64o((cptr.add(mons, name, 96)), $permonst_mflags2) & 524288n) != 0n) || (cptr.ldU16o2(mons, name, 96, $permonst_geno) & NHM.G_NOGEN)));
    if (name >= NHC.SPECIAL_PM) {
        mnam = (yield* bogusmon(cptr.decay(__static_rndmonnam_buf), code));
    } else {
        mnam = cptr.strcpy(cptr.decay(__static_rndmonnam_buf), pmname(cptr.add(mons, name, 96), rn2_on_display_rng(2)));
    }
    return mnam;
}

/** C ref: do_name.c:1415 — @param {CInt} code @returns {CInt} */
export function bogon_is_pname(code) {
    if (!code)
        return 0;
    return schar((cptr.strchr(__sl132, code) ? 1 : 0));
}

/** C ref: do_name.c:1424 @returns {CPtr} */
export function roguename() {
    let i;
    let opts;
    if ((opts = nh_getenv(__sl133)) !== null) {
        for (i = opts; cptr.ld1s(i); i = cptr.add(i, 1))
            if (!cptr.strncmp(__sl134, i, 5n)) {
                let j;
                if ((j = cptr.strchr(cptr.add(i, 5), 44)) !== null)
                    cptr.st1(j, 0);
                return cptr.add(i, 5);
            }
    }
    return (rng_log_enabled() ? (rng_log_set_caller(__sl33, 1437, __sl135), rn2(3)) : rn2(3)) ? ((rng_log_enabled() ? (rng_log_set_caller(__sl33, 1437, __sl135), rn2(2)) : rn2(2)) ? __sl136 : __sl137) : __sl138;
}

/** C ref: do_name.c:1441 — char *[74] */
const hcolors = cptr.alloc(74 * 8);
cptr.stPtro(hcolors, 0, __sl139);
cptr.stPtro(hcolors, 8, __sl140);
cptr.stPtro(hcolors, 16, __sl141);
cptr.stPtro(hcolors, 24, __sl142);
cptr.stPtro(hcolors, 32, __sl143);
cptr.stPtro(hcolors, 40, __sl144);
cptr.stPtro(hcolors, 48, __sl145);
cptr.stPtro(hcolors, 56, __sl146);
cptr.stPtro(hcolors, 64, __sl147);
cptr.stPtro(hcolors, 72, __sl148);
cptr.stPtro(hcolors, 80, __sl149);
cptr.stPtro(hcolors, 88, __sl150);
cptr.stPtro(hcolors, 96, __sl151);
cptr.stPtro(hcolors, 104, __sl152);
cptr.stPtro(hcolors, 112, __sl153);
cptr.stPtro(hcolors, 120, __sl154);
cptr.stPtro(hcolors, 128, __sl155);
cptr.stPtro(hcolors, 136, __sl156);
cptr.stPtro(hcolors, 144, __sl157);
cptr.stPtro(hcolors, 152, __sl158);
cptr.stPtro(hcolors, 160, __sl159);
cptr.stPtro(hcolors, 168, __sl160);
cptr.stPtro(hcolors, 176, __sl161);
cptr.stPtro(hcolors, 184, __sl162);
cptr.stPtro(hcolors, 192, __sl163);
cptr.stPtro(hcolors, 200, __sl164);
cptr.stPtro(hcolors, 208, __sl165);
cptr.stPtro(hcolors, 216, __sl166);
cptr.stPtro(hcolors, 224, __sl167);
cptr.stPtro(hcolors, 232, __sl168);
cptr.stPtro(hcolors, 240, __sl169);
cptr.stPtro(hcolors, 248, __sl170);
cptr.stPtro(hcolors, 256, __sl171);
cptr.stPtro(hcolors, 264, __sl172);
cptr.stPtro(hcolors, 272, __sl173);
cptr.stPtro(hcolors, 280, __sl174);
cptr.stPtro(hcolors, 288, __sl175);
cptr.stPtro(hcolors, 296, __sl176);
cptr.stPtro(hcolors, 304, __sl177);
cptr.stPtro(hcolors, 312, __sl178);
cptr.stPtro(hcolors, 320, __sl179);
cptr.stPtro(hcolors, 328, __sl180);
cptr.stPtro(hcolors, 336, __sl181);
cptr.stPtro(hcolors, 344, __sl182);
cptr.stPtro(hcolors, 352, __sl183);
cptr.stPtro(hcolors, 360, __sl184);
cptr.stPtro(hcolors, 368, __sl185);
cptr.stPtro(hcolors, 376, __sl186);
cptr.stPtro(hcolors, 384, __sl187);
cptr.stPtro(hcolors, 392, __sl188);
cptr.stPtro(hcolors, 400, __sl189);
cptr.stPtro(hcolors, 408, __sl190);
cptr.stPtro(hcolors, 416, __sl191);
cptr.stPtro(hcolors, 424, __sl192);
cptr.stPtro(hcolors, 432, __sl193);
cptr.stPtro(hcolors, 440, __sl194);
cptr.stPtro(hcolors, 448, __sl195);
cptr.stPtro(hcolors, 456, __sl196);
cptr.stPtro(hcolors, 464, __sl197);
cptr.stPtro(hcolors, 472, __sl198);
cptr.stPtro(hcolors, 480, __sl199);
cptr.stPtro(hcolors, 488, __sl200);
cptr.stPtro(hcolors, 496, __sl201);
cptr.stPtro(hcolors, 504, __sl202);
cptr.stPtro(hcolors, 512, __sl203);
cptr.stPtro(hcolors, 520, __sl204);
cptr.stPtro(hcolors, 528, __sl205);
cptr.stPtro(hcolors, 536, __sl206);
cptr.stPtro(hcolors, 544, __sl207);
cptr.stPtro(hcolors, 552, __sl208);
cptr.stPtro(hcolors, 560, __sl209);
cptr.stPtro(hcolors, 568, __sl210);
cptr.stPtro(hcolors, 576, __sl211);
cptr.stPtro(hcolors, 584, __sl212);

/** C ref: do_name.c:1461 — @param {CPtr} colorpref @returns {CPtr} */
export function hcolor(colorpref) {
    return (Hallucination() || !colorpref) ? cptr.ldPtro(hcolors, rn2_on_display_rng(74), 8) : colorpref;
}

/** C ref: do_name.c:1470 @returns {CPtr} */
export function rndcolor() {
    let k = (rng_log_enabled() ? (rng_log_set_caller(__sl33, 1472, __sl213), rn2(NHM.CLR_MAX)) : rn2(NHM.CLR_MAX));
    return Hallucination() ? hcolor(null) : ((k == NHM.NO_COLOR) ? __sl188 : cptr.ldPtro(c_obj_colors, k, 8));
}

/** C ref: do_name.c:1479 — char *[40] */
const hliquids = cptr.alloc(40 * 8);
cptr.stPtro(hliquids, 0, __sl214);
cptr.stPtro(hliquids, 8, __sl215);
cptr.stPtro(hliquids, 16, __sl216);
cptr.stPtro(hliquids, 24, __sl217);
cptr.stPtro(hliquids, 32, __sl218);
cptr.stPtro(hliquids, 40, __sl219);
cptr.stPtro(hliquids, 48, __sl220);
cptr.stPtro(hliquids, 56, __sl221);
cptr.stPtro(hliquids, 64, __sl222);
cptr.stPtro(hliquids, 72, __sl223);
cptr.stPtro(hliquids, 80, __sl224);
cptr.stPtro(hliquids, 88, __sl225);
cptr.stPtro(hliquids, 96, __sl226);
cptr.stPtro(hliquids, 104, __sl227);
cptr.stPtro(hliquids, 112, __sl228);
cptr.stPtro(hliquids, 120, __sl229);
cptr.stPtro(hliquids, 128, __sl230);
cptr.stPtro(hliquids, 136, __sl231);
cptr.stPtro(hliquids, 144, __sl232);
cptr.stPtro(hliquids, 152, __sl233);
cptr.stPtro(hliquids, 160, __sl234);
cptr.stPtro(hliquids, 168, __sl235);
cptr.stPtro(hliquids, 176, __sl236);
cptr.stPtro(hliquids, 184, __sl237);
cptr.stPtro(hliquids, 192, __sl238);
cptr.stPtro(hliquids, 200, __sl239);
cptr.stPtro(hliquids, 208, __sl240);
cptr.stPtro(hliquids, 216, __sl241);
cptr.stPtro(hliquids, 224, __sl242);
cptr.stPtro(hliquids, 232, __sl243);
cptr.stPtro(hliquids, 240, __sl244);
cptr.stPtro(hliquids, 248, __sl245);
cptr.stPtro(hliquids, 256, __sl246);
cptr.stPtro(hliquids, 264, __sl247);
cptr.stPtro(hliquids, 272, __sl248);
cptr.stPtro(hliquids, 280, __sl249);
cptr.stPtro(hliquids, 288, __sl250);
cptr.stPtro(hliquids, 296, __sl251);
cptr.stPtro(hliquids, 304, __sl252);
cptr.stPtro(hliquids, 312, __sl253);

/** C ref: do_name.c:1493 — @param {CPtr} liquidpref @returns {CPtr} */
export function hliquid(liquidpref) {
    let hallucinate = schar((Hallucination() && !cptr.ldI32(program_state) ? 1 : 0));
    if (hallucinate || !liquidpref || !cptr.ld1s(liquidpref)) {
        let indx;
        let count = 40;
        if (liquidpref && cptr.ld1s(liquidpref))
            ++count;
        indx = rn2_on_display_rng(count);
        if (((indx) >= 0 && (indx) < 40))
            return cptr.ldPtro(hliquids, indx, 8);
    }
    return liquidpref;
}

/** C ref: do_name.c:1514 — char *[22] */
const coynames = cptr.alloc(22 * 8);
cptr.stPtro(coynames, 0, __sl254);
cptr.stPtro(coynames, 8, __sl255);
cptr.stPtro(coynames, 16, __sl256);
cptr.stPtro(coynames, 24, __sl257);
cptr.stPtro(coynames, 32, __sl258);
cptr.stPtro(coynames, 40, __sl259);
cptr.stPtro(coynames, 48, __sl260);
cptr.stPtro(coynames, 56, __sl261);
cptr.stPtro(coynames, 64, __sl262);
cptr.stPtro(coynames, 72, __sl263);
cptr.stPtro(coynames, 80, __sl264);
cptr.stPtro(coynames, 88, __sl265);
cptr.stPtro(coynames, 96, __sl266);
cptr.stPtro(coynames, 104, __sl267);
cptr.stPtro(coynames, 112, __sl268);
cptr.stPtro(coynames, 120, __sl269);
cptr.stPtro(coynames, 128, __sl270);
cptr.stPtro(coynames, 136, __sl271);
cptr.stPtro(coynames, 144, __sl272);
cptr.stPtro(coynames, 152, __sl273);
cptr.stPtro(coynames, 160, __sl274);
cptr.stPtro(coynames, 168, __sl275);

/** C ref: do_name.c:1526 — @param {CPtr} mtmp @param {CPtr} buf @returns {CPtr} */
export function* coyotename(mtmp, buf) {
    if (mtmp && buf) {
        void cptr.sprintf(buf, __sl276, (yield* x_monnam(mtmp, NHM.ARTICLE_NONE, null, 0, 1)), (cptr.ldI32o(mtmp, $monst_mcan) & 1) | 0 ? cptr.ldPtro(coynames, (22 - 1) | 0, 8) : cptr.ldPtro(coynames, u32mod(cptr.ldI32o(mtmp, $monst_m_id), ((22 - 1) | 0) >>> 0), 8));
    }
    return buf;
}

const __static_rndorcname_v = cptr.alloc(4 * 8);
cptr.stPtro(__static_rndorcname_v, 0, __sl280);
cptr.stPtro(__static_rndorcname_v, 8, __sl281);
cptr.stPtro(__static_rndorcname_v, 16, __sl282);
cptr.stPtro(__static_rndorcname_v, 24, __sl283); /** C ref: do_name.c:1540 — char *[4] (function-static) */
const __static_rndorcname_snd = cptr.alloc(11 * 8);
cptr.stPtro(__static_rndorcname_snd, 0, __sl284);
cptr.stPtro(__static_rndorcname_snd, 8, __sl285);
cptr.stPtro(__static_rndorcname_snd, 16, __sl286);
cptr.stPtro(__static_rndorcname_snd, 24, __sl287);
cptr.stPtro(__static_rndorcname_snd, 32, __sl288);
cptr.stPtro(__static_rndorcname_snd, 40, __sl289);
cptr.stPtro(__static_rndorcname_snd, 48, __sl290);
cptr.stPtro(__static_rndorcname_snd, 56, __sl291);
cptr.stPtro(__static_rndorcname_snd, 64, __sl292);
cptr.stPtro(__static_rndorcname_snd, 72, __sl293);
cptr.stPtro(__static_rndorcname_snd, 80, __sl294); /** C ref: do_name.c:1541 — char *[11] (function-static) */

/** C ref: do_name.c:1538 — @param {CPtr} s @returns {CPtr} */
export function rndorcname(s) {
    let i;
    let iend = (((rng_log_enabled() ? (rng_log_set_caller(__sl33, 1543, __sl277), rn2(2)) : rn2(2)) + 3) | 0);
    let vstart = (rng_log_enabled() ? (rng_log_set_caller(__sl33, 1543, __sl277), rn2(2)) : rn2(2));
    if (s) {
        cptr.st1(s, 0);
        for (i = 0; i < iend; ++i) {
            vstart = (1 - vstart) | 0;
            void cptr.sprintf(eos(s), __sl278, (i > 0 && !(rng_log_enabled() ? (rng_log_set_caller(__sl33, 1549, __sl277), rn2(30)) : rn2(30))) ? __sl279 : __sl0, vstart ? cptr.ldPtro(__static_rndorcname_v, (rng_log_enabled() ? (rng_log_set_caller(__sl33, 1550, __sl277), rn2(4)) : rn2(4)), 8) : cptr.ldPtro(__static_rndorcname_snd, (rng_log_enabled() ? (rng_log_set_caller(__sl33, 1550, __sl277), rn2(11)) : rn2(11)), 8));
        }
    }
    return s;
}

/** C ref: do_name.c:1557 — @param {CPtr} mtmp @param {CPtr} gang @param {CPtr} other @returns {CPtr} */
export function* christen_orc(mtmp, gang, other) {
    let sz = 0;
    let buf = new Uint8Array(256);
    let buf2 = new Uint8Array(256);
    let orcname;
    orcname = rndorcname(cptr.decay(buf2));
    sz = Number(BigInt.asIntN(32, cptr.strlen(orcname)));
    if (gang)
        sz = (sz + Number(BigInt.asIntN(32, (BigInt.asUintN(64, BigInt.asUintN(64, cptr.strlen(gang) + 5n) - 1n))))) | 0;
    else if (other)
        sz = (sz + Number(BigInt.asIntN(32, cptr.strlen(other)))) | 0;
    if (sz < NHM.BUFSZ) {
        let gbuf = new Uint8Array(256);
        let nameit = 0;
        if (gang) {
            void cptr.sprintf(cptr.decay(buf), __sl295, upstart(orcname), upstart(cptr.strcpy(cptr.decay(gbuf), gang)));
            nameit = 1;
        } else if (other) {
            void cptr.sprintf(cptr.decay(buf), __sl278, upstart(orcname), other);
            nameit = 1;
        }
        if (nameit)
            mtmp = (yield* christen_monst(mtmp, cptr.decay(buf)));
    }
    return mtmp;
}

/** C ref: do_name.c:1591 — char *[41] */
const sir_Terry_novels = cptr.alloc(41 * 8);
cptr.stPtro(sir_Terry_novels, 0, __sl296);
cptr.stPtro(sir_Terry_novels, 8, __sl297);
cptr.stPtro(sir_Terry_novels, 16, __sl298);
cptr.stPtro(sir_Terry_novels, 24, __sl299);
cptr.stPtro(sir_Terry_novels, 32, __sl300);
cptr.stPtro(sir_Terry_novels, 40, __sl301);
cptr.stPtro(sir_Terry_novels, 48, __sl302);
cptr.stPtro(sir_Terry_novels, 56, __sl303);
cptr.stPtro(sir_Terry_novels, 64, __sl304);
cptr.stPtro(sir_Terry_novels, 72, __sl305);
cptr.stPtro(sir_Terry_novels, 80, __sl306);
cptr.stPtro(sir_Terry_novels, 88, __sl307);
cptr.stPtro(sir_Terry_novels, 96, __sl308);
cptr.stPtro(sir_Terry_novels, 104, __sl309);
cptr.stPtro(sir_Terry_novels, 112, __sl310);
cptr.stPtro(sir_Terry_novels, 120, __sl311);
cptr.stPtro(sir_Terry_novels, 128, __sl312);
cptr.stPtro(sir_Terry_novels, 136, __sl313);
cptr.stPtro(sir_Terry_novels, 144, __sl314);
cptr.stPtro(sir_Terry_novels, 152, __sl315);
cptr.stPtro(sir_Terry_novels, 160, __sl316);
cptr.stPtro(sir_Terry_novels, 168, __sl317);
cptr.stPtro(sir_Terry_novels, 176, __sl318);
cptr.stPtro(sir_Terry_novels, 184, __sl319);
cptr.stPtro(sir_Terry_novels, 192, __sl320);
cptr.stPtro(sir_Terry_novels, 200, __sl321);
cptr.stPtro(sir_Terry_novels, 208, __sl322);
cptr.stPtro(sir_Terry_novels, 216, __sl323);
cptr.stPtro(sir_Terry_novels, 224, __sl324);
cptr.stPtro(sir_Terry_novels, 232, __sl325);
cptr.stPtro(sir_Terry_novels, 240, __sl326);
cptr.stPtro(sir_Terry_novels, 248, __sl327);
cptr.stPtro(sir_Terry_novels, 256, __sl328);
cptr.stPtro(sir_Terry_novels, 264, __sl329);
cptr.stPtro(sir_Terry_novels, 272, __sl330);
cptr.stPtro(sir_Terry_novels, 280, __sl331);
cptr.stPtro(sir_Terry_novels, 288, __sl332);
cptr.stPtro(sir_Terry_novels, 296, __sl333);
cptr.stPtro(sir_Terry_novels, 304, __sl334);
cptr.stPtro(sir_Terry_novels, 312, __sl335);
cptr.stPtro(sir_Terry_novels, 320, __sl336);

/** C ref: do_name.c:1611 — @param {CPtr} novidx @returns {CPtr} */
export function noveltitle(novidx) {
    let j;
    let k = 41;
    j = (rng_log_enabled() ? (rng_log_set_caller(__sl33, 1615, __sl337), rn2(k)) : rn2(k));
    if (novidx) {
        if (cptr.ldI32(novidx) == -1)
            cptr.stI32(novidx, j);
        else if (cptr.ldI32(novidx) >= 0 && cptr.ldI32(novidx) < k)
            j = cptr.ldI32(novidx);
    }
    return cptr.ldPtro(sir_Terry_novels, j, 8);
}

/** C ref: do_name.c:1627 — @param {CPtr} lookname @param {CPtr} idx @returns {CPtr} */
export function* lookup_novel(lookname, idx) {
    let k;
    if (!(yield* strncmpi(((yield* The(lookname))), (__sl338), -1)))
        lookname = cptr.ldPtro(sir_Terry_novels, 0, 8);
    else if (!(yield* strncmpi((lookname), (__sl339), -1)))
        lookname = cptr.ldPtro(sir_Terry_novels, 4, 8);
    else if (!(yield* strncmpi((lookname), (__sl340), -1)))
        lookname = cptr.ldPtro(sir_Terry_novels, 17, 8);
    else if (!(yield* strncmpi(((yield* The(lookname))), (__sl341), -1)))
        lookname = cptr.ldPtro(sir_Terry_novels, 27, 8);
    else if (!(yield* strncmpi((lookname), (__sl342), -1)))
        lookname = cptr.ldPtro(sir_Terry_novels, 33, 8);
    for (k = 0; k < 41; ++k) {
        if (!(yield* strncmpi((lookname), (cptr.ldPtro(sir_Terry_novels, k, 8)), -1)) || !(yield* strncmpi(((yield* The(lookname))), (cptr.ldPtro(sir_Terry_novels, k, 8)), -1))) {
            if (idx)
                cptr.stI32(idx, k);
            return cptr.ldPtro(sir_Terry_novels, k, 8);
        }
    }
    if (idx && ((cptr.ldI32(idx)) >= 0 && (cptr.ldI32(idx)) < 41))
        return cptr.ldPtro(sir_Terry_novels, cptr.ldI32(idx), 8);
    return null;
}

// --- BEGIN c2js reset block (tools/c2js/resetify.mjs) — do not edit ---
// 11 bindings: 0 rebound+refilled, 1 rebound, 10 refilled.
// S/P are supplied by js/generated-y/__reset.js so this module needs no new import.
let __c2js_rs = null;
export function __captureState(S) { __c2js_rs = [S(__static_nextmbuf_bufs), S(__static_nextmbuf_bufidx), S(ghostnames), S(bogon_codes), S(__static_rndmonnam_buf), S(hcolors), S(hliquids), S(coynames), S(__static_rndorcname_v), S(__static_rndorcname_snd), S(sir_Terry_novels)]; }
export function __resetState(P) {
    const r = __c2js_rs;
    if (r === null) throw new Error("do_name.js: __resetState before __captureState");
    P(r[0]);
    __static_nextmbuf_bufidx = P(r[1]);
    P(r[2]);
    P(r[3]);
    P(r[4]);
    P(r[5]);
    P(r[6]);
    P(r[7]);
    P(r[8]);
    P(r[9]);
    P(r[10]);
}
// --- END c2js reset block ---
