// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/lcorolib.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/lib/lua-5.4.8/src/lcorolib.c
// Input sha256: 5408ccec737678d045d421f84a56e1ce03192a42c55440ffef07bec356aaec89
// Transpiler: tools/c2js c2js emit v1+batch

import * as cptr from '../cptr.js';
import * as FLD from './nhfield.js';
import {
    lua_checkstack, lua_concat, lua_createtable, lua_error, lua_gettop, lua_pushboolean,
    lua_pushcclosure, lua_pushstring, lua_pushthread, lua_pushvalue, lua_rotate, lua_settop,
    lua_status, lua_tothread, lua_type, lua_xmove
} from './lapi.js';
import {
    luaL_checktype, luaL_checkversion_, luaL_error, luaL_setfuncs, luaL_typeerror, luaL_where
} from './lauxlib.js';
import { lua_isyieldable, lua_resume, lua_yieldk } from './ldo.js';
import { lua_closethread, lua_newthread } from './lstate.js';
import { lua_getstack } from './ldebug.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $luaL_Reg_func = FLD.luaL_Reg_func, $sizeof_luaL_Reg = FLD.sizeof_luaL_Reg;

// string literals (C char* uses decay to CPtr into these static buffers)
const __s_thread = cptr.lit("thread");
const __s_too_many_arguments_to_resume = cptr.lit("too many arguments to resume");
const __s_too_many_results_to_resume = cptr.lit("too many results to resume");
const __s_running = cptr.lit("running");
const __s_dead = cptr.lit("dead");
const __s_suspended = cptr.lit("suspended");
const __s_normal = cptr.lit("normal");
const __s_cannot_close_a_s_coroutine = cptr.lit("cannot close a %s coroutine");
const __s_create = cptr.lit("create");
const __s_resume = cptr.lit("resume");
const __s_status = cptr.lit("status");
const __s_wrap = cptr.lit("wrap");
const __s_yield = cptr.lit("yield");
const __s_isyieldable = cptr.lit("isyieldable");
const __s_close = cptr.lit("close");

/** C ref: lcorolib.c:21 — @param {CPtr<lua_State>} L @returns {CPtr<lua_State>} */
function* getco(L) {
    let co = lua_tothread(L, 1);
    (void ((__builtin_expect(BigInt(((co) !== null)), 1n)) || (yield* luaL_typeerror(L, 1, (__s_thread)))
            ? 1
            : 0));
    return co;
}

/*
** Resumes a coroutine. Returns the number of results for non-error
** cases or -1 for errors.
*/
/**
 * C ref: lcorolib.c:32
 * @param {CPtr<lua_State>} L
 * @param {CPtr<lua_State>} co
 * @param {CInt} narg
 * @returns {CInt}
 */
function* auxresume(L, co, narg) {
    let status;
    let nres = cptr.box(0);
    if ((__builtin_expect(BigInt(((!(yield* lua_checkstack(co, narg))) != 0)), 0n))) {
        (yield* lua_pushstring(L, __s_too_many_arguments_to_resume));
        return -1;  /* error flag */
    }
    (yield* lua_xmove(L, co, narg));
    status = (yield* lua_resume(co, L, narg, nres));
    if ((__builtin_expect(BigInt(((status == 0 || status == 1 ? 1 : 0) != 0)), 1n))) {
        if ((__builtin_expect(BigInt(((!(yield* lua_checkstack(L, (nres.v + 1) | 0))) != 0)), 0n))) {
            (yield* lua_settop(co, (-(nres.v) - 1) | 0));  /* remove results anyway */
            (yield* lua_pushstring(L, __s_too_many_results_to_resume));
            return -1;  /* error flag */
        }
        (yield* lua_xmove(co, L, nres.v));  /* move yielded values */
        return nres.v;
    } else {
        (yield* lua_xmove(co, L, 1));  /* move error message */
        return -1;  /* error flag */
    }
}

/** C ref: lcorolib.c:56 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_coresume(L) {
    let co = (yield* getco(L));
    let r;
    r = (yield* auxresume(L, co, (lua_gettop(L) - 1) | 0));
    if ((__builtin_expect(BigInt(((r < 0) != 0)), 0n))) {
        (yield* lua_pushboolean(L, 0));
        lua_rotate(L, -2, 1);
        return 2;  /* return false + error message */
    } else {
        (yield* lua_pushboolean(L, 1));
        lua_rotate(L, (-((r + 1) | 0)), 1);
        return (r + 1) | 0;  /* return true + 'resume' returns */
    }
}

/** C ref: lcorolib.c:73 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_auxwrap(L) {
    let co = lua_tothread(L, -1001001);
    let r = (yield* auxresume(L, co, lua_gettop(L)));
    if ((__builtin_expect(BigInt(((r < 0) != 0)), 0n))) {
        let stat = lua_status(co);
        if (stat != 0 && stat != 1) {
            stat = (yield* lua_closethread(co, L));  /* close its tbc variables */
            (void 0);
            (yield* lua_xmove(co, L, 1));  /* move error message to the caller */
        }
        if (stat != 4 && lua_type(L, -1) == 4) {
            (yield* luaL_where(L, 1));  /* add extra info, if available */
            lua_rotate(L, -2, 1);
            (yield* lua_concat(L, 2));
        }
        return (yield* lua_error(L));  /* propagate error */
    }
    return r;
}

/** C ref: lcorolib.c:95 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_cocreate(L) {
    let NL;
    (yield* luaL_checktype(L, 1, 6));
    NL = (yield* lua_newthread(L));
    (yield* lua_pushvalue(L, 1));  /* move function to top */
    (yield* lua_xmove(L, NL, 1));  /* move function from L to NL */
    return 1;
}

/** C ref: lcorolib.c:105 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_cowrap(L) {
    (yield* luaB_cocreate(L));
    (yield* lua_pushcclosure(L, luaB_auxwrap, 1));
    return 1;
}

/** C ref: lcorolib.c:112 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_yield(L) {
    return (yield* lua_yieldk(L, (lua_gettop(L)), 0n, null));
}

/** C ref: lcorolib.c:123 — char *[4] */
const statname = cptr.alloc(4 * 8);
cptr.stPtro(statname, 0, __s_running);
cptr.stPtro(statname, 8, __s_dead);
cptr.stPtro(statname, 16, __s_suspended);
cptr.stPtro(statname, 24, __s_normal);

/**
 * C ref: lcorolib.c:127
 * @param {CPtr<lua_State>} L
 * @param {CPtr<lua_State>} co
 * @returns {CInt}
 */
function auxstatus(L, co) {
    if (cptr.eq(L, co))
        return 0;
    else {
        switch (lua_status(co)) {
            case 1:
                return 2;
            case 0:
                {
                    let ar = cptr.alloc(136);
                    if (lua_getstack(co, 0, ar))
                        return 3;  /* it is running */
                    else if (lua_gettop(co) == 0)
                        return 1;
                    else
                        return 2;  /* initial state */
                }
            default:
                return 1;
        }
    }
}

/** C ref: lcorolib.c:149 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_costatus(L) {
    let co = (yield* getco(L));
    (yield* lua_pushstring(L, cptr.ldPtro(statname, auxstatus(L, co), 8)));
    return 1;
}

/** C ref: lcorolib.c:156 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_yieldable(L) {
    let co = (lua_type(L, 1) == -1) ? L : (yield* getco(L));
    (yield* lua_pushboolean(L, lua_isyieldable(co)));
    return 1;
}

/** C ref: lcorolib.c:163 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_corunning(L) {
    let ismain = (yield* lua_pushthread(L));
    (yield* lua_pushboolean(L, ismain));
    return 2;
}

/** C ref: lcorolib.c:170 — @param {CPtr<lua_State>} L @returns {CInt} */
function* luaB_close(L) {
    let co = (yield* getco(L));
    let status = auxstatus(L, co);
    switch (status) {
        case 1:
        case 2:
            {
                status = (yield* lua_closethread(co, L));
                if (status == 0) {
                    (yield* lua_pushboolean(L, 1));
                    return 1;
                } else {
                    (yield* lua_pushboolean(L, 0));
                    (yield* lua_xmove(co, L, 1));  /* move error message */
                    return 2;
                }
            }
        default:
            return (yield* luaL_error(L, __s_cannot_close_a_s_coroutine, cptr.ldPtro(statname, status, 8)));
    }
}

/** C ref: lcorolib.c:192 — luaL_Reg[9] */
const co_funcs = cptr.alloc(9 * $sizeof_luaL_Reg);
cptr.stPtro(co_funcs, 0, __s_create);
cptr.stPtro(co_funcs, 0 + $luaL_Reg_func, luaB_cocreate);
cptr.stPtro(co_funcs, 16, __s_resume);
cptr.stPtro(co_funcs, 16 + $luaL_Reg_func, luaB_coresume);
cptr.stPtro(co_funcs, 32, __s_running);
cptr.stPtro(co_funcs, 32 + $luaL_Reg_func, luaB_corunning);
cptr.stPtro(co_funcs, 48, __s_status);
cptr.stPtro(co_funcs, 48 + $luaL_Reg_func, luaB_costatus);
cptr.stPtro(co_funcs, 64, __s_wrap);
cptr.stPtro(co_funcs, 64 + $luaL_Reg_func, luaB_cowrap);
cptr.stPtro(co_funcs, 80, __s_yield);
cptr.stPtro(co_funcs, 80 + $luaL_Reg_func, luaB_yield);
cptr.stPtro(co_funcs, 96, __s_isyieldable);
cptr.stPtro(co_funcs, 96 + $luaL_Reg_func, luaB_yieldable);
cptr.stPtro(co_funcs, 112, __s_close);
cptr.stPtro(co_funcs, 112 + $luaL_Reg_func, luaB_close);
cptr.stPtro(co_funcs, 128, null);
cptr.stPtro(co_funcs, 128 + $luaL_Reg_func, null);

/** C ref: lcorolib.c:206 — @param {CPtr<lua_State>} L @returns {CInt} */
export function* luaopen_coroutine(L) {
    (
        (yield* luaL_checkversion_(L, 504, 136n)),
        (yield* lua_createtable(L, 0, Number(BigInt.asIntN(32, BigInt.asUintN(64, 144n / 16n - 1n))))),
        (yield* luaL_setfuncs(L, co_funcs, 0))
    );
    return 1;
}

// --- BEGIN c2js reset block (tools/c2js/resetify.mjs) — do not edit ---
// 2 bindings: 0 rebound+refilled, 0 rebound, 2 refilled.
// S/P are supplied by js/generated-y/__reset.js so this module needs no new import.
let __c2js_rs = null;
export function __captureState(S) { __c2js_rs = [S(statname), S(co_funcs)]; }
export function __resetState(P) {
    const r = __c2js_rs;
    if (r === null) throw new Error("lcorolib.js: __resetState before __captureState");
    P(r[0]);
    P(r[1]);
}
// --- END c2js reset block ---
