// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/liolib.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/lib/lua-5.4.8/src/liolib.c
// Input sha256: bd3176d1c5d30d61fdfc2aa17d7af0819f2da51694942a24b6c185ef797f0060
// Transpiler: tools/c2js c2js emit v1+batch

import { schar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as FLD from './nhfield.js';
import {
    luaL_argerror, luaL_buffinit, luaL_checkany, luaL_checkinteger, luaL_checklstring,
    luaL_checkoption, luaL_checkstack, luaL_checkudata, luaL_checkversion_, luaL_error,
    luaL_execresult, luaL_fileresult, luaL_newmetatable, luaL_optinteger, luaL_optlstring,
    luaL_prepbuffsize, luaL_pushresult, luaL_setfuncs, luaL_setmetatable, luaL_testudata
} from './lauxlib.js';
import {
    lua_copy, lua_createtable, lua_getfield, lua_gettop, lua_isinteger, lua_newuserdatauv,
    lua_pushboolean, lua_pushcclosure, lua_pushfstring, lua_pushinteger, lua_pushnil,
    lua_pushstring, lua_pushvalue, lua_rawlen, lua_rotate, lua_setfield, lua_settop,
    lua_stringtonumber, lua_toboolean, lua_tointegerx, lua_tolstring, lua_tonumberx, lua_touserdata,
    lua_type
} from './lapi.js';

// struct field offsets used below, bound at module scope so V8 folds them
// (values from ./nhfield.js, which is the whole table)
const $FILE__r = FLD.FILE__r, $LStream_closef = FLD.LStream_closef, $RN_buff = FLD.RN_buff,
      $RN_c = FLD.RN_c, $RN_n = FLD.RN_n, $luaL_Buffer_n = FLD.luaL_Buffer_n,
      $luaL_Buffer_size = FLD.luaL_Buffer_size, $luaL_Reg_func = FLD.luaL_Reg_func,
      $sizeof_luaL_Reg = FLD.sizeof_luaL_Reg;

// string literals (C char* uses decay to CPtr into these static buffers)
const __s_rwa = cptr.lit("rwa");
const __s_b = cptr.lit("b");
const __s_file = cptr.lit("FILE*");
const __s_closed_file = cptr.lit("closed file");
const __s_file__2 = cptr.lit("file");
const __s_file_closed = cptr.lit("file (closed)");
const __s_file_p = cptr.lit("file (%p)");
const __s_attempt_to_use_a_closed_file = cptr.lit("attempt to use a closed file");
const __s_io_output = cptr.lit("_IO_output");
const __s_cannot_open_file_s_s = cptr.lit("cannot open file '%s' (%s)");
const __s_r = cptr.lit("r");
const __s_invalid_mode = cptr.lit("invalid mode");
const __s_default_s_file_is_closed = cptr.lit("default %s file is closed");
const __s_io_input = cptr.lit("_IO_input");
const __s_w = cptr.lit("w");
const __s_too_many_arguments = cptr.lit("too many arguments");
const __s_dash_plus = cptr.lit("-+");
const __s_00 = cptr.lit("00");
const __s_xx = cptr.lit("xX");
const __s_pp = cptr.lit("pP");
const __s_ee = cptr.lit("eE");
const __s_empty = cptr.lit("");
const __s_invalid_format = cptr.lit("invalid format");
const __s_file_is_already_closed = cptr.lit("file is already closed");
const __s_pct_s = cptr.lit("%s");
const __s_lld = cptr.lit("%lld");
const __s_14g = cptr.lit("%.14g");
const __s_cur = cptr.lit("cur");
const __s_not_an_integer_in_proper_range = cptr.lit("not an integer in proper range");
const __s_set = cptr.lit("set");
const __s_end = cptr.lit("end");
const __s_no = cptr.lit("no");
const __s_full = cptr.lit("full");
const __s_line = cptr.lit("line");
const __s_close = cptr.lit("close");
const __s_flush = cptr.lit("flush");
const __s_input = cptr.lit("input");
const __s_lines = cptr.lit("lines");
const __s_open = cptr.lit("open");
const __s_output = cptr.lit("output");
const __s_popen = cptr.lit("popen");
const __s_read = cptr.lit("read");
const __s_tmpfile = cptr.lit("tmpfile");
const __s_type = cptr.lit("type");
const __s_write = cptr.lit("write");
const __s_seek = cptr.lit("seek");
const __s_setvbuf = cptr.lit("setvbuf");
const __s_index = cptr.lit("__index");
const __s_gc = cptr.lit("__gc");
const __s_close__2 = cptr.lit("__close");
const __s_tostring = cptr.lit("__tostring");
const __s_cannot_close_standard_file = cptr.lit("cannot close standard file");
const __s_stdin = cptr.lit("stdin");
const __s_stdout = cptr.lit("stdout");
const __s_stderr = cptr.lit("stderr");

/* Check whether 'mode' matches '[rwa]%+?[L_MODEEXT]*' */
/** C ref: liolib.c:40 — @param {CPtr<char>} mode @returns {CInt} */
function* l_checkmode(mode) {
    return (cptr.ld1s(mode) != 0 &&
        !cptr.eq(
            cptr.strchr(__s_rwa, cptr.ld1s((cptr.postinc(() => mode, (v) => { mode = v; })))),
            (null)
        ) &&
        (cptr.ld1s(mode) != 43 || (void (cptr.preinc(() => mode, (v) => { mode = v; })), 1)) &&
        (strspn(mode, __s_b) == cptr.strlen(mode))
            ? 1
            : 0);  /* check extensions */
}

/** C ref: liolib.c:155 — typedef LStream (type alias only, no runtime output) */

/** C ref: liolib.c:163 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_type(L) {
    let p;
    (yield* luaL_checkany(L, 1));
    p = (yield* luaL_testudata(L, 1, __s_file));
    if (cptr.eq(p, (null)))
        (yield* lua_pushnil(L));  /* not a file */
    else if ((cptr.ldPtro((p), $LStream_closef) === (null)))
        (yield* lua_pushstring(L, __s_closed_file));
    else
        (yield* lua_pushstring(L, __s_file__2));
    return 1;
}

/** C ref: liolib.c:177 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_tostring(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    if ((cptr.ldPtro((p), $LStream_closef) === (null)))
        (yield* lua_pushstring(L, __s_file_closed));
    else
        (yield* lua_pushfstring(L, __s_file_p, cptr.ldPtr(p)));
    return 1;
}

/** C ref: liolib.c:187 — @param {CPtr<lua_State>} L @returns {CPtr<FILE>} */
function* tofile(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    if ((__builtin_expect(BigInt((((cptr.ldPtro((p), $LStream_closef) === (null))) != 0)), 0n)))
        (yield* luaL_error(L, __s_attempt_to_use_a_closed_file));
    (void 0);
    return cptr.ldPtr(p);
}

/*
** When creating file handles, always creates a 'closed' file handle
** before opening the actual file; so, if there is a memory error, the
** handle is in a consistent state.
*/
/** C ref: liolib.c:201 — @param {CPtr<lua_State>} L @returns {CPtr<LStream>} */
function* newprefile(L) {
    let p = (yield* lua_newuserdatauv(L, 16n, 0));
    cptr.stPtro(p, $LStream_closef, null);  /* mark file handle as 'closed' */
    (yield* luaL_setmetatable(L, __s_file));
    return p;
}

/*
** Calls the 'close' function from a file handle. The 'volatile' avoids
** a bug in some versions of the Clang compiler (e.g., clang 3.0 for
** 32 bits).
*/
/** C ref: liolib.c:214 — @param {CPtr<lua_State>} L @returns {CInt} */
function* aux_close(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    let cf = cptr.ldPtro(p, $LStream_closef);
    cptr.stPtro(p, $LStream_closef, null);  /* mark stream as closed */
    return (yield* Y.icall((cf)(L)));  /* close it */
}

/** C ref: liolib.c:222 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_close(L) {
    (yield* tofile(L));  /* make sure argument is an open stream */
    return (yield* aux_close(L));
}

/** C ref: liolib.c:228 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_close(L) {
    if ((lua_type(L, 1) == -1))
        (yield* lua_getfield(L, -1001000, (__s_io_output)));  /* use default output */
    return (yield* f_close(L));
}

/** C ref: liolib.c:235 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_gc(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    if (!(cptr.ldPtro((p), $LStream_closef) === (null)) && !cptr.eq(cptr.ldPtr(p), (null)))
        (yield* aux_close(L));  /* ignore closed and incompletely open files */
    return 0;
}

/*
** function to close regular files
*/
/** C ref: liolib.c:246 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_fclose(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    cptr.stI32(__error(), 0);
    return (yield* luaL_fileresult(L, (fclose(cptr.ldPtr(p)) == 0), null));
}

/** C ref: liolib.c:253 — @param {CPtr<lua_State>} L @returns {CPtr<LStream>} */
function* newfile(L) {
    let p = (yield* newprefile(L));
    cptr.stPtr(p, null);
    cptr.stPtro(p, $LStream_closef, io_fclose);
    return p;
}

/**
 * C ref: liolib.c:261
 * @param {CPtr<lua_State>} L
 * @param {CPtr<char>} fname
 * @param {CPtr<char>} mode
 */
function* opencheck(L, fname, mode) {
    let p = (yield* newfile(L));
    cptr.stPtr(p, fopen(fname, mode));
    if ((__builtin_expect(BigInt(((cptr.eq(cptr.ldPtr(p), (null))) != 0)), 0n)))
        (yield* luaL_error(L, __s_cannot_open_file_s_s, fname, strerror((cptr.ldI32(__error())))));
}

/** C ref: liolib.c:269 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_open(L) {
    let filename = ((yield* luaL_checklstring(L, 1, null)));
    let mode = ((yield* luaL_optlstring(L, 2, (__s_r), null)));
    let p = (yield* newfile(L));
    let md = mode;  /* to traverse/check mode */
    (void ((__builtin_expect(BigInt((((yield* l_checkmode(md))) != 0)), 1n)) ||
        (yield* luaL_argerror(L, 2, (__s_invalid_mode)))
            ? 1
            : 0));
    cptr.stI32(__error(), 0);
    cptr.stPtr(p, fopen(filename, mode));
    return (cptr.eq(cptr.ldPtr(p), (null))) ? (yield* luaL_fileresult(L, 0, filename)) : 1;
}

/*
** function to close 'popen' files
*/
/** C ref: liolib.c:284 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_pclose(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    cptr.stI32(__error(), 0);
    return (yield* luaL_execresult(L, (pclose(cptr.ldPtr(p)))));
}

/** C ref: liolib.c:291 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_popen(L) {
    let filename = ((yield* luaL_checklstring(L, 1, null)));
    let mode = ((yield* luaL_optlstring(L, 2, (__s_r), null)));
    let p = (yield* newprefile(L));
    (void ((__builtin_expect(
        BigInt(((((cptr.ld1so(mode, 0) == 114 || cptr.ld1so(mode, 0) == 119) &&
            cptr.ld1so(mode, 1) == 0
            ? 1
            : 0)) !=
            0)),
        1n
    )) ||
        (yield* luaL_argerror(L, 2, (__s_invalid_mode)))
            ? 1
            : 0));
    cptr.stI32(__error(), 0);
    cptr.stPtr(p, (fflush(null), popen(filename, mode)));
    cptr.stPtro(p, $LStream_closef, io_pclose);
    return (cptr.eq(cptr.ldPtr(p), (null))) ? (yield* luaL_fileresult(L, 0, filename)) : 1;
}

/** C ref: liolib.c:303 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_tmpfile(L) {
    let p = (yield* newfile(L));
    cptr.stI32(__error(), 0);
    cptr.stPtr(p, tmpfile());
    return (cptr.eq(cptr.ldPtr(p), (null))) ? (yield* luaL_fileresult(L, 0, null)) : 1;
}

/**
 * C ref: liolib.c:311
 * @param {CPtr<lua_State>} L
 * @param {CPtr<char>} findex
 * @returns {CPtr<FILE>}
 */
function* getiofile(L, findex) {
    let p;
    (yield* lua_getfield(L, -1001000, findex));
    p = lua_touserdata(L, -1);
    if ((__builtin_expect(BigInt((((cptr.ldPtro((p), $LStream_closef) === (null))) != 0)), 0n)))
        (yield* luaL_error(
            L,
            __s_default_s_file_is_closed,
            cptr.add(findex, (BigInt.asUintN(64, 5n / 1n - 1n)))
        ));
    return cptr.ldPtr(p);
}

/**
 * C ref: liolib.c:321
 * @param {CPtr<lua_State>} L
 * @param {CPtr<char>} f
 * @param {CPtr<char>} mode
 * @returns {CInt}
 */
function* g_iofile(L, f, mode) {
    if (!(lua_type(L, 1) <= 0)) {
        let filename = (yield* lua_tolstring(L, 1, null));
        if (filename)
            (yield* opencheck(L, filename, mode));
        else {
            (yield* tofile(L));  /* check that it's a valid file handle */
            (yield* lua_pushvalue(L, 1));
        }
        (yield* lua_setfield(L, -1001000, f));
    }
    /* return current value */
    (yield* lua_getfield(L, -1001000, f));
    return 1;
}

/** C ref: liolib.c:338 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_input(L) {
    return (yield* g_iofile(L, (__s_io_input), __s_r));
}

/** C ref: liolib.c:343 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_output(L) {
    return (yield* g_iofile(L, (__s_io_output), __s_w));
}

/*
** Auxiliary function to create the iteration function for 'lines'.
** The iteration function is a closure over 'io_readline', with
** the following upvalues:
** 1) The file being read (first value in the stack)
** 2) the number of arguments to read
** 3) a boolean, true iff file has to be closed when finished ('toclose')
** *) a variable number of format arguments (rest of the stack)
*/
/** C ref: liolib.c:366 — @param {CPtr<lua_State>} L @param {CInt} toclose */
function* aux_lines(L, toclose) {
    let n = (lua_gettop(L) - 1) | 0;  /* number of arguments to read */
    (void ((__builtin_expect(BigInt(((n <= 250) != 0)), 1n)) ||
        (yield* luaL_argerror(L, 252, (__s_too_many_arguments)))
            ? 1
            : 0));
    (yield* lua_pushvalue(L, 1));  /* file */
    (yield* lua_pushinteger(L, BigInt(n)));  /* number of arguments to read */
    (yield* lua_pushboolean(L, toclose));  /* close/not close file when finished */
    lua_rotate(L, 2, 3);  /* move the three values to their positions */
    (yield* lua_pushcclosure(L, io_readline, (3 + n) | 0));
}

/** C ref: liolib.c:377 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_lines(L) {
    (yield* tofile(L));  /* check that it's a valid file handle */
    (yield* aux_lines(L, 0));
    return 1;
}

/*
** Return an iteration function for 'io.lines'. If file has to be
** closed, also returns the file itself as a second result (to be
** closed as the state at the exit of a generic for).
*/
/** C ref: liolib.c:389 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_lines(L) {
    let toclose;
    if ((lua_type(L, 1) == -1))
        (yield* lua_pushnil(L));  /* at least one argument */
    if ((lua_type(L, 1) == 0)) {
        (yield* lua_getfield(L, -1001000, (__s_io_input)));  /* get default input */
        (lua_copy(L, -1, 1), (yield* lua_settop(L, -2)));  /* put it at index 1 */
        (yield* tofile(L));  /* check that it's a valid file handle */
        toclose = 0;  /* do not close it after iteration */
    } else {
        let filename = ((yield* luaL_checklstring(L, 1, null)));
        (yield* opencheck(L, filename, __s_r));
        (lua_copy(L, -1, 1), (yield* lua_settop(L, -2)));  /* put file at index 1 */
        toclose = 1;  /* close it after iteration */
    }
    (yield* aux_lines(L, toclose));  /* push iteration function */
    if (toclose) {
        (yield* lua_pushnil(L));  /* state */
        (yield* lua_pushnil(L));  /* control */
        (yield* lua_pushvalue(L, 1));  /* file is the to-be-closed variable (4th result) */
        return 4;
    } else
        return 1;
}

/* auxiliary structure used by 'read_number' */
/** C ref: liolib.c:430 — struct undefined {  } (memory model v0.5) */

/** C ref: liolib.c:435 — typedef RN (type alias only, no runtime output) */

/*
** Add current char to buffer (if not out of space) and read next one
*/
/** C ref: liolib.c:441 — @param {CPtr<RN>} rn @returns {CInt} */
function* nextc(rn) {
    if ((__builtin_expect(BigInt(((cptr.ldI32o(rn, $RN_n) >= 200) != 0)), 0n))) {
        cptr.st1o2(rn, 0, 1, $RN_buff, 0);  /* invalidate result */
        return 0;  /* fail */
    } else {
        cptr.st1o2(
            rn,
            (cptr.stI32o(rn, $RN_n, cptr.ldI32o(rn, $RN_n) + 1)) - (1),
            1,
            $RN_buff,
            schar(cptr.ldI32o(rn, $RN_c))
        );  /* save current char */
        cptr.stI32o(
            rn,
            $RN_c,
            (cptr.stI32o(
                (cptr.ldPtr(rn)),
                $FILE__r,
                cptr.ldI32o((cptr.ldPtr(rn)), $FILE__r) + -1
            ) < 0
                ? __srget(cptr.ldPtr(rn))
                : (cptr.ld1u(cptr.postinc(
                    () => cptr.ldPtr((cptr.ldPtr(rn))),
                    (v) => { cptr.stPtr((cptr.ldPtr(rn)), v); }
                ))))
        );  /* read next one */
        return 1;
    }
}

/*
** Accept current char if it is in 'set' (of size 2)
*/
/** C ref: liolib.c:457 — @param {CPtr<RN>} rn @param {CPtr<char>} set @returns {CInt} */
function* test2(rn, set) {
    if (cptr.ldI32o(rn, $RN_c) == cptr.ld1so(set, 0) ||
            cptr.ldI32o(rn, $RN_c) == cptr.ld1so(set, 1))
        return (yield* nextc(rn));
    else
        return 0;
}

/*
** Read a sequence of (hex)digits
*/
/** C ref: liolib.c:467 — @param {CPtr<RN>} rn @param {CInt} hex @returns {CInt} */
function* readdigits(rn, hex) {
    let count = 0;
    while ((hex ? isxdigit(cptr.ldI32o(rn, $RN_c)) : isdigit(cptr.ldI32o(rn, $RN_c))) && (yield* nextc(rn)))
        count++;
    return count;
}

/*
** Read a number: first reads a valid prefix of a numeral into a buffer.
** Then it calls 'lua_stringtonumber' to check whether the format is
** correct and to convert it to a Lua number.
*/
/** C ref: liolib.c:480 — @param {CPtr<lua_State>} L @param {CPtr<FILE>} f @returns {CInt} */
function* read_number(L, f) {
    let rn = cptr.alloc(224);
    let count = 0;
    let hex = 0;
    let decp = new Uint8Array(2);
    cptr.stPtr(rn, f);
    cptr.stI32o(rn, $RN_n, 0);
    cptr.st1o(cptr.decay(decp), 0, (cptr.ld1so(cptr.ldPtr(localeconv()), 0)), 1);  /* get decimal point from locale */
    cptr.st1o(cptr.decay(decp), 1, 46, 1);  /* always accept a dot */
    flockfile(cptr.ldPtr(rn));
    do {
        cptr.stI32o(
            rn,
            $RN_c,
            (cptr.stI32o(
                (cptr.ldPtr(rn)),
                $FILE__r,
                cptr.ldI32o((cptr.ldPtr(rn)), $FILE__r) + -1
            ) < 0
                ? __srget(cptr.ldPtr(rn))
                : (cptr.ld1u(cptr.postinc(
                    () => cptr.ldPtr((cptr.ldPtr(rn))),
                    (v) => { cptr.stPtr((cptr.ldPtr(rn)), v); }
                ))))
        );  /* skip spaces */
    } while (isspace(cptr.ldI32o(rn, $RN_c)));
    (yield* test2(rn, __s_dash_plus));  /* optional sign */
    if ((yield* test2(rn, __s_00))) {
        if ((yield* test2(rn, __s_xx)))
            hex = 1;  /* numeral is hexadecimal */
        else
            count = 1;  /* count initial '0' as a valid digit */
    }
    count = (count + (yield* readdigits(rn, hex))) | 0;  /* integral part */
    if ((yield* test2(rn, cptr.decay(decp))))
        count = (count + (yield* readdigits(rn, hex))) | 0;  /* fractional part */
    if (count > 0 && (yield* test2(rn, (hex ? __s_pp : __s_ee)))) {
        (yield* test2(rn, __s_dash_plus));  /* exponent sign */
        (yield* readdigits(rn, 0));  /* exponent digits */
    }
    ungetc(cptr.ldI32o(rn, $RN_c), cptr.ldPtr(rn));  /* unread look-ahead char */
    funlockfile(cptr.ldPtr(rn));
    cptr.st1o2(rn, cptr.ldI32o(rn, $RN_n), 1, $RN_buff, 0);  /* finish string */
    if ((__builtin_expect(BigInt((((yield* lua_stringtonumber(L, cptr.add(rn, $RN_buff)))) != 0n)), 1n)))
        return 1;  /* ok, it is a valid number */
    else {
        (yield* lua_pushnil(L));  /* "result" to be removed */
        return 0;  /* read fails */
    }
}

/** C ref: liolib.c:514 — @param {CPtr<lua_State>} L @param {CPtr<FILE>} f @returns {CInt} */
function* test_eof(L, f) {
    let c = getc(f);
    ungetc(c, f);  /* no-op when c == EOF */
    (yield* lua_pushstring(L, __s_empty));
    return (c != -1);
}

/**
 * C ref: liolib.c:522
 * @param {CPtr<lua_State>} L
 * @param {CPtr<FILE>} f
 * @param {CInt} chop
 * @returns {CInt}
 */
function* read_line(L, f, chop) {
    let b = cptr.alloc(1056);
    let c;
    (yield* luaL_buffinit(L, b));
    do {
        let buff = (yield* luaL_prepbuffsize(b, 1024n));  /* preallocate buffer space */
        let i = 0;
        flockfile(f);  /* no memory errors can happen inside the lock */
        while (i < 1024 &&
                (c = (cptr.stI32o((f), $FILE__r, cptr.ldI32o((f), $FILE__r) + -1) < 0
                    ? __srget(f)
                    : (cptr.ld1u(cptr.postinc(
                        () => cptr.ldPtr((f)),
                        (v) => { cptr.stPtr((f), v); }
                    ))))) !=
                    -1 &&
                c != 10)
            cptr.st1o(buff, i++, schar(c));  /* read up to end of line or buffer limit */
        funlockfile(f);
        (cptr.stU64o(
            (b),
            $luaL_Buffer_n,
            cptr.ldU64o((b), $luaL_Buffer_n) + BigInt.asUintN(64, BigInt((i)))
        ));
    } while (c != -1 && c != 10);  /* repeat until end of line */
    if (!chop && c == 10)
        (
            void (cptr.ldU64o((b), $luaL_Buffer_n) < cptr.ldU64o((b), $luaL_Buffer_size) ||
                (yield* luaL_prepbuffsize((b), 1n))
                ? 1
                : 0),
            (cptr.st1o(
                cptr.ldPtr((b)),
                (cptr.stU64o((b), $luaL_Buffer_n, cptr.ldU64o((b), $luaL_Buffer_n) + 1n)) - (1n),
                schar((c))
            ))
        );  /* add ending newline to result */
    (yield* luaL_pushresult(b));  /* close buffer */
    /* return ok if read something (either a newline or something else) */
    return (c == 10 || lua_rawlen(L, -1) > 0n ? 1 : 0);
}

/** C ref: liolib.c:543 — @param {CPtr<lua_State>} L @param {CPtr<FILE>} f */
function* read_all(L, f) {
    let nr;
    let b = cptr.alloc(1056);
    (yield* luaL_buffinit(L, b));
    do {
        let p = (yield* luaL_prepbuffsize(b, 1024n));
        nr = fread(p, 1n, 1024n, f);
        (cptr.stU64o((b), $luaL_Buffer_n, cptr.ldU64o((b), $luaL_Buffer_n) + (nr)));
    } while (nr == 1024n);
    (yield* luaL_pushresult(b));  /* close buffer */
}

/**
 * C ref: liolib.c:556
 * @param {CPtr<lua_State>} L
 * @param {CPtr<FILE>} f
 * @param {CLongLong} n
 * @returns {CInt}
 */
function* read_chars(L, f, n) {
    let nr;  /* number of chars actually read */
    let p;
    let b = cptr.alloc(1056);
    (yield* luaL_buffinit(L, b));
    p = (yield* luaL_prepbuffsize(b, n));  /* prepare buffer to read whole block */
    nr = fread(p, 1n, n, f);  /* try to read 'n' chars */
    (cptr.stU64o((b), $luaL_Buffer_n, cptr.ldU64o((b), $luaL_Buffer_n) + (nr)));
    (yield* luaL_pushresult(b));  /* close buffer */
    return (nr > 0n);  /* true iff read something */
}

/**
 * C ref: liolib.c:569
 * @param {CPtr<lua_State>} L
 * @param {CPtr<FILE>} f
 * @param {CInt} first
 * @returns {CInt}
 */
function* g_read(L, f, first) {
    let nargs = (lua_gettop(L) - 1) | 0;
    let n;
    let success;
    clearerr(f);
    cptr.stI32(__error(), 0);
    if (nargs == 0) {
        success = (yield* read_line(L, f, 1));
        n = (first + 1) | 0;  /* to return 1 result */
    } else {
        /* ensure stack space for all results and for auxlib's buffer */
        (yield* luaL_checkstack(L, (nargs + 20) | 0, __s_too_many_arguments));
        success = 1;
        for (n = first; nargs-- && success; n++) {
            if (lua_type(L, n) == 3) {
                let l = BigInt.asUintN(64, (yield* luaL_checkinteger(L, n)));
                success = (l == 0n) ? (yield* test_eof(L, f)) : (yield* read_chars(L, f, l));
            } else {
                let p = ((yield* luaL_checklstring(L, (n), null)));
                if (cptr.ld1s(p) == 42)
                    p = cptr.add(p, 1);  /* skip optional '*' (for compatibility) */
                switch (cptr.ld1s(p)) {
                    case 110:
                        success = (yield* read_number(L, f));
                        break;
                    case 108:
                        success = (yield* read_line(L, f, 1));
                        break;
                    case 76:
                        success = (yield* read_line(L, f, 0));
                        break;
                    case 97:
                        (yield* read_all(L, f));  /* read entire file */
                        success = 1;  /* always success */
                        break;
                    default:
                        return (yield* luaL_argerror(L, n, __s_invalid_format));
                }
            }
        }
    }
    if (ferror(f))
        return (yield* luaL_fileresult(L, 0, null));
    if (!success) {
        (yield* lua_settop(L, -2));  /* remove last result */
        (yield* lua_pushnil(L));  /* push nil instead */
    }
    return (n - first) | 0;
}

/** C ref: liolib.c:620 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_read(L) {
    return (yield* g_read(L, (yield* getiofile(L, (__s_io_input))), 1));
}

/** C ref: liolib.c:625 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_read(L) {
    return (yield* g_read(L, (yield* tofile(L)), 2));
}

/*
** Iteration function for 'lines'.
*/
/** C ref: liolib.c:633 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_readline(L) {
    let p = lua_touserdata(L, -1001001);
    let i;
    let n = Number(BigInt.asIntN(32, (yield* lua_tointegerx(L, -1001002, null))));
    if ((cptr.ldPtro((p), $LStream_closef) === (null)))
        return (yield* luaL_error(L, __s_file_is_already_closed));
    (yield* lua_settop(L, 1));
    (yield* luaL_checkstack(L, n, __s_too_many_arguments));
    for (i = 1; i <= n; i++)
        (yield* lua_pushvalue(L, ((-1001000 - (3 + i)) | 0)));
    n = (yield* g_read(L, cptr.ldPtr(p), 2));  /* 'n' is number of results */
    (void 0);  /* should return at least a nil */
    if (lua_toboolean(L, -n))
        return n;  /* return them */
    else {
        if (n > 1) {
            /* 2nd result is error message */
            return (yield* luaL_error(L, __s_pct_s, (yield* lua_tolstring(L, ((-n + 1) | 0), null))));
        }
        if (lua_toboolean(L, -1001003)) {
            (yield* lua_settop(L, 0));  /* clear stack */
            (yield* lua_pushvalue(L, -1001001));  /* push file at index 1 */
            (yield* aux_close(L));  /* close it */
        }
        return 0;
    }
}

/* }====================================================== */

/**
 * C ref: liolib.c:664
 * @param {CPtr<lua_State>} L
 * @param {CPtr<FILE>} f
 * @param {CInt} arg
 * @returns {CInt}
 */
function* g_write(L, f, arg) {
    let nargs = (lua_gettop(L) - arg) | 0;
    let status = 1;
    cptr.stI32(__error(), 0);
    for (; nargs--; arg++) {
        if (lua_type(L, arg) == 3) {
            /* optimization: could be done exactly as for strings */
            let len = lua_isinteger(L, arg)
                    ? fprintf(f, __s_lld, (yield* lua_tointegerx(L, (arg), null)))
                    : fprintf(f, __s_14g, (yield* lua_tonumberx(L, (arg), null)));
            status = status && (len > 0) ? 1 : 0;
        } else {
            let l = cptr.box(0n);
            let s = (yield* luaL_checklstring(L, arg, l));
            status = status && (fwrite(s, 1n, l.v, f) == l.v) ? 1 : 0;
        }
    }
    if ((__builtin_expect(BigInt(((status) != 0)), 1n)))
        return 1;  /* file handle already on stack top */
    else
        return (yield* luaL_fileresult(L, status, null));
}

/** C ref: liolib.c:691 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_write(L) {
    return (yield* g_write(L, (yield* getiofile(L, (__s_io_output))), 1));
}

/** C ref: liolib.c:696 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_write(L) {
    let f = (yield* tofile(L));
    (yield* lua_pushvalue(L, 1));  /* push file at the stack top (to be returned) */
    return (yield* g_write(L, f, 2));
}

const __static_f_seek_mode = cptr.alloc(3 * 4);
cptr.stI32o(__static_f_seek_mode, 0, 0);
cptr.stI32o(__static_f_seek_mode, 4, 1);
cptr.stI32o(__static_f_seek_mode, 8, 2); /** C ref: liolib.c:704 — int[3] (function-static) */
const __static_f_seek_modenames = cptr.alloc(4 * 8);
cptr.stPtro(__static_f_seek_modenames, 0, __s_set);
cptr.stPtro(__static_f_seek_modenames, 8, __s_cur);
cptr.stPtro(__static_f_seek_modenames, 16, __s_end);
cptr.stPtro(__static_f_seek_modenames, 24, null); /** C ref: liolib.c:705 — char *[4] (function-static) */

/** C ref: liolib.c:703 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_seek(L) {
    let f = (yield* tofile(L));
    let op = (yield* luaL_checkoption(L, 2, __s_cur, __static_f_seek_modenames));
    let p3 = (yield* luaL_optinteger(L, 3, 0n));
    let offset = p3;
    (void ((__builtin_expect(BigInt(((offset == p3) != 0)), 1n)) ||
        (yield* luaL_argerror(L, 3, (__s_not_an_integer_in_proper_range)))
            ? 1
            : 0));
    cptr.stI32(__error(), 0);
    op = fseeko(f, offset, cptr.ldI32o(__static_f_seek_mode, op, 4));
    if ((__builtin_expect(BigInt(((op) != 0)), 0n)))
        return (yield* luaL_fileresult(L, 0, null));  /* error */
    else {
        (yield* lua_pushinteger(L, ftello(f)));
        return 1;
    }
}

const __static_f_setvbuf_mode = cptr.alloc(3 * 4);
cptr.stI32o(__static_f_setvbuf_mode, 0, 2);
cptr.stI32o(__static_f_setvbuf_mode, 4, 0);
cptr.stI32o(__static_f_setvbuf_mode, 8, 1); /** C ref: liolib.c:724 — int[3] (function-static) */
const __static_f_setvbuf_modenames = cptr.alloc(4 * 8);
cptr.stPtro(__static_f_setvbuf_modenames, 0, __s_no);
cptr.stPtro(__static_f_setvbuf_modenames, 8, __s_full);
cptr.stPtro(__static_f_setvbuf_modenames, 16, __s_line);
cptr.stPtro(__static_f_setvbuf_modenames, 24, null); /** C ref: liolib.c:725 — char *[4] (function-static) */

/** C ref: liolib.c:723 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_setvbuf(L) {
    let f = (yield* tofile(L));
    let op = (yield* luaL_checkoption(L, 2, null, __static_f_setvbuf_modenames));
    let sz = (yield* luaL_optinteger(L, 3, 1024n));
    let res;
    cptr.stI32(__error(), 0);
    res = setvbuf(f, null, cptr.ldI32o(__static_f_setvbuf_mode, op, 4), BigInt.asUintN(64, sz));
    return (yield* luaL_fileresult(L, res == 0, null));
}

/** C ref: liolib.c:737 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_flush(L) {
    let f = (yield* getiofile(L, (__s_io_output)));
    cptr.stI32(__error(), 0);
    return (yield* luaL_fileresult(L, fflush(f) == 0, null));
}

/** C ref: liolib.c:744 — @param {CPtr<lua_State>} L @returns {CInt} */
function* f_flush(L) {
    let f = (yield* tofile(L));
    cptr.stI32(__error(), 0);
    return (yield* luaL_fileresult(L, fflush(f) == 0, null));
}

/*
** functions for 'io' library
*/
/** C ref: liolib.c:754 — luaL_Reg[12] */
const iolib = cptr.alloc(12 * $sizeof_luaL_Reg);
cptr.stPtro(iolib, 0, __s_close);
cptr.stPtro(iolib, 0 + $luaL_Reg_func, io_close);
cptr.stPtro(iolib, 16, __s_flush);
cptr.stPtro(iolib, 16 + $luaL_Reg_func, io_flush);
cptr.stPtro(iolib, 32, __s_input);
cptr.stPtro(iolib, 32 + $luaL_Reg_func, io_input);
cptr.stPtro(iolib, 48, __s_lines);
cptr.stPtro(iolib, 48 + $luaL_Reg_func, io_lines);
cptr.stPtro(iolib, 64, __s_open);
cptr.stPtro(iolib, 64 + $luaL_Reg_func, io_open);
cptr.stPtro(iolib, 80, __s_output);
cptr.stPtro(iolib, 80 + $luaL_Reg_func, io_output);
cptr.stPtro(iolib, 96, __s_popen);
cptr.stPtro(iolib, 96 + $luaL_Reg_func, io_popen);
cptr.stPtro(iolib, 112, __s_read);
cptr.stPtro(iolib, 112 + $luaL_Reg_func, io_read);
cptr.stPtro(iolib, 128, __s_tmpfile);
cptr.stPtro(iolib, 128 + $luaL_Reg_func, io_tmpfile);
cptr.stPtro(iolib, 144, __s_type);
cptr.stPtro(iolib, 144 + $luaL_Reg_func, io_type);
cptr.stPtro(iolib, 160, __s_write);
cptr.stPtro(iolib, 160 + $luaL_Reg_func, io_write);
cptr.stPtro(iolib, 176, null);
cptr.stPtro(iolib, 176 + $luaL_Reg_func, null);

/*
** methods for file handles
*/
/** C ref: liolib.c:773 — luaL_Reg[8] */
const meth = cptr.alloc(8 * $sizeof_luaL_Reg);
cptr.stPtro(meth, 0, __s_read);
cptr.stPtro(meth, 0 + $luaL_Reg_func, f_read);
cptr.stPtro(meth, 16, __s_write);
cptr.stPtro(meth, 16 + $luaL_Reg_func, f_write);
cptr.stPtro(meth, 32, __s_lines);
cptr.stPtro(meth, 32 + $luaL_Reg_func, f_lines);
cptr.stPtro(meth, 48, __s_flush);
cptr.stPtro(meth, 48 + $luaL_Reg_func, f_flush);
cptr.stPtro(meth, 64, __s_seek);
cptr.stPtro(meth, 64 + $luaL_Reg_func, f_seek);
cptr.stPtro(meth, 80, __s_close);
cptr.stPtro(meth, 80 + $luaL_Reg_func, f_close);
cptr.stPtro(meth, 96, __s_setvbuf);
cptr.stPtro(meth, 96 + $luaL_Reg_func, f_setvbuf);
cptr.stPtro(meth, 112, null);
cptr.stPtro(meth, 112 + $luaL_Reg_func, null);

/*
** metamethods for file handles
*/
/** C ref: liolib.c:788 — luaL_Reg[5] */
const metameth = cptr.alloc(5 * $sizeof_luaL_Reg);
cptr.stPtro(metameth, 0, __s_index);
cptr.stPtro(metameth, 0 + $luaL_Reg_func, null);
cptr.stPtro(metameth, 16, __s_gc);
cptr.stPtro(metameth, 16 + $luaL_Reg_func, f_gc);
cptr.stPtro(metameth, 32, __s_close__2);
cptr.stPtro(metameth, 32 + $luaL_Reg_func, f_gc);
cptr.stPtro(metameth, 48, __s_tostring);
cptr.stPtro(metameth, 48 + $luaL_Reg_func, f_tostring);
cptr.stPtro(metameth, 64, null);
cptr.stPtro(metameth, 64 + $luaL_Reg_func, null);

/** C ref: liolib.c:797 — @param {CPtr<lua_State>} L */
function* createmeta(L) {
    (yield* luaL_newmetatable(L, __s_file));  /* metatable for file handles */
    (yield* luaL_setfuncs(L, metameth, 0));  /* add metamethods to new metatable */
    (yield* lua_createtable(L, 0, Number(BigInt.asIntN(32, BigInt.asUintN(64, 128n / 16n - 1n)))));  /* create method table */
    (yield* luaL_setfuncs(L, meth, 0));  /* add file methods to method table */
    (yield* lua_setfield(L, -2, __s_index));  /* metatable.__index = method table */
    (yield* lua_settop(L, -2));  /* pop metatable */
}

/*
** function to (not) close the standard files stdin, stdout, and stderr
*/
/** C ref: liolib.c:810 — @param {CPtr<lua_State>} L @returns {CInt} */
function* io_noclose(L) {
    let p = ((yield* luaL_checkudata(L, 1, __s_file)));
    cptr.stPtro(p, $LStream_closef, io_noclose);  /* keep file opened */
    (yield* lua_pushnil(L));
    (yield* lua_pushstring(L, __s_cannot_close_standard_file));
    return 2;
}

/**
 * C ref: liolib.c:819
 * @param {CPtr<lua_State>} L
 * @param {CPtr<FILE>} f
 * @param {CPtr<char>} k
 * @param {CPtr<char>} fname
 */
function* createstdfile(L, f, k, fname) {
    let p = (yield* newprefile(L));
    cptr.stPtr(p, f);
    cptr.stPtro(p, $LStream_closef, io_noclose);
    if (!cptr.eq(k, (null))) {
        (yield* lua_pushvalue(L, -1));
        (yield* lua_setfield(L, -1001000, k));  /* add file to registry */
    }
    (yield* lua_setfield(L, -2, fname));  /* add file to module */
}

/** C ref: liolib.c:832 — @param {CPtr<lua_State>} L @returns {CInt} */
export function* luaopen_io(L) {
    (
        (yield* luaL_checkversion_(L, 504, 136n)),
        (yield* lua_createtable(L, 0, Number(BigInt.asIntN(32, BigInt.asUintN(64, 192n / 16n - 1n))))),
        (yield* luaL_setfuncs(L, iolib, 0))
    );  /* new module */
    (yield* createmeta(L));
    /* create (and set) default files */
    (yield* createstdfile(L, __stdinp, (__s_io_input), __s_stdin));
    (yield* createstdfile(L, __stdoutp, (__s_io_output), __s_stdout));
    (yield* createstdfile(L, __stderrp, null, __s_stderr));
    return 1;
}
