// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/mklev.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/mklev.c
// Input sha256: 9958b95e15d0a6e27cac80c07a8bb8eac54ef239a51af3992cff303a615731a4
// Transpiler: tools/c2js c2js emit v1+batch

import { i16, schar, uchar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import { isok } from './cmd.js';
import { WIN_MESSAGE, flags, gc, gd, gi, gl, gm, gn, gs, gt, gu, gv, gx, gy, iflags, nhcb_counts, nhcb_name, svd, svi, svl, svm, svn, svr, u, xdir, ydir } from './decl.js';
import { You, impossible, pline, pline_The } from './pline.js';
import { reseed_random, rn2, rn2_on_display_rng, rnd, rng_log_enabled, rng_log_set_caller } from './rnd.js';
import { nh_deterministic_qsort, nh_snprintf } from './hacklib.js';
import { bound_digging, makemaz, mazexy, mkportal, set_levltyp, wallification } from './mkmaze.js';
import { panic } from './end.js';
import { nhl_done, nhl_init, nhl_loadlua, nhl_pcall_handle } from './nhlua.js';
import { check_room, create_des_coder, create_room, dig_corridor, fill_special_room, reset_xystart_size } from './sp_lev.js';
import { lua_gc, lua_getglobal, lua_pushstring, lua_settop } from './lapi.js';
import { init_rect, rnd_rect } from './rect.js';
import { alloc } from './alloc.js';
import { in_rooms, invocation_pos } from './hack.js';
import { Can_fall_thru, In_V_tower, In_hell, In_mines, In_quest, Is_botlevel, Is_branchlev, Is_special, assign_level, at_dgn_entrance, depth, dungeon_branch, dunlev, dunlevs_in_dungeon, find_level, free_exclusions, init_dungeons, init_mapseen, insert_branch, level_difficulty, on_level, single_level_branch } from './dungeon.js';
import { makemon, mkclass, set_mimic_sym } from './makemon.js';
import { deltrap, maketrap, mintrap, reset_utrap, t_at } from './trap.js';
import { make_engr_at, make_grave, random_engraving, wipe_engr_at } from './engrave.js';
import { add_to_buried, add_to_container, curse, dealloc_obj, mkcorpstat, mkgold, mkobj, mkobj_at, mksobj, mksobj_at, obj_extract_self, place_object, weight } from './mkobj.js';
import { stairway_add, stairway_free_all } from './stairs.js';
import { clear_regions } from './region.js';
import { antholemon, do_mkroom, has_dnstairs, has_upstairs, inside_room, somex, somexyspace, somey } from './mkroom.js';
import { mons } from './monst.js';
import { cursed } from './do_wear.js';
import { objects } from './objects.js';
import { oinit } from './o_init.js';
import { makerogueghost, makeroguerooms } from './extralev.js';
import { debugcore, paniclog } from './files.js';
import { nh_getenv } from './options.js';
import { back_to_glyph, flush_screen, newsym, set_wall_state } from './display.js';
import { getbones } from './bones.js';
import { is_lava, is_pool, is_pool_or_lava } from './dbridge.js';
import { breaktest } from './dothrow.js';
import { begin_burn } from './timeout.js';
import { sobj_at } from './invent.js';
import { glyph_to_cmap } from './glyphs.js';
import { defsyms } from './drawing.js';
import { windowprocs } from './windows.js';
import { buried_ball_to_punishment } from './dig.js';
import { fracture_rock } from './zap.js';
import { obfree } from './shk.js';
import { minliquid, seemimic } from './mon.js';
import { does_block, unblock_point } from './vision.js';

// string literals (C char* uses decay to CPtr into these static buffers)
const __sl0 = cptr.lit("finddpos: illegal dir");
const __sl1 = cptr.lit("/Users/noahpeterson/Documents/Projects/teleport-contest-research/original-contest-to-fork/nethack-c/recorder/src/mklev.c");
const __sl2 = cptr.lit("finddpos");
const __sl3 = cptr.lit("level has too many rooms");
const __sl4 = cptr.lit("level has too many subrooms");
const __sl5 = cptr.lit("room has too many subrooms");
const __sl6 = cptr.lit("pre_themerooms_generate");
const __sl7 = cptr.lit("makerooms-1");
const __sl8 = cptr.lit("makerooms");
const __sl9 = cptr.lit("themerooms_generate");
const __sl10 = cptr.lit("makerooms-2");
const __sl11 = cptr.lit("post_themerooms_generate");
const __sl12 = cptr.lit("makerooms-3");
const __sl13 = cptr.lit("makecorridors");
const __sl14 = cptr.lit("dosdoor");
const __sl15 = cptr.lit("place_niche");
const __sl16 = cptr.lit("Vlad was here");
const __sl17 = cptr.lit("ad aerarium");
const __sl18 = cptr.lit("makeniche");
const __sl19 = cptr.lit("make_niches");
const __sl20 = cptr.lit("fill_ordinary_room: Null subroom");
const __sl21 = cptr.lit("fill_ordinary_room");
const __sl22 = cptr.lit("couldn't generate supply chest item");
const __sl23 = cptr.lit("trycnt overflow4");
const __sl24 = cptr.lit("post_level_generate");
const __sl25 = cptr.lit("levl[%i][%i] door not ok");
const __sl26 = cptr.lit("room %i not connected?");
const __sl27 = cptr.lit("makelevel() called when dungeon not yet initialized.");
const __sl28 = cptr.lit("");
const __sl29 = cptr.lit("%s-loca");
const __sl30 = cptr.lit("%s-fil");
const __sl31 = cptr.lit("a");
const __sl32 = cptr.lit("b");
const __sl33 = cptr.lit("makelevel");
const __sl34 = cptr.lit("mklev.c");
const __sl35 = cptr.lit("svn.nroom > 0");
const __sl36 = cptr.lit("trying to make a vault...");
const __sl37 = cptr.lit("SHOPTYPE");
const __sl38 = cptr.lit("nh_callback_run");
const __sl39 = cptr.lit("water_has_kelp");
const __sl40 = cptr.lit("mineralize");
const __sl41 = cptr.lit("find_branch_room");
const __sl42 = cptr.lit("croom != NULL");
const __sl43 = cptr.lit("Can't place branch!");
const __sl44 = cptr.lit("maybe_sdoor");
const __sl45 = cptr.lit("mktrap_victim");
const __sl46 = cptr.lit("x > 0 && x < COLNO && y >= 0 && y < ROWNO");
const __sl47 = cptr.lit("traptype_rnd");
const __sl48 = cptr.lit("traptype_roguelvl");
const __sl49 = cptr.lit("mktrap");
const __sl50 = cptr.lit("args (%d,%d,%s,%s) are invalid");
const __sl51 = cptr.lit("null room");
const __sl52 = cptr.lit("null location");
const __sl53 = cptr.lit("mkstairs:  bogus stair attempt at <%d,%d>");
const __sl54 = cptr.lit("mkstairs:  placing stairs %s on %s at <%d,%d>");
const __sl55 = cptr.lit("up");
const __sl56 = cptr.lit("down");
const __sl57 = cptr.lit("generate_stairs_find_room");
const __sl58 = cptr.lit("mkfount");
const __sl59 = cptr.lit("mkaltar");
const __sl60 = cptr.lit("mkgrave");
const __sl61 = cptr.lit("Saved by the bell!");
const __sl62 = cptr.lit("floor shakes violently under you!");
const __sl63 = cptr.lit("walls around you begin to bend and crumble!");
const __sl64 = cptr.lit("are standing at the top of a stairwell leading down!");
const __sl65 = cptr.lit("mkinvpos: <%d,%d> (%d) off map edge!");
const __sl66 = cptr.lit("mkinvpos called with dist %d");
const __sl67 = cptr.lit("mkinvk_check_wall");
const __sl68 = cptr.lit("x > 0 && x < COLNO");
const __sl69 = cptr.lit("y >= 0 && y < ROWNO");
const __sl70 = cptr.lit("Fort Ludios");
const __sl71 = cptr.lit("mk_knox_portal");
const __sl72 = cptr.lit("br != NULL");
const __sl73 = cptr.lit("The Quest");
const __sl74 = cptr.lit("Made knox portal.");

/** C ref: mklev.c:60 — @param {CPtr} vx @param {CPtr} vy @returns {CInt} */
function mkroom_cmp(vx, vy) {
    let x;
    let y;
    x = vx;
    y = vy;
    if (cptr.ldI16(x) < cptr.ldI16(y))
        return -1;
    return (cptr.ldI16(x) > cptr.ldI16(y));
}

/** C ref: mklev.c:73 — @param {CInt} x @param {CInt} y @param {CInt} dir @param {CPtr} room @returns {CInt} */
function good_rm_wall_doorpos(x, y, dir, room) {
    let tx;
    let ty;
    let rmno;
    if (!isok(x, y) || !cptr.ld1so(room, 12) ? 1 : 0)
        return 0;
    if (!(((cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.HWALL || cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.VWALL ? 1 : 0) || ((cptr.ld1so3(svl, x, 756, y, 36, 1684)) == NHC.DOOR) ? 1 : 0) || cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.SDOOR ? 1 : 0))
        return 0;
    if (bydoor(x, y))
        return 0;
    tx = i16(((x + cptr.ld1so(cptr.decay(xdir), dir, 1)) | 0));
    ty = i16(((y + cptr.ld1so(cptr.decay(ydir), dir, 1)) | 0));
    if (!isok(tx, ty) || ((cptr.ld1so3(svl, tx, 756, ty, 36, 1684)) < NHC.POOL) ? 1 : 0)
        return 0;
    rmno = Number(BigInt.asIntN(32, BigInt.asIntN(64, (cptr.diff(room, svr) / 224n) + 3n)));
    if (rmno != ((cptr.ldI32o3(svl, tx, 756, ty, 36, 1704) & 63) | 0))
        return 0;
    return 1;
}

/** C ref: mklev.c:106 — @param {CPtr} x @param {CPtr} y @param {CInt} dir @param {CPtr} aroom @returns {CInt} */
function finddpos_shift(x, y, dir, aroom) {
    let dx;
    let dy;
    dir = ((((dir) + 4) | 0) % ((NHC.N_DIRS_Z - 2) | 0));
    dx = i16(cptr.ld1so(cptr.decay(xdir), dir, 1));
    dy = i16(cptr.ld1so(cptr.decay(ydir), dir, 1));
    if (good_rm_wall_doorpos(cptr.ldI16(x), cptr.ldI16(y), dir, aroom))
        return 1;
    if (cptr.ld1so(aroom, 21)) {
        let rx = cptr.ldI16(x);
        let ry = cptr.ldI16(y);
        let fail = 0;
        while ((!fail && isok(rx, ry) ? 1 : 0) && (cptr.ld1so3(svl, rx, 756, ry, 36, 1684) == NHC.STONE || cptr.ld1so3(svl, rx, 756, ry, 36, 1684) == NHC.CORR ? 1 : 0) ? 1 : 0) {
            rx = i16(rx + dx);
            ry = i16(ry + dy);
            if (good_rm_wall_doorpos(rx, ry, dir, aroom)) {
                cptr.stI16(x, rx);
                cptr.stI16(y, ry);
                return 1;
            }
            if (!(cptr.ld1so3(svl, rx, 756, ry, 36, 1684) == NHC.STONE || cptr.ld1so3(svl, rx, 756, ry, 36, 1684) == NHC.CORR ? 1 : 0))
                fail = 1;
            if (((rx < cptr.ldI16(aroom) || rx > cptr.ldI16o(aroom, 2) ? 1 : 0) || ry < cptr.ldI16o(aroom, 4) ? 1 : 0) || ry > cptr.ldI16o(aroom, 6) ? 1 : 0)
                fail = 1;
        }
    }
    return 0;
}

/** C ref: mklev.c:147 — @param {CPtr} cc @param {CInt} dir @param {CPtr} aroom @returns {CInt} */
function* finddpos(cc, dir, aroom) {
    let x = cptr.box(0);
    let y = cptr.box(0);
    let x1;
    let y1;
    let x2;
    let y2;
    let tryct = 0;
    __lbl_gotit: {
        switch (dir) {
            case NHC.DIR_N:
            x1 = cptr.ldI16(aroom);
            x2 = cptr.ldI16o(aroom, 2);
            y1 = i16(((cptr.ldI16o(aroom, 4) - 1) | 0));
            y2 = i16(((cptr.ldI16o(aroom, 4) - 1) | 0));
            break;
            case NHC.DIR_S:
            x1 = cptr.ldI16(aroom);
            x2 = cptr.ldI16o(aroom, 2);
            y1 = i16(((cptr.ldI16o(aroom, 6) + 1) | 0));
            y2 = i16(((cptr.ldI16o(aroom, 6) + 1) | 0));
            break;
            case NHC.DIR_W:
            x1 = i16(((cptr.ldI16(aroom) - 1) | 0));
            x2 = i16(((cptr.ldI16(aroom) - 1) | 0));
            y1 = cptr.ldI16o(aroom, 4);
            y2 = cptr.ldI16o(aroom, 6);
            break;
            case NHC.DIR_E:
            x1 = i16(((cptr.ldI16o(aroom, 2) + 1) | 0));
            x2 = i16(((cptr.ldI16o(aroom, 2) + 1) | 0));
            y1 = cptr.ldI16o(aroom, 4);
            y2 = cptr.ldI16o(aroom, 6);
            break;
            default:
            (yield* impossible(__sl0));
            return 0;
        }
        do {
            x.v = i16((((x2 - x1) | 0) ? (((rng_log_enabled() ? (rng_log_set_caller(__sl1, 185, __sl2), rn2((((x2 - x1) | 0) + 1) | 0)) : rn2((((x2 - x1) | 0) + 1) | 0)) + (x1)) | 0) : x1));
            y.v = i16((((y2 - y1) | 0) ? (((rng_log_enabled() ? (rng_log_set_caller(__sl1, 186, __sl2), rn2((((y2 - y1) | 0) + 1) | 0)) : rn2((((y2 - y1) | 0) + 1) | 0)) + (y1)) | 0) : y1));
            if (finddpos_shift(x, y, dir, aroom))
                break __lbl_gotit;
        } while (++tryct < 20);
        for (x.v = x1; x.v <= x2; x.v++)
            for (y.v = y1; y.v <= y2; y.v++)
                if (finddpos_shift(x, y, dir, aroom))
                    break __lbl_gotit;
        cptr.stI16(cc, x1);
        cptr.stI16o(cc, 2, y1);
        return 0;
    }
    cptr.stI16(cc, x.v);
    cptr.stI16o(cc, 2, y.v);
    return 1;
}

/** C ref: mklev.c:210 */
export function* sort_rooms() {
    let x;
    let y;
    let i;
    let ri = cptr.alloc(41 * 4); cptr.stI32o(ri, 0, 0);
    let n = cptr.ldI32o(svn, 44) >>> 0;
    (yield* nh_deterministic_qsort((svr), BigInt((n) >>> 0), 224n, (mkroom_cmp)));
    for (i = 0; i < n; i++)
        cptr.stI32o(ri, cptr.ld1so2(svr, i, 224, 22), i, 4);
    for (x = 1; x < NHM.COLNO; x++)
        for (y = 0; y < NHM.ROWNO; y++) {
            let rno = (cptr.ldI32o3(svl, x, 756, y, 36, 1704) & 63);
            if (rno >= NHM.ROOMOFFSET && rno < 41 ? 1 : 0)
                cptr.stI32o3(svl, x, 756, y, 36, 1704, (cptr.ldI32o(ri, (rno - NHM.ROOMOFFSET) >>> 0, 4) + NHM.ROOMOFFSET) >>> 0);
        }
}

/** C ref: mklev.c:231 — @param {CPtr} croom @param {CInt} lowx @param {CInt} lowy @param {CInt} hix @param {CInt} hiy @param {CInt} lit @param {CInt} rtype @param {CInt} special @param {CInt} is_room */
function* do_room_or_subroom(croom, lowx, lowy, hix, hiy, lit, rtype, special, is_room) {
    let x;
    let y;
    let lev;
    if (!lowx)
        lowx++;
    if (!lowy)
        lowy++;
    if (hix >= 79)
        hix = 78;
    if (hiy >= 20)
        hiy = 19;
    if (lit) {
        for (x = i16(((lowx - 1) | 0)); x <= ((hix + 1) | 0); x++) {
            lev = cptr.add(cptr.add(cptr.add(svl, 1680), x, 756), (((lowy - 1) | 0) > 0 ? ((lowy - 1) | 0) : 0), 36);
            for (y = i16(((lowy - 1) | 0)); y <= ((hiy + 1) | 0); y++)
                cptr.stI32o(cptr.postinc(() => lev, (v) => { lev = v; }, 36), 16, 1);
        }
        cptr.st1o(croom, 10, 1);
    } else
        cptr.st1o(croom, 10, 0);
    cptr.st1o(croom, 22, Number(BigInt.asIntN(8, (cptr.diff(croom, svr) / 224n))));
    cptr.stI16(croom, lowx);
    cptr.stI16o(croom, 2, hix);
    cptr.stI16o(croom, 4, lowy);
    cptr.stI16o(croom, 6, hiy);
    cptr.st1o(croom, 8, rtype);
    cptr.st1o(croom, 13, 0);
    cptr.stI32o(croom, 16, cptr.ldI32(gd));
    cptr.st1o(croom, 21, 0);
    cptr.st1o(croom, 20, 0);
    cptr.stPtro2(croom, 0, 8, 24, null);
    if (!special) {
        cptr.st1o(croom, 12, 1);
        for (x = i16(((lowx - 1) | 0)); x <= ((hix + 1) | 0); x++)
            for (y = i16(((lowy - 1) | 0)); y <= ((hiy + 1) | 0); y = i16(y + ((((hiy - lowy) | 0) + 2) | 0))) {
                cptr.st1o3(svl, x, 756, y, 36, 1684, NHC.HWALL);
                cptr.stI32o3(svl, x, 756, y, 36, 1692, 1);
            }
        for (x = i16(((lowx - 1) | 0)); x <= ((hix + 1) | 0); x = i16(x + ((((hix - lowx) | 0) + 2) | 0)))
            for (y = lowy; y <= hiy; y++) {
                cptr.st1o3(svl, x, 756, y, 36, 1684, NHC.VWALL);
                cptr.stI32o3(svl, x, 756, y, 36, 1692, 0);
            }
        for (x = lowx; x <= hix; x++) {
            lev = cptr.add(cptr.add(cptr.add(svl, 1680), x, 756), lowy, 36);
            for (y = lowy; y <= hiy; y++)
                cptr.st1o(cptr.postinc(() => lev, (v) => { lev = v; }, 36), 4, NHC.ROOM);
        }
        if (is_room) {
            cptr.st1o3(svl, (lowx - 1) | 0, 756, (lowy - 1) | 0, 36, 1684, NHC.TLCORNER);
            cptr.st1o3(svl, (hix + 1) | 0, 756, (lowy - 1) | 0, 36, 1684, NHC.TRCORNER);
            cptr.st1o3(svl, (lowx - 1) | 0, 756, (hiy + 1) | 0, 36, 1684, NHC.BLCORNER);
            cptr.st1o3(svl, (hix + 1) | 0, 756, (hiy + 1) | 0, 36, 1684, NHC.BRCORNER);
        } else {
            (yield* wallification(i16(((lowx - 1) | 0)), i16(((lowy - 1) | 0)), i16(((hix + 1) | 0)), i16(((hiy + 1) | 0))));
        }
    }
}

/** C ref: mklev.c:304 — @param {CInt} lowx @param {CInt} lowy @param {CInt} hix @param {CInt} hiy @param {CInt} lit @param {CInt} rtype @param {CInt} special */
export function* add_room(lowx, lowy, hix, hiy, lit, rtype, special) {
    let croom;
    if (cptr.ldI32o(svn, 44) >= NHM.MAXNROFROOMS)
        (yield* panic(__sl3));
    croom = cptr.add(svr, cptr.ldI32o(svn, 44), 224);
    (yield* do_room_or_subroom(croom, lowx, lowy, hix, hiy, lit, rtype, special, 1));
    croom = cptr.add(croom, 1, 224);
    cptr.stI16o(croom, 2, -1);
    (cptr.stI32o(svn, 44, cptr.ldI32o(svn, 44) + 1)) - (1);
}

/** C ref: mklev.c:322 — @param {CPtr} proom @param {CInt} lowx @param {CInt} lowy @param {CInt} hix @param {CInt} hiy @param {CInt} lit @param {CInt} rtype @param {CInt} special */
export function* add_subroom(proom, lowx, lowy, hix, hiy, lit, rtype, special) {
    let croom;
    if (cptr.ldI32o(gn, 16) >= NHM.MAXNROFROOMS)
        (yield* panic(__sl4));
    if (cptr.ld1so(proom, 20) >= NHM.MAX_SUBROOMS)
        (yield* panic(__sl5));
    croom = cptr.add(cptr.ldPtro(gs, 184), cptr.ldI32o(gn, 16), 224);
    (yield* do_room_or_subroom(croom, lowx, lowy, hix, hiy, lit, rtype, special, 0));
    cptr.stPtro2(proom, cptr.postinc1(cptr.add(proom, 20)), 8, 24, croom);
    croom = cptr.add(croom, 1, 224);
    cptr.stI16o(croom, 2, -1);
    (cptr.stI32o(gn, 16, cptr.ldI32o(gn, 16) + 1)) - (1);
}

/** C ref: mklev.c:345 — @param {*} theme_group */
export function* free_luathemes(theme_group) {
    let i;
    for (i = 0; i < cptr.ldI32(svn); ++i) {
        if ((theme_group == NHC.tut_themes && i != (cptr.ldI16o(svd, 1880)) ? 1 : 0) || (theme_group == NHC.most_themes && i == cptr.ldI16((cptr.add(svd, 1868))) ? 1 : 0) ? 1 : 0)
            continue;
        if (cptr.ldPtro2(gl, i, 8, 80)) {
            (yield* nhl_done(cptr.ldPtro2(gl, i, 8, 80)));
            cptr.stPtro2(gl, i, 8, 80, null);
        }
    }
}

/** C ref: mklev.c:367 */
function* makerooms() {
    let tried_vault = 0;
    let themeroom_tries = 0;
    let fname;
    let sbi = cptr.alloc(16); cptr.stI32(sbi, NHM.NHL_SB_SAFE); cptr.stI32o(sbi, 4, 1048576); cptr.stI32o(sbi, 8, 0); cptr.stI32o(sbi, 12, 1048576);
    let themes = cptr.ldPtro2(gl, cptr.ldI16o(u, 24), 8, 80);
    if (!themes && cptr.ld1s((fname = cptr.add(cptr.add(svd, cptr.ldI16o(u, 24), 112), 54))) ? 1 : 0) {
        if ((themes = (yield* nhl_init(sbi))) !== null) {
            if (!(yield* nhl_loadlua(themes, fname))) {
                (yield* nhl_done(themes));
                themes = null;
            } else {
                cptr.stPtro2(gl, cptr.ldI16o(u, 24), 8, 80, themes);
                cptr.st1o(iflags, 5, 0);
            }
        }
        if (!themes)
            cptr.st1(fname, 0);
    }
    if (themes) {
        (yield* create_des_coder());
        cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 1));
        cptr.st1o(gt, 424, 0);
        (yield* lua_getglobal(themes, __sl6));
        (yield* nhl_pcall_handle(themes, 0, 0, __sl7, NHC.NHLpa_impossible));
        cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 0));
    }
    while (cptr.ldI32o(svn, 44) < 39 && rnd_rect() ? 1 : 0) {
        if ((cptr.ldI32o(svn, 44) >= 6 && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 404, __sl8), rn2(2)) : rn2(2)) ? 1 : 0) && !tried_vault ? 1 : 0) {
            tried_vault = 1;
            if ((yield* create_room(-1, -1, 2, 2, -1, -1, NHC.VAULT, 1))) {
                cptr.stI16o(gv, 82, cptr.ldI16o(svr, cptr.ldI32o(svn, 44), 224));
                cptr.stI16o(gv, 84, cptr.ldI16o2(svr, cptr.ldI32o(svn, 44), 224, 4));
                cptr.stI16o2(svr, cptr.ldI32o(svn, 44), 224, 2, -1);
            }
        } else {
            if (themes) {
                cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 1));
                cptr.st1o(gt, 424, 0);
                (yield* lua_getglobal(themes, __sl9));
                (yield* nhl_pcall_handle(themes, 0, 0, __sl10, NHC.NHLpa_panic));
                cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 0));
                if (cptr.ld1so(gt, 424) && ((themeroom_tries++ > 10) || (cptr.ldI32o(svn, 44) >= 6) ? 1 : 0) ? 1 : 0)
                    break;
            } else {
                if (!(yield* create_room(-1, -1, -1, -1, -1, -1, NHC.OROOM, -1)))
                    break;
                ;
            }
        }
    }
    if (themes) {
        reset_xystart_size();
        cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 1));
        cptr.st1o(gt, 424, 0);
        (yield* lua_getglobal(themes, __sl11));
        (yield* nhl_pcall_handle(themes, 0, 0, __sl12, NHC.NHLpa_panic));
        cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 0));
    }
}

/** C ref: mklev.c:439 — @param {CInt} a @param {CInt} b @param {CInt} nxcor */
function* join(a, b, nxcor) {
    let cc = cptr.alloc(4);
    let tt = cptr.alloc(4);
    let org = cptr.alloc(4);
    let dest = cptr.alloc(4);
    let tx;
    let ty;
    let xx;
    let yy;
    let croom;
    let troom;
    let dx;
    let dy;
    let npoints = cptr.box(0);
    let dig_result;
    croom = cptr.add(svr, a, 224);
    troom = cptr.add(svr, b, 224);
    if (!cptr.ld1so(croom, 12) || !cptr.ld1so(troom, 12) ? 1 : 0)
        return;
    if (cptr.ldI16o(troom, 2) < 0 || cptr.ldI16o(croom, 2) < 0 ? 1 : 0)
        return;
    if (cptr.ldI16(troom) > cptr.ldI16o(croom, 2)) {
        dx = 1;
        dy = 0;
        if (!(yield* finddpos(cc, NHC.DIR_E, croom)))
            return;
        if (!(yield* finddpos(tt, NHC.DIR_W, troom)))
            return;
    } else if (cptr.ldI16o(troom, 6) < cptr.ldI16o(croom, 4)) {
        dy = -1;
        dx = 0;
        if (!(yield* finddpos(cc, NHC.DIR_N, croom)))
            return;
        if (!(yield* finddpos(tt, NHC.DIR_S, troom)))
            return;
    } else if (cptr.ldI16o(troom, 2) < cptr.ldI16(croom)) {
        dx = -1;
        dy = 0;
        if (!(yield* finddpos(cc, NHC.DIR_W, croom)))
            return;
        if (!(yield* finddpos(tt, NHC.DIR_E, troom)))
            return;
    } else {
        dy = 1;
        dx = 0;
        if (!(yield* finddpos(cc, NHC.DIR_S, croom)))
            return;
        if (!(yield* finddpos(tt, NHC.DIR_N, troom)))
            return;
    }
    xx = cptr.ldI16(cc);
    yy = cptr.ldI16o(cc, 2);
    tx = i16(((cptr.ldI16(tt) - dx) | 0));
    ty = i16(((cptr.ldI16o(tt, 2) - dy) | 0));
    if (nxcor && cptr.ld1so3(svl, (xx + dx) | 0, 756, (yy + dy) | 0, 36, 1684) != NHC.STONE ? 1 : 0)
        return;
    cptr.stI16(org, i16(((xx + dx) | 0)));
    cptr.stI16o(org, 2, i16(((yy + dy) | 0)));
    cptr.stI16(dest, tx);
    cptr.stI16o(dest, 2, ty);
    dig_result = (yield* dig_corridor(org, dest, npoints, nxcor, schar(((cptr.ldI32o(svl, 89156) & 1) | 0 ? NHC.ROOM : NHC.CORR)), NHC.STONE));
    if ((npoints.v > 0) && (okdoor(xx, yy) || !nxcor ? 1 : 0) ? 1 : 0)
        (yield* dodoor(xx, yy, croom));
    if (!dig_result)
        return;
    if (okdoor(cptr.ldI16(tt), cptr.ldI16o(tt, 2)) || !nxcor ? 1 : 0)
        (yield* dodoor(cptr.ldI16(tt), cptr.ldI16o(tt, 2), troom));
    if (cptr.ldI32o2(gs, a, 4, 16) < cptr.ldI32o2(gs, b, 4, 16))
        cptr.stI32o2(gs, b, 4, 16, cptr.ldI32o2(gs, a, 4, 16));
    else
        cptr.stI32o2(gs, a, 4, 16, cptr.ldI32o2(gs, b, 4, 16));
}

/** C ref: mklev.c:522 */
export function* makecorridors() {
    let a;
    let b;
    let i;
    let any = 1;
    for (a = 0; a < ((cptr.ldI32o(svn, 44) - 1) | 0); a++) {
        (yield* join(a, (a + 1) | 0, 0));
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 529, __sl13), rn2(50)) : rn2(50)))
            break;
    }
    for (a = 0; a < ((cptr.ldI32o(svn, 44) - 2) | 0); a++)
        if (cptr.ldI32o2(gs, a, 4, 16) != cptr.ldI32o2(gs, (a + 2) | 0, 4, 16))
            (yield* join(a, (a + 2) | 0, 0));
    for (a = 0; any && a < cptr.ldI32o(svn, 44) ? 1 : 0; a++) {
        any = 0;
        for (b = 0; b < cptr.ldI32o(svn, 44); b++)
            if (cptr.ldI32o2(gs, a, 4, 16) != cptr.ldI32o2(gs, b, 4, 16)) {
                (yield* join(a, b, 0));
                any = 1;
            }
    }
    if (cptr.ldI32o(svn, 44) > 2)
        for (i = ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 545, __sl13), rn2(cptr.ldI32o(svn, 44))) : rn2(cptr.ldI32o(svn, 44))) + 4) | 0; i; i--) {
            a = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 546, __sl13), rn2(cptr.ldI32o(svn, 44))) : rn2(cptr.ldI32o(svn, 44)));
            b = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 547, __sl13), rn2((cptr.ldI32o(svn, 44) - 2) | 0)) : rn2((cptr.ldI32o(svn, 44) - 2) | 0));
            if (b >= a)
                b = (b + 2) | 0;
            (yield* join(a, b, 1));
        }
}

/** C ref: mklev.c:556 */
function* alloc_doors() {
    if (!cptr.ldPtro(svd, 1928) || cptr.ldI32(gd) >= cptr.ldI32o(svd, 1936) ? 1 : 0) {
        let c = (cptr.ldI32o(svd, 1936) + NHM.DOORINC) | 0;
        let doortmp = (yield* alloc(Number(BigInt.asUintN(32, BigInt.asUintN(64, BigInt.asUintN(64, BigInt(c)) * 4n)))));
        void __builtin___memset_chk(doortmp, 0, BigInt.asUintN(64, BigInt.asUintN(64, BigInt(c)) * 4n), __builtin_object_size(doortmp, 0));
        if (cptr.ldPtro(svd, 1928)) {
            void cptr.memcpy(doortmp, cptr.ldPtro(svd, 1928), BigInt.asUintN(64, BigInt.asUintN(64, BigInt(cptr.ldI32o(svd, 1936))) * 4n));
            cptr.free(cptr.ldPtro(svd, 1928));
        }
        cptr.stPtro(svd, 1928, doortmp);
        cptr.stI32o(svd, 1936, c);
    }
}

/** C ref: mklev.c:574 — @param {CInt} x @param {CInt} y @param {CPtr} aroom */
export function* add_door(x, y, aroom) {
    let broom;
    let tmp;
    let i;
    (yield* alloc_doors());
    if (cptr.ld1so(aroom, 13)) {
        for (i = 0; i < cptr.ld1so(aroom, 13); i++) {
            tmp = (cptr.ldI32o(aroom, 16) + i) | 0;
            if (cptr.ldI16o(cptr.ldPtro(svd, 1928), tmp, 4) == x && cptr.ldI16o2(cptr.ldPtro(svd, 1928), tmp, 4, 2) == y ? 1 : 0)
                return;
        }
    }
    if (cptr.ld1so(aroom, 13) == 0)
        cptr.stI32o(aroom, 16, cptr.ldI32(gd));
    cptr.postinc1(cptr.add(aroom, 13));
    for (tmp = cptr.ldI32(gd); tmp > cptr.ldI32o(aroom, 16); tmp--)
        cptr.memcpy(cptr.add(cptr.ldPtro(svd, 1928), tmp, 4), cptr.add(cptr.ldPtro(svd, 1928), (tmp - 1) | 0, 4), 4);
    for (i = 0; i < cptr.ldI32o(svn, 44); i++) {
        broom = cptr.add(svr, i, 224);
        if ((!cptr.eq(broom, aroom) && cptr.ld1so(broom, 13) ? 1 : 0) && cptr.ldI32o(broom, 16) >= cptr.ldI32o(aroom, 16) ? 1 : 0)
            (cptr.stI32o(broom, 16, cptr.ldI32o(broom, 16) + 1)) - (1);
    }
    for (i = 0; i < cptr.ldI32o(gn, 16); i++) {
        broom = cptr.add(cptr.ldPtro(gs, 184), i, 224);
        if ((!cptr.eq(broom, aroom) && cptr.ld1so(broom, 13) ? 1 : 0) && cptr.ldI32o(broom, 16) >= cptr.ldI32o(aroom, 16) ? 1 : 0)
            (cptr.stI32o(broom, 16, cptr.ldI32o(broom, 16) + 1)) - (1);
    }
    (cptr.stI32(gd, cptr.ldI32(gd) + 1)) - (1);
    cptr.stI16o(cptr.ldPtro(svd, 1928), cptr.ldI32o(aroom, 16), x, 4);
    cptr.stI16o2(cptr.ldPtro(svd, 1928), cptr.ldI32o(aroom, 16), 4, 2, y);
}

/** C ref: mklev.c:615 — @param {CInt} x @param {CInt} y @param {CPtr} aroom @param {CInt} type */
function* dosdoor(x, y, aroom, type) {
    let shdoor = schar((cptr.ld1s((yield* in_rooms(x, y, NHC.SHOPBASE))) ? 1 : 0));
    if (!((cptr.ld1so3(svl, x, 756, y, 36, 1684)) && (cptr.ld1so3(svl, x, 756, y, 36, 1684)) <= NHC.DBWALL ? 1 : 0))
        type = NHC.DOOR;
    cptr.st1o3(svl, x, 756, y, 36, 1684, schar(type));
    if (type == NHC.DOOR) {
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 623, __sl14), rn2(3)) : rn2(3))) {
            if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 624, __sl14), rn2(5)) : rn2(5)))
                cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_ISOPEN);
            else if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 626, __sl14), rn2(6)) : rn2(6)))
                cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_LOCKED);
            else
                cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_CLOSED);
            if (((((cptr.ldI32o3(svl, x, 756, y, 36, 1688) & 31) | 0) != NHM.D_ISOPEN && !shdoor ? 1 : 0) && (yield* level_difficulty()) >= 5 ? 1 : 0) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 632, __sl14), rn2(25)) : rn2(25)) ? 1 : 0)
                cptr.stI32o3(svl, x, 756, y, 36, 1688, cptr.ldI32o3(svl, x, 756, y, 36, 1688) | NHM.D_TRAPPED);
        } else {
            cptr.stI32o3(svl, x, 756, y, 36, 1688, (shdoor ? NHM.D_ISOPEN : NHM.D_NODOOR) >>> 0);
        }
        if ((((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0)))
            cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_NODOOR);
        if (((cptr.ldI32o3(svl, x, 756, y, 36, 1688) & 31) | 0) & NHM.D_TRAPPED) {
            let mtmp;
            if (((yield* level_difficulty()) >= 9 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 653, __sl14), rn2(5)) : rn2(5)) ? 1 : 0) && !(((cptr.ld1uo2(svm, NHC.PM_SMALL_MIMIC, 12, 18) & 3) && (cptr.ld1uo2(svm, NHC.PM_LARGE_MIMIC, 12, 18) & 3) ? 1 : 0) && (cptr.ld1uo2(svm, NHC.PM_GIANT_MIMIC, 12, 18) & 3) ? 1 : 0) ? 1 : 0) {
                cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_NODOOR);
                mtmp = (yield* makemon((yield* mkclass(NHC.S_MIMIC, 0)), x, y, NHM.NO_MM_FLAGS));
                if (mtmp)
                    (yield* set_mimic_sym(mtmp));
            }
        }
    } else {
        if (shdoor || !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 666, __sl14), rn2(5)) : rn2(5)) ? 1 : 0)
            cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_LOCKED);
        else
            cptr.stI32o3(svl, x, 756, y, 36, 1688, NHM.D_CLOSED);
        if ((!shdoor && (yield* level_difficulty()) >= 4 ? 1 : 0) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 671, __sl14), rn2(20)) : rn2(20)) ? 1 : 0)
            cptr.stI32o3(svl, x, 756, y, 36, 1688, cptr.ldI32o3(svl, x, 756, y, 36, 1688) | NHM.D_TRAPPED);
    }
    (yield* add_door(x, y, aroom));
}

/** C ref: mklev.c:681 — @param {CPtr} aroom @param {CInt} x @param {CInt} y @returns {CInt} */
function cardinal_nextto_room(aroom, x, y) {
    let rmno = Number(BigInt.asIntN(32, (BigInt.asIntN(64, (cptr.diff(aroom, svr) / 224n) + 3n))));
    if ((isok(i16(((x - 1) | 0)), y) && !(cptr.ldI32o3(svl, (x - 1) | 0, 756, y, 36, 1708) & 1) ? 1 : 0) && ((cptr.ldI32o3(svl, (x - 1) | 0, 756, y, 36, 1704) & 63) | 0) == rmno ? 1 : 0)
        return 1;
    if ((isok(i16(((x + 1) | 0)), y) && !(cptr.ldI32o3(svl, (x + 1) | 0, 756, y, 36, 1708) & 1) ? 1 : 0) && ((cptr.ldI32o3(svl, (x + 1) | 0, 756, y, 36, 1704) & 63) | 0) == rmno ? 1 : 0)
        return 1;
    if ((isok(x, i16(((y - 1) | 0))) && !(cptr.ldI32o3(svl, x, 756, (y - 1) | 0, 36, 1708) & 1) ? 1 : 0) && ((cptr.ldI32o3(svl, x, 756, (y - 1) | 0, 36, 1704) & 63) | 0) == rmno ? 1 : 0)
        return 1;
    if ((isok(x, i16(((y + 1) | 0))) && !(cptr.ldI32o3(svl, x, 756, (y + 1) | 0, 36, 1708) & 1) ? 1 : 0) && ((cptr.ldI32o3(svl, x, 756, (y + 1) | 0, 36, 1704) & 63) | 0) == rmno ? 1 : 0)
        return 1;
    return 0;
}

/** C ref: mklev.c:701 — @param {CPtr} aroom @param {CPtr} dy @param {CPtr} xx @param {CPtr} yy @returns {CInt} */
function* place_niche(aroom, dy, xx, yy) {
    let dd = cptr.alloc(4);
    if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 708, __sl15), rn2(2)) : rn2(2))) {
        cptr.stI32(dy, 1);
        if (!(yield* finddpos(dd, NHC.DIR_S, aroom)))
            return 0;
    } else {
        cptr.stI32(dy, -1);
        if (!(yield* finddpos(dd, NHC.DIR_N, aroom)))
            return 0;
    }
    cptr.stI16(xx, cptr.ldI16(dd));
    cptr.stI16(yy, cptr.ldI16o(dd, 2));
    return schar((((isok(cptr.ldI16(xx), i16(((cptr.ldI16(yy) + cptr.ldI32(dy)) | 0))) && cptr.ld1so3(svl, cptr.ldI16(xx), 756, (cptr.ldI16(yy) + cptr.ldI32(dy)) | 0, 36, 1684) == NHC.STONE ? 1 : 0) && ((isok(cptr.ldI16(xx), i16(((cptr.ldI16(yy) - cptr.ldI32(dy)) | 0))) && !((cptr.ld1so3(svl, cptr.ldI16(xx), 756, (cptr.ldI16(yy) - cptr.ldI32(dy)) | 0, 36, 1684)) >= NHC.POOL && (cptr.ld1so3(svl, cptr.ldI16(xx), 756, (cptr.ldI16(yy) - cptr.ldI32(dy)) | 0, 36, 1684)) <= NHC.DRAWBRIDGE_UP ? 1 : 0) ? 1 : 0) && !((cptr.ld1so3(svl, cptr.ldI16(xx), 756, (cptr.ldI16(yy) - cptr.ldI32(dy)) | 0, 36, 1684)) >= NHC.STAIRS && (cptr.ld1so3(svl, cptr.ldI16(xx), 756, (cptr.ldI16(yy) - cptr.ldI32(dy)) | 0, 36, 1684)) <= NHC.ALTAR ? 1 : 0) ? 1 : 0) ? 1 : 0) && cardinal_nextto_room(aroom, cptr.ldI16(xx), cptr.ldI16(yy)) ? 1 : 0));
}

/** C ref: mklev.c:728 — char *[26] */
const trap_engravings = cptr.alloc(26 * 8);
cptr.stPtro(trap_engravings, 0, null);
cptr.stPtro(trap_engravings, 8, null);
cptr.stPtro(trap_engravings, 16, null);
cptr.stPtro(trap_engravings, 24, null);
cptr.stPtro(trap_engravings, 32, null);
cptr.stPtro(trap_engravings, 40, null);
cptr.stPtro(trap_engravings, 48, null);
cptr.stPtro(trap_engravings, 56, null);
cptr.stPtro(trap_engravings, 64, null);
cptr.stPtro(trap_engravings, 72, null);
cptr.stPtro(trap_engravings, 80, null);
cptr.stPtro(trap_engravings, 88, null);
cptr.stPtro(trap_engravings, 96, null);
cptr.stPtro(trap_engravings, 104, null);
cptr.stPtro(trap_engravings, 112, __sl16);
cptr.stPtro(trap_engravings, 120, __sl17);
cptr.stPtro(trap_engravings, 128, __sl17);
cptr.stPtro(trap_engravings, 136, null);
cptr.stPtro(trap_engravings, 144, null);
cptr.stPtro(trap_engravings, 152, null);
cptr.stPtro(trap_engravings, 160, null);
cptr.stPtro(trap_engravings, 168, null);
cptr.stPtro(trap_engravings, 176, null);
cptr.stPtro(trap_engravings, 184, null);
cptr.stPtro(trap_engravings, 192, null);
cptr.stPtro(trap_engravings, 200, null);

/** C ref: mklev.c:740 — @param {CInt} trap_type */
function* makeniche(trap_type) {
    let aroom;
    let rm;
    let dy = cptr.box(0);
    let vct = 8;
    let xx = cptr.box(0);
    let yy = cptr.box(0);
    let ttmp;
    while (vct--) {
        aroom = cptr.add(svr, (rng_log_enabled() ? (rng_log_set_caller(__sl1, 749, __sl18), rn2(cptr.ldI32o(svn, 44))) : rn2(cptr.ldI32o(svn, 44))), 224);
        if (cptr.ld1so(aroom, 8) != NHC.OROOM)
            continue;
        if (cptr.ld1so(aroom, 13) == 1 && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 752, __sl18), rn2(5)) : rn2(5)) ? 1 : 0)
            continue;
        if (!(yield* place_niche(aroom, dy, xx, yy)))
            continue;
        rm = cptr.add(cptr.add(cptr.add(svl, 1680), xx.v, 756), (yy.v + dy.v) | 0, 36);
        if (trap_type || !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 758, __sl18), rn2(4)) : rn2(4)) ? 1 : 0) {
            cptr.st1o(rm, 4, NHC.SCORR);
            if (trap_type) {
                if (((trap_type) == NHC.HOLE || (trap_type) == NHC.TRAPDOOR ? 1 : 0) && !Can_fall_thru(cptr.add(u, 24)) ? 1 : 0)
                    trap_type = NHC.ROCKTRAP;
                ttmp = (yield* maketrap(xx.v, i16(((yy.v + dy.v) | 0)), trap_type));
                if (ttmp) {
                    if (trap_type != NHC.ROCKTRAP)
                        cptr.stI32o(ttmp, 28, 1);
                    if (cptr.ldPtro(trap_engravings, trap_type, 8)) {
                        (yield* make_engr_at(xx.v, i16(((yy.v - dy.v) | 0)), cptr.ldPtro(trap_engravings, trap_type, 8), null, 0n, NHM.DUST));
                        (yield* wipe_engr_at(xx.v, i16(((yy.v - dy.v) | 0)), 5, 0));
                    }
                }
            }
            (yield* dosdoor(xx.v, yy.v, aroom, NHC.SDOOR));
        } else {
            cptr.st1o(rm, 4, NHC.CORR);
            if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 779, __sl18), rn2(7)) : rn2(7))) {
                (yield* dosdoor(xx.v, yy.v, aroom, (rng_log_enabled() ? (rng_log_set_caller(__sl1, 780, __sl18), rn2(5)) : rn2(5)) ? NHC.SDOOR : NHC.DOOR));
            } else {
                if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 783, __sl18), rn2(5)) : rn2(5)) && ((cptr.ld1so3(svl, xx.v, 756, yy.v, 36, 1684)) && (cptr.ld1so3(svl, xx.v, 756, yy.v, 36, 1684)) <= NHC.DBWALL ? 1 : 0) ? 1 : 0) {
                    void (yield* set_levltyp(xx.v, yy.v, NHC.IRONBARS));
                    if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 785, __sl18), rn2(3)) : rn2(3)))
                        void (yield* mkcorpstat(NHC.CORPSE, null, (yield* mkclass(NHC.S_HUMAN, 0)), xx.v, i16(((yy.v + dy.v) | 0)), 1));
                }
                if (!(cptr.ldI32o(svl, 89120) & 1))
                    void (yield* mksobj_at(NHC.SCR_TELEPORTATION, xx.v, i16(((yy.v + dy.v) | 0)), 1, 0));
                if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 793, __sl18), rn2(3)) : rn2(3)))
                    void (yield* mkobj_at(NHC.RANDOM_CLASS, xx.v, i16(((yy.v + dy.v) | 0)), 1));
            }
        }
        return;
    }
}

/** C ref: mklev.c:802 */
function* make_niches() {
    let ct = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 804, __sl19), rnd(((cptr.ldI32o(svn, 44) >> 1) + 1) | 0)) : rnd(((cptr.ldI32o(svn, 44) >> 1) + 1) | 0));
    let dep = depth(cptr.add(u, 24));
    let ltptr = schar((!(cptr.ldI32o(svl, 89120) & 1) && dep > 15 ? 1 : 0));
    let vamp = schar((dep > 5 && dep < 25 ? 1 : 0));
    while (ct--) {
        if (ltptr && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 809, __sl19), rn2(6)) : rn2(6)) ? 1 : 0) {
            ltptr = 0;
            (yield* makeniche(NHC.LEVEL_TELEP));
        } else if (vamp && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 812, __sl19), rn2(6)) : rn2(6)) ? 1 : 0) {
            vamp = 0;
            (yield* makeniche(NHC.TRAPDOOR));
        } else
            (yield* makeniche(NHC.NO_TRAP));
    }
}

/** C ref: mklev.c:821 */
function* makevtele() {
    (yield* makeniche(NHC.TELEP_TRAP));
}

/** C ref: mklev.c:828 */
export function count_level_features() {
    let x;
    let y;
    cptr.st1o(svl, 89080, cptr.st1o(svl, 89081, 0));
    for (y = 0; y < NHM.ROWNO; y++)
        for (x = 1; x < NHM.COLNO; x++) {
            let typ = cptr.ld1so3(svl, x, 756, y, 36, 1684);
            if (typ == NHC.FOUNTAIN)
                cptr.postinc1(cptr.add(svl, 89080));
            else if (typ == NHC.SINK)
                cptr.postinc1(cptr.add(svl, 89081));
        }
}

let __static_clear_level_structures_zerorm = cptr.alloc(36); /** C ref: mklev.c:852 — struct rm (function-static) */
cptr.stI32(__static_clear_level_structures_zerorm, NHC.GLYPH_UNEXPLORED_OFF);
cptr.st1o(__static_clear_level_structures_zerorm, 4, 0);
cptr.st1o(__static_clear_level_structures_zerorm, 5, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 8, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 12, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 16, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 20, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 24, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 28, 0);
cptr.stI32o(__static_clear_level_structures_zerorm, 32, 0);

/** C ref: mklev.c:850 */
export function* clear_level_structures() {
    let x;
    let y;
    let lev;
    for (x = 0; x < NHM.COLNO; x++) {
        lev = cptr.add(cptr.add(cptr.add(svl, 1680), x, 756), 0, 36);
        for (y = 0; y < NHM.ROWNO; y++) {
            cptr.memcpy(cptr.postinc(() => lev, (v) => { lev = v; }, 36), __static_clear_level_structures_zerorm, 36);
            cptr.stPtro3(svl, x, 168, y, 8, 62160, null);
            cptr.stPtro3(svl, x, 168, y, 8, 75600, null);
        }
    }
    cptr.stPtro(svl, 89040, null);
    cptr.stPtro(svl, 89048, null);
    cptr.stPtro(svl, 89056, null);
    cptr.stPtro(svl, 89064, null);
    cptr.stPtro(svl, 89072, null);
    cptr.st1o(svl, 89080, 0);
    cptr.st1o(svl, 89081, 0);
    cptr.stI32o(svl, 89084, 0);
    cptr.stI32o(svl, 89088, 0);
    cptr.stI32o(svl, 89092, 0);
    cptr.stI32o(svl, 89096, 0);
    cptr.stI32o(svl, 89100, cptr.stI32o(svl, 89140, 0));
    cptr.stI32o(svl, 89104, 0);
    cptr.stI32o(svl, 89108, 0);
    cptr.stI32o(svl, 89112, 0);
    cptr.stI32o(svl, 89116, 0);
    cptr.stI32o(svl, 89120, 0);
    cptr.stI32o(svl, 89124, 0);
    cptr.stI32o(svl, 89128, 0);
    cptr.stI32o(svl, 89132, 1);
    cptr.stI32o(svl, 89136, 0);
    cptr.stI32o(svl, 89144, 0);
    cptr.stI32o(svl, 89148, 0);
    cptr.stI32o(svl, 89152, 0);
    cptr.stI32o(svl, 89156, 0);
    cptr.stI32o(svl, 89160, 0);
    cptr.stI32o(svl, 89164, 0);
    cptr.stI32o(svl, 89168, 0);
    cptr.st1o(svl, 89192, schar((In_hell(cptr.add(u, 24)) ? 1 : 0)));
    cptr.stI32o(svl, 89172, 1);
    cptr.stI32o(svl, 89176, 1);
    cptr.stI32o(svl, 89180, 0);
    cptr.stI32o(svl, 89184, 0);
    cptr.stI32o(svl, 89188, 0);
    cptr.stI64o(svl, 89200, 0n);
    cptr.stI32o(svn, 44, 0);
    cptr.stI16o2(svr, 0, 224, 2, -1);
    cptr.stI32o(gn, 16, 0);
    cptr.stI16o2(cptr.ldPtro(gs, 184), 0, 224, 2, -1);
    cptr.stI32(gd, 0);
    if (cptr.ldI32o(svd, 1936)) {
        cptr.free(cptr.ldPtro(svd, 1928));
        cptr.stPtro(svd, 1928, null);
        cptr.stI32o(svd, 1936, 0);
    }
    (yield* init_rect());
    cptr.stI16o(gv, 82, -1);
    stairway_free_all();
    cptr.st1o(gm, 220, 0);
    clear_regions();
    free_exclusions();
    reset_xystart_size();
    if (cptr.ldPtro(gl, 512)) {
        cptr.free(cptr.ldPtro(gl, 512));
        cptr.stPtro(gl, 512, null);
    }
}

const __static_fill_ordinary_room_supply_items = cptr.alloc(9 * 4);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 0, NHC.POT_EXTRA_HEALING);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 4, NHC.POT_SPEED);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 8, NHC.POT_GAIN_ENERGY);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 12, NHC.SCR_ENCHANT_WEAPON);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 16, NHC.SCR_ENCHANT_ARMOR);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 20, NHC.SCR_CONFUSE_MONSTER);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 24, NHC.SCR_SCARE_MONSTER);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 28, NHC.WAN_DIGGING);
cptr.stI32o(__static_fill_ordinary_room_supply_items, 32, NHC.SPE_HEALING); /** C ref: mklev.c:1050 — int[9] (function-static) */
const __static_fill_ordinary_room_extra_classes = cptr.alloc(10 * 4);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 0, NHC.FOOD_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 4, NHC.WEAPON_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 8, NHC.ARMOR_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 12, NHC.GEM_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 16, NHC.SCROLL_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 20, NHC.POTION_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 24, NHC.RING_CLASS);
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 28, ((0 - NHC.SPBOOK_CLASS) | 0));
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 32, ((0 - NHC.SPBOOK_CLASS) | 0));
cptr.stI32o(__static_fill_ordinary_room_extra_classes, 36, ((0 - NHC.SPBOOK_CLASS) | 0)); /** C ref: mklev.c:1087 — int[10] (function-static) */

/** C ref: mklev.c:939 — @param {CPtr} croom @param {CInt} bonus_items */
function* fill_ordinary_room(croom, bonus_items) {
    let trycnt = 0;
    let pos = cptr.alloc(4);
    let tmonst;
    let x;
    let y;
    let skip_chests = 0;
    __lbl_skip_nonrogue: {
        if (cptr.ld1so(croom, 8) != NHC.OROOM && cptr.ld1so(croom, 8) != NHC.THEMEROOM ? 1 : 0)
            return;
        for (x = 0; x < cptr.ld1so(croom, 20); ++x) {
            let subroom = cptr.ldPtro2(croom, x, 8, 24);
            if (!subroom) {
                (yield* impossible(__sl20));
                return;
            }
            (yield* fill_ordinary_room(subroom, 0));
        }
        if (cptr.ld1so(croom, 11) != NHM.FILL_NORMAL)
            return;
        if (((cptr.ldI32o(u, 1944) & 1) | 0 || !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 974, __sl21), rn2(3)) : rn2(3)) ? 1 : 0) && somexyspace(croom, pos) ? 1 : 0) {
            tmonst = (yield* makemon(null, cptr.ldI16(pos), cptr.ldI16o(pos, 2), NHM.MM_NOGRP));
            if ((tmonst && cptr.eq(cptr.ldPtro(tmonst, 8), cptr.add(mons, NHC.PM_GIANT_SPIDER, 96)) ? 1 : 0) && !occupied(cptr.ldI16(pos), cptr.ldI16o(pos, 2)) ? 1 : 0)
                void (yield* maketrap(cptr.ldI16(pos), cptr.ldI16o(pos, 2), NHC.WEB));
        }
        x = i16(((8 - (((yield* level_difficulty()) / 6) | 0)) | 0));
        if (x <= 1)
            x = 2;
        while (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 984, __sl21), rn2(x)) : rn2(x)) && (++trycnt < 1000) ? 1 : 0)
            (yield* mktrap(0, NHM.MKTRAP_NOFLAGS, croom, null));
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 986, __sl21), rn2(3)) : rn2(3)) && somexyspace(croom, pos) ? 1 : 0)
            void (yield* mkgold(0n, cptr.ldI16(pos), cptr.ldI16o(pos, 2)));
        if ((((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0)))
            break __lbl_skip_nonrogue;
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 990, __sl21), rn2(10)) : rn2(10)))
            (yield* mkfount(croom));
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 992, __sl21), rn2(60)) : rn2(60)))
            (yield* mksink(croom));
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 994, __sl21), rn2(60)) : rn2(60)))
            (yield* mkaltar(croom));
        x = i16(((80 - (Math.imul(depth(cptr.add(u, 24)), 2))) | 0));
        if (x < 2)
            x = 2;
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 999, __sl21), rn2(x)) : rn2(x)))
            (yield* mkgrave(croom));
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1003, __sl21), rn2(20)) : rn2(20)) && somexyspace(croom, pos) ? 1 : 0)
            void (yield* mkcorpstat(NHC.STATUE, null, null, cptr.ldI16(pos), cptr.ldI16o(pos, 2), NHM.CORPSTAT_INIT));
        if (bonus_items && somexyspace(croom, pos) ? 1 : 0) {
            let uz_branch = Is_branchlev(cptr.add(u, 24));
            if ((uz_branch && cptr.ldI16o(u, 24) != (cptr.ldI16o(svd, 1876)) ? 1 : 0) && (cptr.ldI16o(uz_branch, 16) == (cptr.ldI16o(svd, 1876)) || cptr.ldI16o(uz_branch, 20) == (cptr.ldI16o(svd, 1876)) ? 1 : 0) ? 1 : 0) {
                void (yield* mksobj_at(((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1032, __sl21), rn2(5)) : rn2(5)) < 3) ? NHC.FOOD_RATION : ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1033, __sl21), rn2(2)) : rn2(2)) ? NHC.CRAM_RATION : NHC.LEMBAS_WAFER), cptr.ldI16(pos), cptr.ldI16o(pos, 2), 1, 0));
            } else if ((cptr.ldI16o(u, 24) == cptr.ldI16((cptr.add(svd, 1792))) && cptr.ldI16o(u, 26) < cptr.ldI16o((cptr.add(svd, 1792)), 2) ? 1 : 0) && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1037, __sl21), rn2(3)) : rn2(3)) ? 1 : 0) {
                let otmp;
                let otyp;
                let tryct = 0;
                let cursed;
                let supply_chest = (yield* mksobj_at((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1044, __sl21), rn2(3)) : rn2(3)) ? NHC.CHEST : NHC.LARGE_BOX, cptr.ldI16(pos), cptr.ldI16o(pos, 2), 0, 0));
                cptr.stI32o(supply_chest, 124, (!!((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1047, __sl21), rn2(6)) : rn2(6)))) >>> 0);
                do {
                    otyp = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1063, __sl21), rn2(2)) : rn2(2)) ? NHC.POT_HEALING : cptr.ldI32o(__static_fill_ordinary_room_supply_items, (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1063, __sl21), rn2(9)) : rn2(9)), 4);
                    otmp = (yield* mksobj(otyp, 1, 0));
                    if (otyp == NHC.POT_HEALING && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1065, __sl21), rn2(2)) : rn2(2)) ? 1 : 0) {
                        cptr.stI64o(otmp, 40, 2n);
                        cptr.stI32o(otmp, 36, (yield* weight(otmp)) >>> 0);
                    }
                    cursed = schar((cptr.ldI32o(otmp, 56) & 1));
                    (yield* add_to_container(supply_chest, otmp));
                    ++tryct;
                    if (tryct == 50) {
                        (yield* impossible(__sl22));
                        break;
                    }
                } while (cursed || !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1081, __sl21), rn2(5)) : rn2(5)) ? 1 : 0);
                if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1086, __sl21), rn2(3)) : rn2(3))) {
                    let oclass = cptr.ldI32o(__static_fill_ordinary_room_extra_classes, (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1099, __sl21), rn2(10)) : rn2(10)), 4);
                    otmp = (yield* mkobj(oclass, 0));
                    if (oclass == ((0 - NHC.SPBOOK_CLASS) | 0)) {
                        let pass;
                        let maxpass = (depth(cptr.add(u, 24)) > 2) ? 2 : 3;
                        for (pass = 1; pass <= maxpass; ++pass) {
                            let otmp2 = (yield* mkobj(oclass, 0));
                            if (cptr.ld1so2(objects, cptr.ldI16o(otmp, 32), 120, 85) <= cptr.ld1so2(objects, cptr.ldI16o(otmp2, 32), 120, 85)) {
                                (yield* dealloc_obj(otmp2));
                            } else {
                                (yield* dealloc_obj(otmp));
                                otmp = otmp2;
                            }
                        }
                    }
                    (yield* add_to_container(supply_chest, otmp));
                }
                cptr.stI32o(supply_chest, 36, (yield* weight(supply_chest)) >>> 0);
                skip_chests = 1;
            }
        }
        if ((!skip_chests && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1137, __sl21), rn2((Math.imul(cptr.ldI32o(svn, 44), 5) / 2) | 0)) : rn2((Math.imul(cptr.ldI32o(svn, 44), 5) / 2) | 0)) ? 1 : 0) && somexyspace(croom, pos) ? 1 : 0)
            void (yield* mksobj_at((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1138, __sl21), rn2(3)) : rn2(3)) ? NHC.LARGE_BOX : NHC.CHEST, cptr.ldI16(pos), cptr.ldI16o(pos, 2), 1, 0));
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1142, __sl21), rn2((27 + Math.imul(3, Math.abs(depth(cptr.add(u, 24))))) | 0)) : rn2((27 + Math.imul(3, Math.abs(depth(cptr.add(u, 24))))) | 0))) {
            let buf = new Uint8Array(256);
            let pristinebuf = new Uint8Array(256);
            let mesg = (yield* random_engraving(cptr.decay(buf), cptr.decay(pristinebuf)));
            if (mesg) {
                do {
                    void somexyspace(croom, pos);
                    x = cptr.ldI16(pos);
                    y = cptr.ldI16o(pos, 2);
                } while (cptr.ld1so3(svl, x, 756, y, 36, 1684) != NHC.ROOM && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1151, __sl21), rn2(40)) : rn2(40)) ? 1 : 0);
                if (cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.ROOM)
                    (yield* make_engr_at(x, y, mesg, cptr.decay(pristinebuf), 0n, NHM.MARK));
            }
        }
    }
    if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1158, __sl21), rn2(3)) : rn2(3)) && somexyspace(croom, pos) ? 1 : 0) {
        void (yield* mkobj_at(NHC.RANDOM_CLASS, cptr.ldI16(pos), cptr.ldI16o(pos, 2), 1));
        trycnt = 0;
        while (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1161, __sl21), rn2(5)) : rn2(5))) {
            if (++trycnt > 100) {
                (yield* impossible(__sl23));
                break;
            }
            if (somexyspace(croom, pos)) {
                void (yield* mkobj_at(NHC.RANDOM_CLASS, cptr.ldI16(pos), cptr.ldI16o(pos, 2), 1));
            }
        }
    }
}

/** C ref: mklev.c:1174 */
function* themerooms_post_level_generate() {
    let themes = cptr.ldPtro2(gl, cptr.ldI16o(u, 24), 8, 80);
    if (!themes)
        return;
    reset_xystart_size();
    cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 1));
    cptr.st1o(gt, 424, 0);
    (yield* lua_getglobal(themes, __sl24));
    (yield* nhl_pcall_handle(themes, 0, 0, __sl24, NHC.NHLpa_panic));
    cptr.st1o(iflags, 5, cptr.st1o(gi, 64, 0));
    (yield* wallification(1, 0, 79, 20));
    if (cptr.ldPtro(gc, 568))
        cptr.free(cptr.ldPtro(gc, 568)), cptr.stPtro(gc, 568, null);
    (yield* lua_gc(themes, 2));
}

/** C ref: mklev.c:1198 — @param {CInt} x @param {CInt} y @returns {CInt} */
function chk_okdoor(x, y) {
    if (((cptr.ld1so3(svl, x, 756, y, 36, 1684)) == NHC.DOOR)) {
        if ((cptr.ldI32o3(svl, x, 756, y, 36, 1692) & 1)) {
            if ((isok(x, i16(((y - 1) | 0))) && (cptr.ld1so3(svl, x, 756, (y - 1) | 0, 36, 1684) > NHC.TREE) ? 1 : 0) && (isok(x, i16(((y + 1) | 0))) && (cptr.ld1so3(svl, x, 756, (y + 1) | 0, 36, 1684) <= NHC.TREE) ? 1 : 0) ? 1 : 0)
                return 0;
            if ((isok(x, i16(((y - 1) | 0))) && (cptr.ld1so3(svl, x, 756, (y - 1) | 0, 36, 1684) <= NHC.TREE) ? 1 : 0) && (isok(x, i16(((y + 1) | 0))) && (cptr.ld1so3(svl, x, 756, (y + 1) | 0, 36, 1684) > NHC.TREE) ? 1 : 0) ? 1 : 0)
                return 0;
        } else {
            if ((isok(i16(((x - 1) | 0)), y) && (cptr.ld1so3(svl, (x - 1) | 0, 756, y, 36, 1684) > NHC.TREE) ? 1 : 0) && (isok(i16(((x + 1) | 0)), y) && (cptr.ld1so3(svl, (x + 1) | 0, 756, y, 36, 1684) <= NHC.TREE) ? 1 : 0) ? 1 : 0)
                return 0;
            if ((isok(i16(((x - 1) | 0)), y) && (cptr.ld1so3(svl, (x - 1) | 0, 756, y, 36, 1684) <= NHC.TREE) ? 1 : 0) && (isok(i16(((x + 1) | 0)), y) && (cptr.ld1so3(svl, (x + 1) | 0, 756, y, 36, 1684) > NHC.TREE) ? 1 : 0) ? 1 : 0)
                return 0;
        }
        return 1;
    }
    return 1;
}

/** C ref: mklev.c:1223 */
function* mklev_sanity_check() {
    let x;
    let y;
    let i;
    let rmno = -1;
    if (!(cptr.ld1so(iflags, 83) || cptr.ld1so(iflags, 15) ? 1 : 0))
        return;
    for (y = 0; y < NHM.ROWNO; y++) {
        for (x = 1; x < NHM.COLNO; x++) {
            if (!chk_okdoor(x, y))
                (yield* impossible(__sl25, x, y));
        }
    }
    for (i = 0; i < cptr.ldI32o(svn, 44); i++) {
        if (!cptr.ld1so2(svr, i, 224, 12))
            continue;
        if (rmno == -1)
            rmno = cptr.ldI32o2(gs, i, 4, 16);
        if (rmno != -1 && cptr.ldI32o2(gs, i, 4, 16) != rmno ? 1 : 0)
            (yield* impossible(__sl26, i));
    }
}

/** C ref: mklev.c:1251 */
function* makelevel() {
    let w = cptr.box(0), h = cptr.box(0);
    let croom;
    let branchp;
    let prevstairs;
    let room_threshold;
    let slev;
    let i;
    if (cptr.ldI16o((cptr.add(svd, 1816)), 2) == 0) {
        (yield* impossible(__sl27));
        (yield* init_dungeons());
    }
    (yield* oinit());
    (yield* clear_level_structures());
    slev = Is_special(cptr.add(u, 24));
    if (slev && !(((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0)) ? 1 : 0) {
        (yield* makemaz(cptr.add(slev, 12)));
    } else if (cptr.ld1so3(svd, cptr.ldI16o(u, 24), 112, 0, 1, 24)) {
        (yield* makemaz(__sl28));
    } else if (cptr.ld1so3(svd, cptr.ldI16o(u, 24), 112, 0, 1, 39)) {
        (yield* makemaz(cptr.add(cptr.add(svd, cptr.ldI16o(u, 24), 112), 39)));
    } else if (In_quest(cptr.add(u, 24))) {
        let fillname = new Uint8Array(9);
        let loc_lev;
        void cptr.sprintf(cptr.decay(fillname), __sl29, cptr.ldPtro(gu, 192));
        loc_lev = (yield* find_level(cptr.decay(fillname)));
        void cptr.sprintf(cptr.decay(fillname), __sl30, cptr.ldPtro(gu, 192));
        void cptr.strcat(cptr.decay(fillname), (cptr.ldI16o(u, 26) < cptr.ldI16o(loc_lev, 10)) ? __sl31 : __sl32);
        (yield* makemaz(cptr.decay(fillname)));
    } else if (In_hell(cptr.add(u, 24)) || (((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1287, __sl33), rn2(5)) : rn2(5)) && cptr.ldI16o(u, 24) == cptr.ldI16((cptr.add(svd, 1804))) ? 1 : 0) && depth(cptr.add(u, 24)) > depth(cptr.add(svd, 1804)) ? 1 : 0) ? 1 : 0) {
        (yield* makemaz(__sl28));
    } else {
        let u_depth = depth(cptr.add(u, 24));
        __lbl_skip0: {
            if ((((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0))) {
                (yield* makeroguerooms());
                (yield* makerogueghost());
            } else {
                (yield* makerooms());
            }
            (__builtin_expect(BigInt((!(cptr.ldI32o(svn, 44) > 0))), 0n) ? __assert_rtn(__sl33, __sl34, 1300, __sl35) : void 0);
            (yield* sort_rooms());
            (yield* generate_stairs());
            branchp = Is_branchlev(cptr.add(u, 24));
            room_threshold = branchp ? 4 : 3;
            if ((((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0)))
                break __lbl_skip0;
            (yield* makecorridors());
            (yield* make_niches());
            (yield* mklev_sanity_check());
            if ((cptr.ldI16o(gv, 82) != -1)) {
                let __go_fill_vault = false;
                __skip_fill_vault: {
                    do {
                        if ((yield* debugcore(__sl1, 1))) {
                            let save_plnmsg = cptr.ldI32o(iflags, 40);
                            (yield* pline(__sl36));
                            cptr.stI32o(iflags, 40, save_plnmsg);
                        }
                    } while (0);
                    w.v = 1;
                    h.v = 1;
                    if ((yield* check_room(cptr.add(gv, 82), w, cptr.add(gv, 84), h, 1))) {
                        __go_fill_vault = true; break __skip_fill_vault;
                    } else if (rnd_rect() && (yield* create_room(-1, -1, 2, 2, -1, -1, NHC.VAULT, 1)) ? 1 : 0) {
                        cptr.stI16o(gv, 82, cptr.ldI16o(svr, cptr.ldI32o(svn, 44), 224));
                        cptr.stI16o(gv, 84, cptr.ldI16o2(svr, cptr.ldI32o(svn, 44), 224, 4));
                        if ((yield* check_room(cptr.add(gv, 82), w, cptr.add(gv, 84), h, 1)))
                            { __go_fill_vault = true; break __skip_fill_vault; }
                        else
                            cptr.stI16o2(svr, cptr.ldI32o(svn, 44), 224, 2, -1);
                    }
                }
                if (__go_fill_vault) {
                    (yield* add_room(cptr.ldI16o(gv, 82), cptr.ldI16o(gv, 84), i16(((cptr.ldI16o(gv, 82) + w.v) | 0)), i16(((cptr.ldI16o(gv, 84) + h.v) | 0)), 1, NHC.VAULT, 0));
                    cptr.stI32o(svl, 89088, 1);
                    ++room_threshold;
                    cptr.st1o2(svr, (cptr.ldI32o(svn, 44) - 1) | 0, 224, 11, NHM.FILL_NORMAL);
                    (yield* fill_special_room(cptr.add(svr, (cptr.ldI32o(svn, 44) - 1) | 0, 224)));
                    (yield* mk_knox_portal(i16(((cptr.ldI16o(gv, 82) + w.v) | 0)), i16(((cptr.ldI16o(gv, 84) + h.v) | 0))));
                    if (!(cptr.ldI32o(svl, 89120) & 1) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1332, __sl33), rn2(3)) : rn2(3)) ? 1 : 0)
                        (yield* makevtele());
                }
            }
            if (cptr.ld1so(flags, 10) && nh_getenv(__sl37) ? 1 : 0)
                (yield* do_mkroom(NHC.SHOPBASE));
            else if (((u_depth > 1 && u_depth < depth(cptr.add(svd, 1804)) ? 1 : 0) && cptr.ldI32o(svn, 44) >= room_threshold ? 1 : 0) && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1350, __sl33), rn2(u_depth)) : rn2(u_depth)) < 3 ? 1 : 0)
                (yield* do_mkroom(NHC.SHOPBASE));
            else if (u_depth > 4 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1352, __sl33), rn2(6)) : rn2(6)) ? 1 : 0)
                (yield* do_mkroom(NHC.COURT));
            else if ((u_depth > 5 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1354, __sl33), rn2(8)) : rn2(8)) ? 1 : 0) && !(cptr.ld1uo2(svm, NHC.PM_LEPRECHAUN, 12, 18) & 3) ? 1 : 0)
                (yield* do_mkroom(NHC.LEPREHALL));
            else if (u_depth > 6 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1357, __sl33), rn2(7)) : rn2(7)) ? 1 : 0)
                (yield* do_mkroom(NHC.ZOO));
            else if (u_depth > 8 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1359, __sl33), rn2(5)) : rn2(5)) ? 1 : 0)
                (yield* do_mkroom(NHC.TEMPLE));
            else if ((u_depth > 9 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1361, __sl33), rn2(5)) : rn2(5)) ? 1 : 0) && !(cptr.ld1uo2(svm, NHC.PM_KILLER_BEE, 12, 18) & 3) ? 1 : 0)
                (yield* do_mkroom(NHC.BEEHIVE));
            else if (u_depth > 11 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1364, __sl33), rn2(6)) : rn2(6)) ? 1 : 0)
                (yield* do_mkroom(NHC.MORGUE));
            else if ((u_depth > 12 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1366, __sl33), rn2(8)) : rn2(8)) ? 1 : 0) && (yield* antholemon()) ? 1 : 0)
                (yield* do_mkroom(NHC.ANTHOLE));
            else if ((u_depth > 14 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1368, __sl33), rn2(4)) : rn2(4)) ? 1 : 0) && !(cptr.ld1uo2(svm, NHC.PM_SOLDIER, 12, 18) & 3) ? 1 : 0)
                (yield* do_mkroom(NHC.BARRACKS));
            else if (u_depth > 15 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1371, __sl33), rn2(6)) : rn2(6)) ? 1 : 0)
                (yield* do_mkroom(NHC.SWAMP));
            else if ((u_depth > 16 && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1373, __sl33), rn2(8)) : rn2(8)) ? 1 : 0) && !(cptr.ld1uo2(svm, NHC.PM_COCKATRICE, 12, 18) & 3) ? 1 : 0)
                (yield* do_mkroom(NHC.COCKNEST));
        }
        prevstairs = cptr.ldPtro(gs, 8);
        (yield* place_branch(branchp, 0, 0));
        if ((cptr.ldI16o(u, 24) == 0 && cptr.ldI16o(u, 26) == 1 ? 1 : 0) && !cptr.eq(cptr.ldPtro(gs, 8), prevstairs) ? 1 : 0)
            cptr.st1o(cptr.ldPtro(gs, 8), 10, 1);
        let fillable_room_count = 0;
        for (croom = svr; cptr.ldI16o(croom, 2) > 0; croom = cptr.add(croom, 1, 224)) {
            if (((cptr.ld1so(croom, 8) == NHC.OROOM || cptr.ld1so(croom, 8) == NHC.THEMEROOM ? 1 : 0) && cptr.ld1so(croom, 11) == NHM.FILL_NORMAL ? 1 : 0))
                fillable_room_count++;
        }
        let bonus_item_room_countdown = fillable_room_count ? (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1402, __sl33), rn2(fillable_room_count)) : rn2(fillable_room_count)) : -1;
        for (croom = svr; cptr.ldI16o(croom, 2) > 0; croom = cptr.add(croom, 1, 224)) {
            let fillable = schar(((cptr.ld1so(croom, 8) == NHC.OROOM || cptr.ld1so(croom, 8) == NHC.THEMEROOM ? 1 : 0) && cptr.ld1so(croom, 11) == NHM.FILL_NORMAL ? 1 : 0));
            (yield* fill_ordinary_room(croom, schar((fillable && bonus_item_room_countdown == 0 ? 1 : 0))));
            if (fillable)
                --bonus_item_room_countdown;
        }
    }
    for (i = 0; i < cptr.ldI32o(svn, 44); ++i) {
        (yield* fill_special_room(cptr.add(svr, i, 224)));
    }
    (yield* themerooms_post_level_generate());
    if (cptr.ldPtro(gl, 216) && cptr.ldI32o(nhcb_counts, NHC.NHCB_LVL_ENTER, 4) ? 1 : 0) {
        (yield* lua_getglobal(cptr.ldPtro(gl, 216), __sl38));
        (yield* lua_pushstring(cptr.ldPtro(gl, 216), cptr.ldPtro(nhcb_name, NHC.NHCB_LVL_ENTER, 8)));
        (yield* nhl_pcall_handle(cptr.ldPtro(gl, 216), 1, 0, __sl33, NHC.NHLpa_panic));
        (yield* lua_settop(cptr.ldPtro(gl, 216), 0));
    }
}

/** C ref: mklev.c:1432 — @param {CInt} x @param {CInt} y @param {CInt} kelp_pool @param {CInt} kelp_moat @returns {CInt} */
function water_has_kelp(x, y, kelp_pool, kelp_moat) {
    if (((kelp_pool && (cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.POOL || (cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.WATER && !(((cptr.ldI16o((cptr.add(svd, 1856)), 2) || cptr.ldI16((cptr.add(svd, 1856))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1856)) ? 1 : 0)) ? 1 : 0) ? 1 : 0) ? 1 : 0) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1436, __sl39), rn2(kelp_pool)) : rn2(kelp_pool)) ? 1 : 0) || ((kelp_moat && cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.MOAT ? 1 : 0) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1437, __sl39), rn2(kelp_moat)) : rn2(kelp_moat)) ? 1 : 0) ? 1 : 0)
        return 1;
    return 0;
}

/** C ref: mklev.c:1449 — @param {CInt} kelp_pool @param {CInt} kelp_moat @param {CInt} goldprob @param {CInt} gemprob @param {CInt} skip_lvl_checks */
export function* mineralize(kelp_pool, kelp_moat, goldprob, gemprob, skip_lvl_checks) {
    let sp;
    let otmp;
    let x;
    let y;
    let cnt;
    if (kelp_pool < 0)
        kelp_pool = 10;
    if (kelp_moat < 0)
        kelp_moat = 30;
    if (!skip_lvl_checks && (cptr.ldI16((cptr.add(u, 24))) == cptr.ldI16((cptr.add(svd, 1868)))) ? 1 : 0)
        return;
    for (x = 2; x < 78; x++)
        for (y = 1; y < 20; y++)
            if (water_has_kelp(x, y, kelp_pool, kelp_moat))
                void (yield* mksobj_at(NHC.KELP_FROND, x, y, 1, 0));
    if (!skip_lvl_checks && ((((In_hell(cptr.add(u, 24)) || In_V_tower(cptr.add(u, 24)) ? 1 : 0) || (((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0)) ? 1 : 0) || (cptr.ldI32o(svl, 89156) & 1) | 0 ? 1 : 0) || (((sp = Is_special(cptr.add(u, 24))) !== null && !(((cptr.ldI16o((cptr.add(svd, 1792)), 2) || cptr.ldI16((cptr.add(svd, 1792))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1792)) ? 1 : 0)) ? 1 : 0) && (!In_mines(cptr.add(u, 24)) || (cptr.ldI32o(sp, 32) & 1) | 0 ? 1 : 0) ? 1 : 0) ? 1 : 0) ? 1 : 0)
        return;
    if (goldprob < 0)
        goldprob = (20 + ((depth(cptr.add(u, 24)) / 3) | 0)) | 0;
    if (gemprob < 0)
        gemprob = (goldprob / 4) | 0;
    if (!skip_lvl_checks) {
        if (In_mines(cptr.add(u, 24))) {
            goldprob = Math.imul(goldprob, 2);
            gemprob = Math.imul(gemprob, 3);
        } else if (In_quest(cptr.add(u, 24))) {
            goldprob = (goldprob / 4) | 0;
            gemprob = (gemprob / 6) | 0;
        }
    }
    for (x = 2; x < 78; x++)
        for (y = 1; y < 20; y++)
            if (cptr.ld1so3(svl, x, 756, (y + 1) | 0, 36, 1684) != NHC.STONE) {
                y = i16(y + 2);
            } else if (cptr.ld1so3(svl, x, 756, y, 36, 1684) != NHC.STONE) {
                y = i16(y + 1);
            } else if (((((((!(((cptr.ldI32o3(svl, x, 756, y, 36, 1688) & 31) | 0) & NHM.W_NONDIGGABLE) && cptr.ld1so3(svl, x, 756, (y - 1) | 0, 36, 1684) == NHC.STONE ? 1 : 0) && cptr.ld1so3(svl, (x + 1) | 0, 756, (y - 1) | 0, 36, 1684) == NHC.STONE ? 1 : 0) && cptr.ld1so3(svl, (x - 1) | 0, 756, (y - 1) | 0, 36, 1684) == NHC.STONE ? 1 : 0) && cptr.ld1so3(svl, (x + 1) | 0, 756, y, 36, 1684) == NHC.STONE ? 1 : 0) && cptr.ld1so3(svl, (x - 1) | 0, 756, y, 36, 1684) == NHC.STONE ? 1 : 0) && cptr.ld1so3(svl, (x + 1) | 0, 756, (y + 1) | 0, 36, 1684) == NHC.STONE ? 1 : 0) && cptr.ld1so3(svl, (x - 1) | 0, 756, (y + 1) | 0, 36, 1684) == NHC.STONE ? 1 : 0) {
                if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1515, __sl40), rn2(1000)) : rn2(1000)) < goldprob) {
                    if ((otmp = (yield* mksobj(NHC.GOLD_PIECE, 0, 0))) !== null) {
                        cptr.stI16o(otmp, 28, x), cptr.stI16o(otmp, 30, y);
                        cptr.stI64o(otmp, 40, BigInt.asIntN(64, 1n + BigInt((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1518, __sl40), rnd(Math.imul(goldprob, 3))) : rnd(Math.imul(goldprob, 3))))));
                        cptr.stI32o(otmp, 36, (yield* weight(otmp)) >>> 0);
                        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1520, __sl40), rn2(3)) : rn2(3)))
                            (yield* add_to_buried(otmp));
                        else
                            (yield* place_object(otmp, x, y));
                    }
                }
                if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1526, __sl40), rn2(1000)) : rn2(1000)) < gemprob) {
                    for (cnt = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1527, __sl40), rnd((2 + ((dunlev(cptr.add(u, 24)) / 3) | 0)) | 0)) : rnd((2 + ((dunlev(cptr.add(u, 24)) / 3) | 0)) | 0)); cnt > 0; cnt--)
                        if ((otmp = (yield* mkobj(NHC.GEM_CLASS, 0))) !== null) {
                            if (cptr.ldI16o(otmp, 32) == NHC.ROCK) {
                                (yield* dealloc_obj(otmp));
                            } else {
                                cptr.stI16o(otmp, 28, x), cptr.stI16o(otmp, 30, y);
                                if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1533, __sl40), rn2(3)) : rn2(3)))
                                    (yield* add_to_buried(otmp));
                                else
                                    (yield* place_object(otmp, x, y));
                            }
                        }
                }
            }
}

/** C ref: mklev.c:1544 */
export function* level_finalize_topology() {
    let croom;
    let ridx;
    bound_digging();
    (yield* mineralize(-1, -1, -1, -1, 0));
    cptr.st1o(gi, 4, 0);
    cptr.stI16o(gx, 48, cptr.stI16o(gy, 340, 0));
    if ((cptr.ldI32o(svl, 89100) & 1))
        cptr.stI32o(svl, 89140, 1);
    if (!(cptr.ldI32o(svl, 89148) & 1)) {
        for (croom = cptr.add(svr, 0, 224); !cptr.eq(croom, cptr.add(svr, cptr.ldI32o(svn, 44), 224)); croom = cptr.add(croom, 1, 224))
            topologize(croom);
    }
    set_wall_state();
    for (ridx = 0; ridx < Number(BigInt.asIntN(32, (18368n / 224n))); ridx++)
        cptr.st1o2(svr, ridx, 224, 9, cptr.ld1so2(svr, ridx, 224, 8));
}

/** C ref: mklev.c:1577 */
export function* mklev() {
    reseed_random(rn2);
    reseed_random(rn2_on_display_rng);
    (yield* init_mapseen(cptr.add(u, 24)));
    if ((yield* getbones()))
        return;
    cptr.st1o(gi, 4, 1);
    (yield* makelevel());
    (yield* level_finalize_topology());
    reseed_random(rn2);
    reseed_random(rn2_on_display_rng);
}

/** C ref: mklev.c:1599 — @param {CPtr} croom */
export function topologize(croom) {
    let x;
    let y;
    let roomno = Number(BigInt.asIntN(32, (BigInt.asIntN(64, (cptr.diff(croom, svr) / 224n) + 3n))));
    let lowx = cptr.ldI16(croom);
    let lowy = cptr.ldI16o(croom, 4);
    let hix = cptr.ldI16o(croom, 2);
    let hiy = cptr.ldI16o(croom, 6);
    let subindex;
    let nsubrooms = cptr.ld1so(croom, 20);
    if (((cptr.ldI32o3(svl, lowx, 756, lowy, 36, 1704) & 63) | 0) == roomno || cptr.ld1so(croom, 21) ? 1 : 0)
        return;
    {
        for (x = lowx; x <= hix; x++)
            for (y = lowy; y <= hiy; y++)
                cptr.stI32o3(svl, x, 756, y, 36, 1704, roomno >>> 0);
        for (x = i16(((lowx - 1) | 0)); x <= ((hix + 1) | 0); x++)
            for (y = i16(((lowy - 1) | 0)); y <= ((hiy + 1) | 0); y = i16(y + ((((hiy - lowy) | 0) + 2) | 0))) {
                cptr.stI32o3(svl, x, 756, y, 36, 1708, 1);
                if ((cptr.ldI32o3(svl, x, 756, y, 36, 1704) & 63))
                    cptr.stI32o3(svl, x, 756, y, 36, 1704, NHM.SHARED);
                else
                    cptr.stI32o3(svl, x, 756, y, 36, 1704, roomno >>> 0);
            }
        for (x = i16(((lowx - 1) | 0)); x <= ((hix + 1) | 0); x = i16(x + ((((hix - lowx) | 0) + 2) | 0)))
            for (y = lowy; y <= hiy; y++) {
                cptr.stI32o3(svl, x, 756, y, 36, 1708, 1);
                if ((cptr.ldI32o3(svl, x, 756, y, 36, 1704) & 63))
                    cptr.stI32o3(svl, x, 756, y, 36, 1704, NHM.SHARED);
                else
                    cptr.stI32o3(svl, x, 756, y, 36, 1704, roomno >>> 0);
            }
    }
    for (subindex = 0; subindex < nsubrooms; subindex++)
        topologize(cptr.ldPtro2(croom, subindex, 8, 24));
}

/** C ref: mklev.c:1660 — @param {CPtr} mp @returns {CPtr} */
function* find_branch_room(mp) {
    let croom = null;
    if (cptr.ldI32o(svn, 44) == 0) {
        (yield* mazexy(mp));
    } else {
        croom = (yield* generate_stairs_find_room());
        (__builtin_expect(BigInt((!(!cptr.eq(croom, (null))))), 0n) ? __assert_rtn(__sl41, __sl34, 1668, __sl42) : void 0);
        if (!somexyspace(croom, mp))
            (yield* impossible(__sl43));
    }
    return croom;
}

/** C ref: mklev.c:1677 — @param {CInt} x @param {CInt} y @returns {CPtr} */
function pos_to_room(x, y) {
    let i;
    let curr;
    for (curr = svr, i = 0; i < cptr.ldI32o(svn, 44); curr = cptr.add(curr, 1, 224), i++)
        if (inside_room(curr, x, y))
            return curr;
    ;
    return null;
}

/** C ref: mklev.c:1691 — @param {CPtr} br @param {CInt} x @param {CInt} y */
export function* place_branch(br, x, y) {
    let m = cptr.alloc(4); cptr.stI16(m, 0);
    let dest;
    let make_stairs;
    if (!br || cptr.ld1so(gm, 220) ? 1 : 0)
        return;
    if (!x) {
        void (yield* find_branch_room(m));
        x = cptr.ldI16(m);
        y = cptr.ldI16o(m, 2);
    } else {
        void pos_to_room(x, y);
    }
    if (on_level(cptr.add(br, 16), cptr.add(u, 24))) {
        make_stairs = schar((cptr.ldI32o(br, 12) != NHM.BR_NO_END1));
        dest = cptr.add(br, 20);
    } else {
        make_stairs = schar((cptr.ldI32o(br, 12) != NHM.BR_NO_END2));
        dest = cptr.add(br, 16);
    }
    if (cptr.ldI32o(br, 12) == NHM.BR_PORTAL) {
        if (cptr.ld1so(iflags, 15) && (cptr.ldI16o(u, 38) || cptr.ldI16o(u, 40) ? 1 : 0) ? 1 : 0)
            (yield* mkportal(x, y, cptr.ldI16o(u, 38), cptr.ldI16o(u, 40)));
        else
            (yield* mkportal(x, y, cptr.ldI16(dest), cptr.ldI16o(dest, 2)));
    } else if (make_stairs) {
        let goes_up = schar((on_level(cptr.add(br, 16), cptr.add(u, 24)) ? cptr.ld1so(br, 24) : !cptr.ld1so(br, 24)));
        (yield* stairway_add(x, y, goes_up, 0, dest));
        void (yield* set_levltyp(x, y, NHC.STAIRS));
        cptr.stI32o3(svl, x, 756, y, 36, 1688, (goes_up ? NHM.LA_UP : NHM.LA_DOWN) >>> 0);
    }
    cptr.st1o(gm, 220, 1);
}

/** C ref: mklev.c:1750 — @param {CInt} x @param {CInt} y @returns {CInt} */
function bydoor(x, y) {
    let typ;
    if (isok(i16(((x + 1) | 0)), y)) {
        typ = cptr.ld1so3(svl, (x + 1) | 0, 756, y, 36, 1684);
        if (((typ) == NHC.DOOR) || typ == NHC.SDOOR ? 1 : 0)
            return 1;
    }
    if (isok(i16(((x - 1) | 0)), y)) {
        typ = cptr.ld1so3(svl, (x - 1) | 0, 756, y, 36, 1684);
        if (((typ) == NHC.DOOR) || typ == NHC.SDOOR ? 1 : 0)
            return 1;
    }
    if (isok(x, i16(((y + 1) | 0)))) {
        typ = cptr.ld1so3(svl, x, 756, (y + 1) | 0, 36, 1684);
        if (((typ) == NHC.DOOR) || typ == NHC.SDOOR ? 1 : 0)
            return 1;
    }
    if (isok(x, i16(((y - 1) | 0)))) {
        typ = cptr.ld1so3(svl, x, 756, (y - 1) | 0, 36, 1684);
        if (((typ) == NHC.DOOR) || typ == NHC.SDOOR ? 1 : 0)
            return 1;
    }
    return 0;
}

/** C ref: mklev.c:1779 — @param {CInt} x @param {CInt} y @returns {CInt} */
export function okdoor(x, y) {
    let near_door = bydoor(x, y);
    return (((cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.HWALL || cptr.ld1so3(svl, x, 756, y, 36, 1684) == NHC.VWALL ? 1 : 0) && ((((isok(i16(((x - 1) | 0)), y) && !((cptr.ld1so3(svl, (x - 1) | 0, 756, y, 36, 1684)) < NHC.POOL) ? 1 : 0) || (isok(i16(((x + 1) | 0)), y) && !((cptr.ld1so3(svl, (x + 1) | 0, 756, y, 36, 1684)) < NHC.POOL) ? 1 : 0) ? 1 : 0) || (isok(x, i16(((y - 1) | 0))) && !((cptr.ld1so3(svl, x, 756, (y - 1) | 0, 36, 1684)) < NHC.POOL) ? 1 : 0) ? 1 : 0) || (isok(x, i16(((y + 1) | 0))) && !((cptr.ld1so3(svl, x, 756, (y + 1) | 0, 36, 1684)) < NHC.POOL) ? 1 : 0) ? 1 : 0) ? 1 : 0) && !near_door ? 1 : 0);
}

/** C ref: mklev.c:1793 — @param {CInt} chance @returns {CInt} */
export function maybe_sdoor(chance) {
    return schar(((depth(cptr.add(u, 24)) > 2) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1795, __sl44), rn2((2 > (chance) ? 2 : (chance)))) : rn2((2 > (chance) ? 2 : (chance)))) ? 1 : 0));
}

/** C ref: mklev.c:1800 — @param {CInt} x @param {CInt} y @param {CPtr} aroom */
export function* dodoor(x, y, aroom) {
    (yield* dosdoor(x, y, aroom, maybe_sdoor(8) ? NHC.SDOOR : NHC.DOOR));
}

/** C ref: mklev.c:1806 — @param {CInt} x @param {CInt} y @returns {CInt} */
export function occupied(x, y) {
    return schar(((((t_at(x, y) || ((cptr.ld1so3(svl, x, 756, y, 36, 1684)) >= NHC.STAIRS && (cptr.ld1so3(svl, x, 756, y, 36, 1684)) <= NHC.ALTAR ? 1 : 0) ? 1 : 0) || is_lava(x, y) ? 1 : 0) || is_pool(x, y) ? 1 : 0) || invocation_pos(x, y) ? 1 : 0));
}

/** C ref: mklev.c:1815 — @param {CPtr} ttmp */
function* mktrap_victim(ttmp) {
    let otmp = null;
    let victim_mnum;
    let lvl = (yield* level_difficulty());
    let kind = (cptr.ldI32o(ttmp, 20) & 31) | 0;
    let x = cptr.ldI16o(ttmp, 8);
    let y = cptr.ldI16o(ttmp, 10);
    (__builtin_expect(BigInt((!(((x > 0 && x < NHM.COLNO ? 1 : 0) && y >= 0 ? 1 : 0) && y < NHM.ROWNO ? 1 : 0))), 0n) ? __assert_rtn(__sl45, __sl34, 1825, __sl46) : void 0);
    switch (kind) {
        case NHC.ARROW_TRAP:
        otmp = (yield* mksobj(NHC.ARROW, 1, 0));
        cptr.stI32o(otmp, 132, 0);
        break;
        case NHC.DART_TRAP:
        otmp = (yield* mksobj(NHC.DART, 1, 0));
        break;
        case NHC.ROCKTRAP:
        otmp = (yield* mksobj(NHC.ROCK, 1, 0));
        break;
        default:
        break;
    }
    if (otmp) {
        (yield* place_object(otmp, x, y));
    }
    do {
        let poss_class = NHC.RANDOM_CLASS;
        switch ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1857, __sl45), rn2(4)) : rn2(4))) {
            case 0:
            poss_class = NHC.WEAPON_CLASS;
            break;
            case 1:
            poss_class = NHC.TOOL_CLASS;
            break;
            case 2:
            poss_class = NHC.FOOD_CLASS;
            break;
            case 3:
            poss_class = NHC.GEM_CLASS;
            break;
        }
        otmp = (yield* mkobj(poss_class, 0));
        (yield* curse(otmp));
        if (((cptr.ldI32o(ttmp, 20) & 31) | 0) == NHC.PIT && breaktest(otmp) ? 1 : 0) {
            (yield* dealloc_obj(otmp));
        } else {
            (yield* place_object(otmp, x, y));
        }
    } while (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1888, __sl45), rn2(5)) : rn2(5)));
    switch ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1891, __sl45), rn2(15)) : rn2(15))) {
        case 0:
        victim_mnum = NHC.PM_ELF;
        if (kind == NHC.SLP_GAS_TRAP && !(lvl <= 2 && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1899, __sl45), rn2(2)) : rn2(2)) ? 1 : 0) ? 1 : 0)
            victim_mnum = NHC.PM_HUMAN;
        break;
        case 1:
        case 2:
        victim_mnum = NHC.PM_DWARF;
        break;
        case 3:
        case 4:
        case 5:
        victim_mnum = NHC.PM_ORC;
        break;
        case 6:
        case 7:
        case 8:
        case 9:
        victim_mnum = NHC.PM_GNOME;
        if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 1912, __sl45), rn2(10)) : rn2(10))) {
            otmp = (yield* mksobj((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1913, __sl45), rn2(4)) : rn2(4)) ? NHC.TALLOW_CANDLE : NHC.WAX_CANDLE, 1, 0));
            cptr.stI64o(otmp, 40, 1n);
            cptr.stI32o(otmp, 36, (yield* weight(otmp)) >>> 0);
            (yield* curse(otmp));
            (yield* place_object(otmp, x, y));
            if (!(cptr.ldI32o3(svl, x, 756, y, 36, 1696) & 1))
                (yield* begin_burn(otmp, 0));
        }
        break;
        default:
        victim_mnum = NHC.PM_HUMAN;
        break;
    }
    if (victim_mnum == NHC.PM_HUMAN && (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1930, __sl45), rn2(25)) : rn2(25)) ? 1 : 0)
        victim_mnum = (((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1931, __sl45), rn2(((NHC.PM_WIZARD - NHC.PM_ARCHEOLOGIST) | 0))) : rn2(((NHC.PM_WIZARD - NHC.PM_ARCHEOLOGIST) | 0))) + NHC.PM_ARCHEOLOGIST) | 0);
    otmp = (yield* mkcorpstat(NHC.CORPSE, null, cptr.add(mons, victim_mnum, 96), x, y, NHM.CORPSTAT_INIT));
    cptr.stI64o(otmp, 184, cptr.ldI64o(otmp, 184) - 51n);
}

/** C ref: mklev.c:1938 — @param {CUInt} mktrapflags @returns {CInt} */
function* traptype_rnd(mktrapflags) {
    let lvl = (yield* level_difficulty());
    let kind = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 1941, __sl47), rnd(((NHC.TRAPNUM - 1) | 0))) : rnd(((NHC.TRAPNUM - 1) | 0)));
    switch (kind) {
        case NHC.TRAPPED_DOOR:
        case NHC.TRAPPED_CHEST:
        kind = NHC.NO_TRAP;
        break;
        case NHC.MAGIC_PORTAL:
        case NHC.VIBRATING_SQUARE:
        kind = NHC.NO_TRAP;
        break;
        case NHC.ROLLING_BOULDER_TRAP:
        case NHC.SLP_GAS_TRAP:
        if (lvl < 2)
            kind = NHC.NO_TRAP;
        break;
        case NHC.LEVEL_TELEP:
        if ((lvl < 5 || (cptr.ldI32o(svl, 89120) & 1) | 0 ? 1 : 0) || single_level_branch(cptr.add(u, 24)) ? 1 : 0)
            kind = NHC.NO_TRAP;
        break;
        case NHC.SPIKED_PIT:
        if (lvl < 5)
            kind = NHC.NO_TRAP;
        break;
        case NHC.LANDMINE:
        if (lvl < 6)
            kind = NHC.NO_TRAP;
        break;
        case NHC.WEB:
        if (lvl < 7 && !((mktrapflags & NHM.MKTRAP_NOSPIDERONWEB) >>> 0) ? 1 : 0)
            kind = NHC.NO_TRAP;
        break;
        case NHC.STATUE_TRAP:
        case NHC.POLY_TRAP:
        if (lvl < 8)
            kind = NHC.NO_TRAP;
        break;
        case NHC.FIRE_TRAP:
        if (!In_hell(cptr.add(u, 24)))
            kind = NHC.NO_TRAP;
        break;
        case NHC.TELEP_TRAP:
        if ((cptr.ldI32o(svl, 89120) & 1))
            kind = NHC.NO_TRAP;
        break;
        case NHC.HOLE:
        if ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 1993, __sl47), rn2(7)) : rn2(7)))
            kind = NHC.NO_TRAP;
        break;
    }
    return kind;
}

/** C ref: mklev.c:2002 @returns {CInt} */
function traptype_roguelvl() {
    let kind;
    switch ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 2006, __sl48), rn2(7)) : rn2(7))) {
        default:
        kind = NHC.BEAR_TRAP;
        break;
        case 1:
        kind = NHC.ARROW_TRAP;
        break;
        case 2:
        kind = NHC.DART_TRAP;
        break;
        case 3:
        kind = NHC.TRAPDOOR;
        break;
        case 4:
        kind = NHC.PIT;
        break;
        case 5:
        kind = NHC.SLP_GAS_TRAP;
        break;
        case 6:
        kind = NHC.RUST_TRAP;
        break;
    }
    return kind;
}

let __static_mktrap_mktrap_err = 0; /** C ref: mklev.c:2042 — int (function-static) */

/** C ref: mklev.c:2036 — @param {CInt} num @param {CUInt} mktrapflags @param {CPtr} croom @param {CPtr} tm */
export function* mktrap(num, mktrapflags, croom, tm) {
    let t;
    let m = cptr.alloc(4);
    let kind;
    let lvl = (yield* level_difficulty());
    if ((!tm && !croom ? 1 : 0) && !((mktrapflags & NHM.MKTRAP_MAZEFLAG) >>> 0) ? 1 : 0) {
        if (!__static_mktrap_mktrap_err++) {
            let errbuf = new Uint8Array(256);
            nh_snprintf(__sl49, 2055, cptr.decay(errbuf), 256n, __sl50, num, mktrapflags, __sl51, __sl52);
            (yield* paniclog(__sl49, cptr.decay(errbuf)));
        }
        return;
    }
    cptr.stI16(m, cptr.stI16o(m, 2, 0));
    if (tm && is_pool_or_lava(cptr.ldI16(tm), cptr.ldI16o(tm, 2)) ? 1 : 0)
        return;
    if (num > NHC.NO_TRAP && num < NHC.TRAPNUM ? 1 : 0) {
        kind = num;
    } else if ((((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0))) {
        kind = traptype_roguelvl();
    } else if (In_hell(cptr.add(u, 24)) && !(rng_log_enabled() ? (rng_log_set_caller(__sl1, 2070, __sl49), rn2(5)) : rn2(5)) ? 1 : 0) {
        kind = NHC.FIRE_TRAP;
    } else {
        do {
            kind = (yield* traptype_rnd(mktrapflags));
        } while (kind == NHC.NO_TRAP);
    }
    if (((kind) == NHC.HOLE || (kind) == NHC.TRAPDOOR ? 1 : 0) && !Can_fall_thru(cptr.add(u, 24)) ? 1 : 0)
        kind = NHC.ROCKTRAP;
    if (tm) {
        cptr.memcpy(m, tm, 4);
    } else {
        let tryct = 0;
        let avoid_boulder = schar((((kind) == NHC.PIT || (kind) == NHC.SPIKED_PIT ? 1 : 0) || ((kind) == NHC.HOLE || (kind) == NHC.TRAPDOOR ? 1 : 0) ? 1 : 0));
        do {
            if (++tryct > 200)
                return;
            if (((mktrapflags & NHM.MKTRAP_MAZEFLAG) >>> 0) != 0)
                (yield* mazexy(m));
            else if (croom && !somexyspace(croom, m) ? 1 : 0)
                return;
        } while (occupied(cptr.ldI16(m), cptr.ldI16o(m, 2)) || (avoid_boulder && sobj_at(NHC.BOULDER, cptr.ldI16(m), cptr.ldI16o(m, 2)) ? 1 : 0) ? 1 : 0);
    }
    t = (yield* maketrap(cptr.ldI16(m), cptr.ldI16o(m, 2), kind));
    kind = t ? (cptr.ldI32o(t, 20) & 31) | 0 : NHC.NO_TRAP;
    if (kind == NHC.WEB && !((mktrapflags & NHM.MKTRAP_NOSPIDERONWEB) >>> 0) ? 1 : 0)
        void (yield* makemon(cptr.add(mons, NHC.PM_GIANT_SPIDER, 96), cptr.ldI16(m), cptr.ldI16o(m, 2), NHM.NO_MM_FLAGS));
    if (t && ((mktrapflags & NHM.MKTRAP_SEEN) >>> 0) ? 1 : 0)
        cptr.stI32o(t, 24, 1);
    if (kind == NHC.MAGIC_PORTAL && (cptr.ldI16o(u, 38) || cptr.ldI16o(u, 40) ? 1 : 0) ? 1 : 0) {
        assign_level(cptr.add(t, 12), cptr.add(u, 38));
    }
    if ((((((((cptr.ld1so(gi, 4) && kind != NHC.NO_TRAP ? 1 : 0) && !((mktrapflags & NHM.MKTRAP_NOVICTIM) >>> 0) ? 1 : 0) && lvl <= (rng_log_enabled() ? (rng_log_set_caller(__sl1, 2137, __sl49), rnd(4)) : rnd(4)) >>> 0 ? 1 : 0) && kind != NHC.SQKY_BOARD ? 1 : 0) && kind != NHC.RUST_TRAP ? 1 : 0) && !((kind == NHC.ROLLING_BOULDER_TRAP && cptr.ldI16o(t, 16) == cptr.ldI16o(t, 8) ? 1 : 0) && cptr.ldI16o(t, 18) == cptr.ldI16o(t, 10) ? 1 : 0) ? 1 : 0) && !((kind) == NHC.PIT || (kind) == NHC.SPIKED_PIT ? 1 : 0) ? 1 : 0) && (kind < NHC.HOLE || kind == NHC.MAGIC_TRAP ? 1 : 0) ? 1 : 0) {
        if (kind == NHC.LANDMINE) {
            cptr.stI32o(t, 20, NHC.PIT);
            cptr.stI32o(t, 24, 1);
        }
        (yield* mktrap_victim(t));
    }
    return;
}

/** C ref: mklev.c:2159 — @param {CInt} x @param {CInt} y @param {CInt} up @param {CPtr} croom @param {CInt} force */
export function* mkstairs(x, y, up, croom, force) {
    let ltyp;
    let dest = cptr.alloc(4);
    if (!x || !isok(x, y) ? 1 : 0) {
        (yield* impossible(__sl53, x, y));
        return;
    }
    if (force)
        cptr.st1o3(svl, x, 756, y, 36, 1684, NHC.ROOM);
    ltyp = cptr.ld1so3(svl, x, 756, y, 36, 1684);
    if ((ltyp != NHC.ROOM && ltyp != NHC.CORR ? 1 : 0) && ltyp != NHC.ICE ? 1 : 0) {
        let glyph = (yield* back_to_glyph(x, y));
        let sidx = glyph_to_cmap(glyph);
        (yield* impossible(__sl54, up ? __sl55 : __sl56, cptr.ldPtro2(defsyms, sidx, 24, 8), x, y));
    }
    if (dunlev(cptr.add(u, 24)) == (up ? 1 : dunlevs_in_dungeon(cptr.add(u, 24))))
        return;
    cptr.stI16(dest, cptr.ldI16o(u, 24));
    cptr.stI16o(dest, 2, i16(((cptr.ldI16o(u, 26) + (up ? -1 : 1)) | 0)));
    (yield* stairway_add(x, y, schar((up ? 1 : 0)), 0, dest));
    void (yield* set_levltyp(x, y, NHC.STAIRS));
    cptr.stI32o3(svl, x, 756, y, 36, 1688, (up ? NHM.LA_UP : NHM.LA_DOWN) >>> 0);
}

/** C ref: mklev.c:2201 — @param {CPtr} croom @param {CInt} phase @returns {CInt} */
function generate_stairs_room_good(croom, phase) {
    return schar((((croom && (cptr.ld1so(croom, 12) || (phase < 0) ? 1 : 0) ? 1 : 0) && ((!has_dnstairs(croom) && !has_upstairs(croom) ? 1 : 0) || phase < 1 ? 1 : 0) ? 1 : 0) && (cptr.ld1so(croom, 8) == NHC.OROOM || ((phase < 2) && cptr.ld1so(croom, 8) == NHC.THEMEROOM ? 1 : 0) ? 1 : 0) ? 1 : 0));
}

/** C ref: mklev.c:2219 @returns {CPtr} */
function* generate_stairs_find_room() {
    let croom;
    let i;
    let phase;
    let ai;
    let rmarr;
    if (!cptr.ldI32o(svn, 44))
        return null;
    rmarr = (yield* alloc(Number(BigInt.asUintN(32, BigInt.asUintN(64, 4n * BigInt.asUintN(64, BigInt(cptr.ldI32o(svn, 44))))))));
    for (phase = 2; phase > -1; phase--) {
        ai = 0;
        for (i = 0; i < cptr.ldI32o(svn, 44); i++)
            if (generate_stairs_room_good(cptr.add(svr, i, 224), phase))
                cptr.stI32o(rmarr, ai++, i, 4);
        if (ai > 0) {
            i = cptr.ldI32o(rmarr, (rng_log_enabled() ? (rng_log_set_caller(__sl1, 2236, __sl57), rn2(ai)) : rn2(ai)), 4);
            cptr.free(rmarr);
            return cptr.add(svr, i, 224);
        }
    }
    cptr.free(rmarr);
    croom = cptr.add(svr, (rng_log_enabled() ? (rng_log_set_caller(__sl1, 2243, __sl57), rn2(cptr.ldI32o(svn, 44))) : rn2(cptr.ldI32o(svn, 44))), 224);
    return croom;
}

const __static_generate_stairs_gen_stairs_panic = cptr.bytes("generate_stairs: failed to find a room! (%d)"); /** C ref: mklev.c:2255 — char[45] (function-static) */

/** C ref: mklev.c:2250 */
function* generate_stairs() {
    let croom;
    let pos = cptr.alloc(4);
    if (!Is_botlevel(cptr.add(u, 24))) {
        if (cptr.eq((croom = (yield* generate_stairs_find_room())), (null)))
            (yield* panic(cptr.decay(__static_generate_stairs_gen_stairs_panic), cptr.ldI32o(svn, 44)));
        if (!somexyspace(croom, pos)) {
            cptr.stI16(pos, i16(somex(croom)));
            cptr.stI16o(pos, 2, i16(somey(croom)));
        }
        (yield* mkstairs(cptr.ldI16(pos), cptr.ldI16o(pos, 2), 0, croom, 0));
    }
    if (cptr.ldI16o(u, 26) != 1) {
        if (cptr.eq((croom = (yield* generate_stairs_find_room())), (null)))
            (yield* panic(cptr.decay(__static_generate_stairs_gen_stairs_panic), cptr.ldI32o(svn, 44)));
        if (!somexyspace(croom, pos)) {
            cptr.stI16(pos, i16(somex(croom)));
            cptr.stI16o(pos, 2, i16(somey(croom)));
        }
        (yield* mkstairs(cptr.ldI16(pos), cptr.ldI16o(pos, 2), 1, croom, 0));
    }
}

/** C ref: mklev.c:2285 — @param {CPtr} croom */
function* mkfount(croom) {
    let m = cptr.alloc(4);
    if (!find_okay_roompos(croom, m))
        return;
    if (!(yield* set_levltyp(cptr.ldI16(m), cptr.ldI16o(m, 2), NHC.FOUNTAIN)))
        return;
    if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 2296, __sl58), rn2(7)) : rn2(7)))
        cptr.stI32o3(svl, cptr.ldI16(m), 756, cptr.ldI16o(m, 2), 36, 1692, 1);
    cptr.postinc1(cptr.add(svl, 89080));
}

/** C ref: mklev.c:2303 — @param {CPtr} croom @param {CPtr} crd @returns {CInt} */
function find_okay_roompos(croom, crd) {
    let tryct = 0;
    do {
        if (++tryct > 200)
            return 0;
        if (!somexyspace(croom, crd))
            return 0;
    } while (occupied(cptr.ldI16(crd), cptr.ldI16o(crd, 2)) || bydoor(cptr.ldI16(crd), cptr.ldI16o(crd, 2)) ? 1 : 0);
    return 1;
}

/** C ref: mklev.c:2317 — @param {CPtr} croom */
function* mksink(croom) {
    let m = cptr.alloc(4);
    if (!find_okay_roompos(croom, m))
        return;
    if (!(yield* set_levltyp(cptr.ldI16(m), cptr.ldI16o(m, 2), NHC.SINK)))
        return;
    cptr.postinc1(cptr.add(svl, 89081));
}

/** C ref: mklev.c:2332 — @param {CPtr} croom */
function* mkaltar(croom) {
    let m = cptr.alloc(4);
    let al;
    if (cptr.ld1so(croom, 8) != NHC.OROOM)
        return;
    if (!find_okay_roompos(croom, m))
        return;
    if (!(yield* set_levltyp(cptr.ldI16(m), cptr.ldI16o(m, 2), NHC.ALTAR)))
        return;
    al = schar((((rng_log_enabled() ? (rng_log_set_caller(__sl1, 2348, __sl59), rn2(3)) : rn2(3)) - 1) | 0));
    cptr.stI32o3(svl, cptr.ldI16(m), 756, cptr.ldI16o(m, 2), 36, 1688, ((((al) == -128) ? NHM.AM_NONE : (((al) == NHM.A_LAWFUL) ? NHM.AM_LAWFUL : (((al) + 2) | 0))) >>> 0));
}

/** C ref: mklev.c:2353 — @param {CPtr} croom */
function* mkgrave(croom) {
    let m = cptr.alloc(4);
    let tryct = 0;
    let otmp;
    let dobell = schar((!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 2358, __sl60), rn2(10)) : rn2(10))));
    if (cptr.ld1so(croom, 8) != NHC.OROOM)
        return;
    if (!find_okay_roompos(croom, m))
        return;
    (yield* make_grave(cptr.ldI16(m), cptr.ldI16o(m, 2), dobell ? __sl61 : null));
    if (!(rng_log_enabled() ? (rng_log_set_caller(__sl1, 2370, __sl60), rn2(3)) : rn2(3))) {
        let gold = (yield* mksobj(NHC.GOLD_PIECE, 1, 0));
        cptr.stI64o(gold, 40, BigInt((((rng_log_enabled() ? (rng_log_set_caller(__sl1, 2378, __sl60), rnd(20)) : rnd(20)) + Math.imul((yield* level_difficulty()), (rng_log_enabled() ? (rng_log_set_caller(__sl1, 2378, __sl60), rnd(5)) : rnd(5)))) | 0)));
        cptr.stI32o(gold, 36, (yield* weight(gold)) >>> 0);
        cptr.stI16o(gold, 28, cptr.ldI16(m)), cptr.stI16o(gold, 30, cptr.ldI16o(m, 2));
        (yield* add_to_buried(gold));
    }
    for (tryct = (rng_log_enabled() ? (rng_log_set_caller(__sl1, 2383, __sl60), rn2(5)) : rn2(5)); tryct; tryct--) {
        otmp = (yield* mkobj(NHC.RANDOM_CLASS, 1));
        if (!otmp)
            return;
        (yield* curse(otmp));
        cptr.stI16o(otmp, 28, cptr.ldI16(m));
        cptr.stI16o(otmp, 30, cptr.ldI16o(m, 2));
        (yield* add_to_buried(otmp));
    }
    if (dobell)
        void (yield* mksobj_at(NHC.BELL, cptr.ldI16(m), cptr.ldI16o(m, 2), 1, 0));
    return;
}

/** C ref: mklev.c:2410 */
export function* mkinvokearea() {
    let dist;
    let wallct;
    let xmin;
    let xmax;
    let ymin;
    let ymax;
    let i;
    (yield* pline_The(__sl62));
    {
        xmin = (xmax = cptr.ldI16(svi));
        ymin = (ymax = cptr.ldI16o(svi, 2));
        wallct = mkinvk_check_wall(xmin, ymin);
        for (dist = 1; !wallct && dist < 7 ? 1 : 0; ++dist) {
            xmin--, xmax++;
            if (dist != 3) {
                ymin--, ymax++;
                for (i = i16(((xmin + 1) | 0)); i < xmax; i++) {
                    if (mkinvk_check_wall(i, ymin))
                        ++wallct;
                    if (mkinvk_check_wall(i, ymax))
                        ++wallct;
                }
            }
            if (!wallct) {
                for (i = ymin; i <= ymax; i++) {
                    if (mkinvk_check_wall(xmin, i))
                        ++wallct;
                    if (mkinvk_check_wall(xmax, i))
                        ++wallct;
                }
            }
        }
        if (wallct)
            (yield* pline_The(__sl63));
    }
    (yield* Y.icall((cptr.ldPtro(windowprocs, 120))(WIN_MESSAGE.v, 1)));
    if (cptr.ldI32o(u, 60)) {
        if (cptr.ldI32o(u, 64) == NHC.TT_BURIEDBALL)
            (yield* buried_ball_to_punishment());
        (yield* reset_utrap(0));
    }
    xmin = (xmax = cptr.ldI16(svi));
    ymin = (ymax = cptr.ldI16o(svi, 2));
    (yield* mkinvpos(xmin, ymin, 0));
    for (dist = 1; dist < 7; dist++) {
        xmin--;
        xmax++;
        if (dist != 3) {
            ymin--;
            ymax++;
            for (i = i16(((xmin + 1) | 0)); i < xmax; i++) {
                (yield* mkinvpos(i, ymin, dist));
                (yield* mkinvpos(i, ymax, dist));
            }
        }
        for (i = ymin; i <= ymax; i++) {
            (yield* mkinvpos(xmin, i, dist));
            (yield* mkinvpos(xmax, i, dist));
        }
        (yield* flush_screen(1));
        (yield* Y.icall((cptr.ldPtro(windowprocs, 320))()));
    }
    (yield* You(__sl64));
    (yield* mkstairs(cptr.ldI16(u), cptr.ldI16o(u, 2), 0, null, 0));
    (yield* newsym(cptr.ldI16(u), cptr.ldI16o(u, 2)));
    cptr.st1o(gv, 144, 1);
}

/** C ref: mklev.c:2503 — @param {CInt} x @param {CInt} y @param {CInt} dist */
function* mkinvpos(x, y, dist) {
    let ttmp;
    let otmp;
    let make_rocks;
    let lev = cptr.add(cptr.add(cptr.add(svl, 1680), x, 756), y, 36);
    let mon;
    if (!((((x) >= 2 && (x) <= (cptr.ldI32(gx)) ? 1 : 0) && (y) >= 2 ? 1 : 0) && (y) <= (cptr.ldI32(gy)) ? 1 : 0)) {
        if (dist < 5) {
            let errfunc;
            errfunc = !isok(x, y) ? panic : impossible;
            (yield* Y.icall((errfunc)(__sl65, x, y, dist)));
        }
        return;
    }
    if ((ttmp = t_at(x, y)) !== null)
        (yield* deltrap(ttmp));
    make_rocks = schar((((dist != 1 && dist != 4 ? 1 : 0) && dist != 5 ? 1 : 0) ? 1 : 0));
    while ((otmp = sobj_at(NHC.BOULDER, x, y)) !== null) {
        if (make_rocks) {
            (yield* fracture_rock(otmp));
            make_rocks = 0;
        } else {
            (yield* obj_extract_self(otmp));
            (yield* obfree(otmp, null));
        }
    }
    cptr.st1o(lev, 5, 0);
    cptr.stI32o(lev, 8, 0);
    if (dist < 6)
        cptr.stI32o(lev, 16, 1);
    cptr.stI32o(lev, 20, 1);
    cptr.stI32o(lev, 12, 0);
    cptr.st1o(cptr.ldPtro(cptr.ldPtro(gv, 120), y, 8), x, uchar(((dist < 6) ? 3 : NHM.COULD_SEE)));
    switch (dist) {
        case 1:
        if (is_pool(x, y))
            break;
        cptr.st1o(lev, 4, NHC.ROOM);
        ttmp = (yield* maketrap(x, y, NHC.FIRE_TRAP));
        if (ttmp)
            cptr.stI32o(ttmp, 24, 1);
        break;
        case 0:
        case 2:
        case 3:
        case 6:
        cptr.st1o(lev, 4, NHC.ROOM);
        break;
        case 4:
        case 5:
        cptr.st1o(lev, 4, NHC.MOAT);
        break;
        default:
        (yield* impossible(__sl66, dist));
        break;
    }
    if ((mon = (cptr.ldPtro3(svl, x, 168, y, 8, 75600))) !== null) {
        if (cptr.ld1uo(mon, 64))
            (yield* seemimic(mon));
        if ((ttmp = t_at(x, y)) !== null)
            void (yield* mintrap(mon, NHM.NO_TRAP_FLAGS));
        else
            void (yield* minliquid(mon));
    }
    if (!(yield* does_block(x, y, lev)))
        unblock_point(x, y);
    (yield* newsym(x, y));
}

/** C ref: mklev.c:2603 — @param {CInt} x @param {CInt} y @returns {CInt} */
function mkinvk_check_wall(x, y) {
    let ltyp;
    if (!isok(x, y))
        return 0;
    (__builtin_expect(BigInt((!(x > 0 && x < NHM.COLNO ? 1 : 0))), 0n) ? __assert_rtn(__sl67, __sl34, 2609, __sl68) : void 0);
    (__builtin_expect(BigInt((!(y >= 0 && y < NHM.ROWNO ? 1 : 0))), 0n) ? __assert_rtn(__sl67, __sl34, 2610, __sl69) : void 0);
    ltyp = cptr.ld1so3(svl, x, 756, y, 36, 1684);
    return (((ltyp) <= NHC.DBWALL) || ltyp == NHC.IRONBARS ? 1 : 0) ? 1 : 0;
}

/** C ref: mklev.c:2624 — @param {CInt} x @param {CInt} y */
function* mk_knox_portal(x, y) {
    let source;
    let br;
    let u_depth;
    br = (yield* dungeon_branch(__sl70));
    (__builtin_expect(BigInt((!(!cptr.eq(br, (null))))), 0n) ? __assert_rtn(__sl71, __sl34, 2632, __sl72) : void 0);
    if (on_level(cptr.add(svd, 1894), cptr.add(br, 16))) {
        source = cptr.add(br, 20);
    } else {
        if (Is_branchlev(cptr.add(u, 24)))
            return;
        source = cptr.add(br, 16);
    }
    if (cptr.ldI16(source) < cptr.ldI32(svn) || ((rng_log_enabled() ? (rng_log_set_caller(__sl1, 2644, __sl71), rn2(3)) : rn2(3)) && !cptr.ld1so(flags, 10) ? 1 : 0) ? 1 : 0)
        return;
    if (!(((cptr.ldI16o(u, 24) == cptr.ldI16((cptr.add(svd, 1792))) && !(yield* at_dgn_entrance(__sl73)) ? 1 : 0) && (u_depth = depth(cptr.add(u, 24))) > 10 ? 1 : 0) && u_depth < depth(cptr.add(svd, 1804)) ? 1 : 0))
        return;
    cptr.memcpy(source, cptr.add(u, 24), 4);
    (yield* insert_branch(br, 1));
    do {
        if ((yield* debugcore(__sl1, 1))) {
            let save_plnmsg = cptr.ldI32o(iflags, 40);
            (yield* pline(__sl74));
            cptr.stI32o(iflags, 40, save_plnmsg);
        }
    } while (0);
    (yield* place_branch(br, x, y));
}
