// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/vision.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
import * as Y from '../yield-rt.js';
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/vision.c
// Input sha256: 88578aa26076563be5f41a0cda0710149eb13b22ee08b53a116f51c0068ead31
// Transpiler: tools/c2js c2js emit v1+batch

import { i16, schar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import { isok } from './cmd.js';
import { flags, gi, gs, gv, iflags, program_state, svc, svd, svl, svr, u } from './decl.js';
import { debugcore } from './files.js';
import { is_moat, is_pool } from './dbridge.js';
import { visible_region_at } from './region.js';
import { canseemon, mon_visible, newsym, see_with_infrared, seenv_matrix, tp_sensemon } from './display.js';
import { on_level } from './dungeon.js';
import { do_light_sources } from './light.js';
import { notice_all_mons } from './hack.js';
import { panic } from './end.js';
import { detecting } from './detect.js';
import { worm_known } from './worm.js';
import { dist2 } from './hacklib.js';

// string literals (C char* uses decay to CPtr into these static buffers)
const __sl0 = cptr.lit("seethru");
const __sl1 = cptr.lit("right_side");
const __sl2 = cptr.lit("vision.c");
const __sl3 = cptr.lit("rowp != NULL");
const __sl4 = cptr.lit("row_min != NULL");
const __sl5 = cptr.lit("row_max != NULL");
const __sl6 = cptr.lit("left_side");
const __sl7 = cptr.lit("view_from called with range %d");
const __sl8 = cptr.lit("view_from");
const __sl9 = cptr.lit("do_clear_area:  illegal range %d");

/** C ref: vision.c:27 — short[137] */
export const circle_data = cptr.alloc(137 * 2);
cptr.stI16o(circle_data, 0, 0);
cptr.stI16o(circle_data, 2, 1);
cptr.stI16o(circle_data, 4, 1);
cptr.stI16o(circle_data, 6, 2);
cptr.stI16o(circle_data, 8, 2);
cptr.stI16o(circle_data, 10, 1);
cptr.stI16o(circle_data, 12, 3);
cptr.stI16o(circle_data, 14, 3);
cptr.stI16o(circle_data, 16, 2);
cptr.stI16o(circle_data, 18, 1);
cptr.stI16o(circle_data, 20, 4);
cptr.stI16o(circle_data, 22, 4);
cptr.stI16o(circle_data, 24, 4);
cptr.stI16o(circle_data, 26, 3);
cptr.stI16o(circle_data, 28, 2);
cptr.stI16o(circle_data, 30, 5);
cptr.stI16o(circle_data, 32, 5);
cptr.stI16o(circle_data, 34, 5);
cptr.stI16o(circle_data, 36, 4);
cptr.stI16o(circle_data, 38, 3);
cptr.stI16o(circle_data, 40, 2);
cptr.stI16o(circle_data, 42, 6);
cptr.stI16o(circle_data, 44, 6);
cptr.stI16o(circle_data, 46, 6);
cptr.stI16o(circle_data, 48, 5);
cptr.stI16o(circle_data, 50, 5);
cptr.stI16o(circle_data, 52, 4);
cptr.stI16o(circle_data, 54, 2);
cptr.stI16o(circle_data, 56, 7);
cptr.stI16o(circle_data, 58, 7);
cptr.stI16o(circle_data, 60, 7);
cptr.stI16o(circle_data, 62, 6);
cptr.stI16o(circle_data, 64, 6);
cptr.stI16o(circle_data, 66, 5);
cptr.stI16o(circle_data, 68, 4);
cptr.stI16o(circle_data, 70, 2);
cptr.stI16o(circle_data, 72, 8);
cptr.stI16o(circle_data, 74, 8);
cptr.stI16o(circle_data, 76, 8);
cptr.stI16o(circle_data, 78, 7);
cptr.stI16o(circle_data, 80, 7);
cptr.stI16o(circle_data, 82, 6);
cptr.stI16o(circle_data, 84, 6);
cptr.stI16o(circle_data, 86, 4);
cptr.stI16o(circle_data, 88, 2);
cptr.stI16o(circle_data, 90, 9);
cptr.stI16o(circle_data, 92, 9);
cptr.stI16o(circle_data, 94, 9);
cptr.stI16o(circle_data, 96, 9);
cptr.stI16o(circle_data, 98, 8);
cptr.stI16o(circle_data, 100, 8);
cptr.stI16o(circle_data, 102, 7);
cptr.stI16o(circle_data, 104, 6);
cptr.stI16o(circle_data, 106, 5);
cptr.stI16o(circle_data, 108, 3);
cptr.stI16o(circle_data, 110, 10);
cptr.stI16o(circle_data, 112, 10);
cptr.stI16o(circle_data, 114, 10);
cptr.stI16o(circle_data, 116, 10);
cptr.stI16o(circle_data, 118, 9);
cptr.stI16o(circle_data, 120, 9);
cptr.stI16o(circle_data, 122, 8);
cptr.stI16o(circle_data, 124, 7);
cptr.stI16o(circle_data, 126, 6);
cptr.stI16o(circle_data, 128, 5);
cptr.stI16o(circle_data, 130, 3);
cptr.stI16o(circle_data, 132, 11);
cptr.stI16o(circle_data, 134, 11);
cptr.stI16o(circle_data, 136, 11);
cptr.stI16o(circle_data, 138, 11);
cptr.stI16o(circle_data, 140, 10);
cptr.stI16o(circle_data, 142, 10);
cptr.stI16o(circle_data, 144, 9);
cptr.stI16o(circle_data, 146, 9);
cptr.stI16o(circle_data, 148, 8);
cptr.stI16o(circle_data, 150, 7);
cptr.stI16o(circle_data, 152, 5);
cptr.stI16o(circle_data, 154, 3);
cptr.stI16o(circle_data, 156, 12);
cptr.stI16o(circle_data, 158, 12);
cptr.stI16o(circle_data, 160, 12);
cptr.stI16o(circle_data, 162, 12);
cptr.stI16o(circle_data, 164, 11);
cptr.stI16o(circle_data, 166, 11);
cptr.stI16o(circle_data, 168, 10);
cptr.stI16o(circle_data, 170, 10);
cptr.stI16o(circle_data, 172, 9);
cptr.stI16o(circle_data, 174, 8);
cptr.stI16o(circle_data, 176, 7);
cptr.stI16o(circle_data, 178, 5);
cptr.stI16o(circle_data, 180, 3);
cptr.stI16o(circle_data, 182, 13);
cptr.stI16o(circle_data, 184, 13);
cptr.stI16o(circle_data, 186, 13);
cptr.stI16o(circle_data, 188, 13);
cptr.stI16o(circle_data, 190, 12);
cptr.stI16o(circle_data, 192, 12);
cptr.stI16o(circle_data, 194, 12);
cptr.stI16o(circle_data, 196, 11);
cptr.stI16o(circle_data, 198, 10);
cptr.stI16o(circle_data, 200, 10);
cptr.stI16o(circle_data, 202, 9);
cptr.stI16o(circle_data, 204, 7);
cptr.stI16o(circle_data, 206, 6);
cptr.stI16o(circle_data, 208, 3);
cptr.stI16o(circle_data, 210, 14);
cptr.stI16o(circle_data, 212, 14);
cptr.stI16o(circle_data, 214, 14);
cptr.stI16o(circle_data, 216, 14);
cptr.stI16o(circle_data, 218, 13);
cptr.stI16o(circle_data, 220, 13);
cptr.stI16o(circle_data, 222, 13);
cptr.stI16o(circle_data, 224, 12);
cptr.stI16o(circle_data, 226, 12);
cptr.stI16o(circle_data, 228, 11);
cptr.stI16o(circle_data, 230, 10);
cptr.stI16o(circle_data, 232, 9);
cptr.stI16o(circle_data, 234, 8);
cptr.stI16o(circle_data, 236, 6);
cptr.stI16o(circle_data, 238, 3);
cptr.stI16o(circle_data, 240, 15);
cptr.stI16o(circle_data, 242, 15);
cptr.stI16o(circle_data, 244, 15);
cptr.stI16o(circle_data, 246, 15);
cptr.stI16o(circle_data, 248, 14);
cptr.stI16o(circle_data, 250, 14);
cptr.stI16o(circle_data, 252, 14);
cptr.stI16o(circle_data, 254, 13);
cptr.stI16o(circle_data, 256, 13);
cptr.stI16o(circle_data, 258, 12);
cptr.stI16o(circle_data, 260, 11);
cptr.stI16o(circle_data, 262, 10);
cptr.stI16o(circle_data, 264, 9);
cptr.stI16o(circle_data, 266, 8);
cptr.stI16o(circle_data, 268, 6);
cptr.stI16o(circle_data, 270, 3);
cptr.stI16o(circle_data, 272, 16);

/** C ref: vision.c:53 — short[16] */
export const circle_start = cptr.alloc(16 * 2);
cptr.stI16o(circle_start, 0, 0);
cptr.stI16o(circle_start, 2, 1);
cptr.stI16o(circle_start, 4, 3);
cptr.stI16o(circle_start, 6, 6);
cptr.stI16o(circle_start, 8, 10);
cptr.stI16o(circle_start, 10, 15);
cptr.stI16o(circle_start, 12, 21);
cptr.stI16o(circle_start, 14, 28);
cptr.stI16o(circle_start, 16, 36);
cptr.stI16o(circle_start, 18, 45);
cptr.stI16o(circle_start, 20, 55);
cptr.stI16o(circle_start, 22, 66);
cptr.stI16o(circle_start, 24, 78);
cptr.stI16o(circle_start, 26, 91);
cptr.stI16o(circle_start, 28, 105);
cptr.stI16o(circle_start, 30, 120);

/** C ref: vision.c:78 — unsigned char[2][21][80] */
const could_see = Array.from({ length: 2 }, () => (function () { const flat = new Uint8Array(21 * (80 * 1)); const a = []; for (let r = 0; r < 21; r++) a.push(flat.subarray(r * (80 * 1), (r + 1) * (80 * 1))); a.buf = flat; return a; })());

/** C ref: vision.c:79 — unsigned char *[21] */
const cs_rows0 = cptr.alloc(21 * 8);

/** C ref: vision.c:79 — unsigned char *[21] */
const cs_rows1 = cptr.alloc(21 * 8);

/** C ref: vision.c:80 — short[21] */
const cs_rmin0 = cptr.alloc(21 * 2);

/** C ref: vision.c:80 — short[21] */
const cs_rmax0 = cptr.alloc(21 * 2);

/** C ref: vision.c:81 — short[21] */
const cs_rmin1 = cptr.alloc(21 * 2);

/** C ref: vision.c:81 — short[21] */
const cs_rmax1 = cptr.alloc(21 * 2);

/** C ref: vision.c:83 — char[21][80] */
const viz_clear = (function () { const flat = new Uint8Array(21 * (80 * 1)); const a = []; for (let r = 0; r < 21; r++) a.push(flat.subarray(r * (80 * 1), (r + 1) * (80 * 1))); a.buf = flat; return a; })();

/** C ref: vision.c:84 — char *[21] */
const viz_clear_rows = cptr.alloc(21 * 8);

/** C ref: vision.c:86 — short[21][80] */
const left_ptrs = (function () { const flat = new Uint8Array(21 * 80 * 2); const a = []; for (let r = 0; r < 21; r++) a.push(flat.subarray(r * 80 * 2, (r + 1) * 80 * 2)); a.buf = flat; return a; })();

/** C ref: vision.c:87 — short[21][80] */
const right_ptrs = (function () { const flat = new Uint8Array(21 * 80 * 2); const a = []; for (let r = 0; r < 21; r++) a.push(flat.subarray(r * 80 * 2, (r + 1) * 80 * 2)); a.buf = flat; return a; })();

/** C ref: vision.c:105 — @param {CInt} x @param {CInt} y @returns {CInt} */
export function get_viz_clear(x, y) {
    if (isok(i16(x), i16(y)) && !cptr.ld1so(cptr.decay(viz_clear[y]), x, 1) ? 1 : 0)
        return 1;
    return 0;
}

/** C ref: vision.c:121 */
export function vision_init() {
    let i;
    for (i = 0; i < NHM.ROWNO; i++) {
        cptr.stPtro(cs_rows0, i, cptr.decay(could_see[0][i]), 8);
        cptr.stPtro(cs_rows1, i, cptr.decay(could_see[1][i]), 8);
        cptr.stPtro(viz_clear_rows, i, cptr.decay(viz_clear[i]), 8);
    }
    cptr.stPtro(gv, 120, cs_rows0);
    cptr.stPtro(gv, 128, cs_rmin0);
    cptr.stPtro(gv, 136, cs_rmax0);
    cptr.st1o(gv, 144, 0);
    void __builtin___memset_chk(cptr.decay(could_see), 0, 3360n, __builtin_object_size(cptr.decay(could_see), 0));
    view_init();
}

/** C ref: vision.c:153 — @param {CInt} x @param {CInt} y @param {CPtr} lev @returns {CInt} */
export function* does_block(x, y, lev) {
    let obj;
    let mon;
    if (cptr.ldI32o(gs, 1416) == 0) {
        cptr.stI32o(gs, 1416, (cptr.ld1so(flags, 10) && (yield* debugcore(__sl0, 0)) ? 1 : 0) ? 1 : -1);
    }
    if ((((cptr.ld1so(lev, 4)) < NHC.POOL) || cptr.ld1so(lev, 4) == NHC.TREE ? 1 : 0) || (((cptr.ld1so(lev, 4)) == NHC.DOOR) && (((cptr.ldI32o(lev, 8) & 31) | 0) & 28) ? 1 : 0) ? 1 : 0)
        return 1;
    if (cptr.ldI32o(gs, 1416) != 1) {
        if (((cptr.ld1so(lev, 4) == NHC.CLOUD || ((cptr.ld1so(lev, 4)) == NHC.WATER) ? 1 : 0) || cptr.ld1so(lev, 4) == NHC.LAVAWALL ? 1 : 0) || (((cptr.ldI32o(u, 1852) & 1)) | 0 && is_moat(i16(x), i16(y)) ? 1 : 0) ? 1 : 0)
            return 1;
    }
    for (obj = cptr.ldPtro3(svl, x, 168, y, 8, 62160); obj; obj = cptr.ldPtro(obj, 8))
        if (cptr.ldI16o(obj, 32) == NHC.BOULDER)
            return 1;
    if (((mon = (cptr.ldPtro3(svl, x, 168, y, 8, 75600))) && (!(cptr.ldI32o(mon, 88) & 1) || (cptr.ldI64o2(u, NHC.SEE_INVIS, 24, 128) || cptr.ldI64o2(u, NHC.SEE_INVIS, 24, 112) ? 1 : 0) ? 1 : 0) ? 1 : 0) && (((cptr.ld1uo((mon), 64) & NHM.M_AP_TYPMASK) == NHC.M_AP_OBJECT && cptr.ldI32o((mon), 60) == NHC.BOULDER ? 1 : 0) || ((cptr.ld1uo((mon), 64) & NHM.M_AP_TYPMASK) == NHC.M_AP_FURNITURE && (((cptr.ldI32o((mon), 60) == NHC.S_hcdoor || cptr.ldI32o((mon), 60) == NHC.S_vcdoor ? 1 : 0) || cptr.ldI32o((mon), 60) < NHC.S_ndoor ? 1 : 0) || cptr.ldI32o((mon), 60) == NHC.S_tree ? 1 : 0) ? 1 : 0) ? 1 : 0) ? 1 : 0)
        return 1;
    if (cptr.ldI32o(gs, 1416) != 1) {
        if (visible_region_at(i16(x), i16(y)))
            return 2;
    }
    return 0;
}

/** C ref: vision.c:211 */
export function* vision_reset() {
    let y;
    let x;
    let i;
    let dig_left;
    let block;
    let lev;
    cptr.stPtro(gv, 120, cs_rows0);
    cptr.stPtro(gv, 128, cs_rmin0);
    cptr.stPtro(gv, 136, cs_rmax0);
    void __builtin___memset_chk(cptr.decay(could_see), 0, 3360n, __builtin_object_size(cptr.decay(could_see), 0));
    void __builtin___memset_chk(cptr.decay(viz_clear), 0, 1680n, __builtin_object_size(cptr.decay(viz_clear), 0));
    for (y = 0; y < NHM.ROWNO; y++) {
        dig_left = 0;
        block = 1;
        lev = cptr.add(cptr.add(cptr.add(svl, 1680), 1, 756), y, 36);
        for (x = 1; x < NHM.COLNO; x++, lev = cptr.add(lev, NHM.ROWNO, 36))
            if (block != (((cptr.ld1so(lev, 4)) < NHC.POOL) || (yield* does_block(x, y, lev)) ? 1 : 0)) {
                if (block) {
                    for (i = dig_left; i < x; i++) {
                        cptr.stI16o(cptr.decay(left_ptrs[y]), i, i16(dig_left), 2);
                        cptr.stI16o(cptr.decay(right_ptrs[y]), i, i16(((x - 1) | 0)), 2);
                    }
                } else {
                    i = dig_left;
                    if (dig_left)
                        dig_left--;
                    for (; i < x; i++) {
                        cptr.stI16o(cptr.decay(left_ptrs[y]), i, i16(dig_left), 2);
                        cptr.stI16o(cptr.decay(right_ptrs[y]), i, i16(x), 2);
                        cptr.st1o(cptr.decay(viz_clear[y]), i, 1, 1);
                    }
                }
                dig_left = x;
                block = !block;
            }
        i = dig_left;
        if (!block && dig_left ? 1 : 0)
            dig_left--;
        for (; i < NHM.COLNO; i++) {
            cptr.stI16o(cptr.decay(left_ptrs[y]), i, i16(dig_left), 2);
            cptr.stI16o(cptr.decay(right_ptrs[y]), i, 79, 2);
            cptr.st1o(cptr.decay(viz_clear[y]), i, schar((!block)), 1);
        }
    }
    cptr.st1o(iflags, 82, 1);
    cptr.st1o(gv, 144, 1);
}

/** C ref: vision.c:274 — @param {CPtr} rows @param {CPtr} rmin @param {CPtr} rmax */
function* get_unused_cs(rows, rmin, rmax) {
    let row;
    let nrmin;
    let nrmax;
    if (cptr.eq(cptr.ldPtro(gv, 120), cs_rows0)) {
        cptr.stPtr(rows, cs_rows1);
        cptr.stPtr(rmin, cs_rmin1);
        cptr.stPtr(rmax, cs_rmax1);
    } else {
        cptr.stPtr(rows, cs_rows0);
        cptr.stPtr(rmin, cs_rmin0);
        cptr.stPtr(rmax, cs_rmax0);
    }
    nrmin = cptr.ldPtr(rmin);
    nrmax = cptr.ldPtr(rmax);
    void __builtin___memset_chk(cptr.ldPtr(cptr.ldPtr(rows)), 0, 1680n, __builtin_object_size(cptr.ldPtr(cptr.ldPtr(rows)), 0));
    for (row = 0; row < NHM.ROWNO; row++) {
        cptr.stI16(cptr.postinc(() => nrmin, (v) => { nrmin = v; }, 2), 79);
        cptr.stI16(cptr.postinc(() => nrmax, (v) => { nrmax = v; }, 2), 1);
    }
}

/** C ref: vision.c:314 — @param {CPtr} next @param {CPtr} rmin @param {CPtr} rmax */
function* rogue_vision(next, rmin, rmax) {
    let rnum = (((cptr.ldI32o3(svl, cptr.ldI16(u), 756, cptr.ldI16o(u, 2), 36, 1704) & 63) | 0) - NHM.ROOMOFFSET) | 0;
    let start;
    let stop;
    let in_door;
    let xhi;
    let xlo;
    let yhi;
    let ylo;
    let zx;
    let zy;
    if (rnum >= 0) {
        for (zy = (cptr.ldI16o2(svr, rnum, 224, 4) - 1) | 0; zy <= ((cptr.ldI16o2(svr, rnum, 224, 6) + 1) | 0); zy++) {
            cptr.stI16o(rmin, zy, i16((start = (cptr.ldI16o(svr, rnum, 224) - 1) | 0)), 2);
            cptr.stI16o(rmax, zy, i16((stop = (cptr.ldI16o2(svr, rnum, 224, 2) + 1) | 0)), 2);
            for (zx = start; zx <= stop; zx++) {
                if (cptr.ld1so2(svr, rnum, 224, 10)) {
                    cptr.st1o(cptr.ldPtro(next, zy, 8), zx, 3);
                    cptr.st1o3(svl, zx, 756, zy, 36, 1685, 255);
                } else
                    cptr.st1o(cptr.ldPtro(next, zy, 8), zx, NHM.COULD_SEE);
            }
        }
    }
    in_door = cptr.ld1so3(svl, cptr.ldI16(u), 756, cptr.ldI16o(u, 2), 36, 1684) == NHC.DOOR;
    ylo = (((cptr.ldI16o(u, 2) - 1) | 0) > 0 ? ((cptr.ldI16o(u, 2) - 1) | 0) : 0);
    yhi = (((cptr.ldI16o(u, 2) + 1) | 0) < 20 ? ((cptr.ldI16o(u, 2) + 1) | 0) : 20);
    xlo = (((cptr.ldI16(u) - 1) | 0) > 1 ? ((cptr.ldI16(u) - 1) | 0) : 1);
    xhi = (((cptr.ldI16(u) + 1) | 0) < 79 ? ((cptr.ldI16(u) + 1) | 0) : 79);
    for (zy = ylo; zy <= yhi; zy++) {
        if (xlo < cptr.ldI16o(rmin, zy, 2))
            cptr.stI16o(rmin, zy, i16(xlo), 2);
        if (xhi > cptr.ldI16o(rmax, zy, 2))
            cptr.stI16o(rmax, zy, i16(xhi), 2);
        for (zx = xlo; zx <= xhi; zx++) {
            cptr.st1o(cptr.ldPtro(next, zy, 8), zx, 3);
            if (in_door && (zx == cptr.ldI16(u) || zy == cptr.ldI16o(u, 2) ? 1 : 0) ? 1 : 0)
                (yield* newsym(i16(zx), i16(zy)));
        }
    }
}

const __static_vision_recalc_colbump = cptr.alloc(81 * 2); /** C ref: vision.c:515 — short[81] (function-static) */

/** C ref: vision.c:512 — @param {CInt} control */
export function* vision_recalc(control) {
    let temp_array;
    let next_array = cptr.box(0);
    let next_row;
    let old_row;
    let next_rmin = cptr.box(0);
    let next_rmax = cptr.box(0);
    let ranges;
    let row = 0;
    let start;
    let stop;
    let dx;
    let dy;
    let col;
    let lev;
    let flev;
    let sv;
    let oldseenv;
    __lbl_skip: {
        cptr.st1o(gv, 144, 0);
        if ((cptr.ld1so(gi, 4) || cptr.ldI32o(program_state, 40) ? 1 : 0) || !cptr.ld1so(iflags, 82) ? 1 : 0)
            return;
        (yield* get_unused_cs(next_array, next_rmin, next_rmax));
        if ((cptr.ldI32o(u, 1848) & 1) | 0 || control == 2 ? 1 : 0) {
            ;
        } else if (((cptr.ldI64o2(u, NHC.BLINDED, 24, 128) || cptr.ldI64o2(u, NHC.BLINDED, 24, 112) ? 1 : 0) && !cptr.ldI64o2(u, NHC.BLINDED, 24, 120) ? 1 : 0)) {
            (yield* view_from(cptr.ldI16o(u, 2), cptr.ldI16(u), next_array.v, next_rmin.v, next_rmax.v, 0, null, null));
            temp_array = cptr.ldPtro(gv, 120);
            cptr.stPtro(gv, 120, next_array.v);
            for (row = 0; row < NHM.ROWNO; row++) {
                old_row = cptr.ldPtro(temp_array, row, 8);
                start = ((cptr.ldI16o(cptr.ldPtro(gv, 128), row, 2)) < (cptr.ldI16o(next_rmin.v, row, 2)) ? (cptr.ldI16o(cptr.ldPtro(gv, 128), row, 2)) : (cptr.ldI16o(next_rmin.v, row, 2)));
                stop = ((cptr.ldI16o(cptr.ldPtro(gv, 136), row, 2)) > (cptr.ldI16o(next_rmax.v, row, 2)) ? (cptr.ldI16o(cptr.ldPtro(gv, 136), row, 2)) : (cptr.ldI16o(next_rmax.v, row, 2)));
                for (col = start; col <= stop; col++)
                    if (cptr.ld1uo(old_row, col) & NHM.IN_SIGHT)
                        (yield* newsym(i16(col), i16(row)));
            }
            break __lbl_skip;
        } else if ((((cptr.ldI16o((cptr.add(svd, 1800)), 2) || cptr.ldI16((cptr.add(svd, 1800))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1800)) ? 1 : 0))) {
            (yield* rogue_vision(next_array.v, next_rmin.v, next_rmax.v));
        } else {
            let lo_col;
            let has_night_vision = 1;
            if (((cptr.ldI32o(u, 1852) & 1)) | 0 && !(((cptr.ldI16o((cptr.add(svd, 1856)), 2) || cptr.ldI16((cptr.add(svd, 1856))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1856)) ? 1 : 0)) ? 1 : 0) {
                has_night_vision = 0;
                lo_col = (((cptr.ldI16(u) - 1) | 0) > 1 ? ((cptr.ldI16(u) - 1) | 0) : 1);
                for (row = (cptr.ldI16o(u, 2) - 1) | 0; row <= ((cptr.ldI16o(u, 2) + 1) | 0); row++)
                    for (col = lo_col; col <= ((cptr.ldI16(u) + 1) | 0); col++) {
                        if (!isok(i16(col), i16(row)) || !is_pool(i16(col), i16(row)) ? 1 : 0)
                            continue;
                        cptr.stI16o(next_rmin.v, row, i16(((cptr.ldI16o(next_rmin.v, row, 2)) < (col) ? (cptr.ldI16o(next_rmin.v, row, 2)) : (col))), 2);
                        cptr.stI16o(next_rmax.v, row, i16(((cptr.ldI16o(next_rmax.v, row, 2)) > (col) ? (cptr.ldI16o(next_rmax.v, row, 2)) : (col))), 2);
                        cptr.st1o(cptr.ldPtro(next_array.v, row, 8), col, 3);
                    }
            } else if (cptr.ldI32o(u, 60) && cptr.ldI32o(u, 64) == NHC.TT_PIT ? 1 : 0) {
                for (row = (cptr.ldI16o(u, 2) - 1) | 0; row <= ((cptr.ldI16o(u, 2) + 1) | 0); row++) {
                    if (row < 0)
                        continue;
                    if (row >= NHM.ROWNO)
                        break;
                    cptr.stI16o(next_rmin.v, row, i16((1 > ((cptr.ldI16(u) - 1) | 0) ? 1 : ((cptr.ldI16(u) - 1) | 0))), 2);
                    cptr.stI16o(next_rmax.v, row, i16((79 < ((cptr.ldI16(u) + 1) | 0) ? 79 : ((cptr.ldI16(u) + 1) | 0))), 2);
                    next_row = cptr.ldPtro(next_array.v, row, 8);
                    for (col = cptr.ldI16o(next_rmin.v, row, 2); col <= cptr.ldI16o(next_rmax.v, row, 2); col++)
                        cptr.st1o(next_row, col, 3);
                }
            } else
                (yield* view_from(cptr.ldI16o(u, 2), cptr.ldI16(u), next_array.v, next_rmin.v, next_rmax.v, 0, null, null));
            if (cptr.ldI32o(u, 1780) >= 0) {
                if (cptr.ldI32o(u, 1780)) {
                    ranges = (cptr.add(circle_data, cptr.ldI16o(circle_start, cptr.ldI32o(u, 1780), 2), 2));
                    for (row = (cptr.ldI16o(u, 2) - cptr.ldI32o(u, 1780)) | 0; row <= ((cptr.ldI16o(u, 2) + cptr.ldI32o(u, 1780)) | 0); row++) {
                        if (row < 0)
                            continue;
                        if (row >= NHM.ROWNO)
                            break;
                        dy = (((cptr.ldI16o(u, 2) - row) | 0) < 0 ? -((cptr.ldI16o(u, 2) - row) | 0) : ((cptr.ldI16o(u, 2) - row) | 0));
                        next_row = cptr.ldPtro(next_array.v, row, 8);
                        start = (1 > ((cptr.ldI16(u) - cptr.ldI16o(ranges, dy, 2)) | 0) ? 1 : ((cptr.ldI16(u) - cptr.ldI16o(ranges, dy, 2)) | 0));
                        stop = (79 < ((cptr.ldI16(u) + cptr.ldI16o(ranges, dy, 2)) | 0) ? 79 : ((cptr.ldI16(u) + cptr.ldI16o(ranges, dy, 2)) | 0));
                        for (col = start; col <= stop; col++) {
                            let old_row_val = schar(cptr.ld1uo(next_row, col));
                            cptr.st1o(next_row, col, cptr.ld1uo(next_row, col) | NHM.IN_SIGHT);
                            oldseenv = cptr.ld1uo3(svl, col, 756, row, 36, 1685);
                            cptr.st1o3(svl, col, 756, row, 36, 1685, 255);
                            if (!(old_row_val & NHM.IN_SIGHT) || oldseenv != 255 ? 1 : 0)
                                (yield* newsym(i16(col), i16(row)));
                        }
                        cptr.stI16o(next_rmin.v, row, i16(((start) < (cptr.ldI16o(next_rmin.v, row, 2)) ? (start) : (cptr.ldI16o(next_rmin.v, row, 2)))), 2);
                        cptr.stI16o(next_rmax.v, row, i16(((stop) > (cptr.ldI16o(next_rmax.v, row, 2)) ? (stop) : (cptr.ldI16o(next_rmax.v, row, 2)))), 2);
                    }
                } else {
                    cptr.st1o(cptr.ldPtro(next_array.v, cptr.ldI16o(u, 2), 8), cptr.ldI16(u), cptr.ld1uo(cptr.ldPtro(next_array.v, cptr.ldI16o(u, 2), 8), cptr.ldI16(u)) | NHM.IN_SIGHT);
                    cptr.st1o3(svl, cptr.ldI16(u), 756, cptr.ldI16o(u, 2), 36, 1685, 255);
                    cptr.stI16o(next_rmin.v, cptr.ldI16o(u, 2), i16(((cptr.ldI16(u)) < (cptr.ldI16o(next_rmin.v, cptr.ldI16o(u, 2), 2)) ? (cptr.ldI16(u)) : (cptr.ldI16o(next_rmin.v, cptr.ldI16o(u, 2), 2)))), 2);
                    cptr.stI16o(next_rmax.v, cptr.ldI16o(u, 2), i16(((cptr.ldI16(u)) > (cptr.ldI16o(next_rmax.v, cptr.ldI16o(u, 2), 2)) ? (cptr.ldI16(u)) : (cptr.ldI16o(next_rmax.v, cptr.ldI16o(u, 2), 2)))), 2);
                }
            }
            if (has_night_vision && cptr.ldI32o(u, 1780) < cptr.ldI32o(u, 1776) ? 1 : 0) {
                if (!cptr.ldI32o(u, 1776)) {
                    cptr.st1o(cptr.ldPtro(next_array.v, cptr.ldI16o(u, 2), 8), cptr.ldI16(u), cptr.ld1uo(cptr.ldPtro(next_array.v, cptr.ldI16o(u, 2), 8), cptr.ldI16(u)) | NHM.IN_SIGHT);
                    cptr.st1o3(svl, cptr.ldI16(u), 756, cptr.ldI16o(u, 2), 36, 1685, 255);
                    cptr.stI16o(next_rmin.v, cptr.ldI16o(u, 2), i16(((cptr.ldI16(u)) < (cptr.ldI16o(next_rmin.v, cptr.ldI16o(u, 2), 2)) ? (cptr.ldI16(u)) : (cptr.ldI16o(next_rmin.v, cptr.ldI16o(u, 2), 2)))), 2);
                    cptr.stI16o(next_rmax.v, cptr.ldI16o(u, 2), i16(((cptr.ldI16(u)) > (cptr.ldI16o(next_rmax.v, cptr.ldI16o(u, 2), 2)) ? (cptr.ldI16(u)) : (cptr.ldI16o(next_rmax.v, cptr.ldI16o(u, 2), 2)))), 2);
                } else if (cptr.ldI32o(u, 1776) > 0) {
                    ranges = (cptr.add(circle_data, cptr.ldI16o(circle_start, cptr.ldI32o(u, 1776), 2), 2));
                    for (row = (cptr.ldI16o(u, 2) - cptr.ldI32o(u, 1776)) | 0; row <= ((cptr.ldI16o(u, 2) + cptr.ldI32o(u, 1776)) | 0); row++) {
                        if (row < 0)
                            continue;
                        if (row >= NHM.ROWNO)
                            break;
                        dy = (((cptr.ldI16o(u, 2) - row) | 0) < 0 ? -((cptr.ldI16o(u, 2) - row) | 0) : ((cptr.ldI16o(u, 2) - row) | 0));
                        next_row = cptr.ldPtro(next_array.v, row, 8);
                        start = (1 > ((cptr.ldI16(u) - cptr.ldI16o(ranges, dy, 2)) | 0) ? 1 : ((cptr.ldI16(u) - cptr.ldI16o(ranges, dy, 2)) | 0));
                        stop = (79 < ((cptr.ldI16(u) + cptr.ldI16o(ranges, dy, 2)) | 0) ? 79 : ((cptr.ldI16(u) + cptr.ldI16o(ranges, dy, 2)) | 0));
                        for (col = start; col <= stop; col++)
                            if (cptr.ld1uo(next_row, col))
                                cptr.st1o(next_row, col, cptr.ld1uo(next_row, col) | NHM.IN_SIGHT);
                        cptr.stI16o(next_rmin.v, row, i16(((start) < (cptr.ldI16o(next_rmin.v, row, 2)) ? (start) : (cptr.ldI16o(next_rmin.v, row, 2)))), 2);
                        cptr.stI16o(next_rmax.v, row, i16(((stop) > (cptr.ldI16o(next_rmax.v, row, 2)) ? (stop) : (cptr.ldI16o(next_rmax.v, row, 2)))), 2);
                    }
                }
            }
        }
        do_light_sources(next_array.v);
        temp_array = cptr.ldPtro(gv, 120);
        cptr.stPtro(gv, 120, next_array.v);
        cptr.stI16o(__static_vision_recalc_colbump, cptr.ldI16(u), cptr.stI16o(__static_vision_recalc_colbump, (cptr.ldI16(u) + 1) | 0, 1, 2), 2);
        for (row = 0; row < NHM.ROWNO; row++) {
            dy = (cptr.ldI16o(u, 2) - row) | 0;
            dy = ((dy) < 0 ? -1 : ((dy) ? 1 : 0));
            next_row = cptr.ldPtro(next_array.v, row, 8);
            old_row = cptr.ldPtro(temp_array, row, 8);
            start = ((cptr.ldI16o(cptr.ldPtro(gv, 128), row, 2)) < (cptr.ldI16o(next_rmin.v, row, 2)) ? (cptr.ldI16o(cptr.ldPtro(gv, 128), row, 2)) : (cptr.ldI16o(next_rmin.v, row, 2)));
            stop = ((cptr.ldI16o(cptr.ldPtro(gv, 136), row, 2)) > (cptr.ldI16o(next_rmax.v, row, 2)) ? (cptr.ldI16o(cptr.ldPtro(gv, 136), row, 2)) : (cptr.ldI16o(next_rmax.v, row, 2)));
            lev = cptr.add(cptr.add(cptr.add(svl, 1680), start, 756), row, 36);
            sv = cptr.add(cptr.decay(seenv_matrix[(dy + 1) | 0]), start < cptr.ldI16(u) ? 0 : (start > cptr.ldI16(u) ? 2 : 1), 1);
            for (col = start; col <= stop; lev = cptr.add(lev, NHM.ROWNO, 36), sv = cptr.add(sv, cptr.ldI16o(__static_vision_recalc_colbump, ++col, 2))) {
                let __go_not_in_sight = false;
                __skip_not_in_sight: {
                    if (cptr.ld1uo(next_row, col) & NHM.IN_SIGHT) {
                        oldseenv = cptr.ld1uo(lev, 5);
                        cptr.st1o(lev, 5, cptr.ld1uo(lev, 5) | (cptr.ld1u(sv)));
                        if (!(cptr.ld1uo(old_row, col) & NHM.IN_SIGHT) || oldseenv != cptr.ld1uo(lev, 5) ? 1 : 0)
                            (yield* newsym(i16(col), i16(row)));
                    } else if ((cptr.ld1uo(next_row, col) & NHM.COULD_SEE) && ((cptr.ldI32o(lev, 16) & 1) | 0 || (cptr.ld1uo(next_row, col) & NHM.TEMP_LIT) ? 1 : 0) ? 1 : 0) {
                        if (((((cptr.ld1so(lev, 4)) == NHC.DOOR) || cptr.ld1so(lev, 4) == NHC.SDOOR ? 1 : 0) || ((cptr.ld1so(lev, 4)) && (cptr.ld1so(lev, 4)) <= NHC.DBWALL ? 1 : 0) ? 1 : 0) && !cptr.ld1so(cptr.decay(viz_clear[row]), col, 1) ? 1 : 0) {
                            dx = (cptr.ldI16(u) - col) | 0;
                            dx = ((dx) < 0 ? -1 : ((dx) ? 1 : 0));
                            flev = cptr.add(cptr.add(cptr.add(svl, 1680), (col + dx) | 0, 756), (row + dy) | 0, 36);
                            if ((cptr.ldI32o(flev, 16) & 1) | 0 || cptr.ld1uo(cptr.ldPtro(next_array.v, (row + dy) | 0, 8), (col + dx) | 0) & NHM.TEMP_LIT ? 1 : 0) {
                                cptr.st1o(next_row, col, cptr.ld1uo(next_row, col) | NHM.IN_SIGHT);
                                oldseenv = cptr.ld1uo(lev, 5);
                                cptr.st1o(lev, 5, cptr.ld1uo(lev, 5) | (cptr.ld1u(sv)));
                                if (!(cptr.ld1uo(old_row, col) & NHM.IN_SIGHT) || oldseenv != cptr.ld1uo(lev, 5) ? 1 : 0)
                                    (yield* newsym(i16(col), i16(row)));
                            } else
                                { __go_not_in_sight = true; break __skip_not_in_sight; }
                        } else {
                            cptr.st1o(next_row, col, cptr.ld1uo(next_row, col) | NHM.IN_SIGHT);
                            oldseenv = cptr.ld1uo(lev, 5);
                            cptr.st1o(lev, 5, cptr.ld1uo(lev, 5) | (cptr.ld1u(sv)));
                            if (!(cptr.ld1uo(old_row, col) & NHM.IN_SIGHT) || oldseenv != cptr.ld1uo(lev, 5) ? 1 : 0)
                                (yield* newsym(i16(col), i16(row)));
                        }
                    } else if ((cptr.ld1uo(next_row, col) & NHM.COULD_SEE) && (cptr.ldI32o(lev, 20) & 1) | 0 ? 1 : 0) {
                        cptr.stI32o(lev, 20, 0);
                        (yield* newsym(i16(col), i16(row)));
                    } else {
                        __go_not_in_sight = true; break __skip_not_in_sight;
                    }
                }
                if (__go_not_in_sight) {
                    if ((cptr.ld1uo(old_row, col) & NHM.IN_SIGHT) || ((cptr.ld1uo(next_row, col) & NHM.COULD_SEE) ^ (cptr.ld1uo(old_row, col) & NHM.COULD_SEE)) ? 1 : 0) {
                        if (col != 0)
                            (yield* newsym(i16(col), i16(row)));
                    }
                }
            }
        }
        cptr.stI16o(__static_vision_recalc_colbump, cptr.ldI16(u), cptr.stI16o(__static_vision_recalc_colbump, (cptr.ldI16(u) + 1) | 0, 0, 2), 2);
    }
    if (!cptr.ldI32o(program_state, 20))
        (yield* newsym(cptr.ldI16(u), cptr.ldI16o(u, 2)));
    cptr.stPtro(gv, 128, next_rmin.v);
    cptr.stPtro(gv, 136, next_rmax.v);
    (yield* notice_all_mons(1));
}

/** C ref: vision.c:865 — @param {CInt} x @param {CInt} y */
export function* block_point(x, y) {
    if (cptr.ldI32o(gs, 1416) == 0) {
        cptr.stI32o(gs, 1416, (cptr.ld1so(flags, 10) && (yield* debugcore(__sl0, 0)) ? 1 : 0) ? 1 : -1);
    }
    if (cptr.ldI32o(gs, 1416) == 1) {
        if (!(yield* does_block(x, y, cptr.add(cptr.add(cptr.add(svl, 1680), x, 756), y, 36))))
            return;
    }
    fill_point(y, x);
    if (cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, 120), y, 8), x))
        cptr.st1o(gv, 144, 1);
}

/** C ref: vision.c:899 — @param {CInt} x @param {CInt} y */
export function unblock_point(x, y) {
    dig_point(y, x);
    if (cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, 120), y, 8), x))
        cptr.st1o(gv, 144, 1);
}

/** C ref: vision.c:911 — @param {CInt} x @param {CInt} y */
export function* recalc_block_point(x, y) {
    if ((yield* does_block(x, y, cptr.add(cptr.add(cptr.add(svl, 1680), x, 756), y, 36))))
        (yield* block_point(x, y));
    else
        unblock_point(x, y);
}

/** C ref: vision.c:967 — @param {CInt} row @param {CInt} col */
function dig_point(row, col) {
    let i;
    if (cptr.ld1so(cptr.decay(viz_clear[row]), col, 1))
        return;
    cptr.st1o(cptr.decay(viz_clear[row]), col, 1, 1);
    if (col == 0) {
        if (cptr.ld1so(cptr.decay(viz_clear[row]), 1, 1)) {
            cptr.stI16o(cptr.decay(right_ptrs[row]), 0, cptr.ldI16o(cptr.decay(right_ptrs[row]), 1, 2), 2);
        } else {
            cptr.stI16o(cptr.decay(right_ptrs[row]), 0, 1, 2);
            for (i = 1; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), 1, 2); i++)
                cptr.stI16o(cptr.decay(left_ptrs[row]), i, 1, 2);
        }
    } else if (col == 79) {
        if (cptr.ld1so(cptr.decay(viz_clear[row]), 78, 1)) {
            cptr.stI16o(cptr.decay(left_ptrs[row]), 79, cptr.ldI16o(cptr.decay(left_ptrs[row]), 78, 2), 2);
        } else {
            cptr.stI16o(cptr.decay(left_ptrs[row]), 79, 78, 2);
            for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), 78, 2); i < 79; i++)
                cptr.stI16o(cptr.decay(right_ptrs[row]), i, 78, 2);
        }
    } else if (cptr.ld1so(cptr.decay(viz_clear[row]), (col - 1) | 0, 1) && cptr.ld1so(cptr.decay(viz_clear[row]), (col + 1) | 0, 1) ? 1 : 0) {
        for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2); i <= col; i++) {
            if (!cptr.ld1so(cptr.decay(viz_clear[row]), i, 1))
                continue;
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2), 2);
        }
        for (i = col; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++) {
            if (!cptr.ld1so(cptr.decay(viz_clear[row]), i, 1))
                continue;
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2), 2);
        }
    } else if (cptr.ld1so(cptr.decay(viz_clear[row]), (col - 1) | 0, 1)) {
        for (i = (col + 1) | 0; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(((col + 1) | 0)), 2);
        for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2); i <= col; i++) {
            if (!cptr.ld1so(cptr.decay(viz_clear[row]), i, 1))
                continue;
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(((col + 1) | 0)), 2);
        }
        cptr.stI16o(cptr.decay(left_ptrs[row]), col, cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2), 2);
    } else if (cptr.ld1so(cptr.decay(viz_clear[row]), (col + 1) | 0, 1)) {
        for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2); i < col; i++)
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(((col - 1) | 0)), 2);
        for (i = col; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++) {
            if (!cptr.ld1so(cptr.decay(viz_clear[row]), i, 1))
                continue;
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(((col - 1) | 0)), 2);
        }
        cptr.stI16o(cptr.decay(right_ptrs[row]), col, cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2), 2);
    } else {
        for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2); i < col; i++)
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(((col - 1) | 0)), 2);
        for (i = (col + 1) | 0; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(((col + 1) | 0)), 2);
        cptr.stI16o(cptr.decay(left_ptrs[row]), col, i16(((col - 1) | 0)), 2);
        cptr.stI16o(cptr.decay(right_ptrs[row]), col, i16(((col + 1) | 0)), 2);
    }
}

/** C ref: vision.c:1051 — @param {CInt} row @param {CInt} col */
function fill_point(row, col) {
    let i;
    if (!cptr.ld1so(cptr.decay(viz_clear[row]), col, 1))
        return;
    cptr.st1o(cptr.decay(viz_clear[row]), col, 0, 1);
    if (col == 0) {
        if (cptr.ld1so(cptr.decay(viz_clear[row]), 1, 1)) {
            cptr.stI16o(cptr.decay(right_ptrs[row]), 0, 0, 2);
        } else {
            cptr.stI16o(cptr.decay(right_ptrs[row]), 0, cptr.ldI16o(cptr.decay(right_ptrs[row]), 1, 2), 2);
            for (i = 1; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), 1, 2); i++)
                cptr.stI16o(cptr.decay(left_ptrs[row]), i, 0, 2);
        }
    } else if (col == 79) {
        if (cptr.ld1so(cptr.decay(viz_clear[row]), 78, 1)) {
            cptr.stI16o(cptr.decay(left_ptrs[row]), 79, 79, 2);
        } else {
            cptr.stI16o(cptr.decay(left_ptrs[row]), 79, cptr.ldI16o(cptr.decay(left_ptrs[row]), 78, 2), 2);
            for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), 78, 2); i < 79; i++)
                cptr.stI16o(cptr.decay(right_ptrs[row]), i, 79, 2);
        }
    } else if (cptr.ld1so(cptr.decay(viz_clear[row]), (col - 1) | 0, 1) && cptr.ld1so(cptr.decay(viz_clear[row]), (col + 1) | 0, 1) ? 1 : 0) {
        for (i = (cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2) + 1) | 0; i <= col; i++)
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(col), 2);
        if (!cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2))
            cptr.stI16o(cptr.decay(right_ptrs[row]), 0, i16(col), 2);
        for (i = col; i < cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(col), 2);
        if (cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2) == 79)
            cptr.stI16o(cptr.decay(left_ptrs[row]), 79, i16(col), 2);
    } else if (cptr.ld1so(cptr.decay(viz_clear[row]), (col - 1) | 0, 1)) {
        for (i = col; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(col), 2);
        for (i = (cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2) + 1) | 0; i < col; i++)
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(col), 2);
        if (!cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2))
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(col), 2);
        cptr.stI16o(cptr.decay(right_ptrs[row]), col, cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2), 2);
    } else if (cptr.ld1so(cptr.decay(viz_clear[row]), (col + 1) | 0, 1)) {
        for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2); i <= col; i++)
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, i16(col), 2);
        for (i = (col + 1) | 0; i < cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(col), 2);
        if (cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2) == 79)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, i16(col), 2);
        cptr.stI16o(cptr.decay(left_ptrs[row]), col, cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2), 2);
    } else {
        for (i = cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2); i <= col; i++)
            cptr.stI16o(cptr.decay(right_ptrs[row]), i, cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2), 2);
        for (i = col; i <= cptr.ldI16o(cptr.decay(right_ptrs[row]), (col + 1) | 0, 2); i++)
            cptr.stI16o(cptr.decay(left_ptrs[row]), i, cptr.ldI16o(cptr.decay(left_ptrs[row]), (col - 1) | 0, 2), 2);
    }
}

/** C ref: vision.c:1136 — int */
let start_row = 0;

/** C ref: vision.c:1137 — int */
let start_col = 0;

/** C ref: vision.c:1138 — int */
let step = cptr.box(0);

/** C ref: vision.c:1139 — unsigned char ** */
let cs_rows = null;

/** C ref: vision.c:1140 — short * */
let cs_left = null;

/** C ref: vision.c:1141 — short * */
let cs_right = null;

/** C ref: vision.c:1143 — void (*)(short, short, void *) */
let vis_func = null;

/** C ref: vision.c:1144 — void * */
let varg = null;

/** C ref: vision.c:1613 — @param {CInt} col1 @param {CInt} row1 @param {CInt} col2 @param {CInt} row2 @returns {CInt} */
export function clear_path(col1, row1, col2, row2) {
    let result;
    __lbl_cleardone: {
        if (col1 < col2) {
            if (row1 > row2) {
                {
                    let dx;
                    let dy;
                    let k;
                    let err;
                    let x;
                    let y;
                    let dxs;
                    let dys;
                    x = (col1);
                    y = (row1);
                    dx = ((col2) - x) | 0;
                    dy = (y - (row2)) | 0;
                    result = 0;
                    dxs = dx << 1;
                    dys = dy << 1;
                    if (dy > dx) {
                        err = (dxs - dy) | 0;
                        for (k = (dy - 1) | 0; k; k--) {
                            if (err >= 0) {
                                x++;
                                err = (err - dys) | 0;
                            }
                            y--;
                            err = (err + dxs) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    } else {
                        err = (dys - dx) | 0;
                        for (k = (dx - 1) | 0; k; k--) {
                            if (err >= 0) {
                                y--;
                                err = (err - dxs) | 0;
                            }
                            x++;
                            err = (err + dys) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    }
                    result = 1;
                }
                ;
            } else {
                {
                    let dx;
                    let dy;
                    let k;
                    let err;
                    let x;
                    let y;
                    let dxs;
                    let dys;
                    x = (col1);
                    y = (row1);
                    dx = ((col2) - x) | 0;
                    dy = ((row2) - y) | 0;
                    result = 0;
                    dxs = dx << 1;
                    dys = dy << 1;
                    if (dy > dx) {
                        err = (dxs - dy) | 0;
                        for (k = (dy - 1) | 0; k; k--) {
                            if (err >= 0) {
                                x++;
                                err = (err - dys) | 0;
                            }
                            y++;
                            err = (err + dxs) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    } else {
                        err = (dys - dx) | 0;
                        for (k = (dx - 1) | 0; k; k--) {
                            if (err >= 0) {
                                y++;
                                err = (err - dxs) | 0;
                            }
                            x++;
                            err = (err + dys) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    }
                    result = 1;
                }
                ;
            }
        } else {
            if (row1 > row2) {
                {
                    let dx;
                    let dy;
                    let k;
                    let err;
                    let x;
                    let y;
                    let dxs;
                    let dys;
                    x = (col1);
                    y = (row1);
                    dx = (x - (col2)) | 0;
                    dy = (y - (row2)) | 0;
                    result = 0;
                    dxs = dx << 1;
                    dys = dy << 1;
                    if (dy > dx) {
                        err = (dxs - dy) | 0;
                        for (k = (dy - 1) | 0; k; k--) {
                            if (err >= 0) {
                                x--;
                                err = (err - dys) | 0;
                            }
                            y--;
                            err = (err + dxs) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    } else {
                        err = (dys - dx) | 0;
                        for (k = (dx - 1) | 0; k; k--) {
                            if (err >= 0) {
                                y--;
                                err = (err - dxs) | 0;
                            }
                            x--;
                            err = (err + dys) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    }
                    result = 1;
                }
                ;
            } else if (row1 == row2 && col1 == col2 ? 1 : 0) {
                result = 1;
            } else {
                {
                    let dx;
                    let dy;
                    let k;
                    let err;
                    let x;
                    let y;
                    let dxs;
                    let dys;
                    x = (col1);
                    y = (row1);
                    dx = (x - (col2)) | 0;
                    dy = ((row2) - y) | 0;
                    result = 0;
                    dxs = dx << 1;
                    dys = dy << 1;
                    if (dy > dx) {
                        err = (dxs - dy) | 0;
                        for (k = (dy - 1) | 0; k; k--) {
                            if (err >= 0) {
                                x--;
                                err = (err - dys) | 0;
                            }
                            y++;
                            err = (err + dxs) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    } else {
                        err = (dys - dx) | 0;
                        for (k = (dx - 1) | 0; k; k--) {
                            if (err >= 0) {
                                y++;
                                err = (err - dxs) | 0;
                            }
                            x--;
                            err = (err + dys) | 0;
                            if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                break __lbl_cleardone;
                        }
                    }
                    result = 1;
                }
                ;
            }
        }
    }
    return schar(result);
}

/** C ref: vision.c:1651 */
function view_init() {
}

/** C ref: vision.c:1666 — @param {CInt} row @param {CInt} left @param {CInt} right_mark @param {CPtr} limits */
function* right_side(row, left, right_mark, limits) {
    let right;
    let right_edge;
    let nrow;
    let deeper;
    let result;
    let i;
    let rowp = null;
    let row_min = null;
    let row_max = null;
    let lim_max;
    nrow = (row + step.v) | 0;
    deeper = ((nrow) >= 0 && (nrow) < NHM.ROWNO ? 1 : 0) && (!limits || (cptr.ldI16(limits) >= cptr.ldI16((cptr.add(limits, 1, 2)))) ? 1 : 0) ? 1 : 0;
    if (!vis_func) {
        rowp = cptr.ldPtro(cs_rows, row, 8);
        row_min = cptr.add(cs_left, row, 2);
        row_max = cptr.add(cs_right, row, 2);
    }
    if (limits) {
        lim_max = (start_col + cptr.ldI16(limits)) | 0;
        if (lim_max > 79)
            lim_max = 79;
        if (right_mark > lim_max)
            right_mark = lim_max;
        limits = cptr.add(limits, 1, 2);
    } else
        lim_max = 79;
    while (left <= right_mark) {
        right_edge = cptr.ldI16o(cptr.decay(right_ptrs[row]), left, 2);
        if (right_edge > lim_max)
            right_edge = lim_max;
        if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, row, 8), left)) {
            if (right_edge > right_mark) {
                right_edge = cptr.ld1so(cptr.ldPtro(viz_clear_rows, (row - step.v) | 0, 8), right_mark) ? (right_mark + 1) | 0 : right_mark;
            }
            if (vis_func) {
                for (i = left; i <= right_edge; i++)
                    (yield* Y.icall((vis_func)(i16(i), i16(row), varg)));
            } else {
                for (i = left; i <= right_edge; i++)
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1735, __sl3) : void 0);
                        cptr.st1o(rowp, i, NHM.COULD_SEE);
                    } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_min, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1736, __sl4) : void 0);
                    if (cptr.ldI16(row_min) > (left))
                        cptr.stI16(row_min, i16((left)));
                } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_max, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1737, __sl5) : void 0);
                    if (cptr.ldI16(row_max) < (right_edge))
                        cptr.stI16(row_max, i16((right_edge)));
                } while (0);
            }
            left = (right_edge + 1) | 0;
            continue;
        }
        if (left != start_col) {
            for (; left <= right_edge; left++) {
                __lbl_rside1: {
                    if (step.v < 0) {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = ((left) - x) | 0;
                            dy = (y - (row)) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x++;
                                        err = (err - dys) | 0;
                                    }
                                    y--;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside1;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y--;
                                        err = (err - dxs) | 0;
                                    }
                                    x++;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside1;
                                }
                            }
                            result = 1;
                        }
                        ;
                    } else {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = ((left) - x) | 0;
                            dy = ((row) - y) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x++;
                                        err = (err - dys) | 0;
                                    }
                                    y++;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside1;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y++;
                                        err = (err - dxs) | 0;
                                    }
                                    x++;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside1;
                                }
                            }
                            result = 1;
                        }
                        ;
                    }
                }
                if (result)
                    break;
            }
            if (left > lim_max)
                return;
            if (left == lim_max) {
                if (vis_func) {
                    (yield* Y.icall((vis_func)(i16(lim_max), i16(row), varg)));
                } else {
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1773, __sl3) : void 0);
                        cptr.st1o(rowp, lim_max, NHM.COULD_SEE);
                    } while (0);
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(row_max, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1774, __sl5) : void 0);
                        if (cptr.ldI16(row_max) < (lim_max))
                            cptr.stI16(row_max, i16((lim_max)));
                    } while (0);
                }
                return;
            }
            if (left >= right_edge) {
                left = right_edge;
                continue;
            }
        }
        if (right_mark < right_edge) {
            for (right = right_mark; right <= right_edge; right++) {
                __lbl_rside2: {
                    if (step.v < 0) {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = ((right) - x) | 0;
                            dy = (y - (row)) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x++;
                                        err = (err - dys) | 0;
                                    }
                                    y--;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside2;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y--;
                                        err = (err - dxs) | 0;
                                    }
                                    x++;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside2;
                                }
                            }
                            result = 1;
                        }
                        ;
                    } else {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = ((right) - x) | 0;
                            dy = ((row) - y) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x++;
                                        err = (err - dys) | 0;
                                    }
                                    y++;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside2;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y++;
                                        err = (err - dxs) | 0;
                                    }
                                    x++;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_rside2;
                                }
                            }
                            result = 1;
                        }
                        ;
                    }
                }
                if (!result)
                    break;
            }
            --right;
        } else
            right = right_edge;
        if (left <= right) {
            if (((left == right && left == start_col ? 1 : 0) && start_col < 79 ? 1 : 0) && !cptr.ld1so(cptr.ldPtro(viz_clear_rows, row, 8), (start_col + 1) | 0) ? 1 : 0)
                right = (start_col + 1) | 0;
            if (right > lim_max)
                right = lim_max;
            if (vis_func) {
                for (i = left; i <= right; i++)
                    (yield* Y.icall((vis_func)(i16(i), i16(row), varg)));
            } else {
                for (i = left; i <= right; i++)
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1840, __sl3) : void 0);
                        cptr.st1o(rowp, i, NHM.COULD_SEE);
                    } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_min, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1841, __sl4) : void 0);
                    if (cptr.ldI16(row_min) > (left))
                        cptr.stI16(row_min, i16((left)));
                } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_max, (null))))), 0n) ? __assert_rtn(__sl1, __sl2, 1842, __sl5) : void 0);
                    if (cptr.ldI16(row_max) < (right))
                        cptr.stI16(row_max, i16((right)));
                } while (0);
            }
            if (deeper)
                (yield* right_side(nrow, left, right, limits));
            left = (right + 1) | 0;
        }
    }
}

/** C ref: vision.c:1858 — @param {CInt} row @param {CInt} left_mark @param {CInt} right @param {CPtr} limits */
function* left_side(row, left_mark, right, limits) {
    let left;
    let left_edge;
    let nrow;
    let deeper;
    let result;
    let i;
    let rowp = null;
    let row_min = null;
    let row_max = null;
    let lim_min;
    nrow = (row + step.v) | 0;
    deeper = ((nrow) >= 0 && (nrow) < NHM.ROWNO ? 1 : 0) && (!limits || (cptr.ldI16(limits) >= cptr.ldI16((cptr.add(limits, 1, 2)))) ? 1 : 0) ? 1 : 0;
    if (!vis_func) {
        rowp = cptr.ldPtro(cs_rows, row, 8);
        row_min = cptr.add(cs_left, row, 2);
        row_max = cptr.add(cs_right, row, 2);
    }
    if (limits) {
        lim_min = (start_col - cptr.ldI16(limits)) | 0;
        if (lim_min < 0)
            lim_min = 0;
        if (left_mark < lim_min)
            left_mark = lim_min;
        limits = cptr.add(limits, 1, 2);
    } else
        lim_min = 0;
    while (right >= left_mark) {
        left_edge = cptr.ldI16o(cptr.decay(left_ptrs[row]), right, 2);
        if (left_edge < lim_min)
            left_edge = lim_min;
        if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, row, 8), right)) {
            if (left_edge < left_mark) {
                left_edge = cptr.ld1so(cptr.ldPtro(viz_clear_rows, (row - step.v) | 0, 8), left_mark) ? (left_mark - 1) | 0 : left_mark;
            }
            if (vis_func) {
                for (i = left_edge; i <= right; i++)
                    (yield* Y.icall((vis_func)(i16(i), i16(row), varg)));
            } else {
                for (i = left_edge; i <= right; i++)
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1905, __sl3) : void 0);
                        cptr.st1o(rowp, i, NHM.COULD_SEE);
                    } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_min, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1906, __sl4) : void 0);
                    if (cptr.ldI16(row_min) > (left_edge))
                        cptr.stI16(row_min, i16((left_edge)));
                } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_max, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1907, __sl5) : void 0);
                    if (cptr.ldI16(row_max) < (right))
                        cptr.stI16(row_max, i16((right)));
                } while (0);
            }
            right = (left_edge - 1) | 0;
            continue;
        }
        if (right != start_col) {
            for (; right >= left_edge; right--) {
                __lbl_lside1: {
                    if (step.v < 0) {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = (x - (right)) | 0;
                            dy = (y - (row)) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x--;
                                        err = (err - dys) | 0;
                                    }
                                    y--;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside1;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y--;
                                        err = (err - dxs) | 0;
                                    }
                                    x--;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside1;
                                }
                            }
                            result = 1;
                        }
                        ;
                    } else {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = (x - (right)) | 0;
                            dy = ((row) - y) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x--;
                                        err = (err - dys) | 0;
                                    }
                                    y++;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside1;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y++;
                                        err = (err - dxs) | 0;
                                    }
                                    x--;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside1;
                                }
                            }
                            result = 1;
                        }
                        ;
                    }
                }
                if (result)
                    break;
            }
            if (right < lim_min)
                return;
            if (right == lim_min) {
                if (vis_func) {
                    (yield* Y.icall((vis_func)(i16(lim_min), i16(row), varg)));
                } else {
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1933, __sl3) : void 0);
                        cptr.st1o(rowp, lim_min, NHM.COULD_SEE);
                    } while (0);
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(row_min, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1934, __sl4) : void 0);
                        if (cptr.ldI16(row_min) > (lim_min))
                            cptr.stI16(row_min, i16((lim_min)));
                    } while (0);
                }
                return;
            }
            if (right <= left_edge) {
                right = left_edge;
                continue;
            }
        }
        if (left_mark > left_edge) {
            for (left = left_mark; left >= left_edge; --left) {
                __lbl_lside2: {
                    if (step.v < 0) {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = (x - (left)) | 0;
                            dy = (y - (row)) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x--;
                                        err = (err - dys) | 0;
                                    }
                                    y--;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside2;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y--;
                                        err = (err - dxs) | 0;
                                    }
                                    x--;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside2;
                                }
                            }
                            result = 1;
                        }
                        ;
                    } else {
                        {
                            let dx;
                            let dy;
                            let k;
                            let err;
                            let x;
                            let y;
                            let dxs;
                            let dys;
                            x = (start_col);
                            y = (start_row);
                            dx = (x - (left)) | 0;
                            dy = ((row) - y) | 0;
                            result = 0;
                            dxs = dx << 1;
                            dys = dy << 1;
                            if (dy > dx) {
                                err = (dxs - dy) | 0;
                                for (k = (dy - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        x--;
                                        err = (err - dys) | 0;
                                    }
                                    y++;
                                    err = (err + dxs) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside2;
                                }
                            } else {
                                err = (dys - dx) | 0;
                                for (k = (dx - 1) | 0; k; k--) {
                                    if (err >= 0) {
                                        y++;
                                        err = (err - dxs) | 0;
                                    }
                                    x--;
                                    err = (err + dys) | 0;
                                    if (!cptr.ld1so(cptr.ldPtro(viz_clear_rows, y, 8), x))
                                        break __lbl_lside2;
                                }
                            }
                            result = 1;
                        }
                        ;
                    }
                }
                if (!result)
                    break;
            }
            left++;
        } else
            left = left_edge;
        if (left <= right) {
            if (((left == right && right == start_col ? 1 : 0) && start_col > 0 ? 1 : 0) && !cptr.ld1so(cptr.ldPtro(viz_clear_rows, row, 8), (start_col - 1) | 0) ? 1 : 0)
                left = (start_col - 1) | 0;
            if (left < lim_min)
                left = lim_min;
            if (vis_func) {
                for (i = left; i <= right; i++)
                    (yield* Y.icall((vis_func)(i16(i), i16(row), varg)));
            } else {
                for (i = left; i <= right; i++)
                    do {
                        (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1974, __sl3) : void 0);
                        cptr.st1o(rowp, i, NHM.COULD_SEE);
                    } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_min, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1975, __sl4) : void 0);
                    if (cptr.ldI16(row_min) > (left))
                        cptr.stI16(row_min, i16((left)));
                } while (0);
                do {
                    (__builtin_expect(BigInt((!(!cptr.eq(row_max, (null))))), 0n) ? __assert_rtn(__sl6, __sl2, 1976, __sl5) : void 0);
                    if (cptr.ldI16(row_max) < (right))
                        cptr.stI16(row_max, i16((right)));
                } while (0);
            }
            if (deeper)
                (yield* left_side(nrow, left, right, limits));
            right = (left - 1) | 0;
        }
    }
}

/** C ref: vision.c:2002 — @param {CInt} srow @param {CInt} scol @param {CPtr} loc_cs_rows @param {CPtr} left_most @param {CPtr} right_most @param {CInt} range @param {CPtr} func @param {CPtr} arg */
function* view_from(srow, scol, loc_cs_rows, left_most, right_most, range, func, arg) {
    let i;
    let rowp;
    let nrow;
    let left;
    let right;
    let limits;
    start_col = scol;
    start_row = srow;
    cs_rows = loc_cs_rows;
    cs_left = left_most;
    cs_right = right_most;
    vis_func = func;
    varg = arg;
    if (cptr.ld1so(cptr.ldPtro(viz_clear_rows, srow, 8), scol)) {
        left = cptr.ldI16o(cptr.decay(left_ptrs[srow]), scol, 2);
        right = cptr.ldI16o(cptr.decay(right_ptrs[srow]), scol, 2);
    } else {
        left = (!scol) ? 0 : (cptr.ld1so(cptr.ldPtro(viz_clear_rows, srow, 8), (scol - 1) | 0) ? cptr.ldI16o(cptr.decay(left_ptrs[srow]), (scol - 1) | 0, 2) : (scol - 1) | 0);
        right = (scol == 79) ? 79 : (cptr.ld1so(cptr.ldPtro(viz_clear_rows, srow, 8), (scol + 1) | 0) ? cptr.ldI16o(cptr.decay(right_ptrs[srow]), (scol + 1) | 0, 2) : (scol + 1) | 0);
    }
    if (range) {
        if (range > NHM.MAX_RADIUS || range < 1 ? 1 : 0)
            (yield* panic(__sl7, range));
        limits = cptr.add((cptr.add(circle_data, cptr.ldI16o(circle_start, range, 2), 2)), 1, 2);
        if (left < ((scol - range) | 0))
            left = (scol - range) | 0;
        if (right > ((scol + range) | 0))
            right = (scol + range) | 0;
    } else
        limits = null;
    if (func) {
        for (i = left; i <= right; i++)
            (yield* Y.icall((func)(i16(i), srow, arg)));
    } else {
        rowp = cptr.ldPtro(cs_rows, srow, 8);
        for (i = left; i <= right; i++)
            do {
                (__builtin_expect(BigInt((!(!cptr.eq(rowp, (null))))), 0n) ? __assert_rtn(__sl8, __sl2, 2066, __sl3) : void 0);
                cptr.st1o(rowp, i, NHM.COULD_SEE);
            } while (0);
        cptr.stI16o(cs_left, srow, i16(left), 2);
        cptr.stI16o(cs_right, srow, i16(right), 2);
    }
    if ((nrow = (srow + 1) | 0) < NHM.ROWNO) {
        step.v = 1;
        if (scol < 79)
            (yield* right_side(nrow, scol, right, limits));
        if (scol)
            (yield* left_side(nrow, left, scol, limits));
    }
    if ((nrow = (srow - 1) | 0) >= 0) {
        step.v = -1;
        if (scol < 79)
            (yield* right_side(nrow, scol, right, limits));
        if (scol)
            (yield* left_side(nrow, left, scol, limits));
    }
}

/** C ref: vision.c:2107 — @param {CInt} scol @param {CInt} srow @param {CInt} range @param {CPtr} func @param {CPtr} arg */
export function* do_clear_area(scol, srow, range, func, arg) {
    if (scol != cptr.ldI16(u) || srow != cptr.ldI16o(u, 2) ? 1 : 0) {
        (yield* view_from(srow, scol, null, null, null, range, func, arg));
    } else {
        let x;
        let y;
        let min_x;
        let max_x;
        let max_y;
        let offset;
        let limits;
        let override_vision;
        override_vision = schar((detecting(func) && ((((cptr.ldI16o((cptr.add(svd, 1856)), 2) || cptr.ldI16((cptr.add(svd, 1856))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1856)) ? 1 : 0)) || (((cptr.ldI16o((cptr.add(svd, 1864)), 2) || cptr.ldI16((cptr.add(svd, 1864))) ? 1 : 0) && on_level(cptr.add(u, 24), cptr.add(svd, 1864)) ? 1 : 0)) ? 1 : 0) ? 1 : 0));
        if (range > NHM.MAX_RADIUS || range < 1 ? 1 : 0)
            (yield* panic(__sl9, range));
        if (cptr.ld1so(gv, 144))
            (yield* vision_recalc(0));
        limits = (cptr.add(circle_data, cptr.ldI16o(circle_start, range, 2), 2));
        if ((max_y = ((srow + range) | 0)) >= NHM.ROWNO)
            max_y = 20;
        if ((y = ((srow - range) | 0)) < 0)
            y = 0;
        for (; y <= max_y; y++) {
            offset = cptr.ldI16o(limits, (((y - srow) | 0) < 0 ? -((y - srow) | 0) : ((y - srow) | 0)), 2);
            if ((min_x = ((scol - offset) | 0)) < 1)
                min_x = 1;
            if ((max_x = ((scol + offset) | 0)) >= NHM.COLNO)
                max_x = 79;
            for (x = min_x; x <= max_x; x++)
                if (((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, 120), y, 8), x) & NHM.COULD_SEE) != 0) || override_vision ? 1 : 0)
                    (yield* Y.icall((func)(i16(x), i16(y), arg)));
        }
    }
}

/** C ref: vision.c:2152 — @param {CPtr} mon @returns {CUInt} */
export function howmonseen(mon) {
    let useemon = schar(canseemon(mon));
    let xraydist = (cptr.ldI32o(u, 1780) < 0) ? -1 : (Math.imul(cptr.ldI32o(u, 1780), cptr.ldI32o(u, 1780)));
    let how_seen = 0;
    if ((((cptr.ldI32o(mon, 200) & 31) | 0 ? worm_known(mon) : (((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, 120), cptr.ldI16o(mon, 30), 8), cptr.ldI16o(mon, 28)) & NHM.IN_SIGHT) != 0) && ((cptr.ld1uo(cptr.ldPtro(cptr.ldPtro(gv, 120), cptr.ldI16o(mon, 30), 8), cptr.ldI16o(mon, 28)) & NHM.COULD_SEE) != 0) ? 1 : 0)) && mon_visible(mon) ? 1 : 0) && !(cptr.ldI32o(mon, 88) & 1) ? 1 : 0)
        how_seen |= NHM.MONSEEN_NORMAL;
    if (useemon && (cptr.ldI32o(mon, 88) & 1) | 0 ? 1 : 0)
        how_seen |= NHM.MONSEEN_SEEINVIS;
    if ((!(cptr.ldI32o(mon, 88) & 1) || (cptr.ldI64o2(u, NHC.SEE_INVIS, 24, 128) || cptr.ldI64o2(u, NHC.SEE_INVIS, 24, 112) ? 1 : 0) ? 1 : 0) && see_with_infrared(mon) ? 1 : 0)
        how_seen |= NHM.MONSEEN_INFRAVIS;
    if (tp_sensemon(mon))
        how_seen |= NHM.MONSEEN_TELEPAT;
    if ((useemon && xraydist > 0 ? 1 : 0) && dist2((cptr.ldI16o((mon), 28)), (cptr.ldI16o((mon), 30)), cptr.ldI16(u), cptr.ldI16o(u, 2)) <= xraydist ? 1 : 0)
        how_seen |= NHM.MONSEEN_XRAYVIS;
    if ((cptr.ldI64o2(u, NHC.DETECT_MONSTERS, 24, 128) || cptr.ldI64o2(u, NHC.DETECT_MONSTERS, 24, 112) ? 1 : 0))
        how_seen |= NHM.MONSEEN_DETECT;
    if (((cptr.ldI64o2(u, NHC.WARN_OF_MON, 24, 128) || cptr.ldI64o2(u, NHC.WARN_OF_MON, 24, 112) ? 1 : 0) && (((cptr.ldU64o(svc, 552) & cptr.ldU64o(cptr.ldPtro((mon), 8), 80)) != 0n || (cptr.ldU64o(svc, 560) & cptr.ldU64o(cptr.ldPtro((mon), 8), 80)) != 0n ? 1 : 0) || (cptr.ldPtro(svc, 568) && (cptr.eq(cptr.ldPtro(svc, 568), cptr.ldPtro((mon), 8))) ? 1 : 0) ? 1 : 0) ? 1 : 0))
        how_seen |= NHM.MONSEEN_WARNMON;
    return how_seen;
}
