// YIELDABLE BUILD — generated by tools/c2js/yieldify.mjs from js/generated/write.js
// Do not edit by hand, and do not score from this directory: the synchronous
// build in js/generated/ is the one the judge runs. Coloured functions here
// are generators; `yield*` marks every call that can reach a keystroke read.
// Generated by tools/c2js — do not edit by hand
// Input: nethack-c/recorder/src/write.c
// Input sha256: 7942dc3bdf0fc2e4fefd0a904c78a598767c0204574f7a207bbced46c4e2bd35
// Transpiler: tools/c2js c2js emit v1+batch

import { schar } from '../cmachine.js';
import * as cptr from '../cptr.js';
import * as NHC from './nhconst.js';
import * as NHM from './nhmacro.js';
import { obj_descr, objects } from './objects.js';
import { There, You, You_cant, Your, impossible, livelog_printf, pline, pline_The } from './pline.js';
import { gu, gy, svb, svp, u } from './decl.js';
import { The, Tobjnam, an, aobjnam, ysimple_name } from './objnam.js';
import { fingers_or_gloves } from './do_wear.js';
import { dropx } from './do.js';
import { getobj, hold_another_object, update_inventory, useup } from './invent.js';
import { mungspaces, strncmpi, strstri, upstart } from './hacklib.js';
import { discover_object, observe_object } from './o_init.js';
import { exercise } from './attrib.js';
import { getlin } from './windows.js';
import { rn2, rng_log_enabled, rng_log_set_caller, rnl } from './rnd.js';
import { bcsign, mksobj } from './mkobj.js';
import { check_unpaid, obfree } from './shk.js';
import { known_spell } from './spell.js';
import { wipeout_text } from './engrave.js';

// string literals (C char* uses decay to CPtr into these static buffers)
const __sl0 = cptr.lit("You can't write such a weird scroll!");
const __sl1 = cptr.lit("need hands to be able to write!");
const __sl2 = cptr.lit("%s from your %s.");
const __sl3 = cptr.lit("slip");
const __sl4 = cptr.lit("write on");
const __sl5 = cptr.lit("book");
const __sl6 = cptr.lit("spellbook");
const __sl7 = cptr.lit("scroll");
const __sl8 = cptr.lit("don't know whether that %s is blank or not.");
const __sl9 = cptr.lit("%s can't create braille text.");
const __sl10 = cptr.lit("That %s is not blank!");
const __sl11 = cptr.lit("What type of %s do you want to write?");
const __sl12 = cptr.lit("scroll ");
const __sl13 = cptr.lit("spellbook ");
const __sl14 = cptr.lit("of ");
const __sl15 = cptr.lit(" armour");
const __sl16 = cptr.lit(" armor ");
const __sl17 = cptr.lit("/Users/noahpeterson/Documents/Projects/teleport-contest-research/original-contest-to-fork/nethack-c/recorder/src/write.c");
const __sl18 = cptr.lit("dowrite");
const __sl19 = cptr.lit("is no such %s!");
const __sl20 = cptr.lit("write that!");
const __sl21 = cptr.lit("It's obscene!");
const __sl22 = cptr.lit("%s to write the Great Yendorian Novel, but %s inspiration.");
const __sl23 = cptr.lit("prepare");
const __sl24 = cptr.lit("try");
const __sl25 = cptr.lit("lack");
const __sl26 = cptr.lit("have too much");
const __sl27 = cptr.lit("%sproduce really %s fan-fiction.");
const __sl28 = cptr.lit("start to ");
const __sl29 = cptr.lit("");
const __sl30 = cptr.lit("lame");
const __sl31 = cptr.lit("awesome");
const __sl32 = cptr.lit("give up on the idea.");
const __sl33 = cptr.lit("tear it up.");
const __sl34 = cptr.lit("No mere dungeon adventurer could write that.");
const __sl35 = cptr.lit("Unfortunately you don't have enough information to go on.");
const __sl36 = cptr.lit("became literate by writing %s");
const __sl37 = cptr.lit("marker is too dry to write that!");
const __sl38 = cptr.lit("marker dries out!");
const __sl39 = cptr.lit("spellbook is left unfinished and your writing fades.");
const __sl40 = cptr.lit("scroll is now useless and disappears!");
const __sl41 = cptr.lit("%s to write that.");
const __sl42 = cptr.lit("fail");
const __sl43 = cptr.lit("don't know how");
const __sl44 = cptr.lit("write in your best handwriting:  \"My Diary\", but it quickly fades.");
const __sl45 = cptr.lit("%s was here!");
const __sl46 = cptr.lit("write \"%s\" and the scroll disappears.");
const __sl47 = cptr.lit("fail to write the scroll correctly and it disappears.");
const __sl48 = cptr.lit("spellbook warps strangely, then turns %s.");
const __sl49 = cptr.lit("Oops!  %s out of your grasp!");
const __sl50 = cptr.lit("%s%s");
const __sl51 = cptr.lit("into ");
const __sl52 = cptr.lit("parchment");
const __sl53 = cptr.lit("vellum");
const __sl54 = cptr.lit("cloth");

/** C ref: write.c:14 — @param {CPtr} otmp @returns {CInt} */
function* cost(otmp) {
    if (cptr.ld1so(otmp, 49) == NHC.SPBOOK_CLASS)
        return (Math.imul(10, cptr.ld1so2(objects, cptr.ldI16o(otmp, 32), 120, 85)));
    switch (cptr.ldI16o(otmp, 32)) {
        case NHC.SCR_MAIL:
        return 2;
        case NHC.SCR_LIGHT:
        case NHC.SCR_GOLD_DETECTION:
        case NHC.SCR_FOOD_DETECTION:
        case NHC.SCR_MAGIC_MAPPING:
        case NHC.SCR_AMNESIA:
        case NHC.SCR_FIRE:
        case NHC.SCR_EARTH:
        return 8;
        case NHC.SCR_DESTROY_ARMOR:
        case NHC.SCR_CREATE_MONSTER:
        case NHC.SCR_PUNISHMENT:
        return 10;
        case NHC.SCR_CONFUSE_MONSTER:
        return 12;
        case NHC.SCR_IDENTIFY:
        return 14;
        case NHC.SCR_ENCHANT_ARMOR:
        case NHC.SCR_REMOVE_CURSE:
        case NHC.SCR_ENCHANT_WEAPON:
        case NHC.SCR_CHARGING:
        return 16;
        case NHC.SCR_SCARE_MONSTER:
        case NHC.SCR_STINKING_CLOUD:
        case NHC.SCR_TAMING:
        case NHC.SCR_TELEPORTATION:
        return 20;
        case NHC.SCR_GENOCIDE:
        return 30;
        case NHC.SCR_BLANK_PAPER:
        default:
        (yield* impossible(__sl0));
    }
    return 1000;
}

/** C ref: write.c:61 — @param {CPtr} obj @returns {CInt} */
function write_ok(obj) {
    if (!obj || (cptr.ld1so(obj, 49) != NHC.SCROLL_CLASS && cptr.ld1so(obj, 49) != NHC.SPBOOK_CLASS ? 1 : 0) ? 1 : 0)
        return NHC.GETOBJ_EXCLUDE;
    if (cptr.ldI16o(obj, 32) == NHC.SCR_BLANK_PAPER || cptr.ldI16o(obj, 32) == NHC.SPE_BLANK_PAPER ? 1 : 0)
        return NHC.GETOBJ_SUGGEST;
    return NHC.GETOBJ_DOWNPLAY;
}

/** C ref: write.c:74 — @param {CPtr} pen @returns {CInt} */
export function* dowrite(pen) {
    let paper;
    let namebuf = [0];
    let nm;
    let bp;
    let new_obj;
    let basecost;
    let actualcost;
    let curseval;
    let qbuf = new Uint8Array(128);
    let first;
    let last;
    let i;
    let deferred;
    let deferralchance;
    let real;
    let by_descr = 0;
    let typeword;
    let spell_knowledge;
    __lbl_found: {
        if (((cptr.ldU64o((cptr.ldPtro(gy, 16)), 72) & 8192n) != 0n)) {
            (yield* You(__sl1));
            return NHM.ECMD_OK;
        } else if (cptr.ldI64o2(u, NHC.GLIB, 24, 128)) {
            (yield* pline(__sl2, (yield* Tobjnam(pen, __sl3)), (yield* fingers_or_gloves(0))));
            (yield* dropx(pen));
            return NHM.ECMD_TIME;
        }
        paper = (yield* getobj(__sl4, write_ok, NHM.GETOBJ_NOFLAGS));
        if (!paper)
            return NHM.ECMD_CANCEL;
        typeword = (cptr.ldI16o(paper, 32) == NHC.SPE_NOVEL) ? __sl5 : ((cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS) ? __sl6 : __sl7);
        if (((cptr.ldI64o2(u, NHC.BLINDED, 24, 128) || cptr.ldI64o2(u, NHC.BLINDED, 24, 112) ? 1 : 0) && !cptr.ldI64o2(u, NHC.BLINDED, 24, 120) ? 1 : 0)) {
            if (!(cptr.ldI32o(paper, 84) & 1)) {
                (yield* You(__sl8, typeword));
                return NHM.ECMD_OK;
            } else if (cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS) {
                (yield* pline(__sl9, upstart((yield* ysimple_name(pen)))));
                return NHM.ECMD_OK;
            }
        }
        (yield* observe_object(paper));
        if (cptr.ldI16o(paper, 32) != NHC.SCR_BLANK_PAPER && cptr.ldI16o(paper, 32) != NHC.SPE_BLANK_PAPER ? 1 : 0) {
            (yield* pline(__sl10, typeword));
            (yield* exercise(NHC.A_WIS, 0));
            return NHM.ECMD_TIME;
        }
        (yield* discover_object(NHC.SCR_BLANK_PAPER, 1, 1, 1));
        void cptr.sprintf(cptr.decay(qbuf), __sl11, typeword);
        (yield* getlin(cptr.decay(qbuf), cptr.decay(namebuf)));
        void (yield* mungspaces(cptr.decay(namebuf)));
        if (cptr.ld1so(cptr.decay(namebuf), 0, 1) == 27 || !cptr.ld1so(cptr.decay(namebuf), 0, 1) ? 1 : 0)
            return NHM.ECMD_TIME;
        nm = cptr.decay(namebuf);
        if (!(yield* strncmpi(nm, __sl12, 7)))
            nm = cptr.add(nm, 7);
        else if (!(yield* strncmpi(nm, __sl13, 10)))
            nm = cptr.add(nm, 10);
        if (!(yield* strncmpi(nm, __sl14, 3)))
            nm = cptr.add(nm, 3);
        if ((bp = (yield* strstri(nm, __sl15))) !== null) {
            cptr.memcpy(bp, __sl16, 7n);
            void (yield* mungspaces(cptr.add(bp, 1)));
        }
        deferred = (real = 0);
        deferralchance = 0;
        first = cptr.ldI32o2(svb, cptr.ld1so(paper, 49), 4, 16);
        last = (cptr.ldI32o2(svb, (cptr.ld1so(paper, 49) + 1) | 0, 4, 16) - 1) | 0;
        for (i = first; i <= last; i++) {
            if (!(cptr.ldPtro(obj_descr, cptr.ldI16((cptr.add(objects, i, 120))), 16)))
                continue;
            if (!(yield* strncmpi(((cptr.ldPtro(obj_descr, cptr.ldI16((cptr.add(objects, i, 120))), 16))), (nm), -1))) {
                if ((cptr.ldI32o2(objects, i, 120, 16) & 1) | 0 || cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS ? 1 : 0) {
                    break __lbl_found;
                } else {
                    real = (deferred = i);
                    break;
                }
            }
            if (!(yield* strncmpi(((cptr.ldPtro2(obj_descr, cptr.ldI16o((cptr.add(objects, i, 120)), 2), 16, 8))), (nm), -1))) {
                by_descr = 1;
                break __lbl_found;
            }
        }
        for (i = first; i <= last; i++) {
            if (((cptr.ldPtro2(objects, i, 120, 8) && !(yield* strncmpi((cptr.ldPtro2(objects, i, 120, 8)), (nm), -1)) ? 1 : 0) && !(real && (cptr.ldI32o2(objects, i, 120, 16) & 1) | 0 ? 1 : 0) ? 1 : 0) && !(rng_log_enabled() ? (rng_log_set_caller(__sl17, 193, __sl18), rn2(++deferralchance)) : rn2(++deferralchance)) ? 1 : 0) {
                deferred = i;
                by_descr = 1;
            }
        }
        if (deferred) {
            i = deferred;
            break __lbl_found;
        }
        (yield* There(__sl19, typeword));
        return NHM.ECMD_TIME;
    }
    if (i == NHC.SCR_BLANK_PAPER || i == NHC.SPE_BLANK_PAPER ? 1 : 0) {
        (yield* You_cant(__sl20));
        (yield* pline(__sl21));
        return NHM.ECMD_TIME;
    } else if (i == NHC.SPE_NOVEL) {
        let fanfic = schar((!(rng_log_enabled() ? (rng_log_set_caller(__sl17, 216, __sl18), rn2(3)) : rn2(3))));
        let tearup = schar((!(rng_log_enabled() ? (rng_log_set_caller(__sl17, 216, __sl18), rn2(3)) : rn2(3))));
        if (!fanfic) {
            (yield* You(__sl22, !tearup ? __sl23 : __sl24, !(cptr.ldI64o2(u, NHC.HALLUC, 24, 128) && !(cptr.ldI64o2(u, NHC.HALLUC_RES, 24, 128) || cptr.ldI64o2(u, NHC.HALLUC_RES, 24, 112) ? 1 : 0) ? 1 : 0) ? __sl25 : __sl26));
        } else {
            (yield* You(__sl27, !tearup ? __sl28 : __sl29, !(cptr.ldI64o2(u, NHC.HALLUC, 24, 128) && !(cptr.ldI64o2(u, NHC.HALLUC_RES, 24, 128) || cptr.ldI64o2(u, NHC.HALLUC_RES, 24, 112) ? 1 : 0) ? 1 : 0) ? __sl30 : __sl31));
        }
        if (!tearup) {
            (yield* You(__sl32));
        } else {
            (yield* You(__sl33));
            (yield* useup(paper));
        }
        return NHM.ECMD_TIME;
    } else if (i == NHC.SPE_BOOK_OF_THE_DEAD) {
        (yield* pline(__sl34));
        return NHM.ECMD_TIME;
    } else if ((by_descr && cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS ? 1 : 0) && !(cptr.ldI32o2(objects, i, 120, 16) & 1) ? 1 : 0) {
        (yield* pline(__sl35));
        return NHM.ECMD_TIME;
    }
    if (!((cptr.stI64o(u, 2016, cptr.ldI64o(u, 2016) + 1n)) - (1n)))
        (yield* livelog_printf(32n, __sl36, (yield* an(typeword))));
    new_obj = (yield* mksobj(i, 0, 0));
    cptr.stI32o(new_obj, 88, ((cptr.ldI32o(paper, 88) & 1) | 0 && (cptr.ldI32o(pen, 88) & 1) | 0 ? 1 : 0) >>> 0);
    (yield* check_unpaid(pen));
    basecost = (yield* cost(new_obj));
    if (cptr.ld1so(pen, 48) < ((basecost / 2) | 0)) {
        (yield* Your(__sl37));
        (yield* obfree(new_obj, null));
        return NHM.ECMD_TIME;
    }
    actualcost = (((rng_log_enabled() ? (rng_log_set_caller(__sl17, 265, __sl18), rn2((basecost / 2) | 0)) : rn2((basecost / 2) | 0)) + ((basecost / 2) | 0)) | 0);
    curseval = (bcsign(pen) + bcsign(paper)) | 0;
    (yield* exercise(NHC.A_WIS, 1));
    if (cptr.ld1so(pen, 48) < actualcost) {
        cptr.st1o(pen, 48, 0);
        (yield* Your(__sl38));
        if (cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS) {
            (yield* pline_The(__sl39));
            (yield* update_inventory());
        } else {
            (yield* pline_The(__sl40));
            (yield* useup(paper));
        }
        (yield* obfree(new_obj, null));
        return NHM.ECMD_TIME;
    }
    cptr.st1o(pen, 48, cptr.ld1so(pen, 48) - actualcost);
    if (cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS) {
        spell_knowledge = known_spell(cptr.ldI16o(new_obj, 32));
    } else {
        spell_knowledge = NHC.spe_Unknown;
    }
    if (((!(cptr.ldI32o2(objects, cptr.ldI16o(new_obj, 32), 120, 16) & 1) && !(by_descr && (cptr.ldI32o2(objects, cptr.ldI16o(new_obj, 32), 120, 28) & 1) | 0 ? 1 : 0) ? 1 : 0) && spell_knowledge != NHC.spe_Fresh ? 1 : 0) && (rng_log_enabled() ? (rng_log_set_caller(__sl17, 321, __sl18), rnl((((cptr.ldI16o(gu, 216) == NHC.PM_WIZARD) && cptr.ld1so(paper, 49) != NHC.SPBOOK_CLASS ? 1 : 0) || spell_knowledge == NHC.spe_GoingStale ? 1 : 0) ? 5 : 15)) : rnl((((cptr.ldI16o(gu, 216) == NHC.PM_WIZARD) && cptr.ld1so(paper, 49) != NHC.SPBOOK_CLASS ? 1 : 0) || spell_knowledge == NHC.spe_GoingStale ? 1 : 0) ? 5 : 15)) ? 1 : 0) {
        (yield* You(__sl41, by_descr ? __sl42 : __sl43));
        if (cptr.ld1so(paper, 49) == NHC.SPBOOK_CLASS) {
            (yield* You(__sl44));
            (yield* update_inventory());
        } else {
            if (by_descr) {
                void cptr.strcpy(cptr.decay(namebuf), (cptr.ldPtro2(obj_descr, cptr.ldI16o((cptr.add(objects, cptr.ldI16o(new_obj, 32), 120)), 2), 16, 8)));
                wipeout_text(cptr.decay(namebuf), (((36 - cptr.ldI32o(u, 48)) | 0) / 6) | 0, 0);
            } else
                void cptr.sprintf(cptr.decay(namebuf), __sl45, svp);
            (yield* You(__sl46, cptr.decay(namebuf)));
            (yield* useup(paper));
        }
        (yield* obfree(new_obj, null));
        return NHM.ECMD_TIME;
    }
    if (((cptr.ldI64o2(u, NHC.BLINDED, 24, 128) || cptr.ldI64o2(u, NHC.BLINDED, 24, 112) ? 1 : 0) && !cptr.ldI64o2(u, NHC.BLINDED, 24, 120) ? 1 : 0) && (rng_log_enabled() ? (rng_log_set_caller(__sl17, 342, __sl18), rnl(3)) : rnl(3)) ? 1 : 0) {
        (yield* You(__sl47));
        (yield* useup(paper));
        (yield* obfree(new_obj, null));
        return NHM.ECMD_TIME;
    }
    (yield* useup(paper));
    if (cptr.ld1so(new_obj, 49) == NHC.SPBOOK_CLASS) {
        (yield* pline_The(__sl48, (yield* new_book_description(cptr.ldI16o(new_obj, 32), cptr.decay(namebuf)))));
    }
    cptr.stI32o(new_obj, 60, (curseval > 0) >>> 0);
    cptr.stI32o(new_obj, 56, (curseval < 0) >>> 0);
    if (cptr.ldI16o(new_obj, 32) == NHC.SCR_MAIL)
        cptr.st1o(new_obj, 48, 2);
    cptr.stI32o(new_obj, 84, 0);
    if ((cptr.ldI32o2(objects, cptr.ldI16o(new_obj, 32), 120, 16) & 1) | 0 || by_descr ? 1 : 0)
        (yield* observe_object(new_obj));
    new_obj = (yield* hold_another_object(new_obj, __sl49, (yield* The((yield* aobjnam(new_obj, __sl3)))), null));
    (void (new_obj));
    return NHM.ECMD_TIME;
}

const __static_new_book_description_compositions = cptr.alloc(4 * 8);
cptr.stPtro(__static_new_book_description_compositions, 0, __sl52);
cptr.stPtro(__static_new_book_description_compositions, 8, __sl53);
cptr.stPtro(__static_new_book_description_compositions, 16, __sl54);
cptr.stPtro(__static_new_book_description_compositions, 24, null); /** C ref: write.c:399 — char *[4] (function-static) */

/** C ref: write.c:395 — @param {CInt} booktype @param {CPtr} outbuf @returns {CPtr} */
function* new_book_description(booktype, outbuf) {
    let descr;
    let comp_p;
    descr = (cptr.ldPtro2(obj_descr, cptr.ldI16o((cptr.add(objects, booktype, 120)), 2), 16, 8));
    for (comp_p = __static_new_book_description_compositions; cptr.ldPtr(comp_p); comp_p = cptr.add(comp_p, 1, 8))
        if (!(yield* strncmpi((descr), (cptr.ldPtr(comp_p)), -1)))
            break;
    void cptr.sprintf(outbuf, __sl50, cptr.ldPtr(comp_p) ? __sl51 : __sl29, descr);
    return outbuf;
}
