// extversion.js — Extended compile/runtime version disclosure.
// C refs: version.c:doextversion(), mdlib.c:do_runtime_info().
//
// Keep this separate from version.js: const.js imports that build-metadata
// leaf, while this interactive command depends on display and window layers.

import { game } from './gstate.js';
import { bot, docrtRecalc, flush_screen } from './display.js';
import { rn2 } from './rng.js';
import { showTextPages } from './windows.js';

const VERSION_PAGE_1 = [
    'MacOS NetHack Version 5.0.0 - last build May  2 2026 12:00:00.',
    '',
    'Options compiled into this edition:',
    '    I32LP64 data model, color, data file compression, deferred handling of',
    '    hangup signal, insurance files for recovering from crashes, live logging',
    '    support, log file, extended log file, errors and warnings log file, mail',
    '    daemon, news file, internal pager used for viewing help files, pattern',
    '    matching via posixregex, pseudo random numbers generated by ISAAC64,',
    '    strong PRNG seed from /dev/random, restore saved games via menu, screen',
    '    clipping, shell command, traditional status display, status via',
    '    windowport with highlighting, suspend command, terminal info library,',
    '    system configuration at run-time, show stack trace on error, launch',
    '    browser to report issues, save and bones files accepted from version',
    '    5.0.0 only, and basic NetHack features.',
    '',
    'Supported windowing system:',
    '    "tty" (traditional text with optional line-drawing).',
    '',
    'Supported soundlib:',
    '    "nosound".',
    '',
    "NetHack 5.0.* uses the 'Lua' interpreter to process some data:",
    '    Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio',
    '--More--',
];

const VERSION_PAGE_2 = [
    '    "Permission is hereby granted, free of charge, to any person obtaining',
    '     a copy of this software and associated documentation files (the',
    '     "Software"), to deal in the Software without restriction including',
    '     without limitation the rights to use, copy, modify, merge, publish,',
    '     distribute, sublicense, and/or sell copies of the Software, and to',
    '     permit persons to whom the Software is furnished to do so, subject to',
    '     the following conditions:',
    '     The above copyright notice and this permission notice shall be',
    '     included in all copies or substantial portions of the Software."',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '--More--',
];

export async function doextversion() {
    // version.c substitutes :LUAVERSION:/:LUACOPYRIGHT: lazily. The first
    // get_lua_version() opens a sandboxed Lua state, whose nhlib setup owns
    // the same two alignment-shuffle calls observed by the C runtime-info
    // witness. Later disclosures reuse the populated runtime strings.
    if (!game._runtimeVersionInfoInitialized) {
        rn2(3);
        rn2(2);
        game._runtimeVersionInfoInitialized = true;
    }

    await showTextPages([
        { lines: VERSION_PAGE_1, cursor: [8, 23] },
        { lines: VERSION_PAGE_2, cursor: [8, 23] },
    ], { validKeys: [27, 32, 10, 13] });

    // Destroying NHW_TEXT restores the live map rather than leaving the
    // editor or either text page in the tty backing buffer.
    game._pending_message = '';
    game._retained_message = '';
    await docrtRecalc();
    await bot();
    await flush_screen(1);
    game.context.move = 0;
}
