// castle.js — AUTO-GENERATED from
// nethack-c/upstream/dat/castle.lua.  Do NOT edit by hand.
// Regenerate via tools/c2js/build-dat-bundle.mjs.
// Category: jsmodule.
export default async function({ des, selection, shuffle }) {
  await des.level_init({ style: "mazegrid", bg: "-" });
  await des.level_flags("mazelevel", "noteleport", "noflipy");
  await des.map("}}}}}}}}}.............................................}}}}}}}}}\n}-------}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}-------}\n}|.....|-----------------------------------------------|.....|}\n}|.....+...............................................+.....|}\n}-------------------------------+-----------------------------}\n}}}}}}|........|..........+...........|.......S.S.......|}}}}}}\n.....}|........|..........|...........|.......|.|.......|}.....\n.....}|........------------...........---------S---------}.....\n.....}|...{....+..........+.........\\.S.................+......\n.....}|........------------...........---------S---------}.....\n.....}|........|..........|...........|.......|.|.......|}.....\n}}}}}}|........|..........+...........|.......S.S.......|}}}}}}\n}-------------------------------+-----------------------------}\n}|.....+...............................................+.....|}\n}|.....|-----------------------------------------------|.....|}\n}-------}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}-------}\n}}}}}}}}}.............................................}}}}}}}}}\n");
  let object = ["[", ")", "*", "%"];
  shuffle(object);
  let place = selection.new();
  place.set(4, 2);
  place.set(58, 2);
  place.set(4, 14);
  place.set(58, 14);
  let monster = ["L", "N", "E", "H", "M", "O", "R", "T", "X", "Z"];
  shuffle(monster);
  await des.teleport_region({ region: [1, 0, 10, 20], region_islev: 1, exclude: [1, 1, 61, 15], dir: "down" });
  await des.teleport_region({ region: [69, 0, 79, 20], region_islev: 1, exclude: [1, 1, 61, 15], dir: "up" });
  await des.levregion({ region: [1, 0, 10, 20], region_islev: 1, exclude: [0, 0, 62, 16], type: "stair-up" });
  await des.feature("fountain", 10, 8);
  await des.door("closed", 7, 3);
  await des.door("closed", 55, 3);
  await des.door("locked", 32, 4);
  await des.door("locked", 26, 5);
  await des.door("locked", 46, 5);
  await des.door("locked", 48, 5);
  await des.door("locked", 47, 7);
  await des.door("closed", 15, 8);
  await des.door("closed", 26, 8);
  await des.door("locked", 38, 8);
  await des.door("locked", 56, 8);
  await des.door("locked", 47, 9);
  await des.door("locked", 26, 11);
  await des.door("locked", 46, 11);
  await des.door("locked", 48, 11);
  await des.door("locked", 32, 12);
  await des.door("closed", 7, 13);
  await des.door("closed", 55, 13);
  await des.drawbridge({ dir: "east", state: "closed", x: 5, y: 8 });
  await des.object(object[0], 39, 5);
  await des.object(object[0], 40, 5);
  await des.object(object[0], 41, 5);
  await des.object(object[0], 42, 5);
  await des.object(object[0], 43, 5);
  await des.object(object[0], 44, 5);
  await des.object(object[0], 45, 5);
  await des.object(object[0], 39, 6);
  await des.object(object[0], 40, 6);
  await des.object(object[0], 41, 6);
  await des.object(object[0], 42, 6);
  await des.object(object[0], 43, 6);
  await des.object(object[0], 44, 6);
  await des.object(object[0], 45, 6);
  await des.object(object[1], 49, 5);
  await des.object(object[1], 50, 5);
  await des.object(object[1], 51, 5);
  await des.object(object[1], 52, 5);
  await des.object(object[1], 53, 5);
  await des.object(object[1], 54, 5);
  await des.object(object[1], 55, 5);
  await des.object(object[1], 49, 6);
  await des.object(object[1], 50, 6);
  await des.object(object[1], 51, 6);
  await des.object(object[1], 52, 6);
  await des.object(object[1], 53, 6);
  await des.object(object[1], 54, 6);
  await des.object(object[1], 55, 6);
  await des.object(object[2], 39, 10);
  await des.object(object[2], 40, 10);
  await des.object(object[2], 41, 10);
  await des.object(object[2], 42, 10);
  await des.object(object[2], 43, 10);
  await des.object(object[2], 44, 10);
  await des.object(object[2], 45, 10);
  await des.object(object[2], 39, 11);
  await des.object(object[2], 40, 11);
  await des.object(object[2], 41, 11);
  await des.object(object[2], 42, 11);
  await des.object(object[2], 43, 11);
  await des.object(object[2], 44, 11);
  await des.object(object[2], 45, 11);
  await des.object(object[3], 49, 10);
  await des.object(object[3], 50, 10);
  await des.object(object[3], 51, 10);
  await des.object(object[3], 52, 10);
  await des.object(object[3], 53, 10);
  await des.object(object[3], 54, 10);
  await des.object(object[3], 55, 10);
  await des.object(object[3], 49, 11);
  await des.object(object[3], 50, 11);
  await des.object(object[3], 51, 11);
  await des.object(object[3], 52, 11);
  await des.object(object[3], 53, 11);
  await des.object(object[3], 54, 11);
  await des.object(object[3], 55, 11);
  let loc = place.rndcoord(1);
  await des.object({ id: "chest", trapped: 0, locked: 1, coord: loc, contents: (async () => {
      await des.object("wishing");
      await des.object("potion of gain level");
    }) });
  await des.engraving({ coord: loc, type: "burn", text: "Elbereth" });
  await des.object({ id: "scroll of scare monster", coord: loc, buc: "cursed" });
  await des.object("chest", 37, 8);
  await des.trap("trap door", 40, 8);
  await des.trap("trap door", 44, 8);
  await des.trap("trap door", 48, 8);
  await des.trap("trap door", 52, 8);
  await des.trap("trap door", 55, 8);
  await des.monster("soldier", 8, 6);
  await des.monster("soldier", 9, 5);
  await des.monster("soldier", 11, 5);
  await des.monster("soldier", 12, 6);
  await des.monster("soldier", 8, 10);
  await des.monster("soldier", 9, 11);
  await des.monster("soldier", 11, 11);
  await des.monster("soldier", 12, 10);
  await des.monster("lieutenant", 9, 8);
  await des.monster("soldier", 3, 2);
  await des.monster("soldier", 5, 2);
  await des.monster("soldier", 57, 2);
  await des.monster("soldier", 59, 2);
  await des.monster("soldier", 3, 14);
  await des.monster("soldier", 5, 14);
  await des.monster("soldier", 57, 14);
  await des.monster("soldier", 59, 14);
  await des.monster("D", 47, 5);
  await des.monster("D", 47, 6);
  await des.monster("D", 47, 10);
  await des.monster("D", 47, 11);
  await des.monster("giant eel", 5, 7);
  await des.monster("giant eel", 5, 9);
  await des.monster("giant eel", 57, 7);
  await des.monster("giant eel", 57, 9);
  await des.monster("shark", 5, 0);
  await des.monster("shark", 5, 16);
  await des.monster("shark", 57, 0);
  await des.monster("shark", 57, 16);
  await des.monster(monster[9], 27, 5);
  await des.monster(monster[0], 30, 5);
  await des.monster(monster[1], 33, 5);
  await des.monster(monster[2], 36, 5);
  await des.monster(monster[3], 28, 6);
  await des.monster(monster[4], 31, 6);
  await des.monster(monster[5], 34, 6);
  await des.monster(monster[6], 37, 6);
  await des.monster(monster[7], 27, 7);
  await des.monster(monster[8], 30, 7);
  await des.monster(monster[9], 33, 7);
  await des.monster(monster[0], 36, 7);
  await des.monster(monster[1], 28, 8);
  await des.monster(monster[2], 31, 8);
  await des.monster(monster[3], 34, 8);
  await des.monster(monster[4], 27, 9);
  await des.monster(monster[5], 30, 9);
  await des.monster(monster[6], 33, 9);
  await des.monster(monster[7], 36, 9);
  await des.monster(monster[8], 28, 10);
  await des.monster(monster[9], 31, 10);
  await des.monster(monster[0], 34, 10);
  await des.monster(monster[1], 37, 10);
  await des.monster(monster[2], 27, 11);
  await des.monster(monster[3], 30, 11);
  await des.monster(monster[4], 33, 11);
  await des.monster(monster[5], 36, 11);
  await des.mazewalk(0, 10, "west");
  await des.mazewalk(62, 6, "east");
  await des.non_diggable(selection.area(0, 0, 62, 16));
  await des.region(selection.area(0, 0, 62, 16), "unlit");
  await des.region(selection.area(0, 5, 5, 11), "lit");
  await des.region(selection.area(57, 5, 62, 11), "lit");
  await des.region({ region: [27, 5, 37, 11], lit: 1, type: "throne", filled: 2 });
  await des.region(selection.area(7, 5, 14, 11), "lit");
  await des.region(selection.area(39, 5, 45, 6), "lit");
  await des.region(selection.area(39, 10, 45, 11), "lit");
  await des.region(selection.area(49, 5, 55, 6), "lit");
  await des.region(selection.area(49, 10, 55, 11), "lit");
  await des.region(selection.area(2, 2, 6, 3), "lit");
  await des.region(selection.area(56, 2, 60, 3), "lit");
  await des.region(selection.area(2, 13, 6, 14), "lit");
  await des.region(selection.area(56, 13, 60, 14), "lit");
  await des.region({ region: [16, 5, 25, 6], lit: 1, type: "barracks", filled: 1 });
  await des.region({ region: [16, 10, 25, 11], lit: 1, type: "barracks", filled: 1 });
  await des.region(selection.area(8, 3, 54, 3), "unlit");
  await des.region(selection.area(8, 13, 54, 13), "unlit");
  await des.region(selection.area(16, 8, 25, 8), "unlit");
  await des.region(selection.area(39, 8, 55, 8), "unlit");
  await des.region(selection.area(47, 5, 47, 6), "unlit");
  await des.region(selection.area(47, 10, 47, 11), "unlit");
}
