// minend-3.js — AUTO-GENERATED from
// nethack-c/upstream/dat/minend-3.lua.  Do NOT edit by hand.
// Regenerate via tools/c2js/build-dat-bundle.mjs.
// Category: jsmodule.
export default async function({ des, selection, shuffle }) {
  await des.level_init({ style: "solidfill", fg: "-" });
  await des.level_flags("mazelevel", "nommap");
  await des.map({ halign: "center", valign: "bottom", map: " - - - - - - - - - - -- -- - - . - - - - - - - - - -- - - -- - - - - . - - |\n------...---------.-----------...-----.-------.-------     ----------------|\n - - - - - - - - - - - . - - - . - - - - - - - - - - -- - -- - . - - - - - |\n------------.---------...-------------------------.---   ------------------|\n - - - - - - - - - - . . - - --- - . - - - - - - - - -- -- - - - - |.....| |\n--.---------------.......------------------------------- ----------|.....S-|\n - - - - |.. ..| - ....... . - - - - |.........| - - - --- - - - - |.....| |\n----.----|.....|------.......--------|.........|--------------.------------|\n - - - - |..{..| - - -.... . --- - -.S.........S - - - - - - - - - - - - - |\n---------|.....|--.---...------------|.........|---------------------------|\n - - - - |.. ..| - - - . - - - - - - |.........| - --- . - - - - - - - - - |\n----------------------...-------.---------------------...------------------|\n---..| - - - - - - - - . --- - - - - - - - - - - - - - . - - --- - - --- - |\n-.S..|----.-------.------- ---------.-----------------...----- -----.-------\n---..| - - - - - - - -- - - -- . - - - - - . - - - . - . - - -- -- - - - -- \n-.S..|--------.---.---       -...---------------...{.---------   ---------  \n--|. - - - - - - - -- - - - -- . - - - --- - - - . . - - - - -- - - - - - - \n" });
  let place = [[1, 15], [68, 6], [1, 13]];
  await shuffle(place);
  await des.non_diggable(selection.area(67, 3, 73, 7));
  await des.non_diggable(selection.area(0, 12, 2, 16));
  await des.feature("fountain", [12, 8]);
  await des.feature("fountain", [51, 15]);
  await des.region(selection.area(0, 0, 75, 16), "unlit");
  await des.region(selection.area(38, 6, 46, 10), "lit");
  await des.door("closed", 37, 8);
  await des.door("closed", 47, 8);
  await des.door("closed", 73, 5);
  await des.door("closed", 2, 15);
  await des.mazewalk({ x: 36, y: 8, dir: "west", stocked: false });
  await des.stair("up", 42, 8);
  await des.wallify();
  await des.object("diamond");
  await des.object("*");
  await des.object("diamond");
  await des.object("*");
  await des.object("emerald");
  await des.object("*");
  await des.object("emerald");
  await des.object("*");
  await des.object("emerald");
  await des.object("*");
  await des.object("ruby");
  await des.object("*");
  await des.object("ruby");
  await des.object("amethyst");
  await des.object("*");
  await des.object("amethyst");
  await des.object({ id: "luckstone", coord: place[1], buc: "not-cursed", achievement: 1 });
  await des.object("flint", place[0]);
  await des.object("?");
  await des.object("?");
  await des.object("?");
  await des.object("?");
  await des.object("?");
  await des.object("+");
  await des.object("+");
  await des.object("+");
  await des.object("+");
  await des.object();
  await des.object();
  await des.object();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap("level teleport", place[1]);
  await des.trap("level teleport", place[0]);
  await des.monster("M");
  await des.monster("M");
  await des.monster("M");
  await des.monster("M");
  await des.monster("M");
  await des.monster("ettin mummy");
  await des.monster("V");
  await des.monster("Z");
  await des.monster("Z");
  await des.monster("Z");
  await des.monster("Z");
  await des.monster("Z");
  await des.monster("V");
  await des.monster("e");
  await des.monster("e");
  await des.monster("e");
  await des.monster("e");
}
