// minend-1.js — AUTO-GENERATED from
// nethack-c/upstream/dat/minend-1.lua.  Do NOT edit by hand.
// Regenerate via tools/c2js/build-dat-bundle.mjs.
// Category: jsmodule.
export default async function({ des, selection, shuffle }) {
  await des.level_init({ style: "solidfill", fg: " " });
  await des.level_flags("mazelevel");
  await des.map("------------------------------------------------------------------   ------\n|                        |.......|     |.......-...|       |.....|.       |\n|    ---------        ----.......-------...........|       ---...-S-      |\n|    |.......|        |..........................-S-      --.......|      |\n|    |......-------   ---........................|.       |.......--      |\n|    |..--........-----..........................|.       -.-..----       |\n|    --..--.-----........-.....................---        --..--          |\n|     --..--..| -----------..................---.----------..--           |\n|      |...--.|    |..S...S..............---................--            |\n|     ----..-----  ------------........--- ------------...---             |\n|     |.........--            ----------              ---...-- -----      |\n|    --.....---..--                           --------  --...---...--     |\n| ----..-..-- --..---------------------      --......--  ---........|     |\n|--....-----   --..-..................---    |........|    |.......--     |\n|.......|       --......................S..  --......--    ---..----      |\n|--.--.--        ----.................---     ------..------...--         |\n| |....S..          |...............-..|         ..S...........|          |\n--------            --------------------           ------------------------\n");
  let place = [[8, 16], [13, 7], [21, 8], [41, 14], [50, 4], [50, 16], [66, 1]];
  shuffle(place);
  await des.region({ region: [26, 1, 32, 1], lit: 0, type: "ordinary", irregular: 1, arrival_room: true });
  await des.region(selection.area(20, 8, 21, 8), "unlit");
  await des.region(selection.area(23, 8, 25, 8), "unlit");
  await des.door("locked", 7, 16);
  await des.door("locked", 22, 8);
  await des.door("locked", 26, 8);
  await des.door("locked", 40, 14);
  await des.door("locked", 50, 3);
  await des.door("locked", 51, 16);
  await des.door("locked", 66, 2);
  await des.stair("up", 36, 4);
  await des.non_diggable(selection.area(0, 0, 74, 17));
  await des.object("diamond", place[6]);
  await des.object("emerald", place[6]);
  await des.object("worthless piece of violet glass", place[6]);
  await des.monster({ class: "m", coord: place[6], appear_as: "obj:luckstone" });
  await des.object("worthless piece of white glass", place[0]);
  await des.object("emerald", place[0]);
  await des.object("amethyst", place[0]);
  await des.monster({ class: "m", coord: place[0], appear_as: "obj:loadstone" });
  await des.object("diamond", place[1]);
  await des.object("worthless piece of green glass", place[1]);
  await des.object("amethyst", place[1]);
  await des.monster({ class: "m", coord: place[1], appear_as: "obj:flint" });
  await des.object("worthless piece of white glass", place[2]);
  await des.object("emerald", place[2]);
  await des.object("worthless piece of violet glass", place[2]);
  await des.monster({ class: "m", coord: place[2], appear_as: "obj:touchstone" });
  await des.object("worthless piece of red glass", place[3]);
  await des.object("ruby", place[3]);
  await des.object("loadstone", place[3]);
  await des.object("ruby", place[4]);
  await des.object("worthless piece of red glass", place[4]);
  await des.object({ id: "luckstone", coord: place[4], buc: "not-cursed", achievement: 1 });
  await des.object("*");
  await des.object("*");
  await des.object("*");
  await des.object("*");
  await des.object("*");
  await des.object("*");
  await des.object("*");
  await des.object("(");
  await des.object("(");
  await des.object();
  await des.object();
  await des.object();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.trap();
  await des.monster("gnome king");
  await des.monster("gnome lord");
  await des.monster("gnome lord");
  await des.monster("gnome lord");
  await des.monster("gnomish wizard");
  await des.monster("gnomish wizard");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("gnome");
  await des.monster("hobbit");
  await des.monster("hobbit");
  await des.monster("dwarf");
  await des.monster("dwarf");
  await des.monster("dwarf");
  await des.monster("h");
}
