// Tou-goal.js — AUTO-GENERATED from
// nethack-c/upstream/dat/Tou-goal.lua.  Do NOT edit by hand.
// Regenerate via tools/c2js/build-dat-bundle.mjs.
// Category: jsmodule.
export default async function({ des, selection }) {
  await des.level_init({ style: "solidfill", fg: " " });
  await des.level_flags("mazelevel");
  await des.map("----------------------------------------------------------------------------\n|.........|.........|..........|..| |.................|........|........|..|\n|.........|.........|..........|..| |....--------.....|........|........|..|\n|------S--|--+-----------+------..| |....|......|.....|........|........|..|\n|.........|.......................| |....|......+.....--+-------------+--..|\n|.........|.......................| |....|......|..........................|\n|-S-----S-|......----------.......| |....|......|..........................|\n|..|..|...|......|........|.......| |....-----------.........----..........|\n|..+..+...|......|........|.......| |....|.........|.........|}}|..........|\n|..|..|...|......+........|.......| |....|.........+.........|}}|..........|\n|..|..|...|......|........|.......S.S....|.........|.........----..........|\n|---..----|......|........|.......| |....|.........|.......................|\n|.........+......|+F-+F-+F|.......| |....-----------.......................|\n|---..----|......|..|..|..|.......| |......................--------------..|\n|..|..|...|......--F-F--F--.......| |......................+............|..|\n|..+..+...|.......................| |--.---...-----+-----..|............|..|\n|--|..----|--+-----------+------..| |.....|...|.........|..|------------|..|\n|..+..+...|.........|..........|..| |.....|...|.........|..+............|..|\n|..|..|...|.........|..........|..| |.....|...|.........|..|............|..|\n----------------------------------------------------------------------------\n");
  await des.region(selection.area(0, 0, 75, 19), "lit");
  await des.region(selection.area(1, 1, 9, 2), "lit");
  await des.region({ region: [1, 4, 9, 5], lit: 1, type: "barracks", filled: 1 });
  await des.region(selection.area(1, 7, 2, 10), "unlit");
  await des.region(selection.area(7, 7, 9, 10), "unlit");
  await des.region(selection.area(1, 14, 2, 15), "unlit");
  await des.region(selection.area(7, 14, 9, 15), "unlit");
  await des.region(selection.area(1, 17, 2, 18), "unlit");
  await des.region(selection.area(7, 17, 9, 18), "unlit");
  await des.region({ region: [11, 1, 19, 2], lit: 0, type: "barracks", filled: 1 });
  await des.region(selection.area(21, 1, 30, 2), "unlit");
  await des.region({ region: [11, 17, 19, 18], lit: 0, type: "barracks", filled: 1 });
  await des.region(selection.area(21, 17, 30, 18), "unlit");
  await des.region(selection.area(18, 7, 25, 11), "lit");
  await des.region(selection.area(18, 13, 19, 13), "unlit");
  await des.region(selection.area(21, 13, 22, 13), "unlit");
  await des.region(selection.area(24, 13, 25, 13), "unlit");
  await des.region(selection.area(42, 3, 47, 6), "unlit");
  await des.region(selection.area(42, 8, 50, 11), "unlit");
  await des.region({ region: [37, 16, 41, 18], lit: 0, type: "morgue", filled: 1 });
  await des.region(selection.area(47, 16, 55, 18), "unlit");
  await des.region(selection.area(55, 1, 62, 3), "unlit");
  await des.region(selection.area(64, 1, 71, 3), "unlit");
  await des.region({ region: [60, 14, 71, 15], lit: 1, type: "shop", filled: 1 });
  await des.region({ region: [60, 17, 71, 18], lit: 1, type: "shop", filled: 1 });
  await des.non_diggable(selection.area(0, 0, 75, 19));
  await des.stair("up", 70, 8);
  await des.door("locked", 7, 3);
  await des.door("locked", 2, 6);
  await des.door("locked", 8, 6);
  await des.door("closed", 3, 8);
  await des.door("closed", 6, 8);
  await des.door("open", 10, 12);
  await des.door("closed", 3, 15);
  await des.door("closed", 6, 15);
  await des.door("closed", 3, 17);
  await des.door("closed", 6, 17);
  await des.door("closed", 13, 3);
  await des.door("random", 25, 3);
  await des.door("closed", 13, 16);
  await des.door("random", 25, 16);
  await des.door("locked", 17, 9);
  await des.door("locked", 18, 12);
  await des.door("locked", 21, 12);
  await des.door("locked", 24, 12);
  await des.door("locked", 34, 10);
  await des.door("locked", 36, 10);
  await des.door("random", 48, 4);
  await des.door("random", 56, 4);
  await des.door("random", 70, 4);
  await des.door("random", 51, 9);
  await des.door("random", 51, 15);
  await des.door("open", 59, 14);
  await des.door("open", 59, 17);
  await des.object({ id: "credit card", x: 4, y: 1, buc: "blessed", spe: 0, name: "The Platinum Yendorian Express Card" });
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  await des.object();
  let validtraps = selection.area(0, 0, 75, 19).filter_mapchar(".");
  validtraps = validtraps - selection.area(60, 14, 71, 18);
  {
      const __hi = 6;
      const __step = 1;
      for (let i = 1; __step > 0 ? i <= __hi : i >= __hi; i += __step) {
        await des.trap(validtraps.rndcoord(1));
      }
    }
  await des.monster({ id: "Master of Thieves", x: 4, y: 1, peaceful: 0 });
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("giant spider");
  await des.monster("s");
  await des.monster("s");
  await des.monster("succubus", 2, 8);
  await des.monster("succubus", 8, 8);
  await des.monster("incubus", 2, 14);
  await des.monster("incubus", 8, 14);
  await des.monster("incubus", 2, 17);
  await des.monster("incubus", 8, 17);
  await des.monster({ id: "Kop Kaptain", x: 24, y: 9, peaceful: 0 });
  await des.monster({ id: "Kop Lieutenant", x: 20, y: 9, peaceful: 0 });
  await des.monster({ id: "Kop Lieutenant", x: 22, y: 11, peaceful: 0 });
  await des.monster({ id: "Kop Lieutenant", x: 22, y: 7, peaceful: 0 });
  await des.monster({ id: "Keystone Kop", x: 19, y: 7, peaceful: 0 });
  await des.monster({ id: "Keystone Kop", x: 19, y: 8, peaceful: 0 });
  await des.monster({ id: "Keystone Kop", x: 22, y: 9, peaceful: 0 });
  await des.monster({ id: "Keystone Kop", x: 24, y: 11, peaceful: 0 });
  await des.monster({ id: "Keystone Kop", x: 19, y: 11, peaceful: 0 });
  await des.monster("prisoner", 19, 13);
  await des.monster("prisoner", 21, 13);
  await des.monster("prisoner", 24, 13);
  await des.monster({ id: "watchman", x: 33, y: 10, peaceful: 0 });
  await des.wallify();
}
