// nhlib-fns.mjs — ports of 7 functions from dat/nhlib.lua.
//
// GENERATED by tools/lua-port-gen/lua2des.mjs. Regenerate rather than
// hand-edit; each function is re-checked against the .lua by
// test/lua-port-scripts.test.mjs on every run — call stream, return
// value, and the rn2() draws it spends.
//
// WHY THESE ARE NOT LEVEL SCRIPT PORTS. nhlib.lua is loaded into every
// lua_State nhl_init() builds and nhcore.lua into gl.luacore, so their
// functions are in scope for every script and callable from C. A port of
// one is a function, not a chunk; js/lua-js/scripts/nhlib.mjs and
// js/lua-js/scripts/nhcore.mjs are the chunks, and they install these.
//
// The api arrives as a parameter rather than a destructured signature
// because each function has the .lua's own parameters to carry too.

/** @param {object} api */
export function hell_tweaks(api, protected_area) {
    const { des, selection, percent, math, u, nhc } = api;

    const liquid = 'L';
    const ground = '.';
    const n_prot = selection.numpoints(protected_area);
    const prot = selection.negate(protected_area);

    // random pools
    if (percent(20 + u.depth)) {
        let pools = selection.new();
        const maxpools = 5 + math.random(u.depth);
        for (let i = 1; i <= maxpools; i++) {
            selection.set(pools);
        }
        pools = selection.bor(pools, selection.grow(selection.set(selection.new()), 'west'));
        pools = selection.bor(pools, selection.grow(selection.set(selection.new()), 'north'));
        pools = selection.bor(pools, selection.grow(selection.set(selection.new()), 'random'));

        pools = selection.band(pools, prot);

        if (percent(80)) {
            const poolground = selection.band(selection.grow(selection.clone(pools), 'all'), prot);
            const pval = math.random(1, 8) * 10;
            des.terrain(selection.percentage(poolground, pval), ground);
        }
        des.terrain(pools, liquid);
    }

    // river
    if (percent(50)) {
        let allrivers = selection.new();
        const reqpts = ((nhc.COLNO * nhc.ROWNO) - n_prot) / 12;
        // # of lava pools required
        let rpts = 0;
        let rivertries = 0;

        do {
            const floor = selection.match(ground);
            const a = selection.rndcoord(floor);
            const b = selection.rndcoord(floor);
            let lavariver = selection.randline(selection.new(), a.x, a.y, b.x, b.y, 10);

            if (percent(50)) {
                lavariver = selection.grow(lavariver, 'north');
            }
            if (percent(50)) {
                lavariver = selection.grow(lavariver, 'west');
            }
            allrivers = selection.bor(allrivers, lavariver);
            allrivers = selection.band(allrivers, prot);

            rpts = selection.numpoints(allrivers);
            rivertries = rivertries + 1;
        } while (!((rpts > reqpts) || (rivertries > 7)));

        if (percent(60)) {
            const prc = 10 * math.random(1, 6);
            let riverbanks = selection.grow(allrivers);
            riverbanks = selection.band(riverbanks, prot);
            des.terrain(selection.percentage(riverbanks, prc), ground);
        }

        des.terrain(allrivers, liquid);
    }

    // replacing some walls with boulders
    if (percent(20)) {
        const amount = 3 * math.random(1, 8);
        let bwalls = selection.bor(
            selection.percentage(selection.match(`.w.`), amount),
            selection.percentage(selection.match('.\nw\n.'), amount)
        );
        bwalls = selection.band(bwalls, prot);
        selection.iterate(bwalls, (x, y) => {
            des.terrain(x, y, '.');
            des.object('boulder', x, y);
        });
    }

    // replacing some walls with iron bars
    if (percent(20)) {
        const amount = 3 * math.random(1, 8);
        let fwalls = selection.bor(
            selection.percentage(selection.match(`.w.`), amount),
            selection.percentage(selection.match('.\nw\n.'), amount)
        );
        fwalls = selection.band(selection.band(selection.grow(fwalls), selection.match('w')), prot);
        des.terrain(fwalls, 'F');
    }
}

/** @param {object} api */
export function monkfoodshop(api) {
    const { u } = api;

    if (u.role === 'Monk') {
        return 'health food shop';
    }
    return 'food shop';
}

/** @param {object} api */
export function nh_set_variables_string(api, key, tbl) {
    const { table_stringify } = api;

    return 'nh_lua_variables["' + key + '"]=' + table_stringify(tbl) + ';';
}

/** @param {object} api */
export function nh_get_variables_string(api, tbl) {
    const { table_stringify } = api;

    return 'return ' + table_stringify(tbl) + ';';
}

// dat/nhlib.lua's file-scope local, which tutorial_cmd_before() closes over.
const tutorial_blacklist_commands = {
    save: true,
};

/** @param {object} api */
export function tutorial_cmd_before(api, cmd) {
    // nh.pline("TUT:cmd_before:" .. cmd);

    if (tutorial_blacklist_commands[cmd]) {
        return false;
    }
    return true;
}

/** @param {object} api */
export function tutorial_enter(api) {
    const { nh } = api;

    // nh.pline("TUT:enter");

    // add the tutorial branch callbacks
    nh.callback('cmd_before', 'tutorial_cmd_before');
    nh.callback('end_turn', 'tutorial_turn');

    // save state for later restore
    nh.gamestate();
}

/** @param {object} api */
export function tutorial_leave(api) {
    const { nh } = api;

    // nh.pline("TUT:leave");

    // remove the tutorial branch callbacks
    nh.callback('cmd_before', 'tutorial_cmd_before', true);
    nh.callback('end_turn', 'tutorial_turn', true);

    // restore state for regular play
    nh.gamestate(true);
}

export default hell_tweaks;
