// Generated from nethack-c/upstream/dat/bogusmon.txt (NetHack 5.0).
// C refs: util/makedefs.c:do_rnd_access_file(), do_name.c:bogusmon().
// Keep this browser-safe: production JS must not read files at runtime.
export const BOGUSMON_LINES = [
    "grue\n",
    "jumbo shrimp\n",
    "giant pigmy\n",
    "gnu\n",
    "killer penguin\n",
    "giant cockroach\n",
    "giant slug\n",
    "maggot\n",
    "pterodactyl\n",
    "tyrannosaurus rex\n",
    "basilisk\n",
    "beholder\n",
    "nightmare\n",
    "efreeti\n",
    "marid\n",
    "rot grub\n",
    "bookworm\n",
    "master lichen\n",
    "shadow\n",
    "hologram\n",
    "jester\n",
    "attorney\n",
    "sleazoid\n",
    "killer tomato\n",
    "amazon\n",
    "robot\n",
    "battlemech\n",
    "rhinovirus\n",
    "harpy\n",
    "lion-dog\n",
    "rat-ant\n",
    "Y2K bug\n",
    "angry mariachi\n",
    "arch-pedant\n",
    "bluebird of happiness\n",
    "cardboard golem\n",
    "duct tape golem\n",
    "diagonally moving grid bug\n",
    "evil overlord\n",
    "newsgroup troll\n",
    "ninja pirate zombie robot\n",
    "octarine dragon\n",
    "plaid unicorn\n",
    "gonzo journalist\n",
    "lag monster\n",
    "loan shark\n",
    "possessed waffle iron\n",
    "poultrygeist\n",
    "stuffed raccoon puppet\n",
    "viking\n",
    "wee green blobbie\n",
    "wereplatypus\n",
    "hag of bolding\n",
    "blancmange\n",
    "raging nerd\n",
    "spelling bee\n",
    "land octopus\n",
    "frog prince\n",
    "pigasus\n",
    "_Semigorgon\n",
    "conventioneer\n",
    "large microbat\n",
    "small megabat\n",
    "uberhulk\n",
    "tofurkey\n",
    "+Dudley\n",
    "shrinking violet\n",
    "shallow one\n",
    "spherical cow\n",
    "electric giraffe\n",
    "steam dragon\n",
    "omnibus\n",
    "slinky\n",
    "maxotaur\n",
    "millitaur\n",
    "octahedron\n",
    "dungeon core\n",
    "quale\n",
    "holloway\n",
    "chiasmus\n",
    "giant tetrapod\n",
    "voussoir\n",
    "barking spider\n",
    "frog cloud\n",
    "toothsayer\n",
    "third eye\n",
    "owlpug\n",
    "pugasus\n",
    "acorn\n",
    "red dot\n",
    "robot chicken\n",
    "doozer\n",
    "poison cackler\n",
    "lhurgoyf\n",
    "phelddagrif\n",
    "tiktaalik\n",
    "weremoustache\n",
    "rapier tapir\n",
    "choplet\n",
    "pommelbug\n",
    "quest sprout\n",
    "grue\n",
    "Christmas-tree monster\n",
    "luck sucker\n",
    "paskald\n",
    "brogmoid\n",
    "dornbeast\n",
    "Ancient Multi-Hued Dragon\n",
    "+Evil Iggy\n",
    "rattlesnake\n",
    "ice monster\n",
    "phantom\n",
    "quagga\n",
    "aquator\n",
    "griffin\n",
    "emu\n",
    "kestrel\n",
    "xeroc\n",
    "venus flytrap\n",
    "creeping coins\n",
    "hydra\n",
    "siren\n",
    "killer bunny\n",
    "rodent of unusual size\n",
    "were-rabbit\n",
    "+Smokey Bear\n",
    "Luggage\n",
    "vampiric watermelon\n",
    "Ent\n",
    "tangle tree\n",
    "nickelpede\n",
    "wiggle\n",
    "white rabbit\n",
    "snark\n",
    "pushmi-pullyu\n",
    "smurf\n",
    "tribble\n",
    "Klingon\n",
    "Borg\n",
    "Ewok\n",
    "Totoro\n",
    "ohmu\n",
    "youma\n",
    "nyaasu\n",
    "-Godzilla\n",
    "+King Kong\n",
    "earthquake beast\n",
    "Invid\n",
    "Terminator\n",
    "boomer\n",
    "Dalek\n",
    "microscopic space fleet\n",
    "Ravenous Bugblatter Beast of Traal\n",
    "leathery-winged avian\n",
    "teenage mutant ninja turtle\n",
    "samurai rabbit\n",
    "aardvark\n",
    "=Audrey II\n",
    "witch doctor\n",
    "one-eyed one-horned flying purple people eater\n",
    "+Barney the dinosaur\n",
    "+Morgoth\n",
    "Vorlon\n",
    "questing beast\n",
    "Predator\n",
    "dementor\n",
    "mother-in-law\n",
    "praying mantis\n",
    "beluga whale\n",
    "chicken\n",
    "coelacanth\n",
    "star-nosed mole\n",
    "lungfish\n",
    "slow loris\n",
    "sea cucumber\n",
    "tapeworm\n",
    "liger\n",
    "velociraptor\n",
    "corpulent porpoise\n",
    "quokka\n",
    "potoo\n",
    "lemming\n",
    "dhole\n",
    "wolpertinger\n",
    "elwedritsche\n",
    "skvader\n",
    "+Nessie\n",
    "tatzelwurm\n",
    "dahu\n",
    "dropbear\n",
    "wild haggis\n",
    "jackalope\n",
    "flying monkey\n",
    "flying pig\n",
    "hippocampus\n",
    "hippogriff\n",
    "kelpie\n",
    "catoblepas\n",
    "phoenix\n",
    "amphisbaena\n",
    "bouncing eye\n",
    "floating nose\n",
    "wandering eye\n",
    "buffer overflow\n",
    "dangling pointer\n",
    "walking disk drive\n",
    "floating point\n",
    "regex engine\n",
    "netsplit\n",
    "wiki\n",
    "peer\n",
    "COBOL\n",
    "wire shark\n",
    "stray tab\n",
    "bohrbug\n",
    "mandelbug\n",
    "schroedinbug\n",
    "heisenbug\n",
    "cacodemon\n",
    "scrag\n",
    "+Crow T. Robot\n",
    "chess pawn\n",
    "chocolate pudding\n",
    "ooblecks\n",
    "terracotta warrior\n",
    "hearse\n",
    "roomba\n",
    "miniature blimp\n",
    "dust speck\n",
    "gazebo\n",
    "gray goo\n",
    "magnetic monopole\n",
    "first category perpetual motion device\n",
    "big dumb object\n",
    "+Lord British\n",
    "particle man\n",
    "kitten prospecting robot\n",
    "guillemet\n",
    "solidus\n",
    "obelus\n",
    "dingbat\n",
    "bold face\n",
    "boustrophedon\n",
    "ligature\n",
    "rebus\n",
    "dinkus\n",
    "apostrophe golem\n",
    "voluptuous ampersand\n",
    "+Bob the angry flower\n",
    "+Strong Bad\n",
    "+Magical Trevor\n",
    "smakken\n",
    "mimmoth\n",
    "one-winged dewinged stab-bat\n",
    "Invisible Pink Unicorn\n",
    "Flying Spaghetti Monster\n",
    "three-headed monkey\n",
    "+El Pollo Diablo\n",
    "little green man\n",
    "weighted Companion Cube\n",
    "manbearpig\n",
    "bonsai-kitten\n",
    "tie-thulu\n",
    "+Domo-kun\n",
    "looooooooooooong cat\n",
    "nyan cat\n",
    "ceiling cat\n",
    "basement cat\n",
    "monorail cat\n",
    "tridude\n",
    "orcus cosmicus\n",
    "yeek\n",
    "quylthulg\n",
    "Greater Hell Beast\n",
    "+Vendor of Yizard\n",
    "+Sigmund\n",
    "lernaean hydra\n",
    "-Ijyb\n",
    "=Gloorx Vloq\n",
    "+Blork the orc\n",
    "unicorn pegasus kitten\n",
    "enderman\n",
    "wight supremacist\n",
    "zergling\n",
    "existential angst\n",
    "figment of your imagination\n",
    "flash of insight\n",
    "ghoti\n",
    "vermicious knid\n",
    "meeple\n",
    "womble\n",
    "fraggle\n",
    "stainless steel rat\n",
    "antagonistic undecagonstring\n",
    "mock role\n",
    "clown\n",
    "mime\n",
    "peddler\n",
    "haggler\n",
    "gloating eye\n",
    "flush golem\n",
    "martyr orc\n",
    "mortar orc\n",
    "acid blog\n",
    "acute blob\n",
    "aria elemental\n",
    "aliasing priest\n",
    "aligned parasite\n",
    "aligned parquet\n",
    "aligned proctor\n",
    "baby balky dragon\n",
    "baby blues dragon\n",
    "baby caricature\n",
    "baby crochet\n",
    "baby grainy dragon\n",
    "baby bong worm\n",
    "baby long word\n",
    "baby parable worm\n",
    "barfed devil\n",
    "beer wight\n",
    "boor wight\n",
    "brawny mold\n",
    "rave spider\n",
    "clue golem\n",
    "bust vortex\n",
    "errata elemental\n",
    "elastic eel\n",
    "electrocardiogram eel\n",
    "fir elemental\n",
    "tire elemental\n",
    "flamingo sphere\n",
    "fallacy golem\n",
    "frizzed centaur\n",
    "forest centerfold\n",
    "fierceness sphere\n",
    "frosted giant\n",
    "geriatric snake\n",
    "gnat ant\n",
    "giant bath\n",
    "grant beetle\n",
    "greater snake\n",
    "grind bug\n",
    "giant mango\n",
    "glossy golem\n",
    "gnome laureate\n",
    "gnome dummy\n",
    "gooier ooze\n",
    "green slide\n",
    "guardian nacho\n",
    "hell hound pun\n",
    "high purist\n",
    "hairnet devil\n",
    "ice trowel\n",
    "killer beet\n",
    "feather golem\n",
    "lounge worm\n",
    "mountain lymph\n",
    "pager golem\n",
    "pie fiend\n",
    "prophylactic worm\n",
    "sock mole\n",
    "rogue piercer\n",
    "seesawing sphere\n",
    "simile mimic\n",
    "moldier ant\n",
    "stain vortex\n",
    "scone giant\n",
    "umbrella hulk\n",
    "vampire mace\n",
    "verbal jabberwock\n",
    "water lemon\n",
    "water melon\n",
    "winged grizzly\n",
    "yellow wight\n"
];
