// roles.js — Role, race, gender, alignment data.
// C ref: role.c — roles[], races[], aligns[], genders[]
//
// Attribute order: A_STR=0 A_INT=1 A_WIS=2 A_DEX=3 A_CON=4 A_CHA=5
// attrbase: starting attribute values; attrdist: probability weights for rnd_attr (sum=100)
// attrmin/attrmax: bounds from race data (human: min=[3×6], max=[118,18,18,18,18,18])
// STR18(100) = 118 in the internal representation (18/100 exceptional strength)

// petnum: 'CAT'=PM_KITTEN, 'DOG'=PM_LITTLE_DOG, 'PONY'=PM_PONY, null=NON_PM (random)
// Source: role.c — 2nd PM_ field per role entry (petnum in struct Role).
// startAC: starting armor class (10 - sum of all equipped armor bonuses including spe)
// title: rank title array (9 entries), indexed by xlev_to_rank(ulevel)
//   xlev_to_rank: 1-2→0, 3-5→1, 6-9→2, 10-13→3, 14-17→4, 18-21→5, 22-25→6, 26-29→7, 30→8
// lgod/ngod/cgod: deity strings from role.c; leading '_' flags a goddess
export const roles = [
    { name: { m: 'Archeologist', f: 'Archeologist' }, mnum: 0, petnum: null,
      attrbase: [7, 10, 10, 7, 7, 7], attrdist: [20, 20, 20, 10, 20, 10],
      hpadv: { infix: 11, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 9,
      lgod: 'Quetzalcoatl', ngod: 'Camaxtli', cgod: 'Huhetotl',
      title: [{ m: 'Digger', f: 'Digger' },
              { m: 'Field Worker', f: 'Field Worker' },
              { m: 'Investigator', f: 'Investigator' },
              { m: 'Exhumer', f: 'Exhumer' },
              { m: 'Excavator', f: 'Excavator' },
              { m: 'Spelunker', f: 'Spelunker' },
              { m: 'Speleologist', f: 'Speleologist' },
              { m: 'Collector', f: 'Collector' },
              { m: 'Curator', f: 'Curator' }] },
    { name: { m: 'Barbarian', f: 'Barbarian' }, mnum: 1, petnum: null,
      attrbase: [16, 7, 7, 15, 16, 6], attrdist: [30, 6, 7, 20, 30, 7],
      hpadv: { infix: 14, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 7,
      lgod: 'Mitra', ngod: 'Crom', cgod: 'Set',
      title: [{ m: 'Plunderer', f: 'Plunderess' },
              { m: 'Pillager', f: 'Pillager' },
              { m: 'Bandit', f: 'Bandit' },
              { m: 'Brigand', f: 'Brigand' },
              { m: 'Raider', f: 'Raider' },
              { m: 'Reaver', f: 'Reaver' },
              { m: 'Slayer', f: 'Slayer' },
              { m: 'Chieftain', f: 'Chieftainess' },
              { m: 'Conqueror', f: 'Conqueress' }] },
    { name: { m: 'Caveman', f: 'Cavewoman' }, mnum: 2, petnum: 'DOG',
      attrbase: [10, 7, 7, 7, 8, 6], attrdist: [30, 6, 7, 20, 30, 7],
      hpadv: { infix: 14, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 8,
      lgod: 'Anu', ngod: '_Ishtar', cgod: 'Anshar',
      title: [{ m: 'Troglodyte', f: 'Troglodyte' },
              { m: 'Aborigine', f: 'Aborigine' },
              { m: 'Wanderer', f: 'Wanderer' },
              { m: 'Vagrant', f: 'Vagrant' },
              { m: 'Wayfarer', f: 'Wayfarer' },
              { m: 'Roamer', f: 'Roamer' },
              { m: 'Nomad', f: 'Nomad' },
              { m: 'Rover', f: 'Rover' },
              { m: 'Pioneer', f: 'Pioneer' }] },
    { name: { m: 'Healer', f: 'Healer' }, mnum: 3, petnum: null,
      attrbase: [7, 7, 13, 7, 11, 16], attrdist: [15, 20, 20, 15, 25, 5],
      hpadv: { infix: 11, inrnd: 0 }, enadv: { infix: 1, inrnd: 4 }, startAC: 8,
      lgod: '_Athena', ngod: 'Hermes', cgod: 'Poseidon',
      title: [{ m: 'Rhizotomist', f: 'Rhizotomist' },
              { m: 'Empiric', f: 'Empiric' },
              { m: 'Embalmer', f: 'Embalmer' },
              { m: 'Dresser', f: 'Dresser' },
              { m: 'Medicus ossium', f: 'Medica ossium' },
              { m: 'Herbalist', f: 'Herbalist' },
              { m: 'Magister', f: 'Magistra' },
              { m: 'Physician', f: 'Physician' },
              { m: 'Chirurgeon', f: 'Chirurgeon' }] },
    { name: { m: 'Knight', f: 'Knight' }, mnum: 4, petnum: 'PONY',
      attrbase: [13, 7, 14, 8, 10, 17], attrdist: [30, 15, 15, 10, 20, 10],
      hpadv: { infix: 14, inrnd: 0 }, enadv: { infix: 1, inrnd: 4 }, startAC: 2,
      lgod: 'Lugh', ngod: '_Brigit', cgod: 'Manannan Mac Lir',
      title: [{ m: 'Gallant', f: 'Gallant' },
              { m: 'Esquire', f: 'Esquire' },
              { m: 'Bachelor', f: 'Bachelor' },
              { m: 'Sergeant', f: 'Sergeant' },
              { m: 'Knight', f: 'Knight' },
              { m: 'Banneret', f: 'Banneret' },
              { m: 'Chevalier', f: 'Chevaliere' },
              { m: 'Seignieur', f: 'Dame' },
              { m: 'Paladin', f: 'Paladin' }] },
    { name: { m: 'Monk', f: 'Monk' }, mnum: 5, petnum: null,
      attrbase: [10, 7, 8, 8, 7, 7], attrdist: [25, 10, 20, 20, 15, 10],
      hpadv: { infix: 12, inrnd: 0 }, enadv: { infix: 2, inrnd: 2 }, startAC: 4,
      lgod: 'Shan Lai Ching', ngod: 'Chih Sung-tzu', cgod: 'Huan Ti',
      title: [{ m: 'Candidate', f: 'Candidate' },
              { m: 'Novice', f: 'Novice' },
              { m: 'Initiate', f: 'Initiate' },
              { m: 'Student of Stones', f: 'Student of Stones' },
              { m: 'Student of Waters', f: 'Student of Waters' },
              { m: 'Student of Metals', f: 'Student of Metals' },
              { m: 'Student of Winds', f: 'Student of Winds' },
              { m: 'Student of Fire', f: 'Student of Fire' },
              { m: 'Master', f: 'Master' }] },
    { name: { m: 'Priest', f: 'Priestess' }, mnum: 6, petnum: null,
      attrbase: [7, 7, 10, 7, 7, 7], attrdist: [15, 10, 30, 15, 20, 10],
      hpadv: { infix: 12, inrnd: 0 }, enadv: { infix: 4, inrnd: 3 }, startAC: 6,
      lgod: null, ngod: null, cgod: null,
      title: [{ m: 'Aspirant', f: 'Aspirant' },
              { m: 'Acolyte', f: 'Acolyte' },
              { m: 'Adept', f: 'Adept' },
              { m: 'Priest', f: 'Priestess' },
              { m: 'Curate', f: 'Curate' },
              { m: 'Canon', f: 'Canoness' },
              { m: 'Lama', f: 'Lama' },
              { m: 'Patriarch', f: 'Matriarch' },
              { m: 'High Priest', f: 'High Priestess' }] },
    { name: { m: 'Ranger', f: 'Ranger' }, mnum: 7, petnum: 'DOG',
      attrbase: [13, 13, 13, 9, 13, 7], attrdist: [30, 10, 10, 20, 20, 10],
      hpadv: { infix: 13, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 7,
      lgod: 'Mercury', ngod: '_Venus', cgod: 'Mars',
      title: [{ m: 'Tenderfoot', f: 'Tenderfoot' },
              { m: 'Lookout', f: 'Lookout' },
              { m: 'Trailblazer', f: 'Trailblazer' },
              { m: 'Reconnoiterer', f: 'Reconnoiteress' },
              { m: 'Scout', f: 'Scout' },
              { m: 'Arbalester', f: 'Arbalester' },
              { m: 'Archer', f: 'Archer' },
              { m: 'Sharpshooter', f: 'Sharpshooter' },
              { m: 'Marksman', f: 'Markswoman' }] },
    { name: { m: 'Rogue', f: 'Rogue' }, mnum: 8, petnum: null,
      attrbase: [7, 7, 7, 10, 7, 6], attrdist: [20, 10, 10, 30, 20, 10],
      hpadv: { infix: 10, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 7,
      lgod: 'Issek', ngod: 'Mog', cgod: 'Kos',
      title: [{ m: 'Footpad', f: 'Footpad' },
              { m: 'Cutpurse', f: 'Cutpurse' },
              { m: 'Rogue', f: 'Rogue' },
              { m: 'Pilferer', f: 'Pilferer' },
              { m: 'Robber', f: 'Robber' },
              { m: 'Burglar', f: 'Burglar' },
              { m: 'Filcher', f: 'Filcher' },
              { m: 'Magsman', f: 'Magswoman' },
              { m: 'Thief', f: 'Thief' }] },
    { name: { m: 'Samurai', f: 'Samurai' }, mnum: 9, petnum: 'DOG',
      attrbase: [10, 8, 7, 10, 17, 6], attrdist: [30, 10, 8, 30, 14, 8],
      hpadv: { infix: 13, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 4,
      lgod: '_Amaterasu Omikami', ngod: 'Raijin', cgod: 'Susanowo',
      title: [{ m: 'Hatamoto', f: 'Hatamoto' },
              { m: 'Ronin', f: 'Ronin' },
              { m: 'Ninja', f: 'Kunoichi' },
              { m: 'Joshu', f: 'Joshu' },
              { m: 'Ryoshu', f: 'Ryoshu' },
              { m: 'Kokushu', f: 'Kokushu' },
              { m: 'Daimyo', f: 'Daimyo' },
              { m: 'Kuge', f: 'Kuge' },
              { m: 'Shogun', f: 'Shogun' }] },
    { name: { m: 'Tourist', f: 'Tourist' }, mnum: 10, petnum: null,
      attrbase: [7, 10, 6, 7, 7, 10], attrdist: [15, 10, 10, 15, 30, 20],
      hpadv: { infix: 8, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 10,
      lgod: 'Blind Io', ngod: '_The Lady', cgod: 'Offler',
      title: [
          { m: 'Rambler', f: 'Rambler' },
          { m: 'Sightseer', f: 'Sightseer' },
          { m: 'Excursionist', f: 'Excursionist' },
          { m: 'Peregrinator', f: 'Peregrinatrix' },
          { m: 'Traveler', f: 'Traveler' },
          { m: 'Journeyer', f: 'Journeyer' },
          { m: 'Voyager', f: 'Voyager' },
          { m: 'Explorer', f: 'Explorer' },
          { m: 'Adventurer', f: 'Adventurer' },
      ] },
    { name: { m: 'Valkyrie', f: 'Valkyrie' }, mnum: 11, petnum: null,
      attrbase: [10, 7, 7, 7, 10, 7], attrdist: [30, 6, 7, 20, 30, 7],
      hpadv: { infix: 14, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 }, startAC: 5,
      lgod: 'Tyr', ngod: 'Odin', cgod: 'Loki',
      title: [{ m: 'Stripling', f: 'Stripling' },
              { m: 'Skirmisher', f: 'Skirmisher' },
              { m: 'Fighter', f: 'Fighter' },
              { m: 'Man-at-arms', f: 'Woman-at-arms' },
              { m: 'Warrior', f: 'Warrior' },
              { m: 'Swashbuckler', f: 'Swashbuckler' },
              { m: 'Hero', f: 'Heroine' },
              { m: 'Champion', f: 'Champion' },
              { m: 'Lord', f: 'Lady' }] },
    { name: { m: 'Wizard', f: 'Wizard' }, mnum: 12, petnum: 'CAT',
      attrbase: [7, 10, 7, 7, 7, 7], attrdist: [10, 30, 10, 20, 20, 10],
      hpadv: { infix: 10, inrnd: 0 }, enadv: { infix: 4, inrnd: 3 }, startAC: 7,
      lgod: 'Ptah', ngod: 'Thoth', cgod: 'Anhur',
      title: [{ m: 'Evoker', f: 'Evoker' },
              { m: 'Conjurer', f: 'Conjurer' },
              { m: 'Thaumaturge', f: 'Thaumaturge' },
              { m: 'Magician', f: 'Magician' },
              { m: 'Enchanter', f: 'Enchantress' },
              { m: 'Sorcerer', f: 'Sorceress' },
              { m: 'Necromancer', f: 'Necromancer' },
              { m: 'Wizard', f: 'Wizard' },
              { m: 'Mage', f: 'Mage' }] },
];

export const races = [
    { name: 'human', adj: 'human', mnum: 0,
      attrmin: [3, 3, 3, 3, 3, 3], attrmax: [118, 18, 18, 18, 18, 18],
      hpadv: { infix: 2, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 } },
    { name: 'elf', adj: 'elven', mnum: 1,
      attrmin: [3, 3, 3, 3, 3, 3], attrmax: [18, 20, 20, 18, 16, 18],
      hpadv: { infix: 1, inrnd: 0 }, enadv: { infix: 2, inrnd: 0 } },
    { name: 'dwarf', adj: 'dwarven', mnum: 2,
      attrmin: [3, 3, 3, 3, 3, 3], attrmax: [118, 16, 16, 20, 20, 16],
      hpadv: { infix: 4, inrnd: 0 }, enadv: { infix: 0, inrnd: 0 } },
    { name: 'gnome', adj: 'gnomish', mnum: 3,
      attrmin: [3, 3, 3, 3, 3, 3], attrmax: [118, 19, 18, 18, 18, 18],
      hpadv: { infix: 1, inrnd: 0 }, enadv: { infix: 2, inrnd: 0 } },
    { name: 'orc', adj: 'orcish', mnum: 4,
      attrmin: [3, 3, 3, 3, 3, 3], attrmax: [118, 16, 16, 18, 18, 16],
      hpadv: { infix: 1, inrnd: 0 }, enadv: { infix: 1, inrnd: 0 } },
];

export const aligns = [
    { name: 'lawful', value: 1 },
    { name: 'neutral', value: 0 },
    { name: 'chaotic', value: -1 },
];

export const genders = [
    { name: 'male', value: 0 },
    { name: 'female', value: 1 },
];

export function findRole(name) {
    if (!name || typeof name !== 'string') return null;
    const lc = name.toLowerCase();
    return roles.find(r => r.name.m.toLowerCase() === lc || r.name.f.toLowerCase() === lc);
}

export function findRace(name) {
    if (!name || typeof name !== 'string') return null;
    const lc = name.toLowerCase();
    return races.find(r => r.name.toLowerCase() === lc);
}
